### ISSUE TITLE
Add core node API for block height to the documentation

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1012]
While exploring expiry of names I was looking for the current block height. An API like `core/v1/node/info` that returns 

* Consensus hash (optionally)
* Last block seen
* Last block processed

would be helpful for that use case

**Comment by jcnelson** [comment]
https://core.blockstack.org/v1/info

**Comment by friedger** [comment]
Oh, it is already there. Great! Should be added to the documentation
