### ISSUE TITLE
Add an editor to the clarity-developer-preview

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/stacks-blockchain#1019]
It would be great to have an editor in that image.

**Comment by jcnelson** [comment]
I'm not sure what this issue is supposed to be.  Doesn't the developer already have a preferred editor?  If so, can we close this?

**Comment by moxiegirl** [comment]
@jcnelson the image doesn't have anything like `vi` or `vim` that's what I mean. So you can edit a file in the image.
