### ISSUE TITLE
Implement Stacks token, unlocking, and genesis block

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1062]

**Comment by diwakergupta** [comment]
@jcnelson did you ever get started on this? Otherwise I'll clear the assignee and we can discuss who and when we can tackle this next Monday.

**Comment by jcnelson** [comment]
@zone117x to take the migration code part
@lgalabru to take the vesting part

**Comment by lgalabru** [comment]
Feature completed, closing now.
