### ISSUE TITLE
Ability to get element at index in buffer / list

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1122]
Feature request extracted from https://github.com/blockstack/blockstack-core/pull/1117

https://github.com/blockstack/blockstack-core/blob/d674066f395c99faaaa6b0b8bfc6abcc32b75f05/core-contracts/contracts/bns.clar#L126-L132

In BNS, in order to get the right value from the price table, based on the namespace length, we'd need to be able to get an element from a list / buffer.

**Note**: This issue is not a blocker, since it can be implemented in Clarity with `(fold ...)`. That being said, it looks like a nice and reasonable native function to have.

**Comment by kantai** [comment]
Reopening this, since this still seems like a useful function.
