### ISSUE TITLE
Work on removing instances of `SELECT COUNT(*)`

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1128]
Turns out, `SELECT COUNT(*)` has at least O(n) complexity in the number of table rows.  It would behoove us to refactor our sqlite-backed databases so we could cache counts ourselves.

Source: https://stackoverflow.com/questions/8988915/sqlite-count-slow-on-big-tables

**Comment by kantai** [comment]
Is this an issue on Stacks V2 or on the Python Stacks V1 codebase?

In Stacks V2, there don't appear to be any such offending uses of `SELECT COUNT` -- the only `SELECT COUNT` uses are limited by `WHERE` clauses which will make use of indexes (COUNT would be O(N) in the return set, but not the row count).
