### ISSUE TITLE
xor command should take a buffer not just numerics

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/stacks-blockchain#1150]
In creating a tuple that includes the owner name, the `xor` command only takes a numeric. Likely users will want to perhaps supply a `blockstack.id` instead of a number.

**Comment by jcnelson** [comment]
@kantai @lgalabru has this been implemented?

**Comment by lgalabru** [comment]
Nope

**Comment by friedger** [comment]
Please!

07.11.2020 20:19:35 stale[bot] <notifications@github.com>:

**Comment by jcnelson** [comment]
Per #2595, the most likely way to approach this will be to add native support for converting sequences to and from integers, which would then yield an efficient and cost-accurate way to do bitwise operators on sequences (via `fold`).
