### ISSUE TITLE
BNS: Stacks Support for Off-Chain (Subdomain) Name Operations

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1160]
Stacks V2 will still require support for Off-Chain names (called Subdomains, sometimes Sponsored Names)

* Off-chain names will not be (directly) part of the consensus state, much like Stacks V1.
* Retain the Atlas network as a distinct network for replicating zone files separate from the blockchain peer network proper.
* Off-chain name batches should be structured such that you can produce a Merkle proof-of-inclusion for an off-chain name that links the name's registration to the subdomain registrar (probably not necessary -- the zonefile is public and relatively concise, the zonefile "hash" is probably commitment enough)
* Update subdomain registrar codebase
* Implement an API service for combined on-chain and off-chain BNS querying

### Ensuring Off-Chain Compliance

* Require subdomain registrars to issue a security deposit into the BNS smart contract, which will be burned if the subdomain registrar issues conflicting name registrations and the user complains (the BNS smart contract can validate the complaint because the user can submit the Merkle proofs for both names, which demonstrates that the subdomain registrar violated the protocol)
* We require any subdomain API services to sign their off-chain queries with a key registered with the BNS smart contract, such that a fraudulent API response will serve as a fraud proof causing the registrar to forfeit its deposit.

**Comment by diwakergupta** [comment]
Needs some additional design discussion / align on product requirements cc/ @jeffdomke

**Comment by quixote911** [comment]
What is your plan of tackling off-chain names in Stacks 2.0? Thanks!

**Comment by jcnelson** [comment]
> Retain the Atlas network as a distinct network for replicating zone files separate from the blockchain peer network proper.

I'm not too sure about this anymore.  I think since the zonefile replication system will be built into the node, we'll want to piggyback off of the peer network to some extent.  There can be a separate protocol (or sub-protocol) for it within the p2p network protocol and there can be HTTP RESTful API endpoints for it.  We'll probably store all subdomain state in a MARF'ed database, where each fork contains all subdomain records processed from its fork's BNS name updates.

**Comment by kantai** [comment]
This has been superseded by: https://github.com/blockstack/stacks-blockchain/issues/1889
