### ISSUE TITLE
Rules for validating PoisonMicroblocks

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1200]
A miner can produce many private microblock stream forks, and release them well after their tenure ends.  If these forks get exposed before the miner reward matures, then the following rules apply for dealing with them.  Consider this example:

```
A--A[1]--A[2]--A[3]--A[4] <-- B <-- C <-- D
      \
_______\_________________Public
Private \
         A'[2]--A'[3]--A'[4]
```

There are three possible PoisonMicroblock transactions that B, C, or D could mine, depending on when A'[x] are discovered:

* `PoisonMicroblock(A[2], A'[2])`
* `PoisonMicroblock(A[3], A'[3])`
* `PoisonMicroblock(A[4], A'[4])`

## Rule 1: Confirmed microblocks stay confirmed

Until any of these are mined, B can build off of any A[x] or A'[x] she wants, since the existence of the equivocation is not guaranteed to be known to B at the time (or known to anyone besides A).  In this example, B builds off of A[4] (note that if B knew of A'[x], she could have also built her anchored block off of it instead, and in doing so, orphaned all conflicting A[x]).  Even if no PoisonMicroblock is mined, it remains the case that B has "chosen" the winning fork -- neither C nor D can mine off of any A'[x] since doing so would confirm A's equivocation.  If C or D try to build off any A'[x], then their blocks would be rejected as invalid (even though no PoisonMicroblock was mined) -- all other peers would see that there exists a confirmed microblock A[x] that is in conflict with C's or D's A'[x], which all other peers would need to be given in order to even consider C or D's anchored block in the first place (thereby publishing the existence of the equivocation).

If C explicitly mines any `PoisonMicroblock(A[x], A'[x])`, then:
* The fork B chose -- `A-A[1]-A[2]-A[3]-A[4]-B` -- remains confirmed
* C destroys A's coinbase and claims some R% reward of the coinbase

Because B confirmed the fork A[1]...A[4], all of these microblocks remain valid chain tips to build off of, regardless of whether or not a PoisonMicroblock gets mined.

## Rule 2:  Reward the earliest fork detection

In this example, there are three possible PoisonMicroblock transactions.  If C mines `PoisonMicroblock(A[4], A'[4])`, and D mines `PoisonMicroblock(A[2], A'[2])`, and A's reward hasn't matured yet, then:
* D gets the reward originally meant for C, since D's fork is earlier in the stream
* C gets nothing
* A loses her coinbase

The fork B chose remains confirmed, per rule 1.

## Remarks

The reason for having a dedicated PoisonMicroblock transaction type is that it disincentivizes miners from creating microblock forks (which they can create infinitely many of).  Even though the system will need to support an "implicit" fork detection rule (i.e. B chooses the winning fork even without mining a PoisonMicroblock transaction), the fact that C or D can opt to punish A even if B doesn't means that A has a financial incentive to not fork the stream in the first place.

Even if A didn't care -- e.g. A just wanted to spam the network with many microblock forks -- the miner B would still confirm a single fork, and allow all other peers to automatically prune all of A's rejected forks from memory (since they'll never be built on).  So A's best course of action is to not fork the microblock stream, even though it's of no real consequence if A doesn't abide.

**Comment by Cherlano** [comment]
Thank you :)
