### ISSUE TITLE
RESTful API for querying node info

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1227]
Keep compatibility with `/v1/info`, and in particular, add a flag that indicates whether or not the node is a Stacks v2 node.

**Comment by yknl** [comment]
Can we add a `blockchain_version` key to the response to indicate the version of Stacks? Wallets will use this flag to switch over from v1 to v2 transactions.

**Comment by jcnelson** [comment]
Would it be okay with you if we treated the _absence_ of a "blockchain_version" key as being a v1 instance?  The v2 instance would include `"blockchain_version": "2.0"` in the `/v1/info` JSON output.

**Comment by yknl** [comment]
yes that's exactly what the wallet will do

**Comment by diwakergupta** [comment]
Reopening this as it hasn't quite been addressed:

* there's no `/v1/info` endpoint anymore
* the current `/v2/info` endpoint doesn't have a `blockchain_version` field

Should be pretty straight-forward to implement. @yknl can you confirm this is still important / required? cc/ @kyranjamie for current wallet.

**Comment by kyranjamie** [comment]
Yeah, we'll need something like this for the wallet to determine a user's connecting to a stacking-capable node.

<details>
<summary>Related wallet screenshot</summary>

https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet?node-id=430%3A563

![image](https://user-images.githubusercontent.com/1618764/89824592-a7ab2080-db53-11ea-9e11-0c072aa6c2dd.png)

</details>

**Comment by yknl** [comment]
The absence of the `blockchain_version` field is sufficient for the older Stacks wallet versions.
