### ISSUE TITLE
Clarity: maximum number of function arguments?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1231]
Is this defined somewhere?

**Comment by diwakergupta** [comment]
Documentation question, that we should address one way or another in the Clarity reference.

@kantai @lgalabru care to chime in?

**Comment by kantai** [comment]
At the moment, there's no specific maximum number of function arguments, except an upper limit on Clarity memory usage. We can either document that as such, or try to set a bound here. I'm inclined towards saying that the upper limit should just be specified via the Clarity memory limit.
