### ISSUE TITLE
Capitalize type identifiers in Clarity

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1245]
This is a proposal to capitalize type identifiers in Clarity. The naming convention makes type identifiers distinct from other symbols such as variable names, making the code more readable.

**Background**

[UpperCamelCase aka PascalCase](https://en.wikipedia.org/wiki/Camel_case) is familiar by many developers for class- and type definitions. It is the convention in _Javascript_ for data types, in _Python_, _Java_ and _Ruby_ for class names, in _Rust_ for type aliases and variants, in _Haskell_ for types and type classes, and in _Swift_ for class and other object type declarations.

Several modern Lisp dialects also capitalize types. [Typed Racket](https://docs.racket-lang.org/ts-guide/beginning.html) by convention [capitalizes type identifiers](https://docs.racket-lang.org/ts-guide/types.html). [Clojure uses UpperCamelCase ](https://guide.clojure.style/#CamelCase-for-protocols-records-structs-and-types) for types and when naming [custom types and records](https://guide.clojure.style/#types-records).

**Examples**

An example based on the code in the [Clarity introduction](https://docs.blockstack.org/core/smart/overview.html#basic-building-blocks-of-clarity-contracts):

```clojure
(define-public (transfer (recipient principal) (amount int))
  ...)
```

with capitalized types:

```clojure
(define-public (transfer (recipient Principal) (amount Int))
  ...)
```
From the language reference:

```clojure
(define-data-var size Int 0)
(define (set-size (value Int))
  (var-set size value))
```

**Comment by njordhov** [comment]
Case in point, Clarity currently uses the symbol `list` both for type declaration and instance constructor, as demonstrated in [test_get_list_max_len](https://github.com/blockstack/stacks-blockchain/blob/411962e5f85a18faf0261ea660ae6625f48302ce/src/vm/tests/datamaps.rs#L296):

```clojure
(define-data-var ranking (list 10 int) (list 1 2 3))
```

The distinction between type declaration and constructor would be clearer with capitalized type labels:

```clojure
(define-data-var ranking (List 10 int) (list 1 2 3))
```

**Comment by dantrevino** [comment]
There must be a downside here, other than optics... what is it?

**Comment by njordhov** [comment]
> There must be a downside here, other than optics

Looking forward, with custom types and type aliases (see https://github.com/clarity-lang/reference/issues/6)  it is often reasonable to use the same name for a function argument as its type, but without a convention for type names, the distinction between argument name and type can become confusing or require other naming schemes to keep them distinct. For example, consider this code from the [Rockets Base](https://clarity.tools/code/rockets-base) example, which follows the UpperCamelCase convention for type names:

```clojure
(define-type-alias Ship {id Int})
(define-type-alias Pilot Principal)

(define-public (authorize-pilot (ship Ship) (pilot Pilot)) .....)
```
