### ISSUE TITLE
Specify maximum Stacks block compute and storage limits. 

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1255]

**Comment by kantai** [comment]
In addition to specifying the block limit, we also need to use this limit to measure the block _fill_ which is used to issue miner tx fee rewards.

**Comment by kantai** [comment]
Regarding the block limit/initial cost function settings. I've so far been unable to reproduce the slowness of transaction processing in isolated benchmarks. This is a problem because isolated benchmarks are ostensibly how we are setting the initial block limit and cost function constants, and so if these benchmarks are giving a realistic estimate of the actual cost to execute, then the block limit and constants set in that manner won't be effective.

An alternative is take a very conservative approach at launch, and rely on the cost-voting mechanism (or perhaps Stacks 2.1) to improve on the block limit. This approach would do more or less the following -- set all the cost function constants to 1000, which would allow for space to reduce them via cost-voting, and then set the block limit by counting the resulting execution cost of a block that we _know_ is near our computation limit (i.e., 100 stack-stx operations)

**Comment by diwakergupta** [comment]
Fixed by #2285
