### ISSUE TITLE
Revise README

### ISSUE THREAD

**Issue by ghost** [blockstack/stacks-blockchain#1270]
## Expected

The usual, like:

* Build Status
* Description (very compact, consistent with repo-description)
* Install from Binaries (can point to online-manuals)
* Build from Source (basic build, e.g. for ubuntu, then point to manual for more info)
  * Running Tests
  * Install
  * Mention Mac and Win
* Contribution (tiny text, then point to manual / file)
* Developer Resources
* Acknowledgements (optionally)
* LICENSE

Most importantly, the "Build from Source" is missing.

**Comment by lgalabru** [comment]
I think we now have all this sections. Closing now.
