### ISSUE TITLE
Bump rusqlite to 0.21

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1274]
It's a breaking change, so best do it in its own PR.  Among other things, this fix makes it so the bundled `libsqlite3` (which we use) gets fetched via HTTPS by default.

**Comment by jcnelson** [comment]
The current version of sqlite we use has known race conditions and DoS vectors, which could lead to a chain split.

**Comment by diwakergupta** [comment]
> The current version of sqlite we use has known race conditions and DoS vectors, which could lead to a chain split.

Yep, this came up in the audits as well. In fact, per `cargo audit`, we should upgrade to at least 0.23 (and indeed, the latest version): https://rustsec.org/advisories/RUSTSEC-2020-0014

**Comment by jcnelson** [comment]
We should broaden this to doing a `cargo audit` on all dependencies and just bite the bullet and do the requisite refactoring work

**Comment by diwakergupta** [comment]
FYI I thought I might take a crack at this: made good progress (150+ errors down to 30+ 😅 ), but am running into the limits of my Rust-fu.

Bulk of the rusqlite API changes are restricted to `row.get` (which now returns a `Result<T>`, and to `query_row`, which expects a closure that returns a `Result<T, rusqlite:Error>`. I addressed most of the former category, but struggling with the latter.

Would anyone like to take my patch forward, unless maybe @lgalabru or @reedrosenbluth you have cycles to work on this?

**Comment by lgalabru** [comment]
Happy to take over.

**Comment by diwakergupta** [comment]
> Happy to take over.

Thanks much! I pushed my changes to `diwaker/audit/sqlite` branch: https://github.com/blockstack/stacks-blockchain/tree/diwaker/audit/sqlite

**Comment by diwakergupta** [comment]
Fixed by #2297
