### ISSUE TITLE
cargo build fails on Raspberry Pi3B. "Unsupported target architecture" for sha2-asm.

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain#1278]
Mainly for visibility.  Not a bug in blockstack-core.   

We ran into this while trying to build on Raspberry Pi.
```
error: failed to run custom build command for `sha2-asm v0.5.3`

Caused by:
  process didn't exit successfully: `/home/pi/blockstack-core/target/debug/build/sha2-asm-a58e6c6d2b010656/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unsupported target architecture', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/sha2-asm-0.5.3/build.rs:13:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jcnelson** [comment]
Thanks @dantrevino.  I think the fix here is going to be making it so Cargo uses `sha2-asm` when the architecture is supported, and plain-old `sha2` otherwise.  Not a Cargo wiz, so I need to figure out how to do this.

**Comment by dantrevino** [comment]
My understanding is that there is no way, currently, to dynamically include/exclude architecture-dependent *features*.  It looks like rust-lang is tracking a fix for this in their nightly branch but implementation timeline seems indeterminate. [#7914](https://github.com/rust-lang/cargo/issues/7914).  

In the meantime, I've been able to consistently get working binaries by removing the 'asm' feature and cross-compiling via [cross](https://github.com/rust-embedded/cross).  I've documented the steps here: https://github.com/dantrevino/stacks-blockchain/

Simply removing the 'asm' feature and trying to build directly on Pi has not worked for me yet.  I'm still working on testing other different hardware.

**Comment by dantrevino** [comment]
Just following up ... building directly on a Pi3B fails consistently with either unable to allocate memory, or over-heating.  Confirmed by myself and @fluidvoice that build normally hits 2GB-ish of memory usage.  Typical failure looks like:
```
memory allocation of 75497472 bytes failed
error: could not compile `blockstack-core`.
```

**Comment by dantrevino** [comment]
Confirm stacks blockchain builds and runs fine on a Pi 4B with >= 2GB of RAM, with removal of "asm" from sha2 features.

**Comment by fluidvoice** [comment]
> Confirm stacks blockchain builds and runs fine on a Pi 4B with >= 2GB of RAM, with removal of "asm" from sha2 features.

So how do I get around this compile problem?  I have Ubuntu 19.10.1 running fine on my Pi4 now.

**Comment by dantrevino** [comment]
Sorry it's not spelled out clearly. As @jcnelson mentions above you have to remove the 'asm' feature from Cargo.toml and use plain old sha2.  Until a better workaround can be submitted as a PR here, I'm maintaining an up-to-date mirror with the change in my gitlab repo mentioned above.

**Comment by fluidvoice** [comment]
> Sorry it's not spelled out clearly. As @jcnelson mentions above you have to remove the 'asm' feature from Cargo.toml and use plain old sha2. Until a better workaround can be submitted as a PR here, I'm maintaining an up-to-date mirror with the change in my gitlab repo mentioned above.

ah ok. I've never done anything with Rust before so needed to find what explicitly to do, namely commenting out this line.  Built fine now :-)

[dependencies.sha2]
version = "0.8.0"
# features = ["asm"]
