### ISSUE TITLE
Sortition: use mean of min and median as weights, smoothed over 6 bitcoin blocks

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1315]
Right now, cryptographic sortition probability weights are assigned according to each miner's relative PoX transfers.  In order to (1) decrease the profit margin a miner can obtain by both Stacking and mining (which leads to consolidation over long enough timescales), and (2) ensure that the most profitable course of action for a miner is to mine at a steady pace at all times (instead of trying to play games with their PoX rates when their Stacking addresses come up), the sortition probability weights need to be changed.  Modeling this out, it seems like taking the average of a miner's minimum transfer amount in the last 6 blocks, and the median transfer amount in the last 6 blocks, achieves this.

**Comment by muneeb-ali** [comment]
Makes sense to do this over 6 blocks. This gives a STX miner roughly 1 hour to change strategy.

**Comment by diwakergupta** [comment]
@blockstack/blockchain-team this hasn't been implemented yet, right?

**Comment by jcnelson** [comment]
Nope, still a TODO

**Comment by kantai** [comment]
One snag here is that we need a way to identify a miner across multiple leader_block_commits (even if we don't ever see the associated Stacks blocks). We cannot use VRF keys for this, because those aren't "authenticated" until the Stacks block is revealed.

I think we'd need to do something like require that each block commit spend an output from the prior commit (being careful to ensure that no two leader block commits could claim the same prior commit). That's certainly implementable (it would make use of the tx_ref field already added in #2015), but I want to confirm that we should go this route beforehand.

**Comment by jcnelson** [comment]
I think doing this through UTXO-chaining would be sufficient.  A simpler and potentially more-robust approach would be to just add a dedicated "miner ID" BTC output to the block-commit, which must contain a scriptPubKey that we can parse.  In most cases, this "miner ID" output would also be the miner's change output.  This removes the need for miners to keep the UTXO chain going (i.e. they can spend their BTC intermittently between block-commits, or use a different funding key), and it should achieve the same purpose (i.e. identify miners' block-commits).

Regardless of how we do it, though, we'll want to store each miner's previous burn/xfer amounts in the sortition DB MARF, not just the burnchain DB (since the burnchain can fork).

**Comment by kantai** [comment]
>  A simpler and potentially more-robust approach would be to just add a dedicated "miner ID" BTC output to the block-commit, which must contain a scriptPubKey that we can parse. In most cases, this "miner ID" output would also be the miner's change output. This removes the need for miners to keep the UTXO chain going (i.e. they can spend their BTC intermittently between block-commits, or use a different funding key), and it should achieve the same purpose (i.e. identify miners' block-commits).

Interesting -- how would we use that to verify a miner ID? Wouldn't we still need to perform a UTXO match on that output to conclude that a subsequent miner signed with that miner ID?

**Comment by jcnelson** [comment]
> Interesting -- how would we use that to verify a miner ID? Wouldn't we still need to perform a UTXO match on that output to conclude that a subsequent miner signed with that miner ID?

You could simply require that the Stacks block's coinbase transaction is signed by the key whose address is this miner ID output's scriptPubKey's address.

**Comment by kantai** [comment]
But I think the verification needs to happen without the Stacks block data -- otherwise, losing miners (or other miners not interested in actually producing blocks) would be able to claim miner IDs they aren't associated with (reducing the likelihood that honest miners are chosen).

**Comment by jcnelson** [comment]
Hmm, I think you're right.  I think UTXO-chaining is the only way to stop griefers from driving up your minimum.  Didn't think of that.
