### ISSUE TITLE
Clarity function definitions to allow multiple expressions

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1345]
**Clarity function definitions should allow multiple expressions in their body** instead of requiring use of the [begin](https://docs.blockstack.org/core/smart/clarityref#begin) construct when there are more than one expression. This applies to `define-private`, `define-public` and `define-read-only`.

Here is an example from the documentation of [define-public](https://docs.blockstack.org/core/smart/clarityref#define-public):

```clojure
(define-public (hello-world (input int))
  (begin (print (+ 2 input))
         (ok input)))
```

With multiple expressions in the definition body, the `begin` construct is no longer required:

```clojure
(define-public (hello-world (input int))
  (print (+ 2 input))
  (ok input))
```

The defined function evaluates each of the body expressions, returning the value of the last expression.

**Comment by kantai** [comment]
I agree with this, and it would be relatively straight-forward to implement this via the sugar expander.

**Comment by njordhov** [comment]
@kantai Thanks for the heads-up! The implementation in #1435 follows your advice elsewhere about expanding multiple body expressions into a `begin` expression during preprocessing. 

I checked out implementing it via the sugar expander, but it would take implementing a parser for pre-expressions to be more than a kludge. Instead, the expansion is done while parsing the symbolic syntax tree into abstract syntax, which already is nicely [implemented for definitions](https://github.com/blockstack/stacks-blockchain/blob/master/src/vm/functions/define.rs).

**Comment by kantai** [comment]
Not stale -- this is still a feature we should implement

**Comment by njordhov** [comment]
> Not stale -- this is still a feature we should implement

Implemented in https://github.com/blockstack/stacks-blockchain/pull/1435

**Comment by psq** [comment]
@njordhov if you mean you can do something like:
```
(define-public (mint (recipient principal) (amount uint))
  (print "token-swapr.mint")
  (print contract-caller)
  (print amount)
  (if (is-eq contract-caller 'ST3J2GVMMM2R07ZFBJDWTYEYAR8FZH5WKDTFJ9AHA.swapr)
    (ft-mint? token amount recipient)
    (err no-acccess-err)
  )
)
```
this does not work with the latest, and I had to wrap the `print`s and `if` in a `begin`

but this would indeed be desirable (I was adding the `print` calls to debug something)
