### ISSUE TITLE
stacks blockchain tests

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain#1353]
Are there tests, automated or otherwise that I can run to ensure the validity of builds?   While building I noticed that I could not get a working build without the "developer-mode" feature.

**Comment by jcnelson** [comment]
Hey @dantrevino, not sure what you mean?  Can you give the output from `cargo` that's preventing you from building without a developer-mode feature?

**Comment by dantrevino** [comment]
user error
