### ISSUE TITLE
Testnet faucet API endpoint for STX

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1359]
(Not sure who exactly to assign this to; please remove/reassign from the issue as applicable).

We need to implement a testnet faucet API endpoint.  The faucet API endpoint needs to implement a HTTP POST endpoint that takes a Stacks address and an amount of uSTX, and in the background, generates and sends a `TokenTransfer` transaction to fund the given address.  The transaction should be signed using a private key that gets its tokens allocated in the testnet node's genesis block.

This service should be coupled with a web front-end faucet.

**Comment by hstove** [comment]
Hey - I already have a faucet server built and tested. It's a basic node.js server, with an ENV variable for the faucet's private key. We would just need to use the private key for some genesis address.

**Comment by jcnelson** [comment]
Excellent!  Is there a repo where it's being developed?

**Comment by agraebe** [comment]
I seem to lack rights to assign someone else from the devx team, but I believe @yknl is the best for this ticket

**Comment by hstove** [comment]
@jcnelson , it's in the UX monorepo, in a PR. [See this commit](https://github.com/blockstack/ux/pull/301/commits/a0eaaf5e92c739b78b7d788a238fe7631002fb03) for the initial implementation

**Comment by jcnelson** [comment]
Cool!  Looks like we can close this issue then.
