### ISSUE TITLE
"God node" for Neon testnet

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1361]
This task involves fleshing out the rest of the Neon testnet node, to the point where it can not only mine and process transactions into blocks, but also (1) make them available for download and (2) push them out into the peer network.  It should also receive transactions relayed from the mempool.

**Comment by lgalabru** [comment]
@jcnelson @kantai is the neon master node:
1. mining/ruling a bitcoin regtest chain
2. mining/ruling a bitcoin regtest chain and mining/ruling the stacks chain

My understanding is that it does `1`, and that anyone can mine the stacks chain.

**Comment by jcnelson** [comment]
If we can do (2), then we should.  However, I think the node should always _attempt_ to mine a Stacks block in each Bitcoin block, in case no one else is mining.

**Comment by lgalabru** [comment]
Should we spawn 10-20 nodes doing some stacks mining, so that we have a baseline and start observing the technical behavior of the chain with many peers, without relying on growth?

**Comment by jcnelson** [comment]
Sure, if it's not too much trouble (but don't worry about it if it takes too much time).  You'd still need one node controlling the bitcoin regtest node, but the rest of the nodes ought to be able to synchronize their chainstate and bitcoin headers.

**Comment by kantai** [comment]
In my mind it becomes a question of what we want to focus our attention on in Neon --

Scenario 2: Other nodes in the network would be testing (and hopefully stressing) the mempool, block downloader, and RPC functionalities of the blockchain, as well as the transaction processing (and therefore Clarity VM).

Scenario 1: Does all of the above _and_ tests the sortition behavior.

I think, in all likelihood, we'll discover plenty of bugs just with Scenario 2 -- by constraining the sortitions, I think we'll end up with easier to debug problems. But this isn't exactly strongly held. So, if you all think it's worthwhile to do sortitions as well in neon, then I'm on board with that.

**Comment by jcnelson** [comment]
I don't think the difference between (1) and (2) is particularly big, from an implementation standpoint.  If we implement (1), we get (2) for free by just blocking inbound bitcoin transactions.  We can implement (1), but deploy as (2) and then transition to (1) once we've convinced ourselves that we fixed all the bugs discovered while running as (2).

**Comment by kantai** [comment]
> If we implement (1), we get (2) for free by just blocking inbound bitcoin transactions. 

Yep -- that was pretty much what I was thinking we'd do. Maybe even easier than that -- we can just not provide a regtest bitcoin faucet.
