### ISSUE TITLE
Integrate P2P and HTTP network state machines into Helium testnet node

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1362]
The main loop for the Helium testnet node should drive the peer network by calling the `PeerNetwork::run()` method every iteration, and consume any blocks, microblocks, and transactions it emits.  In order to avoid starving the network due to (I/O-intensive) block processing, it would be best if the node ran a separate thread to run the network, and buffered up blocks, microblocks, and transactions to be written in a separate thread.

**Comment by kantai** [comment]
Implemented in #1382
