### ISSUE TITLE
Add post-condition results to sidecar messages

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1375]
Current Explorer UI requirements have a display for post-condition(s) status (fail/success). These could be added to the tx JSON message payload.

The format can simply be a boolean array. e.g.
```ts
interface extends Array {
    [post_condition_index: number]: boolean;
}
```

**Comment by diwakergupta** [comment]
@zone117x is this blocking you?

**Comment by aulneau** [comment]
@diwakergupta this is kind of blocking me. We have it designed, and it would be useful information to display. For the time being I will implement a more static version of this until this feature is implemented.

![Screen Shot 2020-05-06 at 9 04 56 AM](https://user-images.githubusercontent.com/11803153/81190440-77b11780-8f7d-11ea-8278-1c34e190cc9d.png)

**Comment by diwakergupta** [comment]
Thanks @aulneau.

Just so I understand the ask, you need some more information in the events we emit to the sidecar. @zone117x is this something you can add?

If not, @lgalabru can you comment on the complexity / scope? Seems like should be a straight forward change.

**Comment by aulneau** [comment]
I don't exactly know the ask as far as it relates to where it should live, someone like @zone117x can answer that better. 

Here is an example response of some post condition data:
```tsx
"post_conditions": [
    {
      "type": "stx",
      "condition_code": "sent_greater_than_or_equal_to",
      "amount": "1",
      "principal": {
        "type_id": "principal_standard",
        "address": "ST3TYD6PWK9621JBT15T5ZYJ70EBSTXSFZ8T7X6YW"
      }
    },
    {
      "type": "stx",
      "condition_code": "sent_greater_than_or_equal_to",
      "amount": "2",
      "principal": {
        "type_id": "principal_standard",
        "address": "ST3TYD6PWK9621JBT15T5ZYJ70EBSTXSFZ8T7X6YW"
      }
    },
    {
      "type": "stx",
      "condition_code": "sent_greater_than_or_equal_to",
      "amount": "3",
      "principal": {
        "type_id": "principal_standard",
        "address": "ST3TYD6PWK9621JBT15T5ZYJ70EBSTXSFZ8T7X6YW"
      }
    },
    {
      "type": "stx",
      "condition_code": "sent_greater_than_or_equal_to",
      "amount": "4",
      "principal": {
        "type_id": "principal_standard",
        "address": "ST3TYD6PWK9621JBT15T5ZYJ70EBSTXSFZ8T7X6YW"
      }
    }
  ]
```
In the initial designs we had some status assigned to each (success/failed). I don't fully understand post conditions and how they work, but I'd assume that an ideal response would be like this:

```tsx
 {
      "type": "stx",
      "condition_code": "sent_greater_than_or_equal_to",
      "amount": "4",
      "success": false,
      "principal": {
        "type_id": "principal_standard",
        "address": "ST3TYD6PWK9621JBT15T5ZYJ70EBSTXSFZ8T7X6YW"
      }
    }
```

Thinking about it now though, it might not be a simple true/false. Just because a post condition hasn't been met yet, does that mean its state should be described as failed? @zone117x or @lgalabru can you add some color to this?

**Comment by zone117x** [comment]
@lgalabru could probably implement this in rust much quicker than I could, although I could take a crack at it if needed

**Comment by lgalabru** [comment]
Can take a crack at it, after looking at this quickly, this data is currently deeply shallowed, there's a good amount of re-wiring required. Probably a day or two.
