### ISSUE TITLE
Consolidate Clarity Coercions

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1377]
The Clarity type assertion/coercion functions [to-int](https://docs.blockstack.org/core/smart/clarityref#to-int), [to-uint](https://docs.blockstack.org/core/smart/clarityref#to-uint) and [as-max-len](https://docs.blockstack.org/core/smart/clarityref#as-max-len) can be consolidated into a special form `as` that takes the type as first argument:

```clojure
    (as int u238)           ;; Returns 238
    (as uint 238)           ;; Returns u238
    (as (buff 5) "abc")     ;; Returns "abc" typed with max length 5
    (as (buff 2) "abc")     ;; Returns none
```

Context: #1139 #1116

**Comment by kantai** [comment]
In general, we try not to use too many specially typed functions (i.e., functions whose types would depend on their input), so for now, I don't think we'd want to pursue this. However, we may revisit this if it turns out the current coercions aren't expressive enough for most use cases.
