### ISSUE TITLE
Ability for blockstack-cli to generate contract-call with post-conditions

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1380]

**Comment by diwakergupta** [comment]
@lgalabru is this meant for the current sprint? If so can you set the milestone appropriately, thanks.

**Comment by friedger** [comment]
How would the command line arguments look like?

**Comment by diwakergupta** [comment]
This will likely be addressed as part of CLI being developed by the DX team.

**Comment by lgalabru** [comment]
This issue is not relevant anymore, this feature has been implemented in our stacks-transaction-js
