### ISSUE TITLE
Create a new `clarity-sdk` release and tag

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#1383]
`clarity-js-sdk` relies on Github releases to provide pre-built binaries. Right now, it's set to use the tag [`clarity-sdk-v0.0.5`](https://github.com/blockstack/stacks-blockchain/releases/tag/clarity-sdk-v0.0.5), which is pretty out of date. Users can still install by building from source, but it's a much longer install time and requires rustup.

It would be great if we could create a new release, especially after merging Dan's arm64 fixes. I'm happy to help here if you'd like.

**Comment by zone117x** [comment]
These release binaries have historically been published to the clarity-js-sdk repo. Latest here https://github.com/blockstack/clarity-js-sdk/releases/tag/clarity-sdk-v0.0.5

This is the build script that deploys the binaries https://github.com/blockstack/clarity-js-sdk/blob/clarity-sdk-v0.0.5/tools/build_clarity_dists.sh

The cross compiling scripts are here: https://github.com/blockstack/stacks-blockchain/blob/master/build-scripts/docker-run.sh

**Comment by zone117x** [comment]
Published dist builds for latest master https://github.com/blockstack/clarity-js-sdk/releases/tag/clarity-sdk-v0.0.6
