### ISSUE TITLE
Repo size is 3.6 GB on disk

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1387]
Most of the size appears to be log files in `legacy/integration_tests/blockstack-consensus-data`. 

Can these safely be removed? 

![image](https://user-images.githubusercontent.com/1447546/78248109-511a3f80-74ec-11ea-8615-cd60fa19e0b7.png)

**Comment by jcnelson** [comment]
We can move them to a different repository and turn this into a submodule, but I'd prefer not to delete them until we're completely off of Stacks 1.0

**Comment by zone117x** [comment]
Closed https://github.com/blockstack/stacks-blockchain/pull/1419
