### ISSUE TITLE
Insert multiple entries into Clarity maps

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1393]
Higher order functions like `map`, `fold` and `filter` are staples of functional programming. They are preferably used with _pure input functions._ Avoiding mutating side-effects in their input functions makes it easier to reason about the code. Unfortunately: 

> Since map, filter, fold are the only methods of iteration in Clarity, mutation in those functions is the only mechanism for iteratively applying mutations. 
https://forum.blockstack.org/t/declarative-clarity/10095/5

A better mechanism can be offered through built-in functions that can insert or update _multiple entries_ in a persistent map. This leaves the higher order functions to **generate entries without mutating global state** in their input functions,  taking us closer to a  more [declarative Clarity](https://forum.blockstack.org/t/declarative-clarity/10095/2).

For example, to mint tokens in a list of accounts, a new built-in function called say `map-extend` could insert a generated list of entries into a persistent map:

```clojure
(define-map tokens ((account principal)) ((balance int)))

(define-private (init-token (account principal))
   { account: account,
     balance: 100 })))

(define-public (mint! (accounts (list 10 principal)))
  (let ((transactions (map init-token accounts)))
     (map-extend tokens transactions)))
```

Here `transactions` is a list of `{account, balance}` tuples that are inserted into the persistent `tokens`. 

Using the suggested `map-extend` **lifts the mutation to the public function**, benefiting static analysis and unit testing. There should also be a similar built-in function that can update multiple existing map entries.

**Comment by njordhov** [comment]
> There should also be a similar built-in function that can update multiple existing map entries.

What about naming this function `map-into`?

**Comment by kantai** [comment]
I think something like this could be helpful, however, it would need to be something of the form

`(map-set-all? data-map-name (list keys) (list values))`

Since keys and values must be explicitly provided.

`set-all` would also I think more accurately convey the operation that is happening.

**Comment by njordhov** [comment]
> set-all would also I think more accurately convey the operation that is happening.

Good idea using the `-all` suffix for functions like these.

> Since keys and values must be explicitly provided.

Is this really the case though? The keys are already declared in `define-map` thus known to the system. A `map-set-all` or `map-insert-all` function can use this information to split entries into keys and values as needed. See also #1334.
