### ISSUE TITLE
Compressed encodings of RPC endpoints

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1397]
The JSON-returning endpoints of blockstack-core are fairly inefficient encodings of their information. For example, byte buffers are encoded as hex strings.

This could be solved by using something like base64 instead of hex strings, or by enabling HTTP compression.

For my part, I think HTTP compression is the more generic and efficient solution -- after all, it should be able to compress more efficiently than a base64 representation.

**Comment by zone117x** [comment]
Would this be a hand rolled compression negotiation? 
Also, do we feel confident that our core-node http server is wise to expose directly without a proxy (e.g. nginx)?

**Comment by jcnelson** [comment]
> Would this be a hand rolled compression negotiation?

We'd probably just use an off-the-shelf gzip crate to do the encoding/decoding heavy lifting, and wrap that into a `Read` and `Write` trait implementation (which meshes naturally with our HTTP server code).

**Comment by jcnelson** [comment]
Related: https://github.com/blockstack/stacks-blockchain/issues/1086
