### ISSUE TITLE
Add RPC endpoint for get_deployment_cost

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1398]
For now, this will basically just be a stubbed function returning 1*byte length.

**Comment by kantai** [comment]
Related: endpoint for `fees/contract-call`

**Comment by diwakergupta** [comment]
Is this a Neon blocker @kantai ? Is it blocking anything on dev-x @yknl ?

If no to both, I will remove it from the Neon project board.

**Comment by yknl** [comment]
I don't think it's a blocker for devx if setting fee rate for contract deploys to 1 will work on core.

**Comment by kantai** [comment]
> I don't think it's a blocker for devx if setting fee rate for contract deploys to 1 will work on core.

I think it would need to 1*byte_len, similar to the STX transfer.

When deployment cost is factored in, the fee rate will be something like:

size_cost + deploy_cost

where size_cost = fee_rate_per_byte * transaction_size,

and deploy_cost is a function of the contract content.

So I think _this_ endpoint would be responsible for calculating deploy_cost, whereas the same endpoint used for transfer should be used to obtain the fee_rate_per_byte.
