### ISSUE TITLE
Add RPC endpoint for get_constant

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1400]

**Comment by jcnelson** [comment]
Isn't this just something you'd pull out of the contract analysis data?

**Comment by kantai** [comment]
It'd be pulled out of the database metadata, but the contract interface data just contains type information, not the actual values. This value, while constant, is still a little similar to data map reads and data-var reads in that the actual value of the constant _isn't_ strictly a result of the contract definition (i.e., this constant could have been set by reading from some other contract during initialization).
