### ISSUE TITLE
Improving integration test throughput

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1401]
I think we should think about improving the throughput of our `cargo test` command -- right now, it takes about 90 minutes to run the cargo tests on Circle CI.

**Comment by jcnelson** [comment]
I've been incrementally refactoring the p2p tests so they all use different ports, which was the reason for using `--test-threads 1`.  If we can also increase the number of file descriptors available for the test process, we should be able to run those in parallel now.

**Comment by diwakergupta** [comment]
> right now, it takes about 90 minutes to run the cargo tests on Circle CI.

Oh wow, that's not great. How long do they take to run locally? Anecdotally, I've found tests taking longer than 10-15 min start to slow development down, esp. as people start to rely on CI checks to flag regressions.

Another option to explore might be to have a "light" test suite for local development that's maybe less comprehensive, or explicitly flag "long-running" tests that only run in the CI environment prior to merges.

**Comment by jcnelson** [comment]
We could probably do a "light" suite.  We already disable at least one of the heavier MARF tests by default because it alone takes about 30 minutes to run.  We control it with an environment variable.

**Comment by kantai** [comment]
> We could probably do a "light" suite. We already disable at least one of the heavier MARF tests by default because it alone takes about 30 minutes to run. We control it with an environment variable.

If we're going to go this route, we should probably use the `#[ignore]` directive for cargo tests -- that way, we won't get `...ok` outputs for the tests that are being excluded via an envar (which may confuse into thinking those tests actually ran).

**Comment by jcnelson** [comment]
Ah, that's even better.  Let's do that instead.

**Comment by kantai** [comment]
I'll open a quick PR that just `#[ignore]`s any tests that either fail when concurrent or take more than 60s -- then we can work on improvements from there.
