### ISSUE TITLE
Allow concurrent access to the burndb and chainstate

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1402]
We're going to need to allow concurrent access to the burndb and chainstate dbs -- the peer network will be running in a separate thread, and it needs to be able to have read-only access to those DBs.

**Comment by jcnelson** [comment]
I think this is blocked on #1130.  While some methods on both the burndb and chainstate can be accessed concurrently right now, any API calls that access MARF'ed state currently require a transaction.  If we keep the MARF state in a sqlite DB of its own, then it'll become possible to safely do concurrent reads from different threads (by nature of this being guarded by sqlite).

**Comment by jcnelson** [comment]
I'm not sure this is done.  I thought this also included removing the need for opening a transaction against a MARF'ed database in order to just read from it?

**Comment by kantai** [comment]
> I'm not sure this is done. I thought this also included removing the need for opening a transaction against a MARF'ed database in order to just read from it?

That seems unrelated to this -- I think that concurrent access for the RPC service works without this. This is also I think already possible -- `ClarityInstance` exposes `read_only_connection`, which doesn't require beginning a new block.

**Comment by jcnelson** [comment]
Fair enough.  As long as it's safe to have two `mut StacksChainState` and two `mut BurnDB` instances in use concurrently, then my concern is addressed.

**Comment by kantai** [comment]
> As long as it's safe to have two mut StacksChainState and two mut BurnDB instances in use concurrently, then my concern is addressed.

Yes -- that's the case for at least the way that they are currently being used -- if not, I think that we should file any bugs more explicitly than in this issue. I think that an intrepid caller of StacksChainState and BurnDB could do things that would get them into trouble with two instances.

Ultimately, I think we should have constructors for BurnDB and StacksChainState that take a read only parameter, since that'll be a much safer way to use them, however, I don't think that should be a blocker for the neon release. So, I'd suggest we close this issue, moving that to issue https://github.com/blockstack/stacks-blockchain/issues/1449.

**Comment by jcnelson** [comment]
Agreed.
