### ISSUE TITLE
Factor option case from match in Clarity

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1403]
This is a proposal to factor out the *option type* case from `match` into a new `if-let` special form.

PR #1174 introduces a `match` construct that matches on optional- and response types. However, the two cases have slightly different signatures:

```
;; response case
;; args are input, var-name for ok, closure for ok, var-name for err, closure for err

(match resp-input bind-name-ok ok-expr bind-name-err err-expr)

```
In the *option* case, there is [weirdly](https://github.com/blockstack/stacks-blockchain/pull/1174#discussion_r358888545) no binding for the *none* branch:

```clojure
;; option case: 
;;  args are input, var-name for the some type, closure for some case, closure for none case

(match opt-input bind-name some-expr none-expr)
```

The option case is functionally equivalent to:

```clojure
(if (is-none? opt-input)
   (let ((bind-name (unwrap opt-input)))
     some-expr)
   none-expr)
```
  
For clarity and readability, the option case can be factored into a new `if-let` construct:

    (if-let ((bind-name opt-input)) some-expr none-expr)

Factoring out the option case obviates syntax diagnosis as implemented in 333838f.

Related: #1138 #1081

**Comment by kantai** [comment]
I think this is a good idea -- reducing function name overloading would make things more clear.
