### ISSUE TITLE
Clarity silently ignores error responses in multi-expression forms

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1409]
Clarity silently ignores error responses in multi-expression forms, specifically in the body of the `let` special form and the `begin` native function, with negative implications for contract safety.

```scheme
(begin (err 0))  ;; errs as expected
(begin (err 0) 666) ;; evaluates to 666, ignoring the error
(let ((ev 666)) (err 0))  ;; errs as expected
(let ((ev 666)) (err 0) ev) ;; evaluates to 666, ignoring the error
(define-private (fail) (err 0)) (let ((a 666)) (fail) a) ;; returns 666 , ignoring the error
``` 

This outcome follows the current implementation:

1. The `begin` native function pops the evaluated result in the last argument, ignoring the evaluated results from earlier expressions:

https://github.com/blockstack/stacks-blockchain/blob/028375815333d9756fdafc58d708ace7d1c3192e/src/vm/functions/mod.rs#L214-L219

2. The implementation of `let` drops the result of all but the last expression, without handling error responses:

https://github.com/blockstack/stacks-blockchain/blob/028375815333d9756fdafc58d708ace7d1c3192e/src/vm/functions/mod.rs#L340-L345
 
Related: #1042

**Comment by lgalabru** [comment]
Tagging https://github.com/blockstack/stacks-blockchain/issues/972

**Comment by Heidi69** [comment]
Need my log in details amd wallet name

**Comment by friedger** [comment]
This is fixed by https://github.com/blockstack/stacks-blockchain/pull/2122

**Comment by njordhov** [comment]
Yes, covered by #2122 to catch it during type checking, and ClarityTools implementing security by default for expression blocks.
