### ISSUE TITLE
Allow multiple transactions per address per block

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1417]
The current implementation of the mempool admission, via nonce checks, only allows one transaction per address per block.

**Comment by jcnelson** [comment]
If we're willing to limit the number of outstanding transactions per account to something reasonable (e.g. 10), then adding this to the `feature/mempool-relay` PR should be doable.

**Comment by jcnelson** [comment]
Actually, this is going to take a bit more work.  Will leave this for a separate PR.

**Comment by diwakergupta** [comment]
Per @kantai this can be closed: mempool does allow multiple transactions per address. When you have a moment, can you link to the relevant PR that fixed it?

**Comment by kantai** [comment]
Yep, this was implemented in https://github.com/blockstack/stacks-blockchain/pull/1697
