### ISSUE TITLE
Ability to start / stop / restart testnet gracefully 

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1418]

**Comment by zone117x** [comment]
Support for SIGTERM would be really helpful

**Comment by lgalabru** [comment]
After investigation, the first obstacle for a crashed / interrupted node is re-opening its chain state - crashing because of partial write errors.
After checking with @kantai, we will wait for https://github.com/blockstack/stacks-blockchain/issues/1130 to be resolved for tackling this issue.

**Comment by diwakergupta** [comment]
@lgalabru I think we can close this now?
