### ISSUE TITLE
Issue trying to clone

### ISSUE THREAD

**Issue by ERPGenie** [blockstack/stacks-blockchain#1424]
I get the following issue when trying to clone the GIT
![image](https://user-images.githubusercontent.com/30003201/79390762-289b3800-7f25-11ea-914e-ba4670ec95f9.png)

**Comment by diwakergupta** [comment]
Likely an issue with your git setup, or some intermittent network issue. Between CI and other workflows, this repo gets cloned several times a day (likely more) with no issues. I suggest trying some of the workarounds listed here:

https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed
