### ISSUE TITLE
Prometheus integration for monitoring

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1432]
For our own uses, and anyone else that wants to monitor their node with prometheus, we should emit prometheus events for monitoring health and other statistics of our node.

To make sure that this isn't something that is absolutely required to run, these events should be gated with a compiler flag (probably a cargo feature).

Things we'd probably want to monitor:

1. Block processing events (block process times)
2. Transaction propagation
3. Mempool / Peer network statistics (these are already getting collected)
4. Bitcoin block processing times

**Comment by xanbots** [comment]
The above in Aaron's comment would be great to have.

We also have a more immediate need to simply understand how many node's have been running at peak, or any given time, and how many miner's have been participating or at least successfully mined a block.

Could we create a system that automatically records the IP address or some unique address for each node and throws it in a database? Similarly when we have mining working, automatically record the IP address and testnet BTC address for each mined block in a database.

This would give us some much needed info while getting around the problem of the testnet resetting. Any big blockers to doing this? cc @diwakergupta @pstan26 @cuevasm

**Comment by diwakergupta** [comment]
@lgalabru is any of the above already getting logged into kibana?

**Comment by lgalabru** [comment]
@diwakergupta yes, things of this nature are currently getting logged in kibana (ip/public key are logged by the bitcoin-neon-controller).

**Comment by wileyj** [comment]
If the logs could be emitted in json format with commonly used keynames, that would be ideal. It would allow easier log mgmt and graphing of patterns.
