### ISSUE TITLE
BadNonces - InvalidStacksTransaction error on publishing contract

### ISSUE THREAD

**Issue by ERPGenie** [blockstack/stacks-blockchain#1433]
I performed the following steps:

1. cargo run --bin blockstack-cli publish cdcbd655254f62cb9ec5f18b73c34682fed55e504575f332266b2e70bd1a931a01 500 0 kv-store ./kv-store.clar --testnet | xxd -r -p > tx1a1.bin
2: curl -X POST -H "Content-Type: application/octet-stream" --data-binary @./tx1a1.bin http://localhost:9000/v2/transactions

I get the following error after executing (2)

    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/blockstack-cli publish cdcbd655254f62cb9ec5f18b73c34682fed55e504575f332266b2e70bd1a931a01 500 0 kv-store ./kv-store.clar --testnet` 
erpgenie@Blockstack:~/blockstack/stacks-blockchain$ vi tx1a1.bin
erpgenie@Blockstack:~/blockstack/stacks-blockchain$ curl -X POST -H "Content-Type: application/octet-stream" --data-binary @./tx1a1.bin http://localhost:9000/v2/transactions
{"reason":"BadNonces(InvalidStacksTransaction(\"**Bad nonce**: origin account ST1N8DRKK9TB3Y43SR2PBNM9TG1VHEQ95RV7MQ0EV nonce of tx 50c171683d7816189f24532b208c2d59af808f830a60b36d5717b0132d20b75f is 0 (expected 1)\"))","txid":"50c171683d7816189f24532b208c2d59af808f830a60b36d5717b0132d20b75f","error":"**transaction rejected**"}erpgenie@Blockstack:~/blockstack/stacks-blockchain$ ^C
erpgenie@Blockstack:~/blockstack/stacks-blockchain$

**Comment by kantai** [comment]
Was this the second transaction constructed by that key? Each transaction from a given address must use a new nonce -- the nonce is the third parameter in the publish command (in your command, you supplied a nonce of "0", which is only valid if it is the address's first transaction).

**Comment by tyGavinZJU** [comment]
> Was this the second transaction constructed by that key? Each transaction from a given address must use a new nonce -- the nonce is the third parameter in the publish command (in your command, you supplied a nonce of "0", which is only valid if it is the address's first transaction).

One question: Is there any APIs for client to get the transaction nonce from a given address?

**Comment by kantai** [comment]
Yes — /v2/accounts will return the nonce.
