### ISSUE TITLE
Parsing symbolic syntax into abstract representation

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1440]
[DefineFunctionsParsed](https://github.com/blockstack/stacks-blockchain/blob/7fd5a8970c69e2208ee3c1d736422fa6dd357ee5/src/vm/functions/define.rs#L172) does a great job in parsing top level *symbolic syntax* into an abstract syntax representation of definitions. While the resulting representation is used to evaluate definitions, it also benefits analysis like the *read only checker* and the *type checker* so neither have to implement redundant parsing of the symbolic representation.

However, the symbolic syntax for other expressions is still parsed during both analysis and evaluation. **Often this is redundant code and duplicated effort, with the same expressions being parsed and validated by similar code during analysis as evaluation.** The hardcoding of symbolic syntax parsing in multiple locations also complicates evolving the Clarity language beyond the surface syntax.

**The remedy is to parse the symbolic syntax of expressions into an abstract syntax representation for use in analysis and evaluation**, similar to how the symbolic representation of definitions are parsed into abstract definitions. This could be the last step in generating the AST, perhaps initially implemented as a separate parser like the definition parser.

**Comment by kantai** [comment]
This is a good point @njordhov -- I think some refactoring of the treatment of native functions is probably a good idea. In particular, it would be great for native functions to define their input and output types in a single location, and for that to be used by the static analysis, interpreter, and docsgen.

However, I think we should take the approach for now of doing something similar to the `DefineFunctionsParsed` -- something that modularizes and factors out repeated code, but doesn't generate a new abstract representation that is passed between phases.
