### ISSUE TITLE
Generate a "Miner CLI" binary

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain#1441]
**Is your feature request related to a problem? Please describe.**
Current binary targets are:
```bash
Available binaries:
    blockstack-cli
    blockstack-core
    clarity-cli
```

**We need a dedicated binary that acts as an entry point for miners**. On a related note, we need to clean up / rescope our binary targets so each binary has a well-defined purpose (and a descriptive name that makes that obvious).

**Describe the solution you'd like**

Copying @jcnelson's list from an internal email thread:

The act of mining a block is as follows:
1. Register your VRF key as a Bitcoin transaction, in at least one Bitcoin block prior to your mining of the block
2. Gather the transactions you want to mine and package them into a block
3. Make a block-commit transaction that commits to your VRF key and the hash of the block
4. Broadcast that block
5. Generate and broadcast microblocks to append to it (optional, but recommended)

> "a separate CLI miner program that can do all of these things.  It would coordinate with a running stx-node to produce the block (either via RPC or via directly reading its chainstate), but it would be responsible for steps 1, 3, 4, and 5."

**Comment by jcnelson** [comment]
Temporarily assigning myself to this.  I'll need to create a rudimentary binary to test out the "get_block_template" RPC call.

**Comment by diwakergupta** [comment]
This is targeted towards a production mining setup, doesn't block opening up mining on the testnet.

**Comment by diwakergupta** [comment]
Maybe we should move this to the cli-blockstack repo instead.

**Comment by diwakergupta** [comment]
Closing in favor of #1969
