### ISSUE TITLE
Add RPC endpoint for querying and bulk-downloading the mempool

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1447]
So we can query pending transactions, give booting nodes a fast way to sync their mempools, and give explorers a way to query transactions that aren't yet confirmed.

**Comment by diwakergupta** [comment]
@jcnelson is this a Neon blocker? (doesn't sound like it) If not, can you remove it from the project board?

Is it a blocker for the explorer? cc/ @zone117x

**Comment by jcnelson** [comment]
It's a blocker for allowing anyone to mine blocks, but I don't think we have a separate project for that?
