### ISSUE TITLE
Execution cost for STX transfer transactions?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1460]
Right now, the Clarity VM doesn't get invoked to process `TokenTransfer` payloads, which means that the only resource limit that applies to them is their encoded length.  Is this what we intend going forward?

**Comment by friedger** [comment]
Let the money flow freely! :moneybag:

**Comment by kantai** [comment]
> Right now, the Clarity VM doesn't get invoked to process TokenTransfer payloads, which means that the only resource limit that applies to them is their encoded length. Is this what we intend going forward?

Yeah -- that was sort of what I was thinking, since the payload processing is otherwise constant (modulo processing larger signatures, captured by the payload length), right?

**Comment by jcnelson** [comment]
Sounds good to me.  Signature verification is O(n) in the encoded length, but you're already paying for that with the transaction fee.  Let the money flow freely! :moneybag:
