### ISSUE TITLE
[Mocknet] Bad Nonce on first transaction

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1461]
**Describe the bug**
After starting testnet, the first transaction is rejected with 
```
ERROR [1587545089.824] [testnet/src/tenure.rs:78] Failed mining transaction - Bad nonce: origin account ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M nonce of tx d5dda9d1ec5cd758b4bdd0453ef336507295045068a3bd0b0d65a116b325e0aa is 0 (expected 1)
``` 
The transactions is a contract deploy transaction. (from friedger/clartiy-smart-contracts - escrow sample - calling `yarn escrow`). 

**Steps To Reproduce**
1. clone stacks-blockchain, stacks-transactions-js and friedger/clarity-smart-contracts
1. in stacks-transactions-js call `yarn install build link`
1. in stacks-blockchain call `cargo testnet ./testnet/Stacks.toml` from branch `fix/burn-db-path`
1. in clarity-smart-contracts call `yarn`, `yarn link @blockstack/stacks-transactions`, `yarn escrow`

see that transactions are rejected due to bad nonce

**Expected behavior**
escrow transactions takes place

**Environment (please complete the following information):**
 - OS: ubuntu
 - Rust version: 1.42.0

**Additional context**
The transactions used to be accepted in an early version of the testnet.

**Comment by zone117x** [comment]
Running into same problem. 

When using the correct nonce (fetched from the account info RPC), the POST request succeeds, but the console outputs a bad nonce error.

When using nonce + 1 (what the console error suggestions), the POST request fails with:
```json
{"reason":"BadNonces(InvalidStacksTransaction(\"Bad nonce: origin account ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH nonce of tx 6b67d124763a8c5102404c1649ce78276d7b330f880df8c26301b8b511bb560d is 1 (expected 0)\"))","txid":"6b67d124763a8c5102404c1649ce78276d7b330f880df8c26301b8b511bb560d","error":"transaction rejected"}
```

And the console still shows bad nonce.

**Comment by lgalabru** [comment]
Addressed with #1456

**Comment by friedger** [comment]
@lgalabru I am running my testnet from branch fix/burn-db-path

**Comment by friedger** [comment]
@lgalabru I see there is a new commit. Thanks for that!
