### ISSUE TITLE
Variadic map function in Clarity

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1482]
**Is your feature request related to a problem? Please describe.**

The [map](https://docs.blockstack.org/core/smart/clarityref#map) function in Clarity currently is limited to functions that takes a single argument, mapping them over a single sequence.

**Describe the solution you'd like**

The `map` function should be variadic and allow functions that takes more than one argument, mapping them over a number of sequences matching their arity. 

For example:

```clojure
(map + (list 1 2 3) (list 4 5 6))     ;; evaluates to (5 7 9) 
```

**Describe alternatives you've considered**

Transpile from an extended map function with multiple sequences into a call to Clarity's constrained `map` or via `fold`. It's a limited work-around resulting in less comprehensive Clarity code.

Supporting _partial function application_ with `map` can cover some of the use cases.

**Additional context**

Variadic `map` functions are found in similar other languages including [Racket](https://docs.racket-lang.org/reference/pairs.html#%28def._%28%28lib._racket%2Fprivate%2Fmap..rkt%29._map%29%29), [Scheme](https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/Mapping-of-Lists.html), [Common Lisp](http://clhs.lisp.se/Body/f_map.htm) and [Clojure](https://clojuredocs.org/clojure.core/map).

**Comment by kantai** [comment]
I'm supportive of this idea @njordhov -- a variadic map would be helpful for any multiple argument functions.

**Comment by njordhov** [comment]
In functional programming, it is commonplace to use `map` with _partial function applications_ and _anonymous functions_, typically closing over local bindings.  **Variadic map could compensate for Clarity lacking closures** by providing an alternative means to pass arguments from the local context to the mapping function.

With multiple sequences as arguments, it's an open question how to handle lists of different length. [Racket](https://docs.racket-lang.org/reference/pairs.html#%28def._%28%28lib._racket%2Fprivate%2Fmap..rkt%29._map%29%29) takes a strict approach, requiring all input lists to have the same length. In contrast, [Common Lisp](http://clhs.lisp.se/Body/f_map.htm) and [Clojure](https://clojuredocs.org/clojure.core/map) only iterates to the end of the shortest input sequence.  

**Clarity can benefit from variadic `map` implicitly extending shorter input sequences to the length of the longest** by repeating their last item. This can be used to pass on arguments to the applied function, without requiring an explicit expression like using [`repeat`](https://clojuredocs.org/clojure.core/repeat) to fill the shorter sequences. 

As a motivating use case from the Blockstack codebase:
https://github.com/blockstack/stacks-blockchain/blob/27381d64b1e6c8f308537a2c397958a97fdea337/src/chainstate/stacks/boot/pox.clar#L338-L352

Assuming that `map` fills list arguments to have the same length, this could be an alternative implementation:

```clojure
(fold + 
  (map add-pox-addr-to-ith-reward-cycle 
    (list {pox-addr: pox-addr, first-reward-cycle: first-reward-cycle, num-cycles: num-cycles, amount-ustx: amount-ustx})
    (list u0 u1 u2 u3 u4 u5 u6 u7 u8 u9})))
```

It is of course possible to rather use `fold` to accumulate the integers, or even combining into a single reducer. A benefit of using `map` for such mapping is that the applied function will be simpler and more straight-forward, returning a single integer result for each iteration with the accumulated result immediately available, while `fold` has to pass on arguments in the accumulator and requires extracting the accumulated result on completion.
