### ISSUE TITLE
Node crash when failing to write to sqlite

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain#1485]
**Describe the bug**
Node crashed when failing to write to sqlite

**Steps To Reproduce**
1. start node
2. wait for db write failure

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Raspbian (micro sd card)
 - 1.4.2
 - neon testnet

**Additional context**
DEBUG [1587687498.688] [src/chainstate/stacks/index/storage.rs:963] Flush: 6484fa2476a927e6cf25602d386835e1b401b68b704390264916b20c2c12207a to self
DEBUG [1587687498.714] [src/chainstate/stacks/index/storage.rs:995] Flush: identifier of self is 1702
DEBUG [1587687498.715] [src/chainstate/burn/db/burndb.rs:621] ACCEPTED(1701) leader key register ee70919087cef3e54453737de91d58ab4c8ad68db68d566208d65270a5b6f881 at 1701,1
DEBUG [1587687498.716] [src/chainstate/burn/db/burndb.rs:626] ACCEPTED(1701) leader block commit e1359c3f28468e5973ea9e3957f84357a7d006c3848feb677e764fb46d434a66 at 1701,2
DEBUG [1587687498.717] [src/burnchains/burnchain.rs:663] OPS-HASH(1701): a2b283a0dc106fa6e5af3ec15c542eb4b609dd3cafa5fec2fc6d16ee28348fc6
DEBUG [1587687498.717] [src/burnchains/burnchain.rs:664] INDEX-ROOT(1701): 9db6ff6c4fe86f255b85168e298f32c25e281b8b2cd6d602313a68e309663bcb
DEBUG [1587687498.717] [src/burnchains/burnchain.rs:665] SORTITION-HASH(1701): 15109fe4ca0c8ca91b26d2a697862368e6c3fd22d1d0a946be2d8b9d0936eb00
DEBUG [1587687498.717] [src/burnchains/burnchain.rs:666] CONSENSUS(1701): 4322f35d3ecfc89dbe2117e5a8c525b3d607cf5f
thread '<unnamed>' panicked at 'FATAL: failed to commit Sqlite transaction: SqliteError(SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked")))', src/burnchains/burnchain.rs:768:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/burnchains/burnchain.rs:939:50

**Comment by laytond** [comment]
Also seeing some SqliteErrors with the same environment, but I think they're different errors (?)...

**First error:**
thread '<unnamed>' panicked at 'FATAL: failed to commit Sqlite transaction: SqliteError(SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked")))', src/burnchains/burnchain.rs:768:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ThreadChannelError', src/burnchains/burnchain.rs:937:9

**Second error:**
thread '<unnamed>' panicked at 'FATAL: failed to commit Sqlite transaction: SqliteError(SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked")))', src/burnchains/burnchain.rs:768:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR [1587687586.856] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Error in thread channel
thread 'main' panicked at 'explicit panic', testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17

[log-4.23-1.txt](https://github.com/blockstack/stacks-blockchain/files/4526535/log-4.23-1.txt)
[log-4.23-2.txt](https://github.com/blockstack/stacks-blockchain/files/4526536/log-4.23-2.txt)

**Comment by diwakergupta** [comment]
To confirm, both of these failures are on a Raspberry PI, correct? @laytond thanks for the logs but I don't see a backtrace in there. 

@dantrevino how soon after startup do you see the failure? 

Could you both repro with `RUST_BACKTRACE=1` and include that? Thanks.

**Comment by laytond** [comment]
Yeah they're both on a Raspberry Pi.

I'm a noob, so not sure if I'm running backtrace right. Basically just entered `RUST_BACKTRACE=1` and then `export `RUST_BACKTRACE=1` and then `./stacks-node neon`

It's currently running, but I'll check in periodically to see if I get an error and share what I see.

**Comment by laytond** [comment]
I think I did this right @diwakergupta -- let me know if it helps.

[log-4.24-1.txt](https://github.com/blockstack/stacks-blockchain/files/4531080/log-4.24-1.txt)

**Comment by jcnelson** [comment]
Confirmed.  I can reproduce this reliably on my laptop.

**Comment by jcnelson** [comment]
Should be fixed in #1522, which is now in master.  Going to go ahead and close this issue; please re-open if the problem persists.  Thanks for the bug report!
