### ISSUE TITLE
[neon faucet] testnet addresses rejected as invalid

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1487]
**Describe the bug**
entering a testnet address on https://testnet.blockstack.org/faucet fails

**Steps To Reproduce**
1. create a testnet ST address
1. enter this address on https://testnet.blockstack.org/faucet
1. submit
1. see error message

**Expected behavior**
some testnet STX in my account :moneybag: 

**Environment (please complete the following information):**
 - OS: Web

**Comment by Trudko** [comment]
Having a same issue, getting Please enter a valid Testnet STX address and 500 HTTP Status Code from https://crashy-stacky.zone117x.com/sidecar/v1/debug/faucet

**Comment by zone117x** [comment]
This should be fixed now. Note that the follower node used by the faucet is not stable -- crashes with https://github.com/blockstack/stacks-blockchain/issues/1488

**Comment by friedger** [comment]
Thank you!
