### ISSUE TITLE
Failed to get peer address of TcpStream - invalid argument

### ISSUE THREAD

**Issue by lketchersid** [blockstack/stacks-blockchain#1489]
On version clarity-sdk-v0.0.8-419-gfbe1ca5c9 accoding to "git describe" (this is the testnet code from yesterday 4/23/2020)

shortly after successfully processing newly received blocks, testnet hung with the following WARN:

"Failed to get peer address of TcpStream" with the error message "Invalid argument"

Console log attached. 

Will pull updated code and restart
![Screen Shot 2020-04-24 at 5 48 57 AM](https://user-images.githubusercontent.com/3418656/80221162-83f6b580-860a-11ea-9910-407eddd15faa.png)
![Screen Shot 2020-04-24 at 5 48 57 AM](https://user-images.githubusercontent.com/3418656/80221204-8fe27780-860a-11ea-830a-83d2b9a9b985.png)

**Comment by lketchersid** [comment]
Did a git pull, and have the last version running. Got the same error but this time it retried and kept going. So I'm assuming this one can be closed?

**Comment by diwakergupta** [comment]
Yep, the log message doesn't indicate a fatal problem.
