### ISSUE TITLE
Test STX are not transferred

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1490]
**Describe the bug**
After posting a stx transfer transaction the balances are not updated and the logs do not show any errors or warning. How to know what happened?

**Steps To Reproduce**
Send a transaction with blockstack-cli (like https://docs.blockstack.org/core/smart/cli-wallet-quickstart.html), see the transaction id, see the balances are unchanged,

**Expected behavior**
Balances are changed.

**Environment (please complete the following information):**
 - OS: Ubuntu

**Additional context**
It is unclear what is happening, not very technical report, sorry.

**Comment by diwakergupta** [comment]
Can you include the transaction id, relevant STX addresses etc? Thanks!

**Comment by friedger** [comment]
``` 
blockstack-cli send_tokens ST1WZ69T99RHQMQX3D91ZH2R37GV5NK8KDS5D5VDZ 1000 1 0 994d526b3b3409def4d3e481f9c4b3debaf9535cffed0769a7543601e1efa3c501 -t -T "http://127.0.0.1:20443/v2/transactions"
691a2735e0da3682a0383a7e64acea01cad02511ee25be2b57114918294b9e1a
```

**Comment by kantai** [comment]
The TXID `691a2735e0da3682a0383a7e64acea01cad02511ee25be2b57114918294b9e1a`, does not appear to have propagated to the mempool -- and that sender address doesn't appear to have any STX:

`
$ curl -s 127.0.0.1:20443/v2/accounts/ST2P4S7Q4PHGQE9VGG6X8Z54MQQMN1E5047ZHVAF7?proof=0`

```
{
  "balance": "0x00000000000000000000000000000000",
  "nonce": 0
}
```

This might be an issue with the error message either from core or blockstack-cli.

**Comment by kantai** [comment]
Yep -- this appears to be an issue in `cli-blockstack`'s error handling. When trying to broadcast the message via CURL, I, appropriately, get an error:

```
$ ./cmd/index.js send_tokens ST1WZ69T99RHQMQX3D91ZH2R37GV5NK8KDS5D5VDZ 1000 1 0 994d526b3b3409def4d3e481f9c4b3debaf9535cffed0769a7543601e1efa3c501 -t -d -x -T "http://127.0.0.1:20443/v2/transactions" | xxd -r -p - | curl -X POST -H 'Content-Type: application/octet-stream' --data-binary "@-" 127.0.0.1:20443/v2/transactions | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   315    0   135  100   180    589    786 --:--:-- --:--:-- --:--:--  1375
{
  "txid": "691a2735e0da3682a0383a7e64acea01cad02511ee25be2b57114918294b9e1a",
  "error": "transaction rejected",
  "reason": "FeeTooLow(1, 180)"
}
```

**Comment by friedger** [comment]
I tried now
```
cargo run --bin blockstack-cli token-transfer  994d526b3b3409def4d3e481f9c4b3debaf9535cffed0769a7543601e1efa3c501 1000 2 ST1WZ69T99RHQMQX3D91ZH2R37GV5NK8KDS5D5VDZ  100 "My name is Pet3r" --testnet | xxd -r -p - | curl -X POST -H 'Content-Type: application/octet-stream' --data-binary "@-" 127.0.0.1:20443/v2/transactions 
```
The transactions was successful, but the nonce for account `ST2P4S7Q4PHGQE9VGG6X8Z54MQQMN1E5047ZHVAF7` was not updated.

**Comment by friedger** [comment]
Not sure whether some code was changed but with fees of 180+ uSTX I can reliably transfer tokens (using the blockstack-cli in stacks-blockchain) like this:

```
cargo run --bin blockstack-cli token-transfer 3af1c76f27c861d7a0f3e85543c0191dff8d8b8de6d27660aadb18b7f20400a901 1000 1 ST270EMD96BPJE79FPP8V457Y20W259HKR33ZMKWW  100 "My name is Pet3r" --testnet | xxd -r -p - | curl -X POST -H 'Content-Type: application/octet-stream' --data-binary "@-" neon.blockstack.org:20443/v2/transactions 
```
