### ISSUE TITLE
Post-Condition NonFungible Asset names should be Clarity Values

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1491]
**Describe the bug**
SIP 5 states:
```
A Non-fungible token post-condition body is encoded as follows:
* A variable-length principal, containing the address of the standard account or contract account
* A variable-length asset info structure that identifies the token type
* A variable-length asset name string that names the token instance
* A 1-byte non-fungible condition code
```

The line `A variable-length asset name string that names the token instance` is incorrect. 
* The Clarity VM allows src that defines an asset value as any Clarity type (does not match SIP).
* The asset value in a serialized tx is a 1-byte length prefixed string (does match SIP).

One of these should be decided upon.

**Comment by kantai** [comment]
The PostCondition encoding of NFTs needs to be updated. NFT instances are identified by a Clarity value, so a NFT post-condition body should be encoded as:

```
* A variable-length principal, containing the address of the standard account or contract account
* A variable-length asset info structure that identifies the token type
* A variable-length Clarity value serialization that names the token instance
```
