### ISSUE TITLE
testnet compiling missing openssl package

### ISSUE THREAD

**Issue by michaeljiflorida08** [blockstack/stacks-blockchain#1501]
**Describe the bug**
during install and run testnet, error message shows openssl package is missing and the following two commands need to run:

sudo apt install pkg-config

sudo apt install libssl-dev 

**Steps To Reproduce**
git clone https://github.com/blockstack/stacks-blockchain.git
cd stacks-blockchain
cargo install --path ./testnet
stacks-node neon

error message will show "error: failed to run custom build command for `openssl-sys v0.9.55`
Caused by:  process didn't exit successfully:"

**Expected behavior**
installation/compiling/run testnet should run smoothly and no need extra installation

**Environment (please complete the following information):**
 - OS: Ubuntu18.04
 - Rust version: rustc 1.43.0 (4fb7144ed 2020-04-20)

**Additional context**
error: failed to run custom build command for `openssl-sys v0.9.55`
Caused by:  process didn't exit successfully:

**Comment by diwakergupta** [comment]
Fixed with #1502
