### ISSUE TITLE
Implement string type support in Clarity

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1504]
Implement a `string` type(s) in Clarity. This type would be used in many areas where the buffer type is currently used.

It seems useful to have variants for valid-utf8 and printable-ascii -- not sure how this would look.

A use case to keep in mind: 
* A Clarity contract that stores usernames -- currently this would use the buffer type.
* A js app that reads usernames -- currently the app is provided raw data (hex string or w/e).
* Most app developers will simply convert the raw buffer to a utf8 string via `Buffer.from(clarityVal, 'hex').toString()` (without sanity checks or knowing how this could be manipulated). 

Another use case is the Explorer, which cannot easily show useful data for probably the majority of smart contract inputs/outputs/state, because the buffer values need to be display as a hex string, rather than what the smart contract author likely intended (a meaningful string).

**Comment by kantai** [comment]
This is a great idea, and I think this can be implemented primarily through static analysis (the type checking pass) and process_transaction's contract-call arguments check. We'd need to add one or two new type signatures, but no new Value type.

**Comment by diwakergupta** [comment]
@zone117x @lgalabru this can be closed now, correct?
