### ISSUE TITLE
Publish Clarity contract issue on stack 2.0 node  

### ISSUE THREAD

**Issue by minafarouk** [blockstack/stacks-blockchain#1525]
I tried to publish clarity contract on stack 2.0 node following described steps [here ](https://github.com/blockstack/stacks-blockchain#download-and-build-stacks-blockchain) as below and so I got txid

	cargo run --bin blockstack-cli publish 749e3af2fde44928d671f0504e4aa3bc20bd217b2ba3d7c4d2341c2562dd5ce201 500 0 kv-store ./kv-store.clar --testnet | xxd -r -p > tx1.bin
	curl -X POST -H “Content-Type: application/octet-stream” --data-binary @./tx1.bin http://localhost:20443/v2/transactions
	13773c0d12ee0fe4cb52d2efc2deb40ec58d1e16dfd444fa3d08cad8acd03355

but when I am trying to retrieve it using curl -X GET http://localhost:20443/v2/contracts/source/STW0XHQAMD1GM9854DSHTG4QNX7J6F8Y38N3F1C/kv-store I got No contract source data found. And also making after making contract-call and trying to publish it as below:

	cargo run --bin blockstack-cli contract-call 749e3af2fde44928d671f0504e4aa3bc20bd217b2ba3d7c4d2341c2562dd5ce201 500 1 STW0XHQAMD1GM9854DSHTG4QNX7J6F8Y38N3F1C kv-store get-value -e \"foo\" --testnet | xxd -r -p > tx2.bin
	warning: unnecessary parentheses around assigned value
	    --> src/net/mod.rs:1160:35
	     |
	1160 | pub const MAX_PAYLOAD_LEN : u32 = (1 + 16 * 1024 * 1024);
	     |                                   ^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
	     |
	     = note: `#[warn(unused_parens)]` on by default

	    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
	     Running `target/debug/blockstack-cli contract-call 749e3af2fde44928d671f0504e4aa3bc20bd217b2ba3d7c4d2341c2562dd5ce201 500 1 STW0XHQAMD1GM9854DSHTG4QNX7J6F8Y38N3F1C kv-store get-value -e '"foo"' --testnet`
	 curl -X POST -H "Content-Type: application/octet-stream" --data-binary @./tx2.bin http://localhost:20443/v2/transactions
	{"reason":"NoSuchContract","txid":"76ee4d653aff462c6723881b32d0e0e043f2d16824090fc235d1c8b0e0c83c52","error":"transaction rejected"} 

Expected: Publishing the contract normally to be used and listed and getting an error if an error happened .

**Comment by diwakergupta** [comment]
@lgalabru to take a look

**Comment by lgalabru** [comment]
@minafarouk thank you for your feedback!
I'd like to have a close look at your issue, can you copy-paste your toml file here, or ping me on our discord (@ludo)?
Thank you!

**Comment by minafarouk** [comment]
This is testnet/Stacks.toml:
	[node]
	name = "helium-node"
	rpc_bind = "127.0.0.1:20443"

	## Settings for local testnet, relying on a local bitcoind server
	## running with the following bitcoin.conf:
	##
	##    chain=regtest
	##    disablewallet=0
	##    txindex=1
	##    server=1
	##    rpcuser=helium-node
	##    rpcpassword=secret
	##
	# [burnchain]
	# chain = "bitcoin"
	# mode = "helium"
	# peer_host = "127.0.0.1"
	# peer_port = 18444
	# rpc_port = 18443
	# rpc_ssl = false
	# username = "helium-node"
	# password = "secret"
	# timeout = 30
	# local_mining_public_key = "04ee0b1602eb18fef7986887a7e8769a30c9df981d33c8380d255edef003abdcd243a0eb74afdf6740e6c423e62aec631519a24cf5b1d62bf8a3e06ddc695dcb77"
	# burnchain_op_tx_fee = 1000
	# commit_anchor_block_within = 3000

	## Settings for public testnet, relying on a remote bitcoind server
	## hosted by blockstack
	##
	# [burnchain]
	# chain = "bitcoin"
	# mode = "neon"
	# peer_host = "127.0.0.1" # todo(ludo): update URL with neon.blockstack.org when deployed
	# burnchain_op_tx_fee = 1000
	# commit_anchor_block_within = 10000
	# rpc_port = 3000
	# peer_port = 18444

	## Settings for a local testnet simulating a burnchain
	## Best setup for smart contract development
	##
	[burnchain]
	chain = "bitcoin"
	mode = "mocknet"
	commit_anchor_block_within = 5000

	# These are addresses from the README.md
	[[mstx_balance]]
	# Private key: b8d99fd45da58038d630d9855d3ca2466e8e0f89d3894c4724f0efc9ff4b51f001
	address = "ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH"
	amount = 100000000

	[[mstx_balance]]
	# Private key: 3a4e84abb8abe0c1ba37cef4b604e73c82b1fe8d99015cb36b029a65099d373601
	address = "ST26FVX16539KKXZKJN098Q08HRX3XBAP541MFS0P"
	amount = 100000000

	[[mstx_balance]]
	# Private key: 052cc5b8f25b1e44a65329244066f76c8057accd5316c889f476d0ea0329632c01
	address = "ST3CECAKJ4BH08JYY7W53MC81BYDT4YDA5M7S5F53"
	amount = 100000000

	[[mstx_balance]]
	# Private key: 9aef533e754663a453984b69d36f109be817e9940519cc84979419e2be00864801
	address = "ST31HHVBKYCYQQJ5AQ25ZHA6W2A548ZADDQ6S16GP"
	amount = 100000000

	[[mstx_balance]]
	# Private key: 02ca897efffec0f7c633a03e69332526df784bb1b1d041f8369e5f8685f3e3d78a
	address = "STW0XHQAMD1GM9854DSHTG4QNX7J6F8Y38N3F1C"
	amount = 100000000

	## Event dispatcher
	## The stacks blockchain can be observed by sidecar processes, notified through TCP socket, of events such as:
	## - print
	## - stx-transfer / stx-burn
	## - ft-mint / ft-transfer
	## - nft-mint / nft-transfer
	## A demo is available here: https://github.com/blockstack/stacks-blockchain-sidecar
	##
	# [[events_observer]]
	# port = 8080
	# address = "127.0.0.1"
	# events_keys = [
	#     "STGT7GSMZG7EA0TS6MVSKT5JC1DCDFGZWJJZXN8A.store::print",
	#     "STGT7GSMZG7EA0TS6MVSKT5JC1DCDFGZWJJZXN8A.contract.ft-token",
	#     "STGT7GSMZG7EA0TS6MVSKT5JC1DCDFGZWJJZXN8A.contract.nft-token",
	#     "stx"
	# ]
	#[mempool]
	#path = "/root/clarity/stacks-blockchain/mempool"

**Comment by friedger** [comment]
I see a similar issue with mocknet. It looks like that previous transactions are re-added or so.

**Comment by lgalabru** [comment]
The action of publishing smart contracts have been stabilized over the last months and I think that this issue have been addressed.@minafarouk feel free to re-open this issue with some logs if this is not the case. Thank you!
