### ISSUE TITLE
PoX: Stacking wire format for burnchain/bitcoin operations

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1527]
Stacking messages need to deserializable and serializable -- this will involve a new burnchain operation, and a contract-call for a "bootcode" smart contract (for issuing stacking messages on the Stacks chain rather than the burnchain)

**Comment by jcnelson** [comment]
Blocked until we resolve #1857

**Comment by kantai** [comment]
Closed by #2015
