### ISSUE TITLE
PoX: Sortition using the recipient set

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1530]
Given a recipient set, Stacks blockchain sortition needs to be able to validate leader commits and remove used recipients from the current epoch's set.

This will likely interact a lot with #1529

**Comment by kantai** [comment]
The most difficult aspect of implementing this is the requirement on evaluating whether or not a block commit should _burn_ or _transfer_ its committed Bitcoin.

Per the design of Stacking in SIP-007, a block commit should _transfer_ committed Bitcoin to recipient addresses if and only if the following is all true:

1. The current reward cycle selected an anchor block _A_.
2. The node processing a sortition has processed Stacks block _A_.
3. The block commit's parent is either block _A_ or a descendant of _A_.

Checking conditions 1 and 2 is pretty straightforward, given all the supporting changes for PoX. Checking condition 3, however, requires determining if block _A_ is an ancestor of the block commit's `parent_block_ptr`. Naively, we could check this by traversing parent pointers until either block _A_ is reached or passed. However, that could be a very expensive check. Alternatively, we could use a MARF to support this check. Unfortunately, neither the SortitionDB, nor the StacksChainState MARFs are currently set up in a way that could support this: we'd want every sortition winner to have a corresponding trie in the MARF (not the case in the StacksChainState: only processed blocks have tries) and we'd want the parent trie for each sortition winner to be it's `parent_block_ptr` sortition (not the case in the SortitionDB: every trie's parent is the sortition that preceded it).

It feels a little like over-kill to add another MARF specifically for supporting this check, so I wanted to check if anyone had any other ideas, or if I'm missing something that could simplify this problem. Any thoughts, @jcnelson or @lgalabru ?

**Comment by psq** [comment]
if for each block, you keep a reference to its anchor block when you load it, checking if the parent block is either the anchor block, or a descendent should not be costly.

**Comment by jcnelson** [comment]
We will change the base branch of #1863 and merge that instead.
