### ISSUE TITLE
Consider a different / complementary approach for parsing utxo.amount

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1537]
The current parsing does not support float scientific notations used by default by serde for displaying UTXO's amount, returned by listunspent RPC call.

**Comment by jcnelson** [comment]
The problem stems from the fact that Serde converts some values into scientific notation when re-serializing them to strings.  If we just parsed the value directly, before Serde can do it, then the problem should go away.

**Comment by diwakergupta** [comment]
Fixed in master
