### ISSUE TITLE
Miner discard blocks cause Clarity SQLite constraint failures

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1540]
Clarity's MARF side storage relies on blockhash uniqueness for uniquely storing metadata entries. These constraints should not be violated by the Clarity runtime, and should cause panics if they are violated (non-uniqueness in Clarity metadata indicates a bug in the Clarity runtime).

However -- miners during block assembly will construct a MARF block that never is itself included in the processed chainstate. These blocks use non-unique "names", and if a given smart contract is mined more than once by a miner (e.g., in blocks in two different forks), the current strategy of "moving" the metadata to the "blockhash.mined" name will violate the uniqueness constraint.

Instead, the Clarity side store should simply drop the associated data with such block assembly information (or move them to a separate table).

**Comment by diwakergupta** [comment]
Fixed
