### ISSUE TITLE
Mocknet outputs `NoSuchNeighbor` warning every 2 ms

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1549]
In mocknet the following warning is printed endlessly every 1-3 millseconds, making local development really painful.

> WARN [1588902424.815] [src/net/neighbors.rs:1244] Failed to load initial walk neighbors: NoSuchNeighbor

Seems like some network code is running that mocknet shouldn't be using at all?

**Comment by zone117x** [comment]
Ping: this is ~20,000 log entires per minute. It is difficult to work around.

**Comment by aulneau** [comment]
Yeah, I have this too. Would be ideal to not have this logging. cc @lgalabru @diwakergupta
