### ISSUE TITLE
Timed out waiting for headers data

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/stacks-blockchain#1550]
**Describe the bug**

After pulling the code from the main repo and running `cargo testnet neon` this morning, my screen is full of timeout errors. See images in Additional Context.

**Steps To Reproduce**

1. `cd ./stacks-blockchain`
1. `git pull`
1. `cargo testnet neon`

**Expected behavior**

Expected the testnet to run normally.

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.04 LTS
 - rustc 1.43.0
 - Latest version (Latest commit 4ede629 18 hours ago)

**Additional context**

Please include any relevant stack traces, error messages and logs.

![VirtualBox_Blockstack-Testnet_08_05_2020_05_38_27](https://user-images.githubusercontent.com/9038904/81407078-a3eca580-90ef-11ea-8a47-041b7357e69b.png)

I also verified my internet connection is working by pinging 8.8.8.8, and ran it again with the environment variables `RUST_BACKTRACE=full` and `BLOCKSTACK_DEBUG=1`. Results below:

![VirtualBox_Blockstack-Testnet_08_05_2020_05_55_35](https://user-images.githubusercontent.com/9038904/81407969-38a3d300-90f1-11ea-8bb4-545c0c70e145.png)

![VirtualBox_Blockstack-Testnet_08_05_2020_05_57_08](https://user-images.githubusercontent.com/9038904/81407977-3b062d00-90f1-11ea-976b-12137350833d.png)

![VirtualBox_Blockstack-Testnet_08_05_2020_06_00_08](https://user-images.githubusercontent.com/9038904/81407985-3d688700-90f1-11ea-8de8-f4caded40378.png)

**Comment by jcnelson** [comment]
Hi @whoabuddy , thanks for the report!  This is already fixed in https://github.com/blockstack/stacks-blockchain/pull/1548, which should land in master shortly.
