### ISSUE TITLE
Chainstate: Track the presence of PoX anchor blocks

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1551]
The chainstate code paths currently consider a burnchain block to be globally unique.  Once a burnchain block is processed, it is never processed again.

With the advent of PoX, this is no longer true.  A burnchain block will be processed at most twice -- once as if it didn't have a PoX anchor block (i.e. all block-commits are burns), and once as if it did (i.e. all block-commits pay to the VRF-assigned Stacking addresses).  The presence/absence of the PoX anchor block needs to be considered when processing a burnchain block.

To do this, I propose altering the representation of a burnchain block as being a hash derived from both the burnchain block itself, and a bit indicating the presence or absence of the PoX anchor block.  Then, `(burn_block_hash, 0)` != `(burn_block_hash, 1)` will hold true while still treating burnchain block identifiers as hashes.  This will also have the desired side-effect of ensuring that a Stacks anchored block's index block hash will depend on whether or not it was accepted into a reward window with or without a PoX anchored block, which will ensure that two identical Stacks blocks that are processed with/without their reward window's PoX anchored block are treated separately.

**Comment by kantai** [comment]
This was implemented in #1807
