### ISSUE TITLE
Chainstate: only require microblock pubkey hashes to be unique within the same Stacks fork

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1555]
Microblock public key hashes need to be unique only within a given Stacks fork.  We currently treat them as needing to be globally unique across all forks (oops).

**Comment by jcnelson** [comment]
The fact that a public key could be _thought_ to be re-used when it _wasn't_ was due to the bug in the MARF fixed in #1560

**Comment by diwakergupta** [comment]
Fixed in #1560
