### ISSUE TITLE
Bitcoin-neon-controller does not build

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1564]
**Describe the bug**
Bitcoin neon controller does not build or run

**Steps To Reproduce**
```
git clone https://github.com/blockstack/stacks-blockchain
cd stacks-blockchain
cd testnet/bitcoin-neon-controller
cargo build
```
see error
![Screenshot from 2020-05-09 13-18-01](https://user-images.githubusercontent.com/1449049/81472348-d08be480-91f7-11ea-9445-648604282b3a.png)

**Expected behavior**
Get a build success message

**Environment (please complete the following information):**
 - OS: Ubuntu
cargo 1.42.0 (86334295e 2020-01-31)
rustc 1.42.0 (b8cedc004 2020-03-09)

**Additional context**
Same error when calling
```
cargo bitcoin-neon-controller
```

**Comment by diwakergupta** [comment]
@friedger that looks like a transient error. Is this a repeatable failure for you? If so, can you include the full logs from the build, thanks.

**Comment by friedger** [comment]
Working now for me.
