### ISSUE TITLE
Chainstate: Switch the block reward smoothing window to something smaller

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1565]
Right now, rewards are slated to be smoothed over 1008 blocks.  I think this is unreasonably high, since it means that rewards can't mature until 1008 blocks have passed.  I think this value should be no bigger than the maturity window (and according to the fee system we're using, it can be as small as e.g. 10).  But, we can't implement this change until Argon, since it's consensus-breaking.

**Comment by diwakergupta** [comment]
@blockstack/blockchain-team thoughts on what's a more appropriate value? Is this something we should update for Krypton?

**Comment by jcnelson** [comment]
It's currently 16.  This issue can be closed.
