### ISSUE TITLE
Chainstate: Stacks header hash cache should be defined in terms of the index block hash

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1566]
Right now, we identify cached Stacks block header hashes in the downloader by the burnchain header hash.  This is problematic for PoX, where the winning Stacks block can be changed for a given burnchain block.  To fix this, we'll need to identify cached Stacks block header hashes by the _index_ block hash, which would incorporate the requisite information to uniquely identify the Stacks block, even if the sortition history needs to be reorganized after discovering a late anchored block.

**Comment by kantai** [comment]
Are you actively working on this @jcnelson ? Otherwise, I'll start working on this, since I think this will need to be the first step on most of the chainstate-related PoX changes.

**Comment by diwakergupta** [comment]
Fixed by #1807
