### ISSUE TITLE
Include tx failure status code in event receipt

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1568]
RE: https://github.com/blockstack/stacks-blockchain-sidecar/issues/97

We currently have the `success` boolean in the tx receipt message to the sidecar. Would it be possible to add status codes / enums to give a bit more detail about why a tx failed?

**Comment by zone117x** [comment]
Note: this seems related to https://github.com/blockstack/stacks-blockchain/issues/1375
(post-condition failure could be one of the status codes?)

**Comment by diwakergupta** [comment]
To be clear, the tx actually succeeded (as in mined) in this case.

The ask is whether we can return runtime errors in the event receipt.

Non-trivial, but modest and do-able.

**Comment by zone117x** [comment]
Closed by #1612 
Note #1375 (indicate _which_ post-condition failed) is probably easier to implement now
