### ISSUE TITLE
testnet neon miner node issue: Unable to sync with burnchain

### ISSUE THREAD

**Issue by michaeljiflorida08** [blockstack/stacks-blockchain#1573]
Describe the bug (stacks-blockchain build up to Merge pull request #1562) 

run testnet neon miner node, shows error message "Unable to sync with burnchain"

Steps To Reproduce

sudo apt-get install build-essential cmake libssl-dev pkg-config
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env
git clone https://github.com/blockstack/stacks-blockchain.git
seed = "75c0d2c967b8a1b2434cca02f7001f36ebf93f7ab9c97f7fad8b80c1ff97173401"
stacks-node start --config=./testnet/stacks-node/conf/neon-miner-config.toml

shows error message: "Unable to sync with burnchain"

Expected behavior
testnet neon miner node should run smoothly

Environment (please complete the following information):
OS: Ubuntu18.04
rustc 1.43.1 (8d69840ab 2020-05-04)

Additional context:

"
$ stacks-node start --config=./testnet/stacks-node/conf/neon-miner-config.toml

INFO [1589242062.965] [testnet/stacks-node/src/run_loop/neon.rs:46] Miner node: checking UTXOs at address: n2Xs6oXYYAL7UXp4sXn1qzeTsuoWrS2dkk
INFO [1589242067.440] [testnet/stacks-node/src/run_loop/neon.rs:54] Miner node: starting up, UTXOs found.
INFO [1589242067.500] [src/chainstate/stacks/index/marf.rs:764] First-ever block 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
 WARN [1589242985.003] [src/burnchains/bitcoin/network.rs:126] Timed out waiting for headers data.  Killing connection.
WARN [1589242985.003] [src/burnchains/bitcoin/indexer.rs:415] Unhandled error TimedOut
ERROR [1589242985.004] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:144] Unable to sync with burnchain: Try synchronizing again
WARN [1589243045.112] [src/burnchains/bitcoin/network.rs:126] Timed out waiting for headers data.  Killing connection.
WARN [1589243045.112] [src/burnchains/bitcoin/indexer.rs:415] Unhandled error TimedOut
ERROR [1589243045.112] [src/burnchains/bitcoin/indexer.rs:508] Failed to fetch Bitcoin headers from 0 - 16: TimedOut
ERROR [1589243045.113] [src/burnchains/burnchain.rs:792] Failed to check for reorgs from /tmp/stacks-testnet-a630671d54a92cdd/burnchain/spv-headers.dat: TrySyncAgain
ERROR [1589243045.113] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:144] Unable to sync with burnchain: Try synchronizing again
WARN [1589243135.245] [src/burnchains/bitcoin/network.rs:126] Timed out waiting for headers data.  Killing connection.
WARN [1589243135.245] [src/burnchains/bitcoin/indexer.rs:415] Unhandled error TimedOut
ERROR [1589243135.246] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:144] Unable to sync with burnchain: Try synchronizing again
WARN [1589243195.336] [src/burnchains/bitcoin/network.rs:126] Timed out waiting for headers data.  Killing connection.
WARN [1589243195.336] [src/burnchains/bitcoin/indexer.rs:415] Unhandled error TimedOut
ERROR [1589243195.336] [src/burnchains/bitcoin/indexer.rs:508] Failed to fetch Bitcoin headers from 0 - 16: TimedOut
ERROR [1589243195.337] [src/burnchains/burnchain.rs:792] Failed to check for reorgs from /tmp/stacks-testnet-a630671d54a92cdd/burnchain/spv-headers.dat: TrySyncAgain
ERROR [1589243195.337] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:144] Unable to sync with burnchain: Try synchronizing again
WARN [1589243255.434] [src/burnchains/bitcoin/network.rs:126] Timed out waiting for headers data.  Killing connection.
WARN [1589243255.434] [src/burnchains/bitcoin/indexer.rs:415] Unhandled error TimedOut
ERROR [1589243255.434] [src/burnchains/bitcoin/indexer.rs:508] Failed to fetch Bitcoin headers from 0 - 16: TimedOut
ERROR [1589243255.435] [src/burnchains/burnchain.rs:792] Failed to check for reorgs from /tmp/stacks-testnet-a630671d54a92cdd/burnchain/spv-headers.dat: TrySyncAgain
ERROR [1589243255.435] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:144] Unable to sync with burnchain: Try synchronizing again"

**Comment by diwakergupta** [comment]
Thanks @michaeljiflorida08 for the report. That log message doesn't necessarily indicate a bug -- just that your node was unable to sync with the burnchain. This can happen, for instance, if the burnchain node you're trying to connect (what's in the `burnchain` section of your config) is unreachable.

If you believe this is still a bug, please reopen with additional details.

**Comment by michaeljiflorida08** [comment]
[logging-2020_05_11.txt](https://github.com/blockstack/stacks-blockchain/files/4612827/logging-2020_05_11.txt)
