### ISSUE TITLE
Testnet Neon Miner Node stopped and thrown err "Unable to sync burnchain: Invalid proof of work"

### ISSUE THREAD

**Issue by michaeljiflorida08** [blockstack/stacks-blockchain#1578]
Describe the bug
during run testnet neon minor node, node is stopped and throw error message "Unable to sync burnchain: Invalid proof of work"

Steps To Reproduce
git clone https://github.com/blockstack/stacks-blockchain.git
cd stacks-blockchain
cargo install --path ./testnet

RUST_BACKTRACE=FULL BLOCKSTACK_DEBUG=1 stacks-node start --config=./testnet/stacks-node/conf/neon-miner-conf.toml

error message will show "Unable to sync burnchain: Invalid proof of work"

Expected behavior
testnet neon miner node should continue running smoothly

Environment (please complete the following information):
OS: Ubuntu18.04
Rust version: rustc 1.43.0 (4fb7144ed 2020-04-20)
approximate build #(Merge pull request #1574)

Additional context
testnet-0177230fca486c49/burnchain/spv-headers.dat.reorg (offset 0 interval 1 of 1-2): 545259519 != 486604799
ERROR [1589397370.635] [src/burnchains/bitcoin/spv.rs:257] Received headers with bad target or difficulty
WARN [1589397370.635] [src/burnchains/bitcoin/indexer.rs:414] Unhandled error InvalidPoW
ERROR [1589397370.635] [src/burnchains/bitcoin/indexer.rs:508] Failed to fetch headers from 0 - 16
ERROR [1589397370.635] [src/burnchains/burnchain.rs:794] Failed to check for reorgs from 0
ERROR [1589397370.635] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Invalid proof of work
thread 'main' panicked at 'explicit panic', testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17
stack backtrace:

**Comment by michaeljiflorida08** [comment]
[logging-2020_05_13-2.txt](https://github.com/blockstack/stacks-blockchain/files/4624355/logging-2020_05_13-2.txt)

**Comment by michaeljiflorida08** [comment]
[neon-miner-conf.toml.txt](https://github.com/blockstack/stacks-blockchain/files/4624369/neon-miner-conf.toml.txt)

**Comment by diwakergupta** [comment]
Pulling out tail of the log:

```
DEBUG [1589397370.635] [src/burnchains/bitcoin/spv.rs:277] Write 5 headers at /tmp/stacks-testnet-0177230fca486c49/bu
rnchain/spv-headers.dat.reorg at 2013
ERROR [1589397370.635] [src/burnchains/bitcoin/spv.rs:152] bits mismatch at block 2016 of /tmp/stacks-testnet-0177230fca486c49/burnchain/spv-headers.dat.reorg (offset 0 interval 1 of 1-2): 545259519 != 486604799
ERROR [1589397370.635] [src/burnchains/bitcoin/spv.rs:257] Received headers with bad target or difficulty
WARN [1589397370.635] [src/burnchains/bitcoin/indexer.rs:414] Unhandled error InvalidPoW
ERROR [1589397370.635] [src/burnchains/bitcoin/indexer.rs:508] Failed to fetch headers from 0 - 16
ERROR [1589397370.635] [src/burnchains/burnchain.rs:794] Failed to check for reorgs from 0
ERROR [1589397370.635] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Invalid proof of work
thread 'main' panicked at 'explicit panic', testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: std::panicking::begin_panic
  12: stacks_node::burnchains::bitcoin_regtest_controller::BitcoinRegtestController::receive_blocks
  13: stacks_node::run_loop::neon::RunLoop::start
  14: stacks_node::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  19: std::panicking::try
             at src/libstd/panicking.rs:281
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  22: main
  23: __libc_start_main
  24: _start
```

I suspect you're running an older binary (looking at `bits mismatch at block 2016 of /tmp/stacks-testnet-0177230fca486c49/burnchain/spv-headers.dat.reorg (offset 0 interval 1 of 1-2): 545259519 != 486604799
` in the logs). Once we have the git revision, we can confirm.

**Comment by michaeljiflorida08** [comment]
I agree. 

The git version is "b418a0a2c", which seems the current one.

Miner node runs good now, after I switch to this command "RUST_BACKTRACE=FULL BLOCKSTACK_DEBUG=1 cargo testnet start --config=./testnet/stacks-node/conf/neon-miner-conf.toml"

(Previously, I used "RUST_BACKTRACE=FULL BLOCKSTACK_DEBUG=1 stacks-node start --config=./testnet/stacks-node/conf/neon-miner-conf.toml")

**Comment by diwakergupta** [comment]
Thanks for confirming, will close for now. Please reopen if you encounter another crash.
