### ISSUE TITLE
Costs for comments?

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1585]
**Is your feature request related to a problem? Please describe.**
The costs to deploy a contract with comments is higher than without, will this change in the future?

The rcp api does not return the comments. So they probably shouldn't be accounted for. 

Ideally, I would write a contract with comments (saved in git somewhere) and deploy a stripped version.

**Comment by jcnelson** [comment]
> The costs to deploy a contract with comments is higher than without, will this change in the future?

This is intentional.  Comments take up space, so they cannot be free.  To make them free would be to introduce a DDoS vector, whereby someone could upload a contract that was almost entirely comments and not get charged for it.

> The rcp api does not return the comments. So they probably shouldn't be accounted for.

Can you give an example?  The RPC code paths should be loading the contract source verbatim.

**Comment by diwakergupta** [comment]
Comments won't be free, but perhaps we can explore making the cost of comments as low as possible.

**Comment by njordhov** [comment]
> perhaps we can explore making the cost of comments as low as possible.

How can the cost of comments be made as low as possible? Would it be for example be possible to store the comments elsewhere on cheaper storage and leave say a hash of the comments and merge rules with the contract?

**Comment by jcnelson** [comment]
The main cost for comments comes from the added bandwidth of having to both relay the transaction the instantiates the contract, as well as the bandwidth from having to indefinitely serve the block that contains it to future peers.

To be clear, the goal is to make it so paying for comments only happens once -- specifically, when the contract is instantiated.  The cost of both `contract-call?`'s and `TransactionContractCall` transactions should not be affected by the presence or absence of comments in the contract they invoke.

**Comment by diwakergupta** [comment]
@reedrosenbluth @kantai is this something the current cost-tracking work is taking into account? If so, please re-open.
