### ISSUE TITLE
as-max-len? fails with a list that is too long

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1591]
**Describe the bug**
When calling `as-max-len?` with a list with a size value longer than the indicated length the transaction fails with an execution error:

Contract snippet: 
```
(define-data-var token-ids (list 10 uint) (list))
...
(as-max-len? (append (var-get token-ids) next-id) u10)
```

Error:
Transaction execution error: 
Unchecked(TypeValueError(ListType(ListTypeData { max_len: 10, entry_type: UIntType }), List(ListData { data: [UInt(1)], type_signature: ListTypeData { max_len: 11, entry_type: UIntType } })))' 

**Steps To Reproduce**
add the above snippet to a contract and call the function containing the snippet

**Expected behavior**
should return `none`

**Environment (please complete the following information):**
 - clarity 1.13
- stack-blockchain 3aa7f7925303499b01033274b83c736a65d20e64

**Additional context**
This happens in unit tests using clarity 1.13 as well as mocknet 

Error on mocknet:
```
 Invalid contract-call transaction f3ffd85bf250f80b9f45aed7021f15bb0fecbee79af97fa5cf041ae8554cdbd7: 
Interpreter(Unchecked(TypeValueError(ListType(ListTypeData { max_len: 10, entry_type: UIntType }), 
List(ListData { data: [UInt(1)], type_signature: ListTypeData { max_len: 11, entry_type: UIntType } }))))
```

**Comment by friedger** [comment]
Used in https://github.com/friedger/clarity-smart-contracts/blob/master/contracts/experiments/animal-kingdom.clar

**Comment by kantai** [comment]
Thanks for catching this @friedger, will open a PR shortly to fix.
