### ISSUE TITLE
docs: definitions on the testnet wiki/doc page

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/stacks-blockchain#1593]
[testnet.blockstack.org](testner.blockstack.org)  a common source of confusion with people is the terms/wording used in the docs. 

> Proof of Transfer (PoX) is the consensus mechanism that leverages the security and stability of Bitcoin to create new blockchains, without modifying the Bitcoin protocol. PoX makes it possible to reward network participants with Bitcoin. An example of this is Stacking.

The definition of "consensus" process/mechanism does not match other doc's like SIP-007.
The consensus process is called **Stacking** not PoX, right?
PoX is the STX _mining_ process, a **part** of the Stacking Consensus process, which rewards Stacking participants with BTC rewards.  Right?

**Comment by jcnelson** [comment]
Hi @fluidvoice, PoX is a part of a consensus algorithm -- specifically, it's part of the mining process, whereby the miners get rid of a resource to gain STX (that resource being BTC).  Transferring BTC in some way or another -- either to Stackers or to a burn address -- is a necessary step in the algorithm to determine who wins the next block race, but it is not the entire algorithm.  The peers also need to run a cryptographic sortition to determine who wins the block (i.e. based on how much each miner transferred).

Stacking is a form of hinting -- Stacks holders provide hints to miners as to which chain tip is the best chain tip.  But Stacking isn't a required step in the consensus algorithm -- if no Stacking occurs, the system will still continue to produce blocks.

@kantai would you agree with this?  If not, maybe SIP 007 needs to be tweaked to make the language clearer.

**Comment by fluidvoice** [comment]
> Hi @fluidvoice, PoX is a part of a consensus algorithm -- specifically, it's part of the mining process, whereby the miners get rid of a resource to gain STX (that resource being BTC). Transferring BTC in some way or another -- either to Stackers or to a burn address -- is a necessary step in the algorithm to determine who wins the next block race, but it is not the entire algorithm. The peers also need to run a cryptographic sortition to determine who wins the block (i.e. based on how much each miner transferred).
> 
> Stacking is a form of hinting -- Stacks holders provide hints to miners as to which chain tip is the best chain tip. But Stacking isn't a required step in the consensus algorithm -- if no Stacking occurs, the system will still continue to produce blocks.
> 
> @kantai would you agree with this? If not, maybe SIP 007 needs to be tweaked to make the language clearer.

Yeah this is just an issue of clarifying the terminology used.  As it is the crypto community seems to mostly use "PoX" as synonymous with the Stacks 2.0 consensus algo. So if it's fine I will reflect the same in the PoX Wiki page?

Btw, "peers also need to run a cryptographic sortition to determine who wins the block".. are these peers other mining nodes, stacking nodes, or both?
