### ISSUE TITLE
Wondering if a continous fail to connect to get peer address is a problem

### ISSUE THREAD

**Issue by paradigma-cl** [blockstack/stacks-blockchain#1595]
**Describe the bug**
From the continous logs failed to connect to get peer address thinking there is a problem with new installation

**Steps To Reproduce**
Please provide detailed instructions (e.g. command line invocation with parameters) to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Rust version: latest
 - Version of the appropriate binary / software package: latest of 16/05/2020

**Additional context**
INFO [1589680155.470] [testnet/stacks-node/src/neon_node.rs:710] Received burnchain block #3139 including block_commit_op (winning) - mymHTVyEtB5p6RVkh4vRWVGwM6VqvRG2bE
INFO [1589680184.784] [src/burnchains/burnchain.rs:855] Node will fetch burnchain blocks 3139-3140...
INFO [1589680185.733] [testnet/stacks-node/src/neon_node.rs:710] Received burnchain block #3140 including block_commit_op (winning) - mx2uds6sgnn9znABQ6iDSSmXY9K5D4SHF9
INFO [1589680216.631] [src/burnchains/burnchain.rs:855] Node will fetch burnchain blocks 3140-3141...
WARN [1589680217.592] [src/burnchains/burnchain.rs:436] Failed to parse leader key register tx ce17411a8130db42c2ed3775a36e9047ac788d6bd8d2d6b8d8c0c1184e48f103 data dc2c54f610b487360630f87db4b2dcad419ed0936c4503ca4374079e991f2ef0360c6cf1b1a306109937b88d4f089a7db016d3d1: InvalidInput
INFO [1589680217.685] [testnet/stacks-node/src/neon_node.rs:710] Received burnchain block #3141 including block_commit_op (winning) - n4CTnRDUFRSwpvf18M2GMjH2X1LHopLwQC
INFO [1589680246.852] [src/burnchains/burnchain.rs:855] Node will fetch burnchain blocks 3141-3142...
INFO [1589680247.740] [testnet/stacks-node/src/neon_node.rs:710] Received burnchain block #3142 including block_commit_op (winning) - n4CTnRDUFRSwpvf18M2GMjH2X1LHopLwQC
WARN [1589680265.808] [src/net/p2p.rs:946] Failed to get peer address of TcpStream { addr: V4(190.113.12.16:39736), fd: 41 }: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
INFO [1589680274.807] [src/burnchains/burnchain.rs:855] Node will fetch burnchain blocks 3142-3143...
INFO [1589680276.042] [testnet/stacks-node/src/neon_node.rs:710] Received burnchain block #3143 including block_commit_op (winning) - mymHTVyEtB5p6RVkh4vRWVGwM6VqvRG2bE
WARN [1589680398.033] [src/net/p2p.rs:946] Failed to get peer address of TcpStream { addr: V4(190.113.12.16:39874), fd: 40 }: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }

**Comment by jcnelson** [comment]
Hey @paradigma-cl, it shouldn't be a problem (looks to be transient).  It can happen if the remote peer resets its connection to your peer before your peer can register the socket as an open connection.
