### ISSUE TITLE
Rename clarity's begin construct

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1602]
Clarity's [begin](https://docs.blockstack.org/core/smart/clarityref#begin) function imperatively executes expressions for side effects, returning the evaluated value of the last expression. 

However, `begin` is unfortunate terminology for this functionality. Presumedly it was inspired by [scheme](https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/Sequencing.html) which historically may have been influenced by the `BEGIN...END` syntax in ALGOL-like languages. But in Clarity, there is no `end` making `begin` a confusing start of the block:

```scheme
(begin 
  (print "All good so far")
  (var-set size 1)
  (ok 0)) 
```

Clarity should instead use `do` to form a sequence of statements to be evaluated imperatively:

```scheme
(do 
  (print "All good so far")
  (var-set size 1)
  (ok 0)) 
```

The word `do` is immediately understandable from English to indicate a sequence of actions to be executed, making it a sensible alternative. The [Clojure](https://clojuredocs.org/clojure.core/do) Lisp dialect also uses `do` to form such sequences of expressions.

**Proposed action: Rename the `begin` construct to `do`.**

**Comment by xmakina** [comment]
If we're talking historic precedent, `do` is also usually coupled with `while` to provide a looping functionality. Begin at least indicates we're only going to execute the sequence once

**Comment by njordhov** [comment]
> Begin at least indicates we're only going to execute the sequence once

Does it really indicate that though? That `begin` indicates a block to execute once is a learned convention from algol-like programming languages. In contrast, little programming experience is required to guess what `do` means.

**Comment by friedger** [comment]
`do` saves three characters over `begin`

**Comment by friedger** [comment]
That is still important to me
