### ISSUE TITLE
Stacks Balance Randomly reset to 0

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain#1606]
This address: ST8E0WHZ0HNHFRT7BVPKB8BDRPJ6GCPGGW9EXH3G
is used on my mining node, and had gotten up to 2M uSTX balance as of May 17/18.  This morning it shows 0.

This address: ST7WEFMJQ11WEBENTM7Q9963FHP55YQHSXWDRNRB
is used for testing transactions and had 500k+ uSTX balance as of May 17/18.  Also showing 0 currently.

I've checked these both against my local node as well as neon.blockstack.org.  My node log does not have any 'ERROR' values and is being run with BLOCKSTACK_DEBUG=1 and RUST_BACKTRACE=FULL

**Comment by diwakergupta** [comment]
@lgalabru can you confirm when the last chain reset was? If @dantrevino observed these balances _after_ the reset, we need to look into why the balances went to 0.

**Comment by lgalabru** [comment]
@dantrevino we restarted the chain yesterday morning EST. This event created a new empty stacks chain, living on a new, longer burn chain. On this new chains, your balances (STX and BTC) are empty. Your node is programmed for following the longest chain, which is what it gracefully did :).

**Comment by dantrevino** [comment]
Thx @lgalabru
