### ISSUE TITLE
BUG: Chainstate: contract analysis data is saved if post-conditions cause a tx abort

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1608]
It's currently possible for a smart contract transaction's post-conditions to fail (thereby preventing the contract from being materialized) while also causing its analysis data to get saved.  This is because the analysis data is unconditionally saved in `process_transaction_payload()` in `src/chainstate/stacks/db/transactions.rs` _after_ the contract is instantiated.  The reason the analysis data is unconditionally saved is because the return type from `process_smart_contract()` in `src/vm/clarity.rs` doesn't indicate whether or not the abort callback (i.e. the post-condition checker) caused the transaction to abort -- either way, an `Ok(..)` type is returned.

**Comment by kantai** [comment]
Yep -- I'll plan to address this by folding the `save_analysis` functionality into `initialize_smart_contract` so that they commit or abort together.

**Comment by jcnelson** [comment]
A related problem is that the transaction receipt for a smart contract currently indicates unconditional success, even if the post-conditions failed.  The receipt needs to be updated to indicate if the post-conditions failed.

**Comment by jcnelson** [comment]
The problem isn't specific to smart-contract payloads.  It also happens for contract-call payloads.

**Comment by jcnelson** [comment]
Opened https://github.com/blockstack/stacks-blockchain/issues/1609 for the post-condition-related errors.
