### ISSUE TITLE
BUG: Chainstate: failed post-conditions are not captured in transaction receipts

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1609]
Because the methods in `src/vm/clarity.rs` do not return whether or not the changes were aborted, we currently do not capture whether or not a contract-call or smart-contract transaction failed due to post-conditions.  The receipt only inspects the return type (or for smart-contracts, defaults to `(ok true)`).

**Comment by kantai** [comment]
This was addressed via #1612
