### ISSUE TITLE
Burnchain in config should accept separate FQDNs/IPs for rpc and peer ports

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain#1613]
Not sure if this would be considered a bug or new feature, apologies if it's misrepresented.

**Describe the bug**
Under the `[burnchain]` section in the config file for stacks-blockchain, two different ports must be specified (rpc and peer ports) but only one host FQDN/IP can be specified (peer_host). This introduces a challenge when you have separate peer (p2p-firewall) and rpc (neon) services in different FQDNs/IPs. The only way to work around this is to colocate the peer and rpc services under a single FQDN/IP in order for stacks-blockchain to be able to reach both peer and rpc ports on the same FQDN/IP.

**Steps To Reproduce**
Deploy the p2p-firewall and neon services under different FQDNs/IPs (easiest to do in K8s). Try configuring the stacks-blockchain `[burnchain]` section to have the `rpc_port` used for the neon service FQDN, and the `peer_port` used for the p2p-firewall service FQDN (can't currently be done).

**Expected behavior**
I expect to be able to configure different FQDNs/IPs for both the `rpc_port` and `peer_port` properties under the `[burnchain]` section.

**Comment by jcnelson** [comment]
The Bitcoin p2p firewall doesn't interact with the Stacks node.  It interacts with the Bitcoin node by filtering out p2p messages (namely, to stop someone else's regtest node from reorging our regtest node).  So, I'm not sure how making it so the Stacks node could bind on different IP addresses for its P2P/RPC services fixes the problems you're having?

**Comment by CharlieC3** [comment]
> The Bitcoin p2p firewall doesn't interact with the Stacks node. It interacts with the Bitcoin node by filtering out p2p messages

Yes, no confusion on that part. I may not have used to best wording in my post, but I'm referring to the services and ports on which the Stacks node _connects_ to, rather than the IPs/ports the Stacks node _binds_ to.

The Stacks node connects to a `peer_host` defined in the config file (example below):
```
    [burnchain]
    ...
    peer_host = "neon.staging-core.svc.cluster.local"
    rpc_port = 18443
    peer_port = 18444
    ...
```

The peer host, neon, is listening on port `18443` as the RPC port. So the Stacks node is able to connect to `neon.staging-core.svc.cluster.local:18443` without issue.
However, neon is _not_ listening on the peer port, 18444. Instead, the Stacks node is supposed to connect to the `p2p-firewall` service on this port. So I need a way to configure the Stacks node to connect to:
* `neon.staging-core.svc.cluster.local:18443` for outgoing RPC connections, and
* `p2p-firewall.staging-core.svc.cluster.local:18444` for outgoing peer connections (hence the two different FQDNs used).

I hope that helps clarify the scenario, but if not I'd be happy to sync up off GH.

**Comment by diwakergupta** [comment]
It seems an easy fix would be to specify host/port combo instead of one host and 2 ports. So something like `rpc_host_port` and `peer_host_port`?

**Comment by jcnelson** [comment]
Sorry, misread your comment originally.  This should be doable.

**Comment by diwakergupta** [comment]
@CharlieC3 this isn't a blocker for you, right? I think we should do this, but likely not our highest priority at the moment.

**Comment by CharlieC3** [comment]
@diwakergupta No, this is not a blocker. I'm currently working around this by configuring the stacks node to connect to `neon` via the external DNS of our cluster, which routes connections based on the port used. But the downside to this is obviously the extra hops involved and we have to send internal traffic to the internet. Once this is fixed we'll be able to keep this connection internal within the cluster.
