### ISSUE TITLE
read-only rpc calls fail with special characters like `?`

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1622]
**Describe the bug**
functions that contain a `?` are not handled correctly on the rpc api. The function name is not found at the contract

**Steps To Reproduce**
Please provide detailed instructions (e.g. command line invocation with parameters) to reproduce the behavior.

**Expected behavior**
1. Deploy contract 
```
(define-read-only (info?)
  (some u1)
)
```
2. call contract `info?`

**Additional context**
Might affect https://github.com/blockstack/stacks-transactions-js/pull/87 how these kind of methods are encoded.

**Comment by kantai** [comment]
Thanks for reporting @friedger -- I think we need to update our RPC URL parser to handle escape characters here.

**Comment by diwakergupta** [comment]
Addressed on the stacks-blockchain side, but stacks-transactions-js might need to be updated cc/ @yknl @reedrosenbluth 

Closing this out.

**Comment by yknl** [comment]
This is addressed in the stacks transactions lib here: https://github.com/blockstack/stacks-transactions-js/pull/87/commits/5d7a1c593d6bab71eae379c48848450502497a9f
