### ISSUE TITLE
Tuple cares about function ordering in physical file

### ISSUE THREAD

**Issue by xmakina** [blockstack/stacks-blockchain#1625]
**Describe the bug**
When a `tuple` is used, `checkContract()` will fail if the tuple requires a private function that is declared below the `tuple` usage

**Steps To Reproduce**
A broken and working example can be found at https://github.com/xmakina/clarity-tuple-function-order/tree/master/contracts and below

**Expected behavior**
Tuple should be able to access a private function from anywhere in the physical script file

**Environment (please complete the following information):**
 - OS: Windows 10
 - Rust version: N/A
 - Version of the appropriate binary / software package: "@blockstack/clarity": "^0.1.16"

**Additional context**

__working.clar__
```
(define-private (get-zero)
    0
)

(define-read-only (get-score)
    (ok 
        (tuple
            (score (get-zero))
        )
    )
)
```
__broken.clar__
```
(define-read-only (get-score)
    (ok 
        (tuple
            (score (get-zero))
        )
    )
)

(define-private (get-zero)
    0
)
```

**Comment by friedger** [comment]
I think that is a general rule, that you can't use functions that are defined later

**Comment by xmakina** [comment]
I thought that too but the reason I've singled out Tuple's above is because this works fine:

I ran some tests and tuples seemed to be the only one that cared about function ordering.

```
(define-read-only (get-score)
    (ok get-zero)
)

(define-private (get-zero)
    0
)
```

**Comment by njordhov** [comment]
> I think that is a general rule, that you can't use functions that are defined later

Definition order is supposed to not matter. Allowing definitions in arbitrary order was proposed in #985 and implemented in #1079. Although personally I favor sticking to a bottom-up order for Clarity with definitions before usage.

**Comment by njordhov** [comment]
The flexible definition order is supported by the *definition sorter* step in the AST, which processes the code to determine dependency order. The problem you've encountered may have already been fixed with PR #1443 as it changes how the definition sorter deals with tuples.

**Comment by kantai** [comment]
Thanks for reporting @xmakina -- this is indeed a bug, the AST's definition sorter should be able to handle this case.

**Comment by njordhov** [comment]
PR #1443 already fixed this bug.

**Comment by kantai** [comment]
> PR #1443 already fixed this bug.

Yes, however, PR #1443 is a backwards-incompatible change (though it's definitely one that I think we should enact), and I don't think we should merge it without a larger announcement about breakage.
