### ISSUE TITLE
Define smart contract addresses with `define-constant`

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#1626]
**Is your feature request related to a problem? Please describe.**
If I can do
```
(begin
  (contract-call? 'SP2NC4YKZWM2YMCJV851VF278H9J50ZSNM33P3JM1.my-token transfer address x)
  (contract-call? 'SP1QR3RAGH3GEME9WV7XB0TZCX6D5MNDQP97D35EH.my-token transfer address y)
)
```
why couldn't I do:
```
(define-constant x-token 'SP2NC4YKZWM2YMCJV851VF278H9J50ZSNM33P3JM1.my-token)
(define-constant y-token 'SP1QR3RAGH3GEME9WV7XB0TZCX6D5MNDQP97D35EH.my-token)
...
(begin
  (contract-call? x-token transfer address x)
  (contract-call? y-token transfer address y)
)
```
This fails with `use of undeclared trait <x-token>`, however it seems that traits should not be required necessarily here.  I also tried using traits, see below.

**Describe the solution you'd like**
Using the above constant should work

**Describe alternatives you've considered**
You need to keep repeating the addresses, making the code more cluttered, and it easy to use the wrong hash value
Also tried using traits, but no luck getting it to work, especially that this would be using the same trait from 2 contracts implementing the same trait
So I tried variations around:
```
(use-trait x-token
    'SP2NC4YKZWM2YMCJV851VF278H9J50ZSNM33P3JM1.token-transfer-trait.can-transfer-tokens)
(use-trait y-token
    'SP1QR3RAGH3GEME9WV7XB0TZCX6D5MNDQP97D35EH.token-transfer-trait.can-transfer-tokens)
```

(errors like `use of unresolved contract 'SP2NC4YKZWM2YMCJV851VF278H9J50ZSNM33P3JM1.token-transfer-trait'`)

Note: not my attempt at using traits, I managed to make a simpler example with a single trait work at https://github.com/psq/ClarityTraitExample but I can't claim I fully understand what's going on :)

**Additional context**
no

**Comment by kantai** [comment]
@psq -- thanks for opening an issue on this.

In general, `contract-call` cannot be used with `define-constant`. This is because Clarity constants aren't macros, but rather evaluated at runtime. For example:

```scm
;; call a different contract to get the contract name
(define-constant x-token (contract-call? .contract-name-factory get-a-contract-name))

;; the type checker can't know where the function `foo!` was defined.
(contract-call? x-token foo!)
```

Using traits would prevent the need for repeating the hash everywhere, but they have their own syntactic requirements, so it may not necessarily be more convenient.

To support something like this, we could add support for something like macro definitions, which _could_ be statically checked.

**Comment by psq** [comment]
@kantai I see your point about the type checker not being able to determine what the value is in all cases, but does it mean the cases when it can should not work either?  I would think testing whether the value of the constant is fully known at deployment time would be doable?

If this is something you'd want to consider, I might try to make this case work in the PR (although this might be too much for to tackle yet given what I know)

I have too many battle scars from using macros, so I'm not sure I'd want to go that route :)
