### ISSUE TITLE
Add contract-read-only

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1627]
**Is your feature request related to a problem? Please describe.**
The same read-only functions for flipping coins are used in the two different contracts. Currently, there is no way to extract these read-only functions into a third contract and call them in a read-only function of the original contract.

**Describe the solution you'd like**
Similar to `contract-call` it should be possible to call a read-only function of another contract

**Describe alternatives you've considered**
* copy paste code
* make the read-only function a normal public function

**Additional context**
Flip Coin contract used in betting game contracts

**Comment by njordhov** [comment]
Seems like read-only functions are supposed to be callable from other contracts. See #1399 and #948.

**Comment by friedger** [comment]
However, they are not recognized as read-only and therefore can't be called **from** read-only functions

**Comment by kantai** [comment]
> However, they are not recognized as read-only and therefore can't be called from read-only functions.

That should be the case -- so long as they are declared read-only, they should be typed as read-only even when used in contract-call.

**Comment by kantai** [comment]
@friedger -- do you have a set of example contracts that failed to pass the read-only checks because of this?

**Comment by friedger** [comment]
I was put off by the error in VS code:

![Screenshot from 2020-05-27 01-22-24](https://user-images.githubusercontent.com/1449049/82959663-902eb380-9fb8-11ea-85b6-996d00a3398d.png)

**Comment by friedger** [comment]
Looks like I can call these functions!

**Comment by friedger** [comment]
Continuing on https://github.com/lgalabru/clarity-lsp/issues/11
