### ISSUE TITLE
Clarity: try-read-only contract calls?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1630]
This is more of a design question.  Should it be possible to call a `define-public` function with a dynamic assertion that it is read-only?  My main motivation for this is to provide a way to call `define-public` functions via the RESTful API that _could_ be read-only, and have them abort with an assertion failure if they try to mutate any state.  I could also see us adding something akin to a `contract-call?` but that adds a runtime assert that no mutations occur (maybe something like `contract-call-ro?`).

**Comment by jcnelson** [comment]
The consensus seems to be that, abort or not, we can run any function or any code via the RESTful API.  We can abort on mutation, or just not materialize any mutation.

**Comment by psq** [comment]
@jcnelson if by the RESTful API, you mean using `/v2/contracts/call-read`, this will fail with `PublicFunctionNotReadOnly`, even though technically, yes, you could rollback it if did mutate, but right now you have to use a transaction to call any function that is not defined as `define-read-only`, but probably a separate issue.

**Comment by jcnelson** [comment]
Right -- what the API should be doing (#1641) is allowing you to call any Clarity function you want (not just the read-only ones) via the RESTful API, but without materializing any writes.

**Comment by psq** [comment]
sounds good!  Thank you @jcnelson
