### ISSUE TITLE
Bug Bounty submission form - to be added to the current issue template

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-blockchain#1632]
_PLEASE CHECK THE BOX THAT BEST FITS THE BOUNTY BUG YOU DISCOVERED. THEN SCROLL TO THE BOTTOM AND ENTER THE BUG DETAILS BELOW._

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

-----------------------------------------------------------------------------------

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by diwakergupta** [comment]
Addressed in e50d9fddb324956e827a2e3a7be4d286b5983a1b
