### ISSUE TITLE
Clarity: pass on wording for AST/Analysys errors 

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1639]
Clarity is a new language with its very own rules. 
Many developers learn new languages using a trial and failure process.
I think we should improve our wording on this user facing errors:
https://github.com/blockstack/stacks-blockchain/blob/20698d69425132efd96f28526edc60cc3ee89dfd/src/vm/analysis/errors.rs#L269
https://github.com/blockstack/stacks-blockchain/blob/20698d69425132efd96f28526edc60cc3ee89dfd/src/vm/analysis/errors.rs#L269

We should also probably fully leverage the `Diagnosable` trait and use the `suggestion` field for as many errors as we see fit.
https://github.com/blockstack/stacks-blockchain/blob/20698d69425132efd96f28526edc60cc3ee89dfd/src/vm/ast/errors.rs#L161-L165
https://github.com/blockstack/stacks-blockchain/blob/20698d69425132efd96f28526edc60cc3ee89dfd/src/vm/analysis/errors.rs#L375-L382

@johndmulhausen is having our back on this DX mission!

**Comment by diwakergupta** [comment]
@johndmulhausen are you actively working on this, or plan to? I'm tentatively tagging it against the next sprint. Thanks!
