### ISSUE TITLE
Block production in Neon slower than expected

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain#1647]
With a block interval of 30s, we should expect to see 120 blocks / hr. Current block height is ~2675 blocks after running for ~60 hrs, so we're actually producing blocks at a much lower rate of ~45 blocks / hr.

@zone117x observed similar phenomenon on mocknet with a block interval of 5s.

Opening this issue for tracking and capturing the investigation.

**Comment by lgalabru** [comment]
#1648 should fix this issue, or will, at least, help revealing other issues.
Will monitor the next deployment and close this issue or pursue the investigations.
