### ISSUE TITLE
Create a new tag for clarity sdk

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1651]
Clarity has been changed and a new tag should be created:

Clarity trait references can now be called inside `let` blocks.

`as-max-len?` now creates the correct type for long lists.

**Comment by jcnelson** [comment]
Hey @friedger, can we go ahead and close this now that we have a new version of the SDK elsewhere?

**Comment by friedger** [comment]
I can see and use clarity 0.2.0 :-)

Is there a checkbox or so for changes that require a new version of the sdk? How to keep both repos in sync?
