### ISSUE TITLE
Stacks Blocks Loss

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1660]
Looking at our different sources of logs, it looks like most of the blocks not mined by our master node are not being received. 
The production of sortitioned blocks is what it should be (120/hour), but the stacks chain height reported by the master node is around 120, after 2 hours. 80% of the coinbase transactions broadcasted to the sidecar are for the master-node, when this node is actually only winning less than 50% of the sortitions.

**Comment by diwakergupta** [comment]
@lgalabru suggested one next step would be to setup a NAT-ed miner at PBC, but no active bug here per se. Closing for now.
