### ISSUE TITLE
Add constructor for empty lists

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1664]
**Is your feature request related to a problem? Please describe.**
The initial value for a list is often empty

**Describe the solution you'd like**
Something like the following should be possible:
```
(define-data-var my-list (list 10 uint) (list))
```
**Describe alternatives you've considered**
Using an optional list. However, the optional value is usually only used until the first value was added to the list

**Additional context**
Maybe #925

**Comment by psq** [comment]
this works for me here https://github.com/psq/swapr/blob/master/contracts/swapr-registry.clar#L33
(and maybe because I'm using a clarity-bin built from the latest master

However I had some issues getting it to work because on how I was doing the append. 

What's your error?

**Comment by friedger** [comment]
@psq I am seeing `invalid variable definition.` with clarity 0.1.16

**Comment by friedger** [comment]
Because I swapped the list args.. all good.
