### ISSUE TITLE
Node: all non-dev HTTP use-cases should use our net::http implementation

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1666]
It's fine for now, but before mainnet launches, we should remove `reqwest` / `tokio` / `async-h1` from our required list of non-dev dependencies.  Both have far too much unsafe code, and we can use our 100%-safe HTTP server and client implementation instead.

**Comment by diwakergupta** [comment]
General alignment that we want to do this, but probably later once the event-dispatcher, prometheus etc modules are stable.
