### ISSUE TITLE
Inconsistent typing between list definition and as-max-len?

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#1668]
**Is your feature request related to a problem? Please describe.**
It is in between a bug and a feature request as nothing is broken per se, but being consistent would make the world  turn more smoothly...  maybe

When you define a list with `(list max-len entry-type)`, `max-len` is an `int` (the documentation does not specify, and it should, but that's what's observed in practice, however, `as-max-len?` takes a `uint` (the [example](https://docs.blockstack.org/core/smart/clarityref#as-max-len) incorrectly uses an `int`, but the type shows `uint`, also observed in practice).

Same would apply for `buff` type definition I think, I just haven't try `as-max-len?` with a `buff`.

**Describe the solution you'd like**
Both types should be the same, and preferably `uint` as negative values don't make sense.

I realize this is going to break a lot of contracts, but better now that after mainnet launches!

**Bonus doc issue:**
`MAX_CLARITY_VALUE` is used twice on the [Clarity Reference](https://docs.blockstack.org/core/smart/clarityref#map-insert) but not defined, it would be helpful to explain it is 1024 * 1024 = 1 MiB.  If you'd rather have this as a separate issue, I can create it, but it feels it would take more time in administrative work vs the time it takes to fix.

**Comment by njordhov** [comment]
See #1344 which proposes inferring the type of integers rather than having to use a prefix to specify unsigned integer type.

**Comment by diwakergupta** [comment]
We'd welcome documentation PRs to clarify this. As @njordhov mentions, a PR that implements type inference for integral literals would help address this.
