### ISSUE TITLE
Clarity symbols can't start with `u` and a digit

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1669]
**Describe the bug**

Clarity symbols can't start with `u` followed by a digit as this matches the production for unsigned integers. 

**Steps To Reproduce**

For example, although `w2x` is a valid symbol, `u2x` is not since `u2` denotes an unsigned integer.

**Expected behavior**

It should be possible to start a symbol with `u` followed by a digit.

Preferably, the type of unsigned integers is inferred as suggested in #1344, eliminating the need for the `u` prefix.

**Additional context**

Symbols [can consist of](https://github.com/blockstack/stacks-blockchain/blob/85f0f8666904f73e83abfe5df43e746ad6033e56/src/vm/ast/parser/mod.rs#L120) one or more of `[-!?+<>=/*]` and word characters _as long as the string doesn't match any preceding production._ That the Clarity [lexer](https://github.com/blockstack/stacks-blockchain/blob/85f0f8666904f73e83abfe5df43e746ad6033e56/src/vm/ast/parser/mod.rs#L98) depends on the precedence order of match patterns invites for errors as introducing new match patterns or reordering them may change the grammar in unexpected ways.

**Comment by njordhov** [comment]
> However, the problem you are raising is definitely valid, and should be addressed the same as in most other languages-- integer literal types are specified with suffixes rather than prefixes:

Systems languages like C++ and Rust are apt to have unsigned integers, while most other modern programming languages do not have an unsigned type. Being able to optimize data encoding to get the most out of every bit makes sense for close to the metal systems languages. 

But Clarity is not a systems language. This would be a good time to consider first principles and design better type safety than peppering the code with unsigned integer literals.

**Comment by kantai** [comment]
> But Clarity is not a systems language. This would be a good time to consider first principles and design better type safety than peppering the code with unsigned integer literals.

The reason for supporting unsigned integers is not that it helps squeeze an extra bit for data, but because smart contracts frequently want to make use of nonnegative integers. Failing to properly handle negative integers is a frequent error in deployed smart contracts. Providing an unsigned integer type allows programmers to avoid that class of errors entirely.

**Comment by njordhov** [comment]
> Failing to properly handle negative integers is a frequent error in deployed smart contracts. Providing an unsigned integer type allows programmers to avoid that class of errors entirely.

What the unsigned integer type provides is to declare and assert values to be whole numbers between zero and a fixed upper bound, benefiting static analysis and runtime safety. 

Having unsigned integer literals is unnecessary for such typing: There is no need for a prefix/suffix  for static analysis to validate that a number like `42` is a nonnegative integer. Systems languages may use such explicit literals to guide the byte-level representation of these numbers and/or to dispatch overloaded operators on the specific argument type. Clarity doesn't have the same need for unsigned integer literals.

**Comment by diwakergupta** [comment]
@kantai to either close this PR or open a separate issue to track dependency with the integer sub-typing proposal.
