### ISSUE TITLE
"exit_at_block_height" key in/v2/info response is null against local node, has value run against argon.blockstack.org endpoint

### ISSUE THREAD

**Issue by lketchersid** [blockstack/stacks-blockchain#1684]
**Describe the bug**
The key "exit_at_block_height" is null when hitting the /v2/info endpoint against local node, but has an integer value when run against argon.blockstack.org endpoint

**Steps To Reproduce**
Ran GET 'http://localnode:20443/v2/info' via curl on miner, received null.
Ran GET 'http://192.168.1.166:20443/v2/info' from POSTMAN in another computer on my network, got null.
Ran GET 'http://argon.blockstack.org:20443/v2/info' via POSTMAN and curl and received integer value.

**Expected behavior**
This is what was received against argon.
{
    "peer_version": 385875968,
    "burn_consensus": "b8723e7d0061cb4c5ec23de62a462c6580c7124a",
    "burn_block_height": 1123,
    "stable_burn_consensus": "4c744e591047df1f7ecc4bea76cefacb6e35b0f1",
    "stable_burn_block_height": 1122,
    "server_version": "blockstack-core 0.0.1 => 23.0.0.0 (master:8054315c1+, release build, linux [x86_64])",
    "network_id": 2147483648,
    "parent_network_id": 3669344250,
    "stacks_tip_height": 422,
    "stacks_tip": "8938f112f8b25ad21fefa6bcc46b768f231869193374cf691d19c94059c20ade",
    "stacks_tip_burn_block": "02989ca0ac04800786cfd97245f8d98b5a1c61d1a37bb3b1c75cc9a4f282a4ab",
    "exit_at_block_height": 20460
}

This is what was received near the same time against local miner

{
    "peer_version": 385875968,
    "burn_consensus": "b8723e7d0061cb4c5ec23de62a462c6580c7124a",
    "burn_block_height": 1123,
    "stable_burn_consensus": "4c744e591047df1f7ecc4bea76cefacb6e35b0f1",
    "stable_burn_block_height": 1122,
    "server_version": "blockstack-core 0.0.1 => 23.0.0.0 (master:85f0f8666, release build, macos [x86_64])",
    "network_id": 2147483648,
    "parent_network_id": 3669344250,
    "stacks_tip_height": 422,
    "stacks_tip": "8938f112f8b25ad21fefa6bcc46b768f231869193374cf691d19c94059c20ade",
    "stacks_tip_burn_block": "02989ca0ac04800786cfd97245f8d98b5a1c61d1a37bb3b1c75cc9a4f282a4ab",
    "exit_at_block_height": null
}

**Environment (please complete the following information):**
 - OS: maco
Build is from pull after this morning's (6/17) chain reset

**Additional context**

There are several "Bad nonce" messages in the miner console logs. Not sure if relevant.

WARN [1592415889.354] [src/chainstate/stacks/miner.rs:652] [ThreadId(6)] Failed to apply tx d6c00efb945e05460642d1576b1234149f7be862cdb8193047f069dc0e9a1e33: InvalidStacksTransaction("Bad nonce: origin account STFB1E2YTA8G70KN485C8R5RS519Z31P0139XJPC nonce of tx d6c00efb945e05460642d1576b1234149f7be862cdb8193047f069dc0e9a1e33 is 2 (expected 3)")
WARN [1592415889.355] [src/chainstate/stacks/db/transactions.rs:263] [ThreadId(6)] Bad nonce: origin account STFB1E2YTA8G70KN485C8R5RS519Z31P0139XJPC nonce of tx d62e03ba6e18b021911deecb820f7a8be2e03d28b69fcf8a02d04e516ac083bb is 1 (expected 3)
WARN [1592415889.355] [src/chainstate/stacks/miner.rs:652] [ThreadId(6)] Failed to apply tx d62e03ba6e18b021911deecb820f7a8be2e03d28b69fcf8a02d04e516ac083bb: InvalidStacksTransaction("Bad nonce: origin account STFB1E2YTA8G70KN485C8R5RS519Z31P0139XJPC nonce of tx d62e03ba6e18b021911deecb820f7a8be2e03d28b69fcf8a02d04e516ac083bb is 1 (expected 3)")
WARN [1592415889.356] [src/chainstate/stacks/db/transactions.rs:263] [ThreadId(6)] Bad nonce: origin account STFB1E2YTA8G70KN485C8R5RS519Z31P0139XJPC nonce of tx 80388c052b289cd26671cc58a648e26d2b758ecc1024236b2de9532fc096c0c4 is 0 (expected 3)
WARN [1592415889.356] [src/chainstate/stacks/miner.rs:652] [ThreadId(6)] Failed to apply tx 80388c052b289cd26671cc58a648e26d2b758ecc1024236b2de9532fc096c0c4: InvalidStacksTransaction("Bad nonce: origin account STFB1E2YTA8G70KN485C8R5RS519Z31P0139XJPC nonce of tx 80388c052b289cd26671cc58a648e26d2b758ecc1024236b2de9532fc096c0c4 is 0 (expected 3)")
WARN [1592415889.357] [src/chainstate/stacks/db/transactions.rs:263] [ThreadId(6)] Bad nonce: origin account STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6 nonce of tx cab61d5fc13d8b0ace5616c9dab8237bb25d9747fa1a20f438c5daf6c1fde695 is 11 (expected 12)
WARN [1592415889.357] [src/chainstate/stacks/miner.rs:652] [ThreadId(6)] Failed to apply tx cab61d5fc13d8b0ace5616c9dab8237bb25d9747fa1a20f438c5daf6c1fde695: InvalidStacksTransaction("Bad nonce: origin account STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6 nonce of tx cab61d5fc13d8b0ace5616c9dab8237bb25d9747fa1a20f438c5daf6c1fde695 is 11 (expected 12)")

**Comment by lgalabru** [comment]
Hi @lketchersid, thank you for reporting this. Can you confirm that you're using the latest master?
Also, do you mind sharing your config?
Thank you!

**Comment by lketchersid** [comment]
Hello Ludo.

Miner config (GitHub would let me attach .toml file)
-----------------
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@argon.blockstack.org:20444"
# Enter your private key here!
seed = "e0af991de106b6dc7cbe95328b7a99da3f097e19fba2c17d5438aa49a56a12cc01"
miner = true

[burnchain]
chain = "bitcoin"
mode = "argon"
peer_host = "argon.blockstack.org"
rpc_port = 18443
peer_port = 18444

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000
[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000

----------------------------------

In the JSON response I posted above hitting my miner node it says "master:85f0f8666, release build". I uploaded a screenshot of a couple of git commands from the miner with version information. I last did a pull after yesterday morning's chain reset.
![Screen Shot 2020-06-18 at 11 36 49 AM](https://user-images.githubusercontent.com/3418656/85059239-ed0d2c00-b168-11ea-8776-5e2d2905b1af.png)

**Comment by lgalabru** [comment]
Got it.
The `exit_at_block_height` is a field that should be in the config used when starting your node - not the case in the config that you've revealed.
You can see this field being set in the recommended configuration for argon here:
https://github.com/blockstack/stacks-blockchain/blob/d8065901aea09dbc014b995d8a3ba727bcfb1b76/testnet/stacks-node/conf/argon-follower-conf.toml#L12

**Comment by lketchersid** [comment]
Easy fix. thanks. The miner documentation at https://docs.blockstack.org/core/smart/testnet-node.html needs to be updated. The field isn't shown in the sample testnet-miner-conf.toml. 

Isn't the value in that field supposed to change or is it static? On Discord diwalker typed this:
"stacks_tip_height is the current Stacks chain height. Delta between exit_at_block_height and burn_block_height tells you how long until the next reset (block interval is 30s)"

**Comment by lgalabru** [comment]
Once set, this value will be returned in the API, and be constant. The `burn_block_height ` will be incremented (once every 30s), and when reaching the termination value set, your node will gracefully exit, along with all the nodes in the network.

> The miner documentation at https://docs.blockstack.org/core/smart/testnet-node.html needs to be updated.
Thank you for sharing, we will update this!

**Comment by lgalabru** [comment]
Will close and transfer this issue to the doc repo.

**Comment by lketchersid** [comment]
Cool. Thanks Ludo! Shall I close or do ya'll do that?
