### ISSUE TITLE
[TESTNET BUG] No ports are exposed after launching the miner

### ISSUE THREAD

**Issue by danielimkk** [blockstack/stacks-blockchain#1685]
## Describe the bug

After launching proof-of-burn miner there are no ports exposed, even though they are specified in the config file.

## Steps To Reproduce

`stacks-node argon > /argon.log 2>&1 &
**Creating a config file. P.S. please see bellow**
stacks-node start --config=/neon-miner-conf.toml`

## Expected behavior

I expect that all of the ports are exposed and API calls through rpc can be done

## Environment

 - OS: Debian
 - Rust 1.44.0
 - Output of `stacks-node version`: `stacks-node 0.1.0 => 23.0.0.0 (master:d8065901a, release build, linux [x86_64])`

## Additional context
Here is the config file:
`
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@neon.blockstack.org:20444"

seed = "2033269b55026ff2eddaf06d2e56938f7fd8e9d697af8fe0f857bb5962894d5801"
miner = true

[burnchain]
chain = "bitcoin"
mode = "neon"
peer_host = "neon.blockstack.org"
rpc_port = 18443
peer_port = 18444

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000
[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000
`

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by psq** [comment]
the miner should open the port when it has caught up on the most recent blocks.

**Comment by danielimkk** [comment]
Got it, thank you
