### ISSUE TITLE
Mempool should accept nonces that increment a pending transaction

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain#1686]
I am working on tracking the local nonce within the sandbox, and I've noticed this situation:

- I sent a transaction, the nonce was 4, tx sent and is now "pending"
- I increment the nonce and persist it in the state of the sandbox
- I send another transaction, with the new nonce of 5, and it is rejected

I am not sure if this is an issue with the sidecar or the node. 

cc @kantai @zone117x

**Comment by diwakergupta** [comment]
Should be closed by #1697
