### ISSUE TITLE
Mempool Replace-By-Fee logic will overwrite in nearly all cases

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1687]
The current replace-by-fee logic only searches for "replace by fee" candidates in the current chain tip:

See:

https://github.com/blockstack/stacks-blockchain/blob/master/src/core/mempool.rs#L555

Which means that if a transaction with the _same_ nonce and sender was submitted in a previous block, the subsequent "INSERT OR REPLACE INTO" SQLite query will replace the prior transaction, regardless of whether or not the fee was higher. If the fee was _lower or equal_, this should result in a mempool rejection.

**Comment by diwakergupta** [comment]
Should be closed by #1697
