### ISSUE TITLE
Power function has undocumented restriction on exponent

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#1692]
**Describe the bug**

The Clarity `pow` function fails when the exponent is `(pow 2 32)` or larger. Yet the Clarity reference [says the exponent can be an `int` or `uint`](https://docs.blockstack.org/core/smart/clarityref#pow) with no further restrictions.

**Steps To Reproduce**

Evaluate:

```scheme
(pow 1 4294967296)
=> 
Runtime Error: Runtime(Arithmetic("Power argument to (pow ...) must be a u32 integer")
```

**Expected behavior**

Either the Clarity reference should document the actual range of the exponent, or the function should support any integer as exponent.

**Additional context**

Except for when the base is -1, 0, or 1, the function is limited to an exponent of less than 127 (or 128u) as a higher exponent will result in an overflow.

**Comment by psq** [comment]
indeed, the underlying implementation uses `u32` for the exponent.  The way it is implemented would be easy to extend to u128, but not terribly efficient...

**Comment by njordhov** [comment]
> The way it is implemented would be easy to extend to u128, but not terribly efficient

The implementation can still be efficient as it can short-circuit, either to constants when the base is -1...1 or to an error when the exponent is above ~128. The real issue is that the `pow` function currently fails on valid input, which may introduce unexpected behavior in some edge cases. Like, this shouldn't fail even when the exponent `x` is 127 or above:

```scheme
(pow (if (< x 127) 2 1) x)
```

**Comment by psq** [comment]
actually there is no need for a `pow` that would take a 128 bits int or uint.  Anything applied to any value other than 0 or 1 will overflow anyway.  The only fix needed is to have a special case for handling 0 and 1, which would return 0 and 1 respectively.  Happy to create a PR for this if this makes sense.

**Comment by njordhov** [comment]
> actually there is no need for a pow that would take a 128 bits int or uint for the exponent.
> Anything applied to any value other than 0 or 1 will overflow anyway.

See the _Additional Context_ section in OP, which expands on this point.

**Comment by njordhov** [comment]
> The only fix needed is to have a special case for handling 0 and 1, which would return 0 and 1 respectively.

Note that `(pow 0 0)` currently evaluates to `1`. This is [documented for Rust](https://docs.rs/num-traits/0.2.10/num_traits/pow/fn.pow.html) as _Mathematically this is undefined._ The Clarity reference should document this as well.

**Comment by diwakergupta** [comment]
@njordhov thanks, would you be interested in submitting a documentation PR to clarify this?

**Comment by njordhov** [comment]
> would you be interested in submitting a documentation PR to clarify this?

@diwakergupta I favor upgrading the Rust implementation as proposed by @psq by using conditionals to cover the cases that currently incorrectly fails for exponents larger than 32 bit, which only happens when the base is -1, 0, or 1. That way, Clarity developers doesn't have to learn to deal with a special 32 bit limitation on the exponent.
