### ISSUE TITLE
Transaction wire format: Fee rate versus fee

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1695]
Currently, the wire format implementation describes a "fee rate", and there's segments of code that treat the supplied fee as a rate, e.g., in `core::mempool`, `estimated_fee = len * fee_rate`, but elsewhere (in the transaction processing and in the mempool _acceptance_ code), the code expects to be supplied a _fee_. We should figure out which of these alternatives we actually want to implement.

**Comment by jcnelson** [comment]
It needs to be `fee_rate`.  We incorrectly use it as a fee right now, but once the block-fill calculation is finished, this field will be multiplied against the runtime-assessed fraction of the block's budget that gets filled.

**Comment by kantai** [comment]
Okay -- that works for me -- I'll leave this issue open until we've implemented the changes.

**Comment by kantai** [comment]
From discussion on #1190 -- we are going to use fee amounts rather than fee rates, so we should update any documentation and references in the code to `fee_amt` rather than `fee_rate`.

**Comment by lgalabru** [comment]
I think this issue was addressed, can we close @kantai ?

**Comment by kantai** [comment]
Yep!
