### ISSUE TITLE
incorrect block reward value

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#1710]
**Describe the bug**
the block reward in https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/db/blocks.rs#L2476-L2500 shows `500 * 100_000`, which is 50 tokens, not 500 (previous value was `500000000`, which was correct).  Same for the other 2 rewards later on

**Expected behavior**
Should be `500 * 1_000_000`

Happy to provide a PR, although not sure how you'd test this...

**Comment by jcnelson** [comment]
Yup, that's correct.  Great catch!  It should be `1_000_000`.  There should be tests for this in `src/chainstate/stacks/miner.rs`, which will also have to be updated.

**Comment by psq** [comment]
I created #1711 and also fixed the value in `coinbase_total_at` in `miner.rs`, however this function does not seem to be called yet.

**Comment by diwakergupta** [comment]
#1711 is merged.
