### ISSUE TITLE
discrepancy between authorization ids constants in sip-005 and stacks-blockchain code

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#1715]
**Describe the bug**
sip-005 (https://github.com/blockstack/stacks-blockchain/blob/develop/sip/sip-005-blocks-and-transactions.md#transaction-authorization) uses `0x03` and `0x04` for standard and sponsored authorizations while `src/chainstate/stacks/mod.rs` (https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/mod.rs#L248-L252) uses `0x04` and `0x05` respectively.

**Expected behavior**
The values should match.

It is possible I'm looking at 2 different things, in which case there is no issue, but there are very few places where the sip refers to sponsored transactions, and looking at block data, the value `0x04` is being used right after the blockchain id bytes.

**Comment by jcnelson** [comment]
@psq The `develop` branch isn't being used anymore.  The copy of SIP-005 in `master` has `0x04` and `0x05` as expected.  Thanks!

**Comment by psq** [comment]
Sorry about that, I realized a couple days ago I was looking at an other outdated SIP.  That’s because the page off of https://blockstack.org points to the `develop` branch (https://blockstack.org/papers).  Maybe this should be updated?

**Comment by diwakergupta** [comment]
> Sorry about that, I realized a couple days ago I was looking at an other outdated SIP. That’s because the page off of https://blockstack.org points to the `develop` branch (https://blockstack.org/papers). Maybe this should be updated?

Good catch @psq ! @markmhx can we update the link to SIPS in the page above to point to the `master` branch instead?

**Comment by psq** [comment]
thank you for the followup, @diwakergupta

**Comment by markmhx** [comment]
Fixed! Thanks for the heads up 🙏

**Comment by psq** [comment]
@markmhx is the fix deployed on the server?  It stills shows a link to https://github.com/blockstack/blockstack-core/tree/develop/sip while it should be https://github.com/blockstack/stacks-blockchain/tree/master/sip

**Comment by markmhx** [comment]
Not yet – this is still awaiting resolution and deploy.

**Comment by markmhx** [comment]
PR submitted here for the fix https://github.com/blockstack/blockstack.org/pull/1140
