### ISSUE TITLE
Re-implement uint/int as a subtype relationship

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1716]
Currently, `uint` is _not_ a subtype of `int`, because it supports `uint`s larger than 2^127 (the max `int` value), however, if we make `uint` a subtype of `int`, many integer operations become much more ergonomic -- integer literals would not need type specifiers, arithmetic and other operations would no longer need to be input type variable, etc.

**Comment by friedger** [comment]
Let's be ergonomic!
