### ISSUE TITLE
Mempool should accept out-of-order nonces up to some limit

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1719]
From @lgalabru and @jcnelson's suggestion in https://github.com/blockstack/stacks-blockchain/pull/1697,

It would be useful in general to support this because transaction messages might get lost or reordered as they are propagated through the p2p network. Balance checks would only work off of the highest contiguous sequence of transactions.

This doesn't _necessarily_ need to be supported from the mempool, nodes could instead detect an out-of-order broadcast and ask other nodes for the missing transactions.

**Comment by diwakergupta** [comment]
@kantai is this still an issue?

**Comment by kantai** [comment]
Yes, the mempool still requires that nonces be submitted in order.

**Comment by kantai** [comment]
Closed via #2153
