### ISSUE TITLE
Long pending transaction 

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1724]
**Describe the bug**
Transaction is shown as pending for more than 20 hours:
https://testnet-explorer.blockstack.org/txid/0x90b4f160aa41457826052e03d606faa20ec6ee7ba8d398a0e02635cdc1e0f399

**Steps To Reproduce**
I have used https://github.com/friedger/clarity-smart-contracts/blob/master/test/integration/flip-coin-deploy-all.ts to deploy `flip-coin` and after ~5 minutes to deploy `flip-coin-tax-office` The first transaction succeeded. The second is still pending

**Expected behavior**
The second transaction should fail or succeed as well.

**Environment (please complete the following information):**
 - submitted through testnet-master.blockstack.org

**Comment by diwakergupta** [comment]
I could only find a _single_ log entry for this transaction in the master logs (on Kibana):

```
DEBUG [1594159223.307] [src/net/relay.rs:934] [ThreadId(6)] local.80000000://(bind=V4(35.221.35.47:20444))(pub=None): Broadcast tx 90b4f160aa41457826052e03d606faa20ec6ee7ba8d398a0e02635cdc1e0f399
```

@blockstack/blockchain-team any pointers on how to further debug this?

**Comment by friedger** [comment]
Here is another long pending tx: https://stacks-node-api.blockstack.org/extended/v1/tx/0x932f5038d0975e88ec708bf8cad48ba5e73ce87d9d93dc1ebb8c9850b18d9e83

**Comment by jcnelson** [comment]
Hey! We recently updated the relay code to be better at transaction replication.  Are you still seeing long-lived transactions in the mempool?

**Comment by aulneau** [comment]
Here is another long pending stx transfer -> 
https://stacks-node-api.blockstack.org/extended/v1/tx/0x682ac08b9193621df450e6b1a7f9c62c0cd27d1f36f279ff6b86e4f2eb5ec7e9

**Comment by diwakergupta** [comment]
We haven't seen this re-occur on Xenon, since a number of improvements captured in other tickets were merged. Closing, we can re-open a more specific issue if needed.
