### ISSUE TITLE
PoX: Implement the Proof-of-Transfer DB for the ChainsCoordinator

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1727]
The ChainsCoordinator and SortitionDB implementation requires that a DB track Proof-of-Transfer forks and maintain some data about the presence of PoX anchors, and construction of PoxIDs.

**Comment by kantai** [comment]
One thing to revisit during the implementation of the PoxDB -- the `pox_id` field of the SortitionDB's snapshot table should have a "foreign key" relationship to the PoX identifier. If possible, SQLite should enforce that foreign key constraint. The current structure of our sqlite databases is such that the various databases are in different SQLite databases. I think that this means enforcing that foreign key relationship would be impossible. However, the PoxDB and the SortitionDB could (in theory) share the same sqlite database.

**Comment by jcnelson** [comment]
> However, the PoxDB and the SortitionDB could (in theory) share the same sqlite database.

This should be fine, if that's what it takes.  This would also make it easier to do transactions across both the `PoxDB` and `SortitionDB` at once (which I think will also be necessary).

**Comment by kantai** [comment]
That works for me -- we could possibly also fold the StacksChainState's sqlite dbs in as well, since I think transactions across all three of those will be necessary. We could also explore SQLite's multi-file commit support (https://www.sqlite.org/atomiccommit.html#_multi_file_commit)

**Comment by jcnelson** [comment]
Per @kantai's comment here (https://github.com/blockstack/stacks-blockchain/pull/1743#issuecomment-660173061), do we even need the `PoxDB` anymore?

**Comment by kantai** [comment]
I don’t think we need a PoxDB as originally imagined here, but we certainly will still need some kind of structure for figuring out the reward set for a PoxAnchor — that will probably be indexed by the SortitionDB’s MARF, but will have to be a new table in the db.

**Comment by jcnelson** [comment]
Consensus is that there won't be a distinct PoxDB.
