### ISSUE TITLE
Clarity: allow partial tuple updates to maps

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#1728]
**Is your feature request related to a problem? Please describe.**
When using a map with many fields, you end up needing to update only a few of the values, but having to specify all values by retrieving they current state.

Examples:
https://github.com/psq/swapr/blob/trait/contracts/swapr.clar#L144-L164
https://github.com/psq/swapr/blob/trait/contracts/swapr.clar#L280-L299
https://github.com/psq/swapr/blob/trait/contracts/swapr.clar#L504-L513

**Describe the solution you'd like**
It would be more convenient to only have to specify the changes values, although this could only work if there is already an existing value for the key, otherwise, this would be an error.

So instead of using:
```
       (map-set pairs-data-map ((token-x token-x) (token-y token-y))
          (
            (shares-total (get shares-total pair))
            (balance-x (get balance-x pair))
            (balance-y (get balance-y pair))
            (fee-balance-x (get fee-balance-y pair))
            (fee-balance-y (get fee-balance-y pair))
            (fee-to-address none)
          )
        )
```
you could use:
```
       (map-set pairs-data-map ((token-x token-x) (token-y token-y))
          (
            (fee-to-address none)
          )
        )
```

**Comment by psq** [comment]
An alternative proposal could be to add a keyword like `rest` to make it explicit that is what you intended to do

**Comment by lgalabru** [comment]
I love this. Recently talked about this feature with @kantai, this could increase the cost since we'd need to read the key/value, then update it. 
Referencing https://github.com/blockstack/stacks-blockchain/issues/1045.

**Comment by psq** [comment]
This is coming mostly from having the most succinct Clarity code, but I would think overall, it would end up costing less.

The `swapr` code already does the read anyway to know what value to use for those that don't change, and this could be cached by the implementation, so there shouldn't be any extra cost (I don't think that's the case currently?).

Regarding the comment from @jcnelson about normalization (which I'm not sure that's what I'd call it since they'd used the same keys), I considered that, and I think this would result into a lot more read and writes for each operations, and also use more storage (which you don't seem to have to pay directly for).

Looking at the `swapr` case, I have the following operations (with the values that change):

```
create pair, no prior value
- shares-total
- balance-x
- balance-y 
- fee-balance-x
- fee-balance-y
- fee-to-address


add to position & reduce-position
- shares-total
- balance-x
- balance-y 

swap-exact-x-for-y & swap-x-for-exact-y
- balance-x
- balance-y
- fee-balance-x

swap-exact-y-for-x & swap-y-for-exact-x
- balance-x
- balance-y
- fee-balance-y

set-fee-to-address & reset-fee-to-address
- fee-to-address

collect-fees
- fee-balance-x
- fee-balance-y
```

so it would make sense to split as follow:
- shares-total
- balance-x + balance-y
- fee-balance-x
- fee-balance-y
- fee-to-address

so 5 maps instead, but now each operations would require a lot more reads and writes, just focusing on the values being updated, ignoring external data:
```
create pair, no prior value: 5 writes
add to position & reduce-position: 2 reads, 2 writes
swap-exact-x-for-y & swap-x-for-exact-y: 2 reads, 2 writes
swap-exact-y-for-x & swap-y-for-exact-x: 2 reads, 2 writes
set-fee-to-address & reset-fee-to-address: 1 reads, 2 writes
collect-fees: 2 reads, 2 writes
```
A lot more costly, and as an added bonus, with shorter code, it costs less to deploy (you only do that once any way).

As you'd do all the `swap` operations most often, these may need to be the cheapest, so maybe you'd combine `balance-x`, `balance-y`, `fee-balance-x`, and `fee-balance-y`, but then you are back to square one...

So, all in all, current implementation is second best from that angle (best would be having partial updates).  Splitting into multiple hashes would also make the code longer, as you'd probably also need to repeat some of the `if`s, so not such an appealing option.

**Comment by njordhov** [comment]
Although not addressing partial updates to map rows, issue #1733 proposes a new function to `merge` records (aka tuples). This provides a step towards more succinct Clarity code. For example, the [third example](https://github.com/psq/swapr/blob/trait/contracts/swapr.clar#L504-L513) in OP can be compressed to:

```clojure
(let ((pair (unwrap! (map-get? pairs-data-map ((token-x token-x) (token-y token-y))) invalid-pair-err)))
  (map-set pairs-data-map ((token-x token-x) (token-y token-y))
    (merge pair { fee-to-address: none })))
```

**Comment by psq** [comment]
I really like the `merge` proposal which provides a suitable solution for what this proposal was addressing, keeps the semantic of `map-set` simpler, and is more versatile as it can be used for other cases as well.

I think we could keep this open for a few more days, then close to focus on https://github.com/blockstack/stacks-blockchain/issues/1733.

**Comment by njordhov** [comment]
> I love this. Recently talked about this feature with @kantai, this could increase the cost since we'd need to read the key/value, then update it.

A `map-update` function that updates an existing map field could take `merge` from #1733 as a function argument to combine the existing field with new values:

```clojure 
(map-update pairs-data-map {token-x, token-y} 
   merge {fee-to-address: none})
```

This concisely implements the same functionality as the examples above, updating the map by merging the `{fee-to-address: none}` record into an existing field matching the `{token-x, token-y}` key (shorthand notation as proposed in #1335). The developer will no longer have to explicitly get the original field values. 

Although `merge` covers the typical case, the function argument can be any other function that returns an updated field. As a consequence, developers can create custom functions that generate the updated field from its original values and the provided arguments. Assuming these functions are pure, it will facilitate unit testing to verify that they generate the correct updated field.

**Comment by lgalabru** [comment]
Addressed and merged.
