### ISSUE TITLE
[Bug] Chain silently hangs when events_observer URL has protocol

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#1741]
**Describe the bug**
When you pass a full URL as the ENV variable for the `events_observer` endpoint, the chain hangs after the 2nd block, and then, nothing happens, and no blocks are further produced. You need to pass the URL without the protocol for it to work, i.e. `127.0.0.1:3700`.

**Steps To Reproduce**

`STACKS_EVENT_OBSERVER=http://127.0.0.1:3700 stacks-node mocknet`

Also reproduceable if you use the same URL in your config file.

**Expected behavior**
Either:
1. Support this kind of URL (better DX for those running a sidecar)
2. Show an error message

**Environment (please complete the following information):**
 - Mac OS. Using a locally built `stacks-node` binary. Built from latest master.

**Comment by aulneau** [comment]
@jcnelson @lgalabru can we re-open this? the event observer cannot seem to accept any url that contains a protocol, or is https
