### ISSUE TITLE
Weak password policy

### ISSUE THREAD

**Issue by nishant8990** [blockstack/stacks-blockchain#1746]
Weak Password Policy :-
In your Website the user are able to use the same password as their user name for eg. the user name is pentest123@ and user can set their password as pestent123@ these type of passwords can be easily guessed

How to Fix this issue ? :-
prevent users to use their username as their password  

Impact: Password should not match with Email address because if password is same as Email address then account can be compromise easily! As well as this password can easily be cracked by dictionary attack

**Comment by jcnelson** [comment]
Hi @nishant8990, thank you for raising this, but this isn't the right repo for these issues.  Please file this at https://hackerone.com/blockstack.  Thanks!
