### ISSUE TITLE
No email verification after signed up

### ISSUE THREAD

**Issue by nishant8990** [blockstack/stacks-blockchain#1747]
Vulnerability name: No email confirmation send after signing up 

When you register for a new account, there is no verification link sent to the email for confirmation. The account is directly activated and can be used without confirming the email.

This is vulnerable as anyone can use anyone's email without verification. and one with valid email owner cant signup with his own email as someone else already took it before him.

Impact:other users data easily stolen by an attacker

**Comment by jcnelson** [comment]
Hi @nishant8990, thank you for raising this, but this isn't the right repo for these issues.  Please file this at https://hackerone.com/blockstack.  Thanks!

**Comment by nishant8990** [comment]
I am not on hackerone. please check my report .
