### ISSUE TITLE
P2P: Track block download rate

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1754]
Make it so the p2p network can track the rate at which blocks arrive, and serve that rate via `/v2/info`.  This is to be used as a heuristic to miners to determine when the node has received enough chainstate that mining is likely to succeed.

**Comment by jcnelson** [comment]
Specifically, we need to make to so that we can infer when a reward cycle has finished downloading.  More generally, this will help the networking code infer when the initial block download has finished, and when the node starts steady-state processing.

**Comment by wileyj** [comment]
Would it be possible to also add this to the prometheus endpoint? This seems like a great metric to keep track of

**Comment by jcnelson** [comment]
Should be possible, but I'm thinking about splitting the work for adding this to `/v2/info` into a separate ticket.

The reason we track this information is so we can make the burnchain block downloader logic wait until all Stacks blocks for the previous reward cycle have been processed before proceeding to download the next burn blocks.  This significantly reduces the amount of sortition-processing work the node needs to do to catch up to the chain (i.e. it makes it a _O(n)_ operation on the happy path, whereas before it was a _O(n^2)_ operation).

The reason for adding this information to `/v2/info` was that it would allow an _external mining program_ to determine whether or not the Stacks node has reached steady-state.  I think this task could be handled differently.

**Comment by jcnelson** [comment]
Implemented!
