### ISSUE TITLE
Testnet panic

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1765]
Jul 24, 2020 @ 11:33:24.342, we've been experiencing a testnet reboot.
The [only log](https://kibana.blockstack.xyz/s/blockstack/app/kibana#/discover/doc/650ba540-a8c0-11e9-af29-99ef60078375/logstash-2020.07.24?id=aEN1gXMBo9ey40_shkDx) we have is:
```Process abort due to thread panic```.

<img width="1417" alt="Screenshot 2020-07-24 at 12 33 46 PM" src="https://user-images.githubusercontent.com/87777/88413874-f57d0600-cda9-11ea-85a7-d18fe24bb2d8.png">

Issue requires a deeper investigation.

**Comment by jcnelson** [comment]
Fixed in #1764
