### ISSUE TITLE
Create GH Action Workflow to build/release stacks-blockchain assets

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain#1780]
# GH Workflow
I'd like to help create and/or consolidate one or more GH workflows to automate the testing, build, release and versioning of this project in GH Actions, and transition this project away from CircleCI if possible. Doing so would allow us to:

* consolidate the number of CI tools we're using across our projects
* align with our other projects which are using Github Actions to automate these processes
* simplify and improve the SDLC

Currently, this project has a [CircleCI workflow](https://app.circleci.com/pipelines/github/blockstack/stacks-blockchain) and a few [GH Action workflows](https://github.com/blockstack/stacks-blockchain/actions). There may be some light redundancy between them, but the goal would be to consolidate the logic needed into one or more GH Actions workflows which would handle the testing, build, release, and versioning of this repository in this order, and delete any previous CircleCi/GH workflows replaced by the new workflow(s). Additional steps such as multiple forms of testing or multiple forms of builds may be parallelized to reduce runtime of the workflow. I would ensure all of the job logic running today would continue, it just may be moved to a different workflow or rearranged according to what makes sense.

# Semantic Versioning
In addition to the change mentioned above, it seems this project is following a custom versioning pattern. If possible, I would like to align this project to follow the [Semantic Versioning](https://semver.org/) pattern since it's used in our other projects. I would be able to implement this in the new GH Workflow I described above, but I want to open up the discussion and see if others would like to head in this direction as well. Using semantic versioning opens the door to automatic versioning via the [semantic-release plugin](https://github.com/semantic-release/semantic-release) which is being used in the [stacks-blockchain-api](https://github.com/blockstack/stacks-blockchain-api) project. This plugin would automate tag creation, version increments, updates to a CHANGELOG.md file, and leave comments on PRs to inform users when it's available in a new release.

# Thoughts?
@blockstack/blockchain-team @wileyj 
Please let me know your thoughts concerns below.

Related to issue https://github.com/blockstackpbc/devops/issues/367

**Comment by kantai** [comment]
I don't think that we're ready for automated versioning in this repo -- ultimately the version for a build in this repo should be equal to what's reflected in the top-level `Cargo.toml` file. We could do something like protect the `master` branch, and then add a check to the PR that ensures that the version there is bumped (and other version locations match), which would at least ensure that we're performing versioning.

As far as automated builds, moving to github workflows goes, I think that's a great idea -- porting our existing CircleCI framework over to GH workflows should be pretty straight-forward. One thing I'd like to see is our GH workflows _also_ producing automated `clarity-cli` builds, which could be consumed by the `clarity-js-sdk` (see: https://github.com/blockstack/clarity-js-sdk/issues/99)

**Comment by CharlieC3** [comment]
Thanks for the input!

> I don't think that we're ready for automated versioning in this repo

Would you be able to clarify what you mean for this? If it's a matter of timing, then I'm fine with pushing this back for consideration down the road. But if the concern is technical, such as finding a way to link updates to the `version` property in the `Cargo.toml` to an automated release, I would be able to automate that to ensure when a new version/tag gets created, it would contain an updated `Cargo.toml` which reflects the new version.

> One thing I'd like to see is our GH workflows also producing automated clarity-cli builds, which could be consumed by the clarity-js-sdk

I may need some direction on this to start, but that should be doable.

**Comment by kantai** [comment]
> Would you be able to clarify what you mean for this? If it's a matter of timing, then I'm fine with pushing this back for consideration down the road. But if the concern is technical, such as finding a way to link updates to the version property in the Cargo.toml to an automated release, I would be able to automate that to ensure when a new version/tag gets created, it would contain an updated Cargo.toml which reflects the new version.

My concern is that we'd like our versions to convey:

1. A major bump if the change is breaking
2. A minor bump if the change is a "non-breaking feature"
3. A patch bump otherwise

But that requires that somebody is indicating that when a PR is merged -- https://github.com/semantic-release/semantic-release uses semantic commit messages to automate the version bump. To support that, we'd need to require that all PR's merge commits convey the version change.

**Comment by CharlieC3** [comment]
> But that requires input from somebody indicating the kind of change when a PR is merged. https://github.com/semantic-release/semantic-release uses semantic commit messages to automate the version bump. To support that, we'd need to require that all PR's merge commits convey the version change.

As long as a PR is _merged_ and not _squashed_, the `semantic-release` plugin will individually analyze all of the new commit messages included in the PR merge, and not just the commit message of the PR merge. So the PR title would not matter in this case. However, if the PR is squashed into the destination branch, then I believe the title and merge description would have to conform to the [Angular commit message convention](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) to be picked up by the `semantic-release` plugin.

The way I've solved this for other projects is as follows:
1. Install a pre-commit hook which runs [commitlint](https://github.com/conventional-changelog/commitlint) upon local commit which will analyze the commit message and reject the commit if the message does not conform to the [Angular commit message convention](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).
1. Create a GH Workflow which scans the title of PRs and runs commitlint on them. If it fails to conform to the Angular commit message convention, the check fails on the PR. If the first option is effective enough, we may not _need_ to do this one.

**Comment by CharlieC3** [comment]
@jcnelson What are your thoughts on the above?

**Comment by kantai** [comment]
I understand the appeal of automating semantic versions, but supporting a flow like the following would reap almost all of the benefits, while avoiding some of the downsides of automated versioning:

1. When a tag matching `vX.Y.Z` is pushed, the normal automated builds are kicked off.
2. Native binary outputs are pushed as release outputs to our Github releases.
3. Docker images are pushed as `vX.Y.Z` tags, rather than just `latest` or `master`

If, in addressing https://github.com/blockstack/clarity-js-sdk/issues/99, they want to automate the process of opening a PR on `clarity-js-sdk`, the PR automation would just need to watch the same actions as the "release".

This process wouldn't be automated, but pushing a git tag is pretty easy, and would dramatically simplify the process of getting a new binary for the clarity-js-sdk.

**Comment by diwakergupta** [comment]
> I understand the appeal of automating semantic versions, but supporting a flow like the following would reap almost all of the benefits, while avoiding some of the downsides of automated versioning:
> 
> 1. When a tag matching `vX.Y.Z` is pushed, the normal automated builds are kicked off.
> 2. Native binary outputs are pushed as release outputs to our Github releases.
> 3. Docker images are pushed as `vX.Y.Z` tags, rather than just `latest` or `master`
> 
> If, in addressing [blockstack/clarity-js-sdk#99](https://github.com/blockstack/clarity-js-sdk/issues/99), they want to automate the process of opening a PR on `clarity-js-sdk`, the PR automation would just need to watch the same actions as the "release".
> 
> This process wouldn't be automated, but pushing a git tag is pretty easy, and would dramatically simplify the process of getting a new binary for the clarity-js-sdk.

Makes sense. @CharlieC3 you good with this?

**Comment by CharlieC3** [comment]
@diwakergupta Yup, will move forward with this. Thanks all.
