### ISSUE TITLE
Regression in `neon_node.rs` in `next` branch

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1784]
There appears to be a regression currently in the `next` branch for the `neon_node`:

```
$  BITCOIND_TEST=1 cargo test --workspace --bin=stacks-node -- --test-threads 1 --ignored neon_integrations::bitcoind_integration_test --nocapture
...
WARN [1596287607.374] [testnet/stacks-node/src/neon_node.rs:502] [ThreadId(8)] Did not win sortition, my blocks [consensus_hash= c124bc708a1fe9d4fcbc482d305b49e71fa6ce77, block_hash= 8a0ac93ffb6bad673f7ee323df379991e6daeafef188a4d5e56db60bc3ec5035], their blocks [parent_consenus_hash= 0000000000000000000000000000000000000000, consensus_hash= f22a52a4811a85980fd2f7d7fcfd93d686d531b4, block_hash =8a0ac93ffb6bad673f7ee323df379991e6daeafef188a4d5e56db60bc3ec5035]
```

That test fails, because even though the miner wins a sortition, it doesn't appear to be able to confirm that it won the sortition, because its expected consensus hash doesn't match the produced consensus hash for the block. I think this check cannot work as it is used there, because a miner _couldn't_ know the consensus hash for the block in which their commitment is included a priori. However, simply changing this check back to a burn_header_hash check didn't solve the problem, so there's probably something more going on here as well.

I'll try to look into fixing this regression this weekend, as this is blocking any integration work on the ChainsCoordinator.

**Comment by jcnelson** [comment]
Sounds good.  But, from what you've explained, wouldn't the miner also _not_ know the burn header hash for the block in which their commitment is included _a priori_?

**Comment by kantai** [comment]
> Sounds good. But, from what you've explained, wouldn't the miner also not know the burn header hash for the block in which their commitment is included a priori?

Yes -- which is why the check is performed on the parent burn block. So the miner records the burn tip that they mined at, and then checks the sortition that they won's parent.

**Comment by jcnelson** [comment]
Fixed in `next`
