### ISSUE TITLE
[TESTNET BUG] Contract calls with fungible post conditions fail when using Connect library

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1791]
## Describe the bug

This is an issue of `ux/packages/app`. Contract calls with fungible post conditions fail when using Connect library
See https://github.com/blockstack/ux/issues/570

## Steps To Reproduce

Try to bet on https://speed-spend.netlify.app

## Expected behavior

contact call transaction can be signed and is processed

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [x] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by timstackblock** [comment]
Thanks @friedger this sounds like a connect issue and not a blockchain issue.

I will talk to @hstove and make sure this in on his radar.

**Comment by friedger** [comment]
Indeed, to me it was not clear whether that is part of the bounty or not. I
created a detailed issue in the ux repo.

timstackblock <notifications@github.com> schrieb am Mi., 5. Aug. 2020,
15:53:

**Comment by diwakergupta** [comment]
@friedger issues that qualify for bug bounties are NOT restricted to the stacks-blockchain repo. We'll consider any qualifying issues, regardless of the repo cc/ @timstackblock 

I'll close this out for now.
