### ISSUE TITLE
Variable expansion in Config.toml **or** additional command-line arguments

### ISSUE THREAD

**Issue by wileyj** [blockstack/stacks-blockchain#1792]
When running multiple miners with minor configuration differences, it would be advantageous to use a single config file with either variable substitution or additional command-line args. 

Example `Config.toml`:
```
peer_host = "${PEER_HOST}"
commit_anchor_block_within = ${COMMIT_ANCHOR_BLOCK_WITHIN}
rpc_port = ${RPC_PORT}
peer_port = ${P2P_PORT}
```

example exec:
```
export PEER_HOST="bitcoin.blockstack.com"
export COMMIT_ANCHOR_BLOCK_WITHIN=300000
export RPC_PORT=8332
export P2P_PORT=8333
./stacks-node start --config=/etc/Config.toml
```

Alternatively, or as an additional option: extra command-line args which override the provided `Config.toml` contents.
ex:
```
./stacks-node start \ 
  --peer_host="bitcoin.blockstack.com" \
  --commit_anchor_block_within=300000\
  --rpc_port=8332 \
  --peer_port=8333 \
  --config=/etc/Config.toml
```

**Comment by jcnelson** [comment]
What if we made it so the `stacks-node` could take its config file on `stdin`?  Then, we can have a `Config.toml` file with variable substitution simply by `eval`ing it against its environment.  We could do something like this:

```
$ cat /etc/Config.toml
peer_host = "${PEER_HOST}"
commit_anchor_block_within = ${COMMIT_ANCHOR_BLOCK_WITHIN}
rpc_port = ${RPC_PORT}
peer_port = ${P2P_PORT}
$ export PEER_HOST="bitcoin.blockstack.com"
$ export COMMIT_ANCHOR_BLOCK_WITHIN=300000
$ export RPC_PORT=8332
$ export P2P_PORT=8333
$ cat /tmp/Config.toml | envsubst | ./stacks-node start --config=-
```
```

**Comment by wileyj** [comment]
This type of templating could work, sure - but it would also still require an update to the default `Config.toml`. 


The goal with this issue is to be able to have a default `Config.toml` with sane defaults, that could be overridden with env vars. 

My preference would be to start the process like this:
```
./stacks-node start \ 
  --peer_host="bitcoin.blockstack.com" \
  --commit_anchor_block_within=300000\
  --rpc_port=8332 \
  --peer_port=8333 \
  --config=/etc/Config.toml
```

where `/etc/Config.toml` is simply the default config, and I'm able to override some specific values on the command line, while still using a provided sample config file such as https://github.com/blockstack/stacks-blockchain/blob/master/testnet/stacks-node/Stacks.toml
