### ISSUE TITLE
Proposal: In-situ Clarity VM upgrades without forks!

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1794]
This is a write-up of a great idea @kantai had, with inspiration from @psq.

## In-Situ Clarity VM Upgrades, Without Forks!

A major consequence of designing Clarity as an on-chain interpreted language is that modifying the language spec would mean modifying the interpreter (VM), which in turn may require a _hard fork_.  But, it turns out that this isn't true for a large class of upgrades that developers would actually want to see -- namely, the introduction of new native functions, with the constraint that they also happen to be entirely expressible in Clarity.  Turns out, this covers a _lot_ of native functions!

In order to support adding new native functions to Clarity, the only thing we need to change about the VM is to make it so miners can vote on the "true" runtime cost for a given public function in a given contract.  If miners can do this, then it becomes possible to replace a Clarity implementation with a cheaper native implementation without breaking compatibility.

With this change to the VM, adding a new native function becomes a three-step process:  (1) write and deploy Clarity implementation of the function as a library smart contract (e.g. one with no state of its own), (2) write and deploy a new version of the VM that handles that contract function invocation with a native implementation, and (3) get the miner network to vote on its native runtime cost (which should be less than its Clarity runtime cost).  We would need to implement the voting mechanism in (3) as a supported feature of the Clarity VM before mainnet, but if we do this, then it would become possible to add native extensions to Clarity over time in a backwards-compatible way.

Let's walk through an example of how this might work in practice with an example: adding a native ed25519 signature verification algorithm to Clarity.

### Step 1:  Write a Clarity Implementation

Despite being a decidable language, Clarity is somewhat expressive and can be used to implement a wide variety of useful algorithms.  For example, suppose we wanted to add a native function to verify ed25519 signatures.  This is currently not supported in Clarity.  However, it should be possible to at least write an ed25519 signature verification implementation as a Clarity public function, even if running it would be slow and expensive.

Once a Clarity implementation exists, the developer only needs to publish it in a library smart contract (i.e. one with no data maps or data vars).  Other contracts could use it to verify ed25519 signatures with `contract-call?`, per usual.

### Step 2:  Write a Native Implementation

Suppose that after deploying the contract, the ed25519 signature verification gets a lot of real-world use.  Because the Clarity version is slow and expensive, the Stacks node developers would modify the Clarity VM to implement the equivalent logic in Rust.  The modified VM would look for `contract-call?`s that call the ed25519 signature verification function, and handle them with the native implementation instead of the Clarity implementation.  This would make the node considerably faster at processing transactions that do this, but the runtime cost of the transactions would remain the same for the time being.

### Step 3:  Vote on a Native Runtime Cost

Suppose that a node implementation with the native ed25519 signature verification gets popular.  Now that a native implementation exists, miners can vote on the _true_ runtime cost for this function.  To do so, they would publish the contract function's address and proposed runtime cost as part of their blocks' coinbase transactions, thereby voting collectively on the true cost (similar to how Bitcoin miners vote on new features).  If the new runtime cost gets enough votes (measured by mining power) over a long enough time period, then all Clarity VMs begin to use that new cost for processing the function instead of the old cost.

## Why This Works

Nodes do not have to upgrade for this process to work.  Because the Clarity VM would be designed to accept miner-given per-public-function cost overrides like that described in step 3, all nodes everywhere would continue to execute the code the same way and assess transactions the same runtime cost for it.  Old nodes with the Clarity implementation would just continue to be slow, but they would never be required to upgrade.  Newer nodes would reap the benefits of the faster implementation.

Thoughts? Comments?

**Comment by psq** [comment]
looks great!

And yet, I'm still having a hard time with having to rely on `contract-call?` rather than a more friendly name like `ed25519-verify` in your Clarity code, especially once it is native and eventually becomes part of the specification.  Whether we use a new syntax for bringing in these library functions, or make it possible to use a shortcut to call a contract by having something like:
```
(use-contract-function 'SP138CBPVKYBQQ480EZXJQK89HCHY32XBQ0T4BCCD.ed25519.ed25519-verify ed25519-verify)
```

**Comment by jcnelson** [comment]
I like that idea!  I think having a `use-contract-function` would be useful syntactic sugar, upgrade process or no.  We need to retain the `contract-call?` usage semantics though, because new nodes with the native implementation have to remain forever compatible with the old nodes with the non-native Clarity implementation.

**Comment by psq** [comment]
yes, indeed.

**Comment by jcnelson** [comment]
Expanding on the `use-contract-function` idea, one thing to consider would be whether or not to implement a catch-all variant that imported each native-replaced Clarity function into the contract as top-level keywords.  Then, you could just have something like `(use-native-functions)` at the top of your contract, and `ed25519-verify` would be usable as if it were a keyword.  This would affect consensus, though -- for example, each native-replaced function name would need to be globally unique, and the catch-all would need to be aware of the list of new native functions at the time of contract instantiation -- but I think it could be doable.

**Comment by psq** [comment]
I'd be a bit worried (well, a lot!) about getting some possible junk, and would make experimenting with multiple versions till one is deemed satisfactory much harder.

Instead, why not deploy contracts that include all the popular extensions that people would want to use, which themselves can be reimplemented natively eventually...  The only thing you'd need is a `use-all-contract-functions` to load all these extensions with one line.  Works recursively too (not calling, including!)

**Comment by kantai** [comment]
So I think this is separable into two different issues:

1. Supporting "cost upgrades" for Clarity

Through some on-channel voting mechanism, the cost-assessment of Clarity functions should be modifiable. This should be true for existent functions, as well as "new natives". Supporting this simultaneously de-risks two aspects of Clarity's mainnet launch. First, it allows adjustment of the assessed costs for Clarity routines without a hard-fork, reducing significantly the pressure to "get the costs right" at launch. Second, it allows for new Clarity functions per @jcnelson's description in the issue.

2. Support for includes

Per @psq's comments, needing to use `contract-call?` even after a function has become native is a bit tedious. However, with the described `use-all-contract-functions` and `use-contract-function` methods, we can resolve this. This is separate from the first issue, because the methods would work both before and after any cost upgrades (this is not true of `(use-native-functions)`, which is why I think we should not try to support that method).

**Comment by diwakergupta** [comment]
Next step: a design doc that we can share internally and with the community. Tentative goal by end of August, hopefully before then.

**Comment by njordhov** [comment]
> Through some on-channel voting mechanism, the cost-assessment of Clarity functions should be modifiable. 

What if the cost-assessment for Clarity functions could be declared as a Clarity contract? Then miners could vote on costs (or offer their prices) by deploying such a contract or tune variables in their deployed cost contract. This could allow upgrades to the cost calculations without forks, decentralize the cost estimates, and perhaps even provide a market mechanism for dynamic pricing for running contracts.

For example, [SIP-008](https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-008-analysis-cost-assessment.md) suggests a [calculation to estimate the cost of `get`](https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-008-analysis-cost-assessment.md#get), based on the number of fields in the tuple and adjustable constants `a` and `b`: This could be written in a cost contract as:

```clojure
(define-read-only (cost_get (num-fields int))
  (+ (* a (log num-fields)) b))
```

The miner could be able to tune cost constants like `a` and `b`. They may also change the fundamental cost calculations if needed by deploying a revised contract.

**Comment by dantrevino** [comment]
Excuse my noob question, but I assume lower runtime cost implies lower transaction fees for users and developers... if this is the case, why would miners vote to enable popular functions that reduce their fees?

**Comment by reedrosenbluth** [comment]
@dantrevino The goal here is to design an incentive structure such that correct/accurate cost-assessment functions get chosen. If we get this right, this should be in everyone's best interest. If the native functions are too expensive, people won't want to write/deploy contracts, and if they are too cheap, the miners won't want to mine.

Curious to hear people's thoughts on this... How can this voting process be designed as to best encourage this outcome? How do we prevent market dynamics from having too much influence over the cost proposals? How can we prevent attackers from using this as a vector to make Clarity less usable?

**Comment by lgalabru** [comment]
@kantai can we mark this issue as closed?

**Comment by kantai** [comment]
Yep!
