### ISSUE TITLE
Add Network name to /v2/info

### ISSUE THREAD

**Issue by noumanahmad001** [blockstack/stacks-blockchain#1798]
**Is your feature request related to a problem? Please describe.**
We are implementing Rosetta Api for Stacks, tracking in this [issue](https://github.com/blockstack/stacks-blockchain-api/issues/187)
Many Rosetta Api requests require this [object](https://www.rosetta-api.org/docs/models/NetworkIdentifier.html):
```json
"network_identifier": {
        "blockchain": "bitcoin",
        "network": "mainnet",
        "sub_network_identifier": {
            "network": "shard 1",
            "metadata": {
                "producer": "0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5"
            }
        }
    }
```
The problem is that `/v2/info` call doesn't return the network name. The `sub_network_identifier` section is optional.

**Describe the solution you'd like**
I have forked this repo and changed the api `/v2/info` response to include the network name, my commit is [here](https://github.com/noumanahmad001/stacks-blockchain/commit/e1f146e1a21f315ac7e0b5d2619317fa3dfb9103) . The updated response is something like this
```json
{
  "peer_version": 385875968,
  "burn_consensus": "358935b493bde19a82f3efe636f21f6a4e7d5c49",
  "burn_block_height": 93,
  "stable_burn_consensus": "bf3303d6fb1c2ccadb0f61c28ec6f10848249cd7",
  "stable_burn_block_height": 92,
  "server_version": "blockstack-core 0.0.1 => 23.0.0.0 (sidecar-api-update-info:afc748aa1+, debug build, macos [x86_64])",
  "network_id": 2147483648,
  "parent_network_id": 3669344250,
  "stacks_tip_height": 92,
  "stacks_tip": "b976a8159c173951f5046b8c82c7d692bb8dd20965b4101b3a3b37833d10d2c1",
  "stacks_tip_burn_block": "a66b01fd6595ebbe9274946f8991d1a11232ed63f334c8ce2004242e54d56944",
  "unanchored_tip": "0000000000000000000000000000000000000000000000000000000000000000",
  "exit_at_block_height": null,
  "network_name": "regtest" 
}
```
**Describe alternatives you've considered**
 If you guys can suggest some other solution , we can also try that. 

**Additional context**
My solution for creating the network identifier object is that blockchain key will be some static string like "blockstack".

**Comment by diwakergupta** [comment]
Looks like the current approach of letting the Stacks Blockchain API node provide the network name is working? I'm going to close this out @noumanahmad001 , please reopen if needed.
