### ISSUE TITLE
Economics: lock fees for longer than coinbases

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1800]
Mirroring an offline discussion with Muneeb.

Make it so transaction fees unlock after a month, but coinbases unlock after one PoX registration window (250 blocks).  More material to come on why, but the high-level idea is that different parties (miners, users, exchanges, etc) value transaction fees differently than the coinbase, and making the transaction fee materialize later mitigates some problematic incentives that paying them out immediately would create.

**Comment by jcnelson** [comment]
* Doesn't fundamentally change anything; just raises the stakes
* Discourages forks (up to a point)
* Variable reward for fees?  Higher fees are redeemed later?
* Need more data / models to understand how/why this helps.

**Comment by diwakergupta** [comment]
Notes from meeting on 8/17: don't have empirical evidence to suggest this is critical to address now. We can revisit this later if there's more data to support this might be useful. Closing for now.
