### ISSUE TITLE
Staging Block Database should evict PoX-invalidated blocks

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1804]
We don't want the staging block DB to accept Stacks blocks which aren't in our PoX fork (this is already enforced by the invalidation in the ChainsCoordinator of PoX-invalidated sortitions.)
 
However, we should also at some point be proactive about evicting previously accepted blocks when a PoX fork becomes invalid.

**Comment by diwakergupta** [comment]
Notes from discussion on 8/17: this is an optimization for our networking path for PoX. Not strictly a mainnet blocker, not consensus-critical. But a strong nice-to-have nonetheless.

**Comment by diwakergupta** [comment]
@kantai @jcnelson we probably still need this?

**Comment by kantai** [comment]
Yep -- this would still be a good optimization.
