### ISSUE TITLE
Clarity: expose underlying burnchain block header hashes

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1806]
The Clarity VM needs to expose burnchain header hashes at given burnchain block heights.  Then, it can verify transactions that have happened on the burnchain.  The caller can supply the burnchain header, Merkle proof, and raw transaction.

This could be part of `(get-block-info ..)`.  For example, `(get-block-info burn-header-hash <burnchain-block-height>)` would evaluate to `(optional (buff 32))`

**Comment by diwakergupta** [comment]
@jcnelson was this implemented? If yes, can you link the relevant PR? If not, would you consider this a Krypton blocker?

**Comment by jcnelson** [comment]
It is _not_ implemented, and it is _not_ a Krypton blocker.

**Comment by jcnelson** [comment]
This was implemented a while ago. Closing...
