### ISSUE TITLE
[TESTNET BUG] Mocknet does not support set-entry with simplified tuples

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1813]
## Describe the bug

Executing a smart contract containing something like
```
(map-set monsters {monster-id: monster-id}
          {
            name: name,
            last-meal: burn-block-height
          })
```
fails with an error `NotImplemented`:

Runtime error NotImplemented on contract-call ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M.monsters.ClarityName("create-monster") [Buffer(426c61636b205469676572)], stack trace Some([FunctionIdentifier { identifier: "ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M.monsters:create-monster" }, FunctionIdentifier { identifier: "_native_:special_let" }, FunctionIdentifier { identifier: "_native_:special_if" }, FunctionIdentifier { identifier: "_native_:native_begin" }, FunctionIdentifier { identifier: "_native_:special_set-entry" }, FunctionIdentifier { identifier: "_native_:special_tuple" }])

## Steps To Reproduce

1. start mocknet
1. clone git repo: https://github.com/friedger/clarity-marketplace
1. run `npx ts-node scripts/market.ts`
1. see error when calling `create-monster`

## Expected behavior
setting map entry with simplified tuples should set the map entry.

## Environment

- mocknet
-     Running `target/debug/stacks-node version`
stacks-node 0.1.0 => 23.0.0.0 (master:2fb1dcfce, debug build, linux [x86_64])
 
## Additional context

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [x] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

@timstackblock

**Comment by psq** [comment]
the actual error comes from `burn-block-height` (https://github.com/blockstack/stacks-blockchain/blob/master/src/vm/variables.rs#L33-L35)

**Comment by psq** [comment]
use `block-height` instead.

**Comment by friedger** [comment]
Thanks for looking into it!
