### ISSUE TITLE
[Feature Request] Larger int sizes in Clarity

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#1814]
**Is your feature request related to a problem? Please describe.**
Many Solidity smart contracts make explicit use of larger int sizes than are supported in Clarity. My understanding is that Clarity only supports 128 bit ints. Solidity's uint is 256, and has support for uint512.

**Describe the solution you'd like**
Support for int256, int512, uint256, and uint512

**Describe alternatives you've considered**
I'm not sure exactly how plausible it is to implement certain Solidity contracts (i.e. [ZKSnark Verifiers](https://github.com/iden3/snarkjs/blob/master/templates/verifier_groth16.sol)) without support for larger numbers.

**Additional context**
I would assume that usage of these types would incur higher fees, which is obviously reasonable.

This request is certainly a bit outside of my scope - I am not sure what the difficulty and tradeoffs would be. I am only looking at this from the perspective of a Clarity contract developer aiming to emulate certain Solidity contracts.\

I am also not sure if there are workarounds to support larger numbers, that wouldn't require a new data type.

**Comment by diwakergupta** [comment]
@hstove please upvote https://github.com/clarity-lang/reference/issues/8 :)

**Comment by hstove** [comment]
Thanks! Closing this in favor of clarity-lang/reference#8. The clarity-lang issue is a better place - I knew that repo existed, but hadn't thought to open the issue there.
