### ISSUE TITLE
@jcnelson as a temporary fix, we could set the amount used in the key registration to 11_000 (I think that's the amount used for commits, or whatever that amount is) and change `list_unspent` to return the smallest UTXO greater or equal than `minimum_sum_amount` instead of the first one that is larger, this would avoid leaving all these UTXOs with an unusable amount as the code is not going to use multiple UTXOs in one tx.

### ISSUE THREAD

**Issue by hellomalaysia** [blockstack/stacks-blockchain#1816]
@jcnelson as a temporary fix, we could set the amount used in the key registration to 11_000 (I think that's the amount used for commits, or whatever that amount is) and change `list_unspent` to return the smallest UTXO greater or equal than `minimum_sum_amount` instead of the first one that is larger, this would avoid leaving all these UTXOs with an unusable amount as the code is not going to use multiple UTXOs in one tx.

Happy to create a PR for this if you think this could work.

in the case of #1783, it was not timing out, just taking enough time to skip a block.  If there's 0.1 BTC left, these would mean @paradigma-cl mined over 1_800 blocks and no UTXO is greater than 5_500.

_Originally posted by @psq in https://github.com/blockstack/stacks-blockchain/issues/1797#issuecomment-673188355_

**Comment by diwakergupta** [comment]
Spam.
