### ISSUE TITLE
Artifacts/binaries are no longer getting created

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain#1824]
**Describe the bug**
Artifacts are no longer getting created after Deploy 390.  PR #1809 is the last deploy that has binaries built.

**Steps To Reproduce**
1. https://github.com/blockstack/stacks-blockchain/actions?query=workflow%3ADeploy
2. Select any of the recent deployment actions

**Expected behavior**
Expected zip files are not displayed.

**Environment (please complete the following information):**
- Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
Unable to download/verify binaries for updated builds
![Screenshot from 2020-08-22 15-03-29](https://user-images.githubusercontent.com/7738/90966578-b44f4300-e488-11ea-8472-2f185baa3878.png)
![Screenshot from 2020-08-22 15-04-26](https://user-images.githubusercontent.com/7738/90966589-cf21b780-e488-11ea-935e-929a1894644f.png)

**Comment by kantai** [comment]
These binaries are only deployed on pushes to `master` -- you can see build artifacts for builds on that branch, e.g., https://github.com/blockstack/stacks-blockchain/actions/runs/221380472

**Comment by jcnelson** [comment]
@CharlieC3 is currently working on automatically building artifacts and making them public.  #1780

**Comment by dantrevino** [comment]
Thanks @kantai I hadnt noticed this before.
