### ISSUE TITLE
Implement smoothing function for miner burn commitments

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain#1831]
Note: this isn't a new change or decision. This was something we had discussed a while back, I'm just opening an issue so we can actually iron out the details and track the implementation.

We want to discourage miners from trying to "game" their burn commitments for each block, and conversely, to encourage miners to take a longer-term view of the chain. One proposal was that rather than considering miner burn commitments per block for the sortitions, we apply a smoothing function over a window of blocks instead.

We still have a couple of open questions:
- exactly what smoothing function to choose? Jesse S had done some analysis that showed both mean and median are sub-optimal. Couple other options that looked promising: mean excluding max, mean of square roots squared, mean of median and min
- length of the window: tentatively 5 blocks?

**Comment by diwakergupta** [comment]
Related #1315 -- I wasn't aware of that issue! cc/ @jcnelson

**Comment by jcnelson** [comment]
I think #1315 offers a more specific solution to this problem.
