### ISSUE TITLE
Stacking limit changes – tiers or longer time intervals

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/stacks-blockchain#1837]
Using liquid supply as the denominator of the Stacking limit, and the scaling based on participation, is problematic because it changes constantly. Potential Stackers want a simple, fixed answer to the question “How many STX do I need to participate?” 

Suggested solutions: 

Not suggesting we change the nature of these limits, but more the presentation to would be Stackers. 

We could create tiers, or round up/down to fixed numbers depending on supply and participation. 

Or create a scheme where the limit adjusts at known intervals, for example once every 5000 blocks. 

Open to ideas but the intention is that we can present would be Stackers with explicit amounts that can be described in marketing, in product, etc. that doesn't require API calls and doesn't change every few days.

**Comment by jcnelson** [comment]
We can have two of the three things:

* a fixed reward cycle length
* a fixed number of STX to lock per reward cycle
* a 100% guarantee that you will get some BTC in a reward cycle

But you cannot have all three.

**Comment by kantai** [comment]
Right, for the reasons @jcnelson describes, the Stacking limit must be dynamic.

However, we _can_ use tiers to simplify the process a bit more -- and this was discussed in a few different places, but I think it didn't make it into the SIP.

I think what we should do is round the stacking limit to the nearest 10K STX, which simplifies the decision about how much STX to lock up (this was, if I am recalling correctly, also the conclusion we'd reached in prior discussions about this).
