### ISSUE TITLE
Stacking reward window: Change to 5000 blocks

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/stacks-blockchain#1838]
The longer reward window is better for Bitcoin fees. But there is another reason: 

We currently support a lock time range. If the minimum becomes 5000 blocks, then there is negligible value in having any range at all. It becomes nuisance to explain, and to ask Stackers to decide each reward cycle, without delivering much value in return. If we adopt 5000 blocks we can also kill the concept of time range. 

I realize a client could simply force users to lock for 5000 blocks and that would partially address this concern. However, I'm more focused on explaining the protocol to thousands of end users and integrators over the next couple years. Protocols gain adoption in part because they are easy to understand. We should edit out the parts that add complexity without adding value.

**Comment by jcnelson** [comment]
We do not support a lock time range.  Currently, the lock time is fixed in perpetuity at 1000 blocks.  There is no "minimum" -- it's always 1000 blocks, no matter how many liquid STX there are or how many STX are Stacked.

**Comment by jeffdomke** [comment]
Sorry imprecise language. I'm not saying we support arbitrary lock times. 

I was referencing the number of reward cycles. I'm assuming we still support this to some upper limit?

**Comment by jeffdomke** [comment]
Closing in favor of #1847 which we would need to answer first
