### ISSUE TITLE
Update DNS to use .org records

### ISSUE THREAD

**Issue by wileyj** [blockstack/stacks-blockchain#1839]
https://github.com/blockstack/stacks-blockchain/blob/97d4e7e2286c773e01cae7bc15762cee97009600/testnet/stacks-node/conf/krypton-follower-conf.toml#L4

In an effort to consolidate and clean up DNS as we move through testnet phases, please adjust to use `krypton.blockstack.org`, rather than the `.xyz` domains. 

additionally, this line:
https://github.com/blockstack/stacks-blockchain/blob/97d4e7e2286c773e01cae7bc15762cee97009600/testnet/stacks-node/conf/krypton-follower-conf.toml#L9

should be modified to `krypton-bitcoind.blockstack.org` 

These will likely change 1 more time as we're able to configure the CNAME records to point to the current testnet phase; will create a new issue for that when it's ready.

**Comment by diwakergupta** [comment]
@wileyj this can be closed now, right?

**Comment by wileyj** [comment]
Yes, it's fine in the current file in `master`. 
There are other updates we can make so that the DNS used is more clear and doesn't require updates to the repo, but that's something for another issue.
