### ISSUE TITLE
`(at-block)` behavior broken when mutations are pending

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1840]
The implementation of Clarity VM's rollback wrapper (to support rollbacks of failed function calls) interacts with `(at-block)` in a buggy way: if a mutation is pending in the wrapper, then a data-storage lookup returns the result of a key-value lookup based on that pending mutation. However, code in an `at-block` closure _should not_ consult that rollback wrapper, but instead directly query the datastore at the given block height.

The branch `fix/at-block` includes a [test for witnessing this behavior](https://github.com/blockstack/stacks-blockchain/blob/fix/at-block/src/vm/tests/forking.rs#L28):

```rust
#[test]
fn test_at_block_mutations() {
    // test how at-block works when a mutation has occurred
    fn initialize(owned_env: &mut OwnedEnvironment) {
        let c = QualifiedContractIdentifier::local("contract").unwrap();
        let contract =
            "(define-data-var datum int 1)
             (define-public (working)
               (ok (at-block 0x0101010101010101010101010101010101010101010101010101010101010101 (var-get datum))))
             (define-public (broken)
               (begin
                 (var-set datum 10)
                 ;; this should return 1, not 10!
                 (ok (at-block 0x0101010101010101010101010101010101010101010101010101010101010101 (var-get datum)))))";

        eprintln!("Initializing contract...");
        owned_env.initialize_contract(c.clone(), &contract).unwrap();
    }
...
```

**Comment by jcnelson** [comment]
We'll need to open this against `next`.

**Comment by jcnelson** [comment]
@kantai Do you want to try and get this merged for the next testnet reboot?

**Comment by kantai** [comment]
Closed via 2027
