### ISSUE TITLE
PoX: synchronize PoX bitvectors before block bitvectors

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1842]
Inventory sync is now a two-stage process:

* Sync all PoX inventories with neighbors
* Sync each neighbor's reward cycle block inventories

In particular:

* A remote node's block inventory will be fetched on a reward-cycle basis.
* A remote node's block inventory will only be fetched for reward cycle _C+1_ if the local node and remote node agree on PoX bit _C_.  Otherwise, inventory synchronization will block (and possibly result in the remote node being removed from the neighbor set).   This implies a tighter integration between the inventory synchronization state-machine, the block-download state machine, and the chain coordinator -- the inventory synchronization state-machine needs to check and see if its own PoX bit for reward cycle _C_ flipped from 0 to 1 as a result of fetching and processing all blocks and microblocks advertised in the reward cycle.

**Comment by diwakergupta** [comment]
@jcnelson is this done?

**Comment by jcnelson** [comment]
Yes
