### ISSUE TITLE
More efficient descendant_of_pox_anchor check in sortition evaluation

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1843]
Per the design of Stacking in SIP-007, a block commit should transfer committed Bitcoin to recipient addresses if and only if the following is all true:

    The current reward cycle selected an anchor block A.
    The node processing a sortition has processed Stacks block A.
    The block commit's parent is either block A or a descendant of A.

Checking conditions 1 and 2 is pretty straightforward, given all the supporting changes for PoX. Checking condition 3, however, requires determining if block A is an ancestor of the block commit's parent_block_ptr. Naively, we could check this by traversing parent pointers until either block A is reached or passed. However, that could be a very expensive check. Alternatively, we could use a MARF to support this check. Unfortunately, neither the SortitionDB, nor the StacksChainState MARFs are currently set up in a way that could support this: we'd want every sortition winner to have a corresponding trie in the MARF (not the case in the StacksChainState: only processed blocks have tries) and we'd want the parent trie for each sortition winner to be it's parent_block_ptr sortition (not the case in the SortitionDB: every trie's parent is the sortition that preceded it).

This is currently implemented in #1827 by just iterating over the block parent pointers, but there's more efficient ways to do this, e.g., @psq suggested storing an anchor block reference in each sortition's entry in the DB, or by managing a cache.

**Comment by jcnelson** [comment]
> e.g., @psq suggested storing an anchor block reference in each sortition's entry in the DB,

This sounds promising, especially because it removes the need to maintain a coherent cache.  It should be a _O(1)_ check to determine which reward cycle any given block-commit is in.
