### ISSUE TITLE
Clarity:  Proposal for loop-like functions?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1844]
This came up in the blockchain meeting.

Currently, it's not straightforward to implement the semantics of a for-loop -- you'd have to (ab)use `map` and `fold` to iterate over a list in hard-to-read ways.  Specifically, you have to implement the loop body as a separate top-level function (because Clarity doesn't support anonymous functions), and the top-level function has to take all of its arguments as a `tuple` (because `map` and `fold` require a function that takes a single argument).

It may be worthwhile to add a `for`-like built-in function that simply binds a variable name to a list item and evaluates a given statement.  But, I think if we do this, it should be done in a way analogous to `map` and `fold`.  For example, we could have:

* `(map-each <name> (list <type>) (statement))`, which iterates through `(list <type>)` and binds `<name>` to the next value in it and evaluates `(statement)` with it.  The whole statement evaluates to `(list <statement-type>)`, where `<statement-type>` is the type that `(statement)` evaluates to.
* `(fold-for (<iter-name> <initial-value>) (<count-name> <uint-value>) (statement))`, which initially binds `<iter-name>` to `<initial-value>` whose type is `<type>`, and binds `<count-name>` to the given `<uint-value>`, and evaluates the given `(statement)` a given number of `<uint-value>` times.  The `(statement)` body must evaluate to the same type as `<initial-value>`, and the entire `(fold-for)` statement evaluates to the same type as the `<initial-value>`.

Examples:

* `map-even`:
```
;; Map a list of 5 numbers to a list of 5 booleans, indicating whether or not the
;; ith number was even.
(define-public (is-even (numbers (list uint 5)))
   (map-each n numbers (is-eq (mod n u2) u0))
```

* `fold-for`:
```
(define-public (pow (base uint) (exp uint))
   (fold-for (x u1) exp (* x base)))
```

Thoughts? Feedback?

**Comment by njordhov** [comment]
Special forms for iteration makes good sense, distinguishing between _list comprehension_ and _looping over a sequence_ for side effects. 

There are unsurprisingly plenty of prior art in other Lisp dialects. Clojure has a [for](https://clojuredocs.org/clojure.core/for) construct providing list comprehension and [doseq](https://clojuredocs.org/clojure.core/doseq) to loop for side effects. Racket has a family of [for](https://docs.racket-lang.org/guide/for.html) syntactic forms to support iteration over sequences. Common Lisp has many syntactic forms for looping, mostly for side effects like [dolist](http://clhs.lisp.se/Body/m_dolist.htm) to loop over a list. They also have loop constructs too powerful/flexible for the restrictions of Clarity.

For binding a variables to sequence items, using a similar syntax as in `let` bindings makes Clarity more consistent:

```clojure
(define-public (is-even (numbers (list uint 5)))
  ;; list comprehension mapping a sequence of numbers to booleans
  (for ((n numbers))
    (is-eq (mod n u2) u0)))
```

**Comment by psq** [comment]
@njordhov I like the proposed syntax, and yet I think some may find the use of 2 levels of parenthesis surprising as not really necessary, but more consistent with `let`.

However, the proposed `fold-for` is more versatile as you you have the accumulator as a shared state between the iterations.  If anything, I'd like to see a more generalized shared state (with more than one variable possibly), rather than force people to use side effects for more complex use cases.

**Comment by jcnelson** [comment]
> @njordhov I like the proposed syntax, and yet I think some may find the use of 2 levels of parenthesis surprising as not really necessary, but more consistent with let.

I think @njordhov might be onto something here.  If we treat the first argument in `map-each` as a `let`-binding, we make it possible for there to be many such bindings within the `(statement)`.  This makes it possible to implement the semantics of a for-loop with multiple iterator variables.

> If anything, I'd like to see a more generalized shared state (with more than one variable possibly), rather than force people to use side effects for more complex use cases. @psq 

I agree.  The `fold-for` example I gave isn't illustrative of this, but the only way to get multiple variables as shared state in `fold-for` would be to use a `tuple`, and construct a new `tuple` at the end of `(statement)` with the next iteration's values.  I don't think this is very ergonomic, but I can't think of a better way without introducing something like a closure type.

**Comment by psq** [comment]
I can see the `let` binding as being quite useful if they are re-evaluated before each iteration, and let you compute values based on the counter and the result of the previous iteration.

> would be to use a tuple ... I don't think this is very ergonomic,

that was my thinking a well, and I can't disagree on the ergonomics, but the more I think about it, the closer I get to to thinking this would do jn practice.

**Comment by njordhov** [comment]
> I think some may find the use of 2 levels of parenthesis surprising as not really necessary, but more consistent with let.

Consistency with `let` bindings is at the essence. It also distinguishes binding syntax from expressions, while `(n numbers)` can be confused with a function call.

Using brackets for bindings is an elegant alternative to nested parens:

```clojure
(for [n numbers]
  (is-eq (mod n 2) 0)))
```

**Comment by njordhov** [comment]
A concern for such syntactic constructs is that Clarity allows abnormal returns from functions, promoting the use of functions like `unwrap!`, which exits the current function if given an `err` response. Combining abnormal exits with the proposed loop-like functions would make for a hairy mess.

**Comment by jcnelson** [comment]
Now that Stacks 2.0 has launched with `element-at`, it looks like we didn't need this after all.  Going to go ahead and close this.

**Comment by njordhov** [comment]
> it looks like we didn't need this after all

Such iterator constructs would be beneficial, but they can just as well be covered by a transpiler like https://clarity.tools
