### ISSUE TITLE
PoX: Delegation Semantics in SIP-007

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1845]
There are a few ambiguities around delegation that I think need some elaboration:

* **Delegate registration.**  SIP-007 does not describe how a delegate comes into existence.  I think they need to be created eagerly -- i.e. before any Stackers list them as delegates.  Moreover, I think all of the parameters of how the delegate will behave need to be registered on-chain in advance, so the Stackers know what they're getting into.  An alternative is to create delegates lazily, whereby a delegate is created implicitly when the first client Stacks their STX with it.  I think this is risky because it makes the protocol vulnerable to accidentally copy/pasting/typing the wrong information when trying to Stack with someone else.

* **Delegate Agency**.  SIP-007 does not describe how a delegate decides who its clients are (only that they cannot be smart contracts, which I also think should be reconsidered).  Right now, it seems anyone can register their STX with any delegate.  But, can the delegate deny the client's registration?  I think this should be possible, because I think that there will be paid-for delegation services that need to deny clients until the clients pay up front for the service.

* **Stacking Control**.  SIP-007 does not describe when a delegate's clients' STX start Stacking, or how this begins.  They cannot start stacking immediately if delegates have to acknowledge a client's request for Stacking, for example.  Do they begin Stacking on the next reward cycle, or does the delegate (as part of its registration) need to set an explicit block height for the client(s)?

* **Stackers/Delegates as Smart Contracts**.  I know I personally was in favor of the provision in SIP-007 that Stackers and delegates must not be smart contracts, but upon reconsideration, I think this would actually _simplify_ the implementation of SIP- 007 because it would let the delegate implementations address most of the above concerns.

**Comment by psq** [comment]
> But, can the delegate deny the client's registration? I think this should be possible, because I think that there will be paid-for delegation services that need to deny clients until the clients pay up front for the service.

the answer to that question must be probably be yes, although most delegates will probably charge a fee (or not) from the reward rather than ask for an upfront payment.
It also poses some interesting logistical challenges on how the delegate learns about who delegated to them, where to send the rewards, etc...  Having contracts for handling this would certainly simplify a lot of these questions, in support of your 4th point.

**Comment by kantai** [comment]
More broadly, given the initial implementation in #1790, I think there's disagreement about what service a delegate is providing _at all_. As proposed in SIP-007, the purpose of a delegate is primarily to limit the usage of a high-risk signing key for Stacking (i.e., how often should a Stacks holder need to sign something with a key that holds 10's of thousands of STX?), however, that _is not_ what the initial implementation in #1790 is concerned with. Instead that seems to be enabling _pooling_ of Stackers. These are different concerns, and probably require different solutions. We need figure out which of those problems we're trying to solve using "first-order" operations in the PoX contract.

**Comment by jcnelson** [comment]
> As proposed in SIP-007, the purpose of a delegate is primarily to limit the usage of a high-risk signing key for Stacking (i.e., how often should a Stacks holder need to sign something with a key that holds 10's of thousands of STX?)

I don't think a SIP-described delegation protocol is the solution to this problem.  I think that if we stripped all mentions of delegation from SIP-007, and just allowed Stackers to be smart contracts, then this problem and its solution space are no longer blockchain-level concerns.  Delegation would be a service that gets added through smart contracts, and thus would be outside the purview of the SIP process.  Moreover, we could defer implementing this "pure" delegation until after mainnet if we had to.

> however, that is not what the initial implementation in #1790 is concerned with. Instead that seems to be enabling pooling of Stackers.

I and many others in the community had been under the impression that "delegation" in SIP-007 was meant to provide a way for smaller Stackers to participate in PoX, so I went ahead and implemented pooling logic as part of #1790.  Regardless of whether we consider delegation and pooling to be logically distinct concerns, I do believe that the ability to pool STX for Stacking is a release-critical feature for PoX.  It would be more difficult to add pooling post-mainnet than adding pure delegation -- you could do it, but it would have to be as a soft-fork (and big, active STX holders like exchanges would be financially incentivized to block any such soft-fork since it would raise their Stacking thresholds).

**Comment by kantai** [comment]
Both pooling and delegation _could_ be implemented via external smart contract if we allow smart contracts to Stack (which, I think, we probably should). In both cases, though, the advantage of building in support to the PoX contract is to avoid requiring that users transfer large amounts of Stacks to smart contracts.

**Comment by jcnelson** [comment]
> Both pooling and delegation could be implemented via external smart contract if we allow smart contracts to Stack

Yes, but lazy token unlocking can't happen within a smart contract.  The token-balance logic for e.g. paying transaction fees needs to be able to determine that the tokens are no longer locked, so they can be spent.

**Comment by muneeb-ali** [comment]
> building in support to the PoX contract is to avoid requiring that users transfer large amounts of Stacks to smart contracts.

I think we extensively debated this earlier this year where we felt uncomfortable with the scenario where  users need to transfer large amounts of Stacks to smart contracts and in fact decided that this feature might be so important that it is worth delaying the testnet launch for it.

Are we re-considering this now?

> We need figure out which of those problems we're trying to solve using "first-order" operations in the PoX contract.

In my mind delegation signing is a first-order operation. I think pooling (as described by Jude) or some other variation can always be implemented as a Clarity contract. In other words, having first-order support for simple delegation (from original discussions) does not stop anyone from having smart contracts that perform delegation or pooling in a different way. Such services/contracts can also appear post mainnet launch.

**Comment by jcnelson** [comment]
> I think pooling (as described by Jude) or some other variation can always be implemented as a Clarity contract.

Pooling _with automatic unlock_ cannot be implemented solely in a smart contract.  The node needs to be aware of the tokens entering the pool, so it can treat them as spendable once the lock-up expires.

**Comment by jcnelson** [comment]
> I think we extensively debated this earlier this year where we felt uncomfortable with the scenario where users need to transfer large amounts of Stacks to smart contracts and in fact decided that this feature might be so important that it is worth delaying the testnet launch for it.

I think pooling at least needs to be controlled by a "blessed" smart contract, much like how locking up STX for PoX is today.  This is because the node itself needs to do some additional bookkeeping on the locked STX so that they'll automatically be unlocked later.  To be clear, in my conceptualization of PR #1790, **no one sends their STX anywhere when pooling**.  The act of pooling simply locks your tokens, and ties them to an _existing_ reward address.  The pool operator must later commence Stacking on behalf of the pool (which prevents subsequent people from joining it), but the pool operator does not have access to the locked STX.

We can create a "blessed" delegation protocol whereby the user locks their tokens with their token-owning key, and authorizes a delegate key to Stack them.  But, this is just a special case of pooling -- here, you're creating a pool with one participant, and the delegate operator is the pool operator.

Because of this design, I don't think there's a risk with allowing a smart contract to lock your STX for you (or to activate the pool's Stacking).  Because the tokens never move, you can guard contract-calls with a post-condition on your STX to make sure the Stacking contract didn't lose or steal your tokens.  Moreover, we can expand post-conditions on STX to cover STX lock-ups _in addition_ to transfers, if users want to be extra cautious.

**Comment by jcnelson** [comment]
I think we have clarity on this now, with Aaron's latest PR.  However, this information should find its way into SIP-007.
