### ISSUE TITLE
Open RPC port while downloading BTC block headers

### ISSUE THREAD

**Issue by wileyj** [blockstack/stacks-blockchain#1849]
**Is your feature request related to a problem? Please describe.**
For xenon, we're using the BTC testnet and starting the node is taking much longer than regtest due to downloading the block headers. 

**Describe the solution you'd like**
Open the RPC port before starting the download, so we can make a request and see something like "downloading headers" or something informative so we know it's processing. This would also allow us to bring up helper services (follower, api) while the miner is coming up, rather than waiting. 

**Describe alternatives you've considered**
N/A

**Additional context**
Having a log output of the progress similar to bitcoin would also be helpful here as well

**Comment by jcnelson** [comment]
We can make it so `/v2/info` just returns an error message saying that it's still synchronizing.

**Comment by wileyj** [comment]
That should be fine, the request is really just to open the port more quickly since other services depend on that port being open (even if it's not fully ready).

**Comment by diwakergupta** [comment]
@wileyj have you tried this recently? When testing locally, I've observed that now v2/info is responsive before the node is fully caught up.

@lgalabru @jcnelson any known changes here? Wondering if we can close this out.

**Comment by psq** [comment]
indeed it is, the node opens its port almost right away, and /v2/info shows the progress as far btc blocks processed to a valid chain

**Comment by diwakergupta** [comment]
OK, going to close it out!
