### ISSUE TITLE
[Stacks v1 → v2 Upgrade] Watch `.miner` namespace

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1851]
Measuring miner interest by counting registrations on `.miner` namespace.

```
[threshold crossed]  ~500 blocks  [import block]  ~500 blocks  [v2_genesis]
|                 | ------------ |              | ----------- |            |
```

Once this has crossed some threshold, the upgrade will occur at a bitcoin block ~1000 blocks after the threshold is crossed — the "imported" state will be from a bitcoin block ~500 blocks after threshold is crossed.

Emit a parseable log entry when the threshold of registrations is reached, and then perform a chain state "dump" when the import block is reached. The dumped chain state and v1 consensus hash will be loaded into Stacks v2 (tbd in a follow up issue).

/ht @kantai for the design

**Comment by jcnelson** [comment]
If you look in `blockstack/lib/virtualchain_hooks.py`, there's a "end-of-block" that gets called when a BTC block is processed that you can extend to keep a running count of the number of `.miner` names.
