### ISSUE TITLE
[TESTNET BUG] - ReadOnlyChecker should check arguments of StxTransfer and other calls.

### ISSUE THREAD

**Issue by vluchangco** [blockstack/stacks-blockchain#1852]
**Describe the bug**

The `check_native_function` method of `ReadOnlyChecker` simply returns `Ok(false)` for functions such as `StxTransfer`, `StxBurn`, etc.  It should recursively check that the arguments to these functions also satisfy the read-only requirements.  In particular, an argument might include an `at-block` expression with a closure that is not read-only.

**Comment by kantai** [comment]
Thanks for filing this issue @vluchangco -- I think a witnessing smart contract for this would be something like:

```scheme
(define-data-var cursor int 0)
(define-public (bad-at-block-function)
  (var-set cursor
    (at-block 0x0101010101010101010101010101010101010101010101010101010101010101
      ;; should be a read only error, caught in analysis, but it isn't                     
      (begin (var-set cursor 1) 2))))
```

**Comment by lgalabru** [comment]
Feature completed, closing now.
