### ISSUE TITLE
[TESTNET BUG] Transaction stuck in pending status

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1853]
## Describe the bug

Transaction 05f57f1f3ba2cf9328a8257726eaf0c69c89ba0b14a38edb39e345b3f0099f7e is still in pending status, even though other transactions from the same sender have been processed successfully.

## Steps To Reproduce

Not sure how to reproduce it, I created several transactions through speed-spend

## Expected behavior

transaction fails or succeeds

## Environment

 - OS: [e.g. Ubuntu / Debian]
 - Rust version
 - Output of `stacks-node version`

## Additional context

https://speed-spend.netlify.app

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [x] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

@timstackblock

**Comment by diwakergupta** [comment]
@friedger how did you submit the transaction? I don't see that txid anywhere in our logs.

**Comment by jcnelson** [comment]
Per our conversation on discord, the follower node in our infrastructure saw the transaction, but for some reason, it was not propagated to the master node.  This may be due to the way the code forwards unsolicited messages; I can take a closer look at that.

**Comment by diwakergupta** [comment]
This is too far back in time to meaningfully debug, and there have been a lot of changes for PoX in the interim. I'm going to close this out, @friedger please reopen if this happens again on Krypton.

**Comment by longtkhd** [comment]
@friedger  my transaction still stuck on pending in here https://explorer.stacks.co/txid/0x4314360cd90d43a0be748b627efec7189cd70ca40ed74aa1de6366040cbb09c7?chain=mainnet
