### ISSUE TITLE
SIP for Bitcoin operation wire formats

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1856]
We currently do not have a SIP describing the wire formats used by the Bitcoin burnchain implementation. This SIP would need to describe the wire formats for:

1. Leader block commits
2. Leader key registers
3. User burn supports

This would also describe the eventual bitcoin formats for PoX operations like lockups and "nay" anchor votes.

**Comment by jcnelson** [comment]
I think the leader key registers, user burn supports, and PoB block commits should be described in SIP-001, and the PoX block commits, on-chain PoX lockups, and on-chain PoX delegations should be described in SIP-007.

**Comment by kantai** [comment]
That's ultimately fine with me. The reason I am advocating for a new SIP is that this description will necessarily be burnchain-dependent: these wire formats are specific to Bitcoin-as-the-Burnchain, whereas the other SIPs (SIP-001 in particular), try to describe things in a burnchain-agnostic way.

**Comment by jcnelson** [comment]
Ah, that makes sense.

I think in general that SIPs should have a section that describes implementation-specific concerns.  If we did this, then we'd have a section in SIP-001 and SIP-007 that described how you would do this in Bitcoin, as well as how you would do this in another burnchain if it came to it (I think we will ultimately describe how to do this on Stacks as well).
