### ISSUE TITLE
PoX: re-conceptualization of Stacking as a multi-item open auction?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1857]
Issue #1846 points out that there are some incentive problems that arise when making the minimum Stacking threshold a dynamically-adjusting value.  But, I think these incentive problems could go away if we re-formulate PoX as an _open auction_ for reward addresses, whereby Stackers use the duration of the reward cycle to bid on address slots.

Specifically, in every reward cycle, we carry out a uniform-value auction for a ~5,000~ 4,000 reward addresses to Stackers.  This is an _open_ auction, since everyone knows each other's bids.  Fortunately, there exists an efficient ascending-bid multi-item open bidding protocol [1] whereby the dominant bidding strategy is to bid the sincerely-held value.  Importantly, **this auction protocol would preserve the dynamic-adjusting minimum Stacks amount while also encouraging honest Stacking.**

The gist of it is that at each bidding round, each reward address has a linearly-increasing lock-up price _p_.  Bidders receive addresses over the course of the reward cycle auction if we can show that their bids are the _sole source of demand_ for those addresses at a given price point _p_.

In our case, each round would be a single Bitcoin block, and _p_ would increase from 1/20,000th of the total liquid STX at the beginning of the reward cycle, to 100% of the total supply at the end.  At any time during the current reward cycle or _any prior reward cycle_, Stackers submit a bid that contains their _per-address lock-up price_ and the _quantity_ of reward addresses they wish to buy.  Upon processing the bid, the Stacks node locks up these offered tokens.  Stackers can increase their bids at any time (locking more tokens on the spot), or drop out at any time (unlocking any tokens not already committed for an earned reward address).  If a Stacker gets out-bid, then all of their un-spent tokens unlock.  Stackers may enter the auction as early as the beginning of the prior auction in order to ensure that their bids are recorded even if a large minority of miners try and censor the bids to suppress prices.

The auction proceeds as follows.  At the end of each round, the Stacks node goes through the list of current bidders whose per-address bids are at least _p_, and awards bidders any addresses that they have "clinched."  That is, the node determines that a given bidder _i_ has "clinched" at least one address in this round if the total number of offered STX for all addresses _without_ bidder _i_'s bid is _less than_ the current total worth of the unclaimed addresses.  If so, then it means bidder _i_ fulfills demand for at least one address at price _p_.  The node would then assign bidder _i_ those otherwise-unclaimed addresses at price _p_, because bidder _i_ was the sole source of demand for those address(es) when valued at _p_.

Each bidder clinches _n = floor((total_demand - bidder_i_demand) / p)_ addresses.  If bidder _i_ clinched _n > 0_ reward addresses, then the node would then lock up _n * p_ STX tokens from bidder _i_ and reduce her outstanding bid by _n_ addresses.  The total supply of addresses is also decreased by _n_; bidder _i_ now controls _n_ address slots.  The auction proceeds in this way until all reward addresses are claimed, or until the reward cycle runs out (any unclaimed addresses are replaced with the burn address for PoX).

For example, suppose Alice, Bob, and Charlie are each bidding on 2 reward addresses.  Suppose Alice bids for 2 addresses, and Bob and Charlie each bid for 1 addresses.  So, there's a supply of 2 addresses and a demand for 4 addresses.  Alice, Bob, and Charlie submit their bid transactions before the start of the auction's reward cycle.

Suppose the reward cycle is 10 blocks long, and the reserve price of the reward address is 100 STX.  Suppose that there are 1100 liquid STX in total, so _p_ starts at 100 STX and increases by 100 STX each block.  Alice bids for 2 addresses at a cost of 300 STX each.  Bob bids for 1 address at a cost of 200 STX.  Charlie bids for 1 address at a cost of 100 STX.

At block height 0, _p_ is 100.
* Supply = 100 * 2 = 200
* Demand without Alice = (1 * 200 + 1 * 100) = 300
* Demand without Bob = (2 * 300 + 1 * 200) = 800
* Demand without Charlie = (2 * 300 + 1 * 100) = 700

No addresses are clinched -- no one guarantees demand for a reward address.

At block height 1, _p_ is 200.  Charlie is now out of the auction, because he cannot afford any reward addresses.
* Supply = 200 * 2 = 400
* Demand without Alice = (1 * 200) = 200
* Demand without Bob = (2 * 300) = 600

The demand without Alice is less than the supply by 200, so Alice clinches floor(200 / _p_) = 1.  Alice receives one reward address, and locks up 200 tokens.

At block height 2, _p_ is 300.  Bob is now out of the auction, because he cannot afford any addresses.
* Supply = 300 * 1 = 300
* Demand without Alice = 0

The demand without Alice is less than the supply by 300, and floor(300 / _p_) = 1.  Alice clinches one address, and locks up 300 tokens.

Now that all addresses have been sold, Alice gets 2 addresses, and Bob and Charlie get none.  Alice has locked up 500 tokens in total, and Bob and Charlie have not locked up any tokens.

The paper I think is worth a read.  The example above is based on the introduction's example, but it has other more-detailed examples (and proofs) as well.

@kantai @lgalabru @diwakergupta @jessesoslow 

[1] http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.133.1536&rep=rep1&type=pdf

**Comment by 314159265359879** [comment]
Will the solution for this issue be added to Stacks 2.1?
Should this be tagged accordingly?

**Comment by kantai** [comment]
I think simply allowing unlocks is perhaps preferable here, it alleviates the pain of missing a slot due to the threshold changing, without introducing an auction mechanism that I'm not sure has desirable properties.

For instance, as proposed here, the auction is dynamic starting at the beginning of a reward cycle and increasing over time. The description in this issue I don't think exactly matches how the linked paper describes the efficient auction. In the efficient auction, an "auctioneer" announces a price and bidders just tell the auctioneer a quantity. To adapt that to PoX, the auctioneer would be the protocol increasing the threshold of a slot over the course of the reward cycle, and bidder quantities would be "implicit": the amount that they stack could be converted to a quantity via `amount_stacked / current_price`. Importantly, bidders do not specify both a quantity and a price. However, if there are many stackers that only participate one cycle at a time, this protocol strongly incentivizes censorship: if a miner can keep out bids for a block or two, they can capture the demand at a lower price.

**Comment by jcnelson** [comment]
Sure, it doesn't have to be an auction as described in this paper.  Per the Stacks 2.1 discussion thread [here](https://github.com/stacksgov/sips/discussions/16), I'm mainly interested in making sure the highest payoff is achieved by Stacking _honestly_ -- i.e. it shouldn't matter when you Stack, or how much, or whether or not you up your Stacking amount (and when you do it, provided it all happens before the start of the target reward cycle).

> To adapt that to PoX, the auctioneer would be the protocol increasing the threshold of a slot over the course of the reward cycle, and bidder quantities would be "implicit": the amount that they stack could be converted to a quantity via amount_stacked / current_price. Importantly, bidders do not specify both a quantity and a price.  However, if there are many stackers that only participate one cycle at a time, this protocol strongly incentivizes censorship: if a miner can keep out bids for a block or two, they can capture the demand at a lower price.

What if, instead, they announce a budget and a maximum number of reward slots?  The reason I bring up announcing a budget is that with this type of auction (also known as a "clinching auction"), the budget of the bidders _must_ be public in order for certain other desirable properties to hold [1].

I think we'd need to make one additional adjustment -- in order for honest bidding to be incentive-compatible with getting non-negative utility, we'd need to make sure that an individual bidder's demand _cannot increase_ over the auction period.  Specifically, once you are eligible for bidding in reward cycle R, your maximum budget is fixed to your current balance at the start of R.  All you'd specify is the minimum number of reward addresses you'd settle for (and you'd only be able to _increase_ this value while bidding is ongoing starts, which lowers your cost of locking in a slot but may cause you to lose bids).

[1] https://www.cs.huji.ac.il/~noam/focs-budget.pdf

**Comment by jeffdomke** [comment]
Not sure I grok all the dimensions of this. I assume there are some upsides to a more efficient market for stacking slots. So open to the idea. 

One thing I worry about is communicating the limit to users and integrators. The limits are pretty clear and predictable currently and we still have a ton of confusion. Is it right to assume that under this design that challenge would be come harder? Any way that it could that be mitigated? 

Another way to think about it is that if the number becomes truly unpredictable that might be better – everyone will just check an API vs. trying to reason about it.

**Comment by jcnelson** [comment]
> One thing I worry about is communicating the limit to users and integrators. The limits are pretty clear and predictable currently and we still have a ton of confusion.

Yes, and I think this is going to be true no matter what.  There's no existing financial derivative I'm aware of that is sufficiently similar to Stacking that we can relate it to concepts they may already be familiar with (even "APY" is misleading).

However, I'm confident that they will _eventually_ understand it even better than we do today, since it's hard to ignore the overarching "the more you hodl, the more BTC yield you get" message.  That's why I'm primarily interested in designing the mechanism to work in the presence of correct-but-dishonest actors, so it'll behave predictably no matter how well people understand it.

Also, I wouldn't say that the stacking limit is predictable today.  Twice now it's given users a nasty surprise -- it increased beyond its last minimum threshold at the last minute.  Even if you're polling an API endpoint ever minute, this won't save you -- you've gotten bumped from a reward slot just before it's too late for you to do anything about it.

I think it's worth investigating ways to make it so you'll at least know in advance how likely it is you'll clinch a reward slot, if at all possible.  Then at least it's less of a surprise.
