### ISSUE TITLE
Binary logarithm function for Clarity

### ISSUE THREAD

**Issue by reedrosenbluth** [blockstack/stacks-blockchain#1862]
Would be nice to have a binary logarithm function so that cost-assessment functions can be expressed in Clarity as @njordhov suggests here: https://github.com/blockstack/stacks-blockchain/issues/1794#issuecomment-675076057

**Comment by jcnelson** [comment]
> Would be nice to have a binary logarithm function 

"Nice" is putting it mildly ;)  Looks like it will be _necessary_.  Same goes for every elementary function that could reasonably get into a cost function.  Can we think of any others?

**Comment by njordhov** [comment]
For a Clarity implementation, feel free to borrow from the `log2`  implementation in ClarityTools, available by running the _Generate Clarity_ toolbox menu command on https://clarity.tools/code?KGxvZzIgOCk= or this [ClarityTools implementation of log2](https://clarity.tools/code?KGRlZmluZS1yZWFkLW9ubHkgKGxvZzItcmVkdWNlciAKICAgICAgICAgICAgICAgICAgIChleCAoaW50IDEgNjQpKSAKICAgICAgICAgICAgICAgICAgIChzdGF0ZSB7biAoaW50IDEpLCByZXN1bHQgKGludCAwIDEyNyl9KSkKICAobGV0ICgoe24sIHJlc3VsdH0gc3RhdGUpCiAgICAgICAgKHAgKHBvdyAyIGV4KSkpCiAgICAoaWYgKD49IG4gcCkgCiAgICAgIHtuICgvIG4gcCkKICAgICAgIHJlc3VsdCAoKyByZXN1bHQgZXgpfSAKICAgICAgc3RhdGUpKSkKCihkZWZpbmUtcmVhZC1vbmx5IChsb2cyIChudW0gKGludCAxKSkpCiAgKGxldCAoKHtyZXN1bHQsIG59IAogICAgICAgICAoZm9sZCBsb2cyLXJlZHVjZXIgKGxpc3QgNjQgMzIgMTYgOCA0IDIgMSkgIAogICAgICAgICAgIHtuIG51bSwgcmVzdWx0IDB9KSkpIAogICAgIChhc3NlcnQgKDw9IG4gMSkgIkV4cGVjdGluZyBhIHNtYWxsZXIgaW50ZWdlciIpCiAgICAgcmVzdWx0KSkgCgoobG9nMiAyMDAp).
