### ISSUE TITLE
PoX: networking: per-node PoX inventory synchronization state machines

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1869]
Right now, the block inventory synchronization logic happens within a singleton state machine.  It's states form a loop: `GetBlocksInvsBegin`, `GetBlocksInvsFinish`, and `Done`.  In `GetBlocksInvsBegin`, the node sends out a `GetBlocksInv` message to all neighbors to ask for all inventories at a particular block height.  In `GetBlocksInvsFinish`, the node waits for all nodes to reply with `BlocksInv` messages.  In `Done`, all fetched inventory messages are merged into the node's set of block inventories for its neighbors, so that the total block inventory for each neighbor is incrementally fetched.

In PoX, there needs to be a state-machine for each node (instead of a singleton), because different nodes can have different PoX vectors, which affect the `GetBlocksInv` message to send (and affect at which heights to send them).  Moreover, the state machine now has five states: `GetPoxInvBegin`, `GetPoxInvFinish`, `GetBlocksInvBegin`, `GetBlocksInvFinish`, and `Done`.  In `GetPoxInvBegin`, the node asks its neighbors for its PoX bit vectors starting at a given reward cycle (via a `GetPoxInv` message).  In `GetPoxInvFinish`, the node waits for the neighbors to reply with `PoxInv` messages that provide its reward cycle bits.  These `PoxInv` messages are then merged into the node's view of its neighbors' PoX inventories, such that _block inventory data is discarded_ for all reward cycles after the lowest such instance of the arriving `PoxInv` message flipping a bit in the neighbor's bit vector from a 0 to a 1.

Once the neighbor's state machine has synchronized the PoX inventories for all neighbors, and discarded any invalidated block and microblock inventories, it advances to the `GetBlocksInvBegin` state where it asks the neighbor for its block and microblock inventories at a given block height.  Unlike before, this block height is now aligned to the start of a reward cycle -- specifically, for each PoX bit, the state machine asks the neighbor for the block inventory bits for the blocks in that reward cycle.  The state machine alternates between `GetBlocksInvBegin` and `GetBlocksInvFinish` as it fetches and merges more and more of the block inventory bits into the neighbor's block inventories.  The state machine advances to `Done` once all inventory data has been fetched.

All the while, whenever the network thread wakes up, it refreshes and caches its PoX bitvector.  This PoX bitvector is compared against the old cached value, _and if it changes at a particular bit_, the neighbors' PoX and block inventories are invalidated for the corresponding reward cycle and all higher reward cycles.  This will have the effect of re-starting all node-specific state machines to `GetPoxInvBegin`, starting at the now-invalidated reward cycle number.

**Comment by diwakergupta** [comment]
Addressed by #1880
