### ISSUE TITLE
PoX: networking: optimistic concurrency control when considering ancestor blocks

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1870]
The logics for generating a `GetPoxInv` and `GetBlocksInv` both require the ability to query the consensus hash of an ancestral block.  But, the arrival of a new burnchain block or Stacks block in a separate thread in the node can invalidate inventory state (per #1869).  Namely, an ancestor block snapshot in the sortition DB can suddenly become invalidated at any point in time -- even in-between generating `GetPoxInv` or `GetBlocksInv` messages during the `GetPoxInvBegin` or `GetBlocksInvBegin` states.  The logics for generating these messages need to be updated to detect when this happens, so they can restart all inventory synchronization state machines (i.e. from scratch, for now).

**Comment by jcnelson** [comment]
The ChainsCoordinator should inform the network (which runs in a separate thread) when the PoX bitvector is invalidated, so the PeerNetwork can go reload it from the sortition DB.

**Comment by diwakergupta** [comment]
Addressed by #1880
