### ISSUE TITLE
PoX: networking: reject a downloaded block before storing it if the underlying block inventory data was invalidated while the request was in-flight

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1872]
When downloading blocks and microblocks, it is possible that the block inventory data that was used to determine that the block/microblocks were available from a node may be invalidated -- the local node can learn about new Stacks blocks through block processing (thereby invalidating the network's cached PoX bitvector, and thereby invalidating all inventory state after the lowest bit that flipped, per #1870) while the download is in-flight.  Therefore, the node should check that the inventory state is still fresh before deciding to store the downloaded block/microblocks to the staging database.

**Comment by diwakergupta** [comment]
Addressed by #1880
