### ISSUE TITLE
PoX: networking: block header cache should move into the PeerNetwork struct

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1875]
This cache is no longer append-only -- a change in the PoX fork can invalidate entries.  The `PeerNetwork` is particularly affected by this, since the whole reason this cache exists is to speed up block download request calculations.  So, the `PeerNetwork` should maintain ownership of this cache, and be responsible for invalidating it (since it already needs to detect when the PoX fork changes).  More generally, this makes the code safer to work with because there really should only ever _possibly_ be one of these caches around.  We currently instantiate multiple `StacksChainState`s in the code -- for mining, for reading, and for reading/writing -- in different threads, and this can (and should!) be avoided so we don't accidentally try to use the wrong instance for something down the road.

**Comment by diwakergupta** [comment]
Addressed by #1880
