### ISSUE TITLE
VM: MARF I/O should be considered much more expensive than side-store I/O

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1877]
This is more of a _nota bene_ for myself when considering block fill calculations.  MARF I/O operations (i.e. `read_count`, `write_count` in `SimpleCostSpecification`) should be treated as fairly expensive operations compared to raw bytes read and written (`read_length` and `write_length`).  We should keep this in mind when designing Clarity built-in functions.

**Comment by kantai** [comment]
Note -- this is already the case in the testnet, the block limit imposes a much smaller limit on `read_count` and `write_count` than it does on the corresponding `_length` dimensions. I think this issue is a subset of #1255

**Comment by jcnelson** [comment]
I think we're already doing this as part of our current cost assessment, so I'll go ahead and close this.
