### ISSUE TITLE
Proposal: enhance support for sponsored transaction

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#1879]
In order to fully support sponsored transaction schemes, I think smart contract developers should be able to get something like `tx-sponsor?`, in Clarity.
Along the same line, I think that sponsors should be able to set some post-conditions, so that they can protect themselves and make sure that they're getting what they want from the sponsorship.
Thought @jcnelson @kantai ?

**Comment by jcnelson** [comment]
This seems related: https://github.com/blockstack/stacks-blockchain/issues/1075

**Comment by jcnelson** [comment]
What would `tx-sponsor?` do?  Would it evaluate to `(optional principal)` -- i.e. the principal who sponsored the transaction, if it was sponsored at all?  If so, then, that sounds good to me :+1: 

> Along the same line, I think that sponsors should be able to set some post-conditions, so that they can protect themselves and make sure that they're getting what they want from the sponsorship.

I'm not sure this is necessary.  A sponsor can already inspect the transaction before signing it, and can simply refuse to sponsor a transaction that does not also guard its own assets.  Post-conditions apply to any principal's spending, not just the sender's.

**Comment by kantai** [comment]
Yep -- I agree with the above, adding `tx-sponsor?` is probably a good idea, and post-conditions shouldn't be necessary, because the sponsor can just require the post-conditions exist before signing the transaction.

**Comment by lgalabru** [comment]
Addressed with  #2480
