### ISSUE TITLE
Determine Krypton PoX parameters

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1882]
We need to fix the Krypton PoX parameters:

* Reward cycle length
* Threshold
* Prepare length

In the process of fixing these parameters, we also need to be sure to advertise these settings broadly.

**Comment by jcnelson** [comment]
* Reward cycle length = 120 BTC blocks
* Threshold = 1/120th of the liquid supply
   * set liquid supply to 10 million uSTX
   * lowest initial threshold is 1/120th of that
* Prepare length = 30 BTC blocks

**Comment by lgalabru** [comment]
Handled with https://github.com/blockstack/stacks-blockchain/pull/1896
