### ISSUE TITLE
Increase the testnet STX amount given out by testnet faucet

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1883]
In order to test Stacking in the Krypton testnet, users will need to be able to receive larger amount of STX.

**Comment by diwakergupta** [comment]
@agraebe @markmhx not sure which team / component this is owned by now? Should be a minor change, cc/ @hstove 

Exact threshold will be communicated via #1882 .

**Comment by hstove** [comment]
Currently, all faucet functionality lives in the Sidecar. I am able to update this value if needed.

**Comment by jcnelson** [comment]
* Make it so the faucet gives out the lowest-possible minimum Stacking threshold (i.e. 1/120th of the initial liquid supply -- see https://github.com/blockstack/stacks-blockchain/issues/1882), but taking into account more liquidity introduced by mining.
   * First 100 people get lots of STX, i.e. 1/120th of initial liquid supply
   * Throttle down afterwards

**Comment by agraebe** [comment]
cc @zone117x

**Comment by zone117x** [comment]
The constant is here: https://github.com/blockstack/stacks-blockchain-api/blob/469f8b783c9c82079f7cc556bd28c36e987d3286/src/api/routes/faucets.ts#L91

I can change it to whatever we need, whenever.

**Comment by diwakergupta** [comment]
Addressed in blockstack/stacks-blockchain-api#246
