### ISSUE TITLE
Block reward: alternative PoX-optimized coinbase schedule?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1888]
Right now, the coinbase schedule is set at 500 STX for the first 5 years, 400 STX for the next 5 years, and 300 in perpetuity afterwards.  These values were chosen arbitrarily, and not to optimize for a particular expected use-case (in fact, they were chosen before PoX was conceived).

An alternative coinbase schedule suggested by @muneeb-ali could be to do the following:

* 1000 STX for years 0-4
* 500 STX for years 4-8
* 250 STX for years 8-12
* 125 STX in perpetuity 

This would result in more initial liquidity for Stacking, but with fewer overall liquid STX by 2050 than the original proposal.

I'm opening this issue to get community feedback as well as to track its implementation (or non-implementation).  I'm mainly curious to see if it would _hurt_ the chain -- i.e. by giving miners more liquidity with which to discount-mine.

**Comment by jcnelson** [comment]
Estimated time to write and test: 1 day
Estimated time to review the PR: 1 day

**Comment by diwakergupta** [comment]
Corresponding forum post: https://forum.blockstack.org/t/pox-consensus-and-stx-future-supply/11232

**Comment by kantai** [comment]
Closed by #2101
