### ISSUE TITLE
BNS: zone file replication API

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1890]
Off-chain name operations are encoded within on-chain BNS zone files.  We'll need to implement a way to store, announce, and replicate BNS zone files in nodes.  In particular:

* The Stacks node needs a RESTful endpoint for uploading a BNS zone file.
* The Stacks node needs a RESTful endpoint for downloading a BNS zone file
* The Stacks node needs a RESTful endpoint for serving a compact representation of its inventory of the BNS zone files.
* The Stacks node needs some logic to periodically poll its neighbors for their BNS zone file inventories, find BNS zone files it does not have, and download them _in rarest-first order_.

**Comment by jcnelson** [comment]
Estimated times:
* to write and test the inventory representation and query path: 3 days (this will likely require some non-trivial structuring of the the BNS smart contract to make this fast and easy).  Tests need to include queries against non-canonical chain state.
* to write and test the RESTful endpoints to load and store zone files: 1 day
* to write and test the logic for discovering zone files from neighbors and drive replication: 5 days.  This includes:
   * fetching all neighbors' zone file inventories on the same chain view as ours
   * building a combined view of all neighbors' inventory views
   * deriving a priority list of zone files to go and download and store in rarest-first order
   * integrating this driver into the Stacks main loop
   * implementing meaningful tests

Estimated time to review a PR: 3 days

**Comment by lgalabru** [comment]
@jcnelson Regarding
> The Stacks node needs a RESTful endpoint for serving a compact representation of its inventory of the BNS zone files

You confirm that we prefer an HTTP endpoint over a P2P message?

**Comment by jcnelson** [comment]
> You confirm that we prefer an HTTP endpoint over a P2P message?

Yes.  There should be new `HttpRequestType` and `HttpResponseType` type variants made for the messages as well.  Feel free to use a JSON-based representation if you want.

**Comment by lgalabru** [comment]
Feature completed, closing now
