### ISSUE TITLE
BNS: zone file storage

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1891]
BNS names have zone files, and they need to be stored with the chainstate.  We used to store them in flat files, but this created some problems with fast-synchronization because it significantly increased the amount of disk I/O required to pack/unpack a snapshot and significantly increased the number of inodes the underlying filesystem needs.

The BNS 2.0 zone file storage system needs to keep all zone files in a Sqlite database instead.

**Comment by jcnelson** [comment]
Estimated time to implement:
* to write and test a zone file database that only loads and stores zone files: 1 day (see #1889)
* to write and test the code to ensure that a zone file only gets added to the database if it corresponds to a `NAME_UPDATE` / `NAME_REGISTRATION` / `NAME_RENEWAL` hash in BNS on the canonical Stacks fork: 1 day
Estimated time to review a PR: 1 day

**Comment by jcnelson** [comment]
The consensus here is that even though zonefile replication is an off-chain concern, it's of paramount importance that the Stacks node handles it because we really need the set of zonefiles to be widely available and distributed.

**Comment by lgalabru** [comment]
Feature completed, closing now
