### ISSUE TITLE
PoX: on-Bitcoin Stacking operations

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1892]
Per SIP-007, the Stacking operation needs to be able to occur on the Bitcoin chain in over to overpower Stacks miners who may be disinclined to mine them.  In particular, we need at least two operations to be on-chain:

* Locking up STX for Stacking
* Rejecting the PoX reward cycle

These need to have fall-back implementations that work on the Bitcoin chain because their execution has monetary repercussions for Stacks miners who participate in Stacking.  Making it so that they are represented on the Bitcoin makes it impossible for correct Stacks miners to ignore them.

**Comment by diwakergupta** [comment]
@kantai this is a superset of #1856 or you want to track them as independent issues?

**Comment by kantai** [comment]
I think they are independent issues, #1856 is about providing a spec for all of our Bitcoin transactions.
