### ISSUE TITLE
Use `rustfmt` to enforce coding style

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1907]
The code base has a lot of different formatting styles, which is bad for several reasons, some of them being:

1. It makes it harder for people new to the code base to read the code, and contribute stylistically acceptable code.
2. It makes the commit history noisier.

And it's easy to fix: `rustfmt` is a standard rust component that we can just add to our unit tests via:

 `cargo fmt --all -- --check`

`rustfmt` will also handle reformatting, so we can open a PR against `master` that applies the formatting change while adding the check.

**Comment by kantai** [comment]
Also-- to minimize disruption, this kind of thing is best to do when there is the least amount of large outstanding work. With the release of `krypton`, a bunch of workflows just committed, so I'd say "now-ish" is a great time to do this.

**Comment by jcnelson** [comment]
We should incorporate a step in our CI process that, eventually, will block the build until the code is de-linted.

**Comment by kantai** [comment]
Closed in #1919, 🤞
