### ISSUE TITLE
Stacks node non-responsive to RPC requests

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1911]
A non-mining stacks-node, after running for some time, became non-responsive to RPC requests.

Attaching stack trace and ~6000 lines of logs from the non-responsive period in question.

[stacktrace.txt](https://github.com/blockstack/stacks-blockchain/files/5284055/stacktrace.txt)
[debug-logs.txt](https://github.com/blockstack/stacks-blockchain/files/5284056/debug-logs.txt)

**Comment by diwakergupta** [comment]
@CharlieC3 can we generate a new tagged build and update just the sidecar/follower? Thanks!
