### ISSUE TITLE
Stacks chain differentiation on Bitcoin testnet

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1926]
In preparation for the Xenon testnet, we will need a strategy for differentiating between Stacks chains on the Bitcoin testnet. While the network would continue to function without this differentiation, it would be pretty degraded because of various nodes seeing block commits as valid vs. invalid, or trying and failing to communicate over the p2p system.

Possible options for differentiation:

1. first_burn_block_height
1. chain_id
1. Magic bytes in the Bitcoin wireformat

In all likelihood, I think we'd want to use all of the above.

**Comment by diwakergupta** [comment]
@kantai @lgalabru don't we still need this?

**Comment by kantai** [comment]
Yeah -- I think we do.
