### ISSUE TITLE
P2P: push blocks that we have to neighbors that don't have them if we're NAT'ed

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1927]
In testing #1903, I noticed that my miner will occasionally disconnect from other peers.  This can happen naturally, such as when the node detects that its public IP address has changed.  However, if my miner is behind a NAT, it will be unable to send any blocks it mines to the peer network while temporarily disconnected.  This is problematic, because it means that no one can build off of my block.

The node should detect when it fails to broadcast a block or a microblock, and re-try it for a set period of time before it expires.  The node could genuinely be offline, in which case, _not_ re-sending after a timeout is the appropriate action.  But, transient disconnections like this should not cause blocks or microblocks to get lost.

**Comment by jcnelson** [comment]
We're going to need to fix this in order to get microblocks to work reliably.

**Comment by jcnelson** [comment]
I think we can be a bit more aggressive about this in the NAT'ed case.  If the node has no inbound connections that are publicly routable, it should assume that it's NAT'ed.  If so, then it should scan all its outbound peers' inventories to see if they're missing blocks that this node possesses.  For each such block, the peer should send them `BlocksData` messages.  The peer should do this scan-and-broadcast pass at least once per sortition.

**Comment by diwakergupta** [comment]
Last 10K lines from my miner log attached: [miner-log-snapshot.log](https://github.com/blockstack/stacks-blockchain/files/5425525/miner-log-snapshot.log)
