### ISSUE TITLE
Testnet: miner node crashes if given the same config file and restarted

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1928]
If you start up a node a second time with the same config file (i.e. with the same seed), it will crash when it tries to create a VRF proof.  This is because it does not calculate the VRF private key for the VRF key registers it previously sent.  Moreover, the call site at which this could be done doesn't even have access to the keychain, so the node can't even re-generate its previous VRF private keys when it sees the VRF public keys being registered.  For now, it's sufficient to just ignore our previous VRF key registers if we discover them during the initial block download, prompting the run loop to regenerate and re-send a VRF key register when the miner finishes booting up.

**Comment by diwakergupta** [comment]
Is this a regression introduced in #1848 (which was fixing #1615)? If so, perhaps @psq can take this on?

**Comment by jcnelson** [comment]
I've already fixed it in #1903

**Comment by psq** [comment]
I'm not sure I fully understand what was causing the crash, as starting a miner with the same configuration file after the same miner has run on the same chain has worked for me (multiple times), and if 2 miners run with the same key, one of the commit will get ignored.

**Comment by jcnelson** [comment]
Fixed in #1903.

@psq The cause was that the keychain was trying to find the VRF private key for a given VRF public key it witnessed on-chain as being one of the transactions it mined.  But because on the second start-up it had _not_ sent the VRF public key register, the code path that generated the VRF private key never executed, leading to a runtime panic.

**Comment by psq** [comment]
thanks @jcnelson!
