### ISSUE TITLE
Miner: don't re-use microblock public key hashes when starting up for the 2nd time with the same seed

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1934]
Right now, if you bootstrap miner node a second time with the same seed, it will cycle through the same microblock public key hashes it used when it mined previous blocks.  This causes the miner to mine invalid blocks.  We can fix this by having the miner software generate its microblock keypairs similar to how it does so for VRF keypairs -- by using the block height as input to the key generator.

**Comment by kantai** [comment]
@jcnelson -- are you actively working on fixing this for the stacks-node, or should I open a quick patch PR for this?

**Comment by jcnelson** [comment]
Go ahead and submit a PR for it.
