### ISSUE TITLE
Nodes fail to broadcast transactions to peers

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1940]
We've seen a number of transactions get "stuck" on the testnet because the node that receives the transactions fails to broadcast them to anyone else in the network. For example:

1.    `0x34e41021755721b837ba54497597e42ab9bbfd9cb71731d28af609ca068613bc`
2.   `0x77c12981affd9f056a81be6546d682d9adbd9b4069e7153a2cf2c7a0e6d69fb2`

It looks like the follower never pushed them to the miner (see the broadcasted to 0 peers message in the attached logs) -- I think this is a problem related to the follower being disconnected by the miner -- see discussion with @jude here:

https://discord.com/channels/621759717756370964/730814571517968436/759146151987118090

[tx1-broadcast-to-none.txt](https://github.com/blockstack/stacks-blockchain/files/5319023/tx1-broadcast-to-none.txt)
[tx2-broadcast-to-none.txt](https://github.com/blockstack/stacks-blockchain/files/5319024/tx2-broadcast-to-none.txt)

**Comment by jcnelson** [comment]
I'm aware -- the same problem manifests for blocks that get mined during when the node gets disconnected.  Related: https://github.com/blockstack/stacks-blockchain/issues/1927

**Comment by kantai** [comment]
Ah, I see -- closing this issue in favor of #1927, then.
