### ISSUE TITLE
EXIF Geolocation Data Not Stripped From Uploaded Images

### ISSUE THREAD

**Issue by 1997pinchu** [blockstack/stacks-blockchain#1942]
Vulnerability Name: EXIF Geolocation Data Not Stripped From Uploaded Images

Vulnerable Site: https://browser.blockstack.org/profiles

VRT: Sensitive Data Exposure > EXIF Geolocation Data Not Stripped From Uploaded Images > Automatic User Enumeration

Summary:
When a user uploads an image  in blockstack.org , the uploaded image’s EXIF Geolocation Data does not gets stripped. As a result, anyone can get sensitive information of blockstack.org users like their Geolocation, their Device information like Device Name, Version, Software & Software version used etc.

Vulnerability Description:
When an image is taken using a smartphone or camera certain metadata fields are often attached to it. These fields could include the model of the camera, the time it was taken, whether the flash was used, the shutter speed, focal length, light value and even the location. In Inturn, while uploading the image as a profile picture, the exif data is not stripped from images. The exif data in images contains sensitive data like Geoloacation, latitude, longitude, etc. Also it contains the camera information and other details.

Step To Reproduce:

1) Got to Github ( https://github.com/ianare/exif-samples/tree/master/jpg)
2) There are lot of images having resolutions (i.e 1280 * 720 ) , and also whith different MB’s .
3) Go to Upload option on the website  chatbox(https://browser.blockstack.org/profiles)
4) Upload the image
5) see the path of uploaded image ( Either by right click on image then copy image address OR right click, inspect the image, the URL will come in the inspect , edit it as html )
6) open it (http://exif.regex.info/exif.cgi)
7) See wheather is that still showing exif data , if it is then Report it.

Confedentiality : Low
Integrity: Low
Availablity: High

Impact
This vulnerability is CRITICAL and impacts all the blockstack.org customer base. This vulnerability violates the privacy of a User and shares sensitive information of the user who uploads an image on blockstack.org or any of the blockstack.org instances.

Fix:
Except from removing EXIF from any new uploads we should also removing EXIF data from existing uploads.

Possible solution:
create a background migration (or rake task) which will select all uploads which have path matching .(jpg|jpeg|tiff) suffix, fetch these uploads, remove EXIF data (mini_magick gem can do this) and write data back again to the original location

cmd = ["exiftool", "-exif:all=", "-tagsFromFile", "@", "-Orientation", path]
output, status = Gitlab::Popen.popen(cmd)

Kind Regards:
Ankit

**Comment by diwakergupta** [comment]
@1997pinchu thanks, we use this repo for issues / bugs / features related to the Stacks Blockchain. For security disclosures, please refer to hackerone.com/blockstack
