### ISSUE TITLE
Regarding PoX

### ISSUE THREAD

**Issue by agnelvishal** [blockstack/stacks-blockchain#1948]
Consider PoX to be like Layer 2 of Bitcoin. 
Is a Layer 3 possible where transfer of STX can be used as consensus for a new blockchain with new token?
I assume Layer 3, Layer 4 and so on will have higher effeciency and lower security.

**Comment by diwakergupta** [comment]
> Consider PoX to be like Layer 2 of Bitcoin.
> Is a Layer 3 possible where transfer of STX can be used as consensus for a new blockchain with new token?

Yes.

@agnelvishal we use Github issues for bugs reports and feature requests. For more open-ended questions / discussions, please join our Discord or visit forums.blockstack.org, thanks!
