### ISSUE TITLE
Include btc block & tx hashes in sidecar event

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1950]
The burnchain block hash and tx hash should be included in the event data sent to the sidecar. 

The sidecar will expose these to the explorer, which will link them to an external Bitcoin explorer that others can use for inspection and verification purposes. 

Reference: https://github.com/blockstack/explorer/issues/225

**Comment by diwakergupta** [comment]
@kantai @lgalabru this should be a pretty small change, right? Some explorer work is blocked on this. Could one of you, or maybe @reedrosenbluth can take this on?

**Comment by kantai** [comment]
Sure, I can add this pretty quickly.

**Comment by diwakergupta** [comment]
Awesome, thanks @kantai ! @aulneau FYI
