### ISSUE TITLE
Faucet throwing 500s

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-blockchain#1953]
As reported first in https://github.com/blockstack/stacks-wallet/issues/259, the faucet endpoint appears to be throwing 500s consistently, for the wallet and faucet page on blockstack.org:

<img width="1564" alt="Screen Shot 2020-10-07 at 15 14 28" src="https://user-images.githubusercontent.com/28991/95335604-e6d5c380-08af-11eb-8c22-5d49ac2fc20d.png">

**Comment by zone117x** [comment]
> This happens if there is more than one faucet tx in one block....

@friedger this is no longer the case. Up to 5 transactions (the current mempool stack limit) can be submitted per block.

**Comment by diwakergupta** [comment]
@markmhx @zone117x is this still happening? Either way let's see how things look on Krypton once #1980 is merged and deployed: I suspect that would address many of the issues we've had on Krypton.

**Comment by markmhx** [comment]
Yep I'm seeing the same error:

![image](https://user-images.githubusercontent.com/28991/96580435-8f384e80-12d8-11eb-8fc5-61e7d0cbccf6.png)

**Comment by markmhx** [comment]
Today it's working for me:

![image](https://user-images.githubusercontent.com/28991/96716365-397da800-13a5-11eb-8436-b0b3846e4f5e.png)

**Comment by diwakergupta** [comment]
> Today it's working for me:
> 
> ![image](https://user-images.githubusercontent.com/28991/96716365-397da800-13a5-11eb-8436-b0b3846e4f5e.png)

Given that this is a symptom, not a cause, of transactions pending in mempool, I'm going to close this out in favor of existing, narrower issues that capture this better.
