### ISSUE TITLE
P2P: trying to connect to the node's bind address during a neighbor walk should cause the walk to fail

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1966]
Right now, a node can get caught in a neighbor walk loop where it constantly tries to handshake with its own bind address.  This does _not_ cause the walk to fail, but it should.  This, in turn, can prevent the node from re-connecting with other peers in the event of a disconnect, leading to network partitions.

This is also the source of the `Denied` errors people have been seeing.

**Comment by psq** [comment]
fixes this is going to make a lot of errors disappear, and make a lot of people happy (even if they realize they will be ...)

**Comment by diwakergupta** [comment]
Fixed with #1980
