### ISSUE TITLE
Incorrect "unused_assigments" warning at compile time

### ISSUE THREAD

**Issue by stedwms** [blockstack/stacks-blockchain#1991]
Hi guys, I was inspired to get a Testnet node up and running, in order to participate in the Mining Challenge starting on Monday 10/26/20. Looking forward to it.
At the step where the packages are compiled, there were warnings, as you can see from the attached image. This happened upon compiling into target/debug as well as target/release.
No big deal as the software seems to be running, but I thought you might appreciate the feedback.
I've now done installations within four different environments: Ubuntu 18.04 on a local virtual machine (bento box on Oracle VM Virtual Box); Ubuntu 18.04 as well as Ubuntu 20.04 on a cloud provider; and I finally selected Debian 10 with the cloud provider.
Do you need to know the output of stacks-node version? It is: stacks-node 0.1.0 => 23.0.0.0 (master:878bf5b73, release build, linux [x86_64])
FYI, for the time being, I'm leaving the software running on the cloud provider on a detached screen on Debian 10. The attached screen was created with screen command along with custom logging to a text file where you can follow current activity in real time with tail -f. This will reduce the need to re-start from scratch, reloading the data to sync, etc., and you can stay in the game of mining and winning sortitions without delay. If you would like me to write up my suggestions for setting up the runtime environment within flavors of Linux, let me know. I haven't had a chance to explore the Docker options yet.

![stacks_testnet_warning](https://user-images.githubusercontent.com/9540918/96915246-0524ed00-1474-11eb-8d1f-11fe3c4aaff8.png)

**Comment by psq** [comment]
that warning is incorrectly generated by the compiler, probably because of the loop, making it harder to detect, so the code is correct.
And there is no way currently to disable this warning on a per line basis, only at the function level with 
```
#[allow(unused_assignments)]                                
```

so that warning may be here to stay till the compiler gets smarter...

**Comment by psq** [comment]
regarding linux setup that differ from existing docs, I would recommend filing issues/creating PRs against https://github.com/blockstack/docs
