### ISSUE TITLE
Live Stacking calculator Bounty

### ISSUE THREAD

**Issue by Trudko** [blockstack/stacks-blockchain#1993]
Hi :) , spoke with  Tim about [bounty for phase 3 ](https://www.blockstack.org/testnet/bounties#Tools) for STXStacking. It's already used by a community. 

For the future  I am planning to do few updates before mainnet like connecting to live data for Bitcoin spent by miners, total liquid supply and total stacked supply.

**Comment by timstackblock** [comment]
Hello @Trudko thanks for the issue. 

I will add your STXStacking app to the bounty list so it can be reviewed thank you for the submission.

**Comment by diwakergupta** [comment]
@Trudko @timstackblock can we track tool bounties etc in a different location? I'd like to keep issues in this repo very focused on actual bugs / features in the stacks-blockchain. I'm going to close this out for now, assuming Tim is already tracking this elsewhere.

**Comment by Trudko** [comment]
@diwakergupta sure. Originally I've created the issue here https://github.com/blockstack/bounties/issues/5 but was told to duplicated it here. @timstackblock, where should I create issue or can we use bounties repository?
