### ISSUE TITLE
Raise value of MAXIMUM_MEMPOOL_TX_CHAINING

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#2009]
The current value is set to 5 (https://github.com/blockstack/stacks-blockchain/blob/master/src/core/mempool.rs#L60), which seems low when considering 10 minutes between blocks.

This currently limits the faucet, and the current version of `swapr` requires deploying 10 contracts, so this would require to split into 2 sets (maybe microblocks would help, a bit, but these would still end up within a block).

I suggest increasing the value to 25, or better yet, make this a node configuration parameter so miners can decide whether they'd want to allow larger values.

**Comment by jcnelson** [comment]
Let's go ahead and do this.
