### ISSUE TITLE
[TESTNET BUG] RBF fee calculation spends too much

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#2010]
While running a miner during the competition, the 0.5 btc ran out much faster than anticipated (after about 1/3 of the blocks it was supposed to last for.  Here's why:

With the burn fee set to 22_000, when attempt = 1:
total_spent: 22_000
tx_fee: 5_500

but when attempt  = 2
total_spent: 22_000
tx_fee: 726_396

The code is adding last_tx_len * min_relay_fee to the original fee

It seems we have 2 problems:
- it is multiplying the calculated fee by `attempt`, while it should be using `attempt - 1` (i.e. add the fee once if that's the second attempt, the fee for the first attempt is the original 5_500)
- the relay fee (as returned by my bitcoind node) is 0.00001000 (or 1000 sats, the code uses 1024), but that's the fee per kb, not per byte

so the current calculation is off by 2048, and instead of 726_396 should be 5500 + 352 = 5852, which seems more reasonable.

**Comment by psq** [comment]
here is the hex of an example transaction:
```
0100000001744ec9b3be64b531de487bf16c04331a210adf893c90fffdb0688dfa7d2d2067030000006b4830450221008a3086fb5ddc321f7f88a5d814f3743c9c0cd6090e14734661b979b4a596075d02203376dea56d5cf98ccd37471094ce1caa0f9d842e2421fe43fdc2d7e9552b7ed6012103c74baf92e45c41c5d16022165753f015b032b0bce30dc848d2a3495128800ccafdffffff040000000000000000536a4c5069645b7864fecd3202dd222b78df943450f6cd1df0506c38137640099b648ac5ce1480d7945e05c3efca65b0418e3aaea7252b548b68e4428b755c39e4bdb283eee3090000059300160000058b001000f82a0000000000001976a914000000000000000000000000000000000000000088acf82a0000000000001976a914000000000000000000000000000000000000000088ac902bcd02000000001976a914be8203fccbca453e0b0dd4edc919451c7895764088ac00000000
```
which has 704 characters

**Comment by jcnelson** [comment]
The PR for this introduced a regression:

```
ERRO [1604362977.817576] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:760] [ThreadId(7)] Bitcoin RPC failure: transaction submission failed - Network("Bitcoin RPC: status(500) != success, body is \'Object({\"error\": Object({\"code\": Number(-26), \"message\": String(\"insufficient fee, rejecting replacement 8f4ba8e0bfc4ba52d726deed4f44a6f3393df0993f5d2129d74ecb93cf7173f4, not enough additional fees to relay; 0.00000351 < 0.00000352 (code 66)\")}), \"id\": String(\"stacks\"), \"result\": Null})\'")
```

**Comment by psq** [comment]
I checked the log, and was getting that error as well when using the RBF fix, but then I can't explain why I found the replaced transaction I checked but not the original committed in a block.

**Comment by psq** [comment]
the calculated fee was 352 (https://github.com/blockstack/stacks-blockchain/pull/2011#issuecomment-719846169).  Anyway, yes, 1000 seems the correct value to use
