### ISSUE TITLE
[TESTNET BUG] Panic "database is locked" making miner crash

### ISSUE THREAD

**Issue by pradel** [blockstack/stacks-blockchain#2017]
## Describe the bug

My testnet miner is currently crashing every time I start it with the following error.

```
ERRO [1604006233.199696] [src/vm/database/sqlite.rs:46] [ThreadId(6)] Failed to insert/replace (b95eda932e33f2c035f9b252f54626e3f88b00c0a
6a7f7e79d3ce6ed56353e710000000000000000,00000000000000000000000b4ad34500000000000000000000000000000000000000000000000000): SqliteFailure(
Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
Process abort due to thread panic
```

## Steps To Reproduce

I just had my miner running for 3 days without a problem and then this happens. Every time I restart it I face the same issue.

## Environment

 - OS: Ubuntu 20.04
 - Latest version of this repo at the time I am creating this issue.

## Additional context

Here is the full log.

[tmux.log](https://github.com/blockstack/stacks-blockchain/files/5464715/tmux.log)

**Comment by kantai** [comment]
This looks like it's the same issue as #1939 -- closing in favor of #1939.
