### ISSUE TITLE
[TESTNET BUG] Miner node does not spend the BTC and cannot its BTC burns are rejected

### ISSUE THREAD

**Issue by paradigma-cl** [blockstack/stacks-blockchain#2019]
## Describe the bug

After several days of the miner running still maintains the initial BTC balance.  Looking at the error log, I notice thatis says Invalid commit tx: different output amounts for different PoX reward addresses and Total burn fee not enough for number of outputs

## Steps To Reproduce
Just running the miner
Please provide detailed instructions (e.g. command line invocation with parameters) to reproduce the behavior.

## Environment

 - OS: [e.g. Ubuntu / Debian] Ubuntu 16.0
 - Rust version
 - Output of `stacks-node version`

## Additional context

Please include any relevant stack traces, error messages and logs.
INFO [1604010913.754925] [testnet/stacks-node/src/neon_node.rs:1117] [ThreadId(1)] Received burnchain block #2709 including block_commit_op - mm4N9cKbN6RrA912gYhCQkm51XRP3dd9L9 (39fd2f1f1361721ff5cda
46a1a0f56582a60fd547c54ef1c8d9ad92ccc49ba11)
INFO [1604010913.754931] [testnet/stacks-node/src/neon_node.rs:1117] [ThreadId(1)] Received burnchain block #2709 including block_commit_op - mx2uds6sgnn9znABQ6iDSSmXY9K5D4SHF9 (d2f717a96abd741e27057
20d78040da0ea8d38b92891322abbcbae4abb76054c)
INFO [1604010913.755059] [testnet/stacks-node/src/neon_node.rs:753] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1604010918.999617] [src/chainstate/stacks/miner.rs:672] [ThreadId(7)] Miner: mined anchored block d960200de20478d1b5f0ecaa172d3af4a66fda108378b47f0fe72df87319be72 with 1 txs, parent block 59885
559c44e8a536e372d874c67364e3c6e706ee0fbb6dbea27440b2efd39a6, state root = 2e3b3d43ba0a4a9108e191ff1251203b48d0f5e942e382fb00ac962fdfd601a6
INFO [1604010919.405069] [testnet/stacks-node/src/neon_node.rs:1024] [ThreadId(7)] Stacks block assembled: d960200de20478d1b5f0ecaa172d3af4a66fda108378b47f0fe72df87319be72, with 1 txs, attempt 1
ERRO [1604010919.925517] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:596] [ThreadId(7)] Total burn fee not enough for number of outputs
INFO [1604010949.392015] [testnet/stacks-node/src/neon_node.rs:753] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1604010984.864368] [src/net/p2p.rs:472] [ThreadId(8)] No open socket for 488
INFO [1604010985.090159] [testnet/stacks-node/src/neon_node.rs:753] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1604011003.542923] [src/net/chat.rs:1823] [ThreadId(8)] convo:id=481,outbound=true,peer=facade01+80000000://V4(8.210.105.204:20444): failed to recv on P2P conversation: PermanentlyDrained
WARN [1604011019.450784] [src/net/relay.rs:696] [ThreadId(7)] Consensus hash 5688909f80f35fb981bb9a67c9cade18058821ca not known to this node
INFO [1604011021.320915] [src/burnchains/burnchain.rs:1105] [ThreadId(1)] Node will fetch burnchain blocks 2709-2710...
WARN [1604011021.726763] [src/chainstate/burn/operations/leader_block_commit.rs:247] [ThreadId(2145)] Invalid commit tx: different output amounts for different PoX reward addresses
WARN [1604011021.726781] [src/burnchains/burnchain.rs:577] [ThreadId(2145)] Failed to parse leader block commit tx fa3c77fc8f8fa044c6adc2dfb13475d4e4deb2bf56cdb80aaade17227192811f data 8e4ea4f64f30d8
d3f465e49906c3d3086759d050978ed40e9549de4b52dacc1b4edcf221c5ed08f49ab550279a4d1f361b898ae4285ff6408bb8df309667afce00000a950004000003fb000200: ParseError
WARN [1604011021.987044] [src/chainstate/burn/operations/leader_block_commit.rs:524] [ThreadId(6)] Invalid block commit: no corresponding leader key at 1813,14 in fork e53de8b43abaf4f2a273f14c5ab05c5
5ea90c5a678e26825456fe951bbe727ee
WARN [1604011021.987057] [src/chainstate/burn/db/processing.rs:63] [ThreadId(6)] REJECTED(2710) leader block commit 55908bbddfaabe31e9d823ad322696616692c043ba8cdb8d25a9c73c5624cd60 at 2710,1: BlockCo
mmitNoLeaderKey
INFO [1604011022.473068] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 0ac796c74ba3831823ceb3db5a7ec0b1cd9970dae0465e2d7fbf5f68ccae2932 at 2710,2
INFO [1604011022.473175] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 5964d7ad51e738ef6244ea95a2144bc9bd9a21ba55102f7d841947f6a0b5f136 at 2710,3
INFO [1604011022.475861] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 980435afa6b2880fff79800a1c64e4ab193766a93ecadb129c11f23ae9a7f5a1 at 2710,4
INFO [1604011022.485155] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit a1cfc59dd5db450a8c2d1e72c6a2cb4972f31596db3d025d54fb6142c65529b9 at 2710,5
INFO [1604011022.488971] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 159e5d695aa3f3e6ed565777507c3d38b5d11445f5e1e6f465c5fb51d603f5f9 at 2710,6
INFO [1604011022.489080] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit f20ddf87004122afe64f113dad3952a920f2862879f5f7258a003a2fe6131a44 at 2710,7
INFO [1604011022.497720] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 7a388cc0119fb394043dc328bb183b39bdb91a38cf0c4a0a2f67815a8154c460 at 2710,8
INFO [1604011022.504427] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 3163130ad87e76018b3aa838bf6499bc643193b1f6e79877e4e62937f75a31d0 at 2710,9
INFO [1604011022.522653] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 055de1d2c90cae71ee1fb3ca5069bed5c06977e5c8cfe2fda6af020602a1c0e1 at 2710,10
INFO [1604011022.523157] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 330d8cad52e1ccf878e28e68ca3e7d173a3f54b8d7588b1ef7604fe0d2dac5eb at 2710,11
INFO [1604011022.533620] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 7972e5e1253560cc82988d804b7be5b52cae9a54a2ecc42db203be2b691da096 at 2710,12
INFO [1604011022.542124] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit df21852ac8c1ba7c061d0b2bb57ab92c5d4dc32dc8fbe9c64267ff2788ca5eca at 2710,13
INFO [1604011022.548218] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 0cb0d3d00e516075dc3c6d0558318c0dbacb10f53f0ac231be4552d6f7438f96 at 2710,15
INFO [1604011022.569319] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 927d89935d3a62846adabdac1df5286a1cbaa23b38a2f8c7ec168701ccee92d7 at 2710,16
INFO [1604011022.577869] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit ac2c281ed3023b7a13841c4a7bd2b48f7724ccd7d120d1e06da04cc8021a7711 at 2710,17
INFO [1604011022.587897] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 695fb3e064c32610af4076ddb3812884aaffad9e97825530489d911352ed1ba1 at 2710,18
INFO [1604011022.591474] [src/chainstate/burn/db/sortdb.rs:2981] [ThreadId(6)] ACCEPTED(2710) leader block commit 5997d68a67d3f4e60b2992f09977280b4284106b76df5f700d1c8453b1c45629 at 2710,19
INFO [1604011023.000293] [testnet/stacks-node/src/neon_node.rs:1117] [ThreadId(1)] Received burnchain block #2710 including block_commit_op - mmLJviAqiRtNGNueMqp9y6zraQLt2kK2iT (3f6c287c2a023c0b3cac8
f13233885ee833d814c6a1e3e03b7ae1f51fd272643)
INFO [1604011023.000311] [testnet/stacks-node/src/neon_node.rs:1117] [ThreadId(1)] Received burnchain block #2710 including block_commit_op - mrfTqmiywagAyHTgqdgaqDoqQ84pFp9BTb (5ba1d5ca810e650d55dad
fe24615fdd68cc9f1f44c555969928f96144f90c4ba)
INFO [1604011023.000318] [testnet/stacks-node/src/neon_node.rs:1117] [ThreadId(1)] Received burnchain block #2710 including block_commit_op - mw2Pg4jQkLeW1R7WTCHcvXqnbRVWWcRmnL (d1cdc6326bf4210b97e56
9af6773598fc10d4f95388af7814d306f03
If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ x] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [x ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ x] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [x ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by diwakergupta** [comment]
@paradigma-cl we suspect you're running an outdated version of `stacks-node` (please run `stacks-node version` or open `/v2/info` to confirm). I'm going to close this out, please reopen if you see this issue with a current version.
