### ISSUE TITLE
Snapshot Fast Sync from Decentralized Cloud

### ISSUE THREAD

**Issue by keleffew** [blockstack/stacks-blockchain#2030]
**Core Problem: Reliance on AWS architecture**

Blockstack is currently hosting periodic, monthly snapshots of the Blockstack chain for end users looking to run an Blockstack node, that will serve a new Blockstack Core node from a recent snapshot of the network state. 

Stacks Fast-sync pulls a snapshot from a single region in Amazon Web Services S3, limiting the architectures’ global accessibility, performance, and decentralized resilience.

**Describe the solution you'd like**
Storj has a decentralized fast sync (DFS) process that is globally performant, resilient, and more economical than the current hosting process that Blockstack is using.  

By migrating to the decentralized cloud, STX users will experience better performance across the globe, while Blockstack will pay a fraction of their current storage and bandwidth costs for Amazon S3.  

I spent some time scoping a solution that subs out AWS for the decentralized cloud.  For the test, I uploaded the most recent snapshot here, where the file is encrypted, erasure coded, and distributed across the world (making it globally available, rather than single AWS region).

Rather than streaming from AWS, this file can be downloaded from Tardigrade, from thousands of nodes in parallel, using the following link:
Latest snapshot of Sep 1st: [download (from the Decentralized Cloud)](https://link.tardigradeshare.io/1BvK3b5EveCJGhHBsY8TtYa6bAY6N3wf4u6MwcvVbUijXA8duLyxmC2YJwVRSyGfphu9F6ie617QJqjVCUHurYHCu83jP3WVt84TZ3L4p5C3p36ZoQr6fEFXryeTuWbYbXuK67f3th8MdAPxiJDPM7KqEYypWzsxVSoyTLeEunPx1JzeHwfV2Y9kdqYhoHzjYbfCmDCWZHmJRNTfmskqphyJPm8oqe7YENWuo4z3fFZDuGhiyrX6Q12buuiXiJ2ttkzvnAMEUnDxVm3adghv3GdvaMQKGxdMoQhfPpkY7hHHAofAvNX7ueVL74oWjnfEV4G4Mo5hv62vpV6vYVCDHtWMP5V5zJPi3A5e7GvnHsRuJWsL2m1WiTWneEQLPTW/dwebdemo/snapshot.bsk)
Size: .92 GB

**Try it out**
You can curl it yourself with: 
`curl -o snapshot.bsk 'https://link.tardigradeshare.io/raw/1BvK3b5EveCJGhHBsY8TtYa6bAY6N3wf4u6MwcvVbUijXA8duLyxmC2YJwVRSyGfphu9F6ie617QJqjVCUHurYHCu83jP3WVt84TZ3L4p5C3p36ZoQr6fEFXryeTuWbYbXuK67f3th8MdAPxiJDPM7KqEYypWzsxVSoyTLeEunPx1JzeHwfV2Y9kdqYhoHzjYbfCmDCWZHmJRNTfmskqphyJPm8oqe7YENWuo4z3fFZDuGhiyrX6Q12buuiXiJ2ttkzvnAMEUnDxVm3adghv3GdvaMQKGxdMoQhfPpkY7hHHAofAvNX7ueVL74oWjnfEV4G4Mo5hv62vpV6vYVCDHtWMP5V5zJPi3A5e7GvnHsRuJWsL2m1WiTWneEQLPTW/dwebdemo/snapshot.bsk'`

**AWS Performance Comparison**
We did an internal test from a service we run, called meteoroid that runs in a VM and compares Upload/Download/Delete performance across providers.  This test uses a 102.5MB file as benchmark comparisons

Across a broad range of file sizes and locations, Tardigrade performance exceeds single region performance for Amazon S3.  Tardigrade’s tight distribution (the small range in performance variance) means more consistency, in addition to better performance.  

These results are consistent even with large numbers of concurrent downloads due to the distributed parallelism inherent in the architecture.

**Potential ROI for Blockstack**
For this ROI analysis, we are assuming that Blockstack keeps a rolling copy of snapshots, that these snapshots are growing at 5 GB a month, and that they are downloaded 50 times a month.

According to the current pricing for Amazon S3 (https://aws.amazon.com/s3/pricing/), the Asia Pacific Region costs $0.023 per GB of storage, and $0.09 per GB of Bandwidth, monthly.

Alternatively, Tardigrade pricing costs $0.010 per GB of storage, and $0.045 per GB of Bandwidth, monthly.

Tardigrade will save Blockstack over 60% per month on Storage and over 50% per month and bandwidth, with native global redundancy (minimizing latency) at no additional cost.

Through Tardigrade, Storj Labs offers an SLA, similar to Amazon S3, of 99.95% Availability and 99.9999999% Durability.  This Service Level Agreement is available for review here:  https://tardigrade.io/terms-of-service/

**Comment by diwakergupta** [comment]
Thanks @keleffew, appreciate the issue. However, it's outside the scope of this repository.
