### ISSUE TITLE
[Stacks v1 → v2 Upgrade] Freeze Stacks 1.0 tx processing after migration trigger

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#2034]
After the export threshold is reached (and the data is dumped), the Stacks 1.0 node should stop processing new transactions. 

This is important to help prevent tx rollbacks from occurring during the hardfork period.

**Comment by zone117x** [comment]
@jcnelson I could use some pointers on this. I'm not sure the which area of the codebase is most appropriate for attempting this.

**Comment by jcnelson** [comment]
Probably in `virtualchain_hooks.py`.  This is where the node handles a block's transactions, processes them, and commits them.  You could do something like the following:

* Once the export is created, no further transactions will be accepted.  You could modify `db_check()` to always return `False` once this happens, for example.
* Once enough blocks have passed that Stacks 2.0 will have started, you could have the Stacks 1.0 node exit.  You could achieve this by adding a special table to the names DB like you did for the v2 export state, and have a flag there that gets set once the block height reaches the first block that will be processed by Stacks 2.0.  Once the node sets this flag, it exits.  Also, you'd want to modify the node to check this flag on start-up, and if set, have it exit immediately.

**Comment by jcnelson** [comment]
Addressed in `v1-migration` in facd6418864d3b216153cbaa53d27ed22e4ef9e6 and f5c9bd67770efceeada5e8857dfef947a15b392c

**Comment by zone117x** [comment]
Perfect, thanks @jcnelson!
