### ISSUE TITLE
Security issue: "contextIsolation" is disabled by default

### ISSUE THREAD

**Issue by Shashank-In** [blockstack/stacks-blockchain#2037]
**Describe the bug**
This means the Electron APIs and the preload script run in the same context, hence an XSS vulnerability could allow an attacker to re-define app functionality via ​prototype tampering​.

**Steps To Reproduce**
1. Go to https://github.com/blockstack/stacks-wallet/blob/master/app/main.dev.js#L62-L66

```
    webPreferences: {
      // nodeIntegration: nodeIntegration,
      preload: path.join(__dirname, "preload.js")
    }
  });
```

Since `contextIsolation` is not mentioned hence it will be disabled by default.

**Expected behavior**
It should have `contextIsolation: true` 

Ref:
https://www.electronjs.org/docs/tutorial/context-isolation

**Environment (please complete the following information):**
N/A

**Comment by jcnelson** [comment]
Hi @Shashank-In, thank you for your report, but this is not the right repository.  Please re-open against https://github.com/blockstack/stacks-wallet.  Thanks!
