### ISSUE TITLE
Broken authentication and session management>>Newsletter page is on http

### ISSUE THREAD

**Issue by Sourabh666** [blockstack/stacks-blockchain#2038]
A page on a http://newsletters.blockstack.org/ is not fully protected by an SSL certificate. This could allow an attacker in a Man-in-the-Middle position to obtain usernames and passwords of users visiting the site.

Note the warning in screenshot 1, firefox has identified that this page is not protected with an SSL certificate, therefore the username and password will be sent over a plaintext connection. In itself, this may be enough to put some users off using your page.
Once submit is pressed on the login, it appears as though the request is sent over a HTTPS connection (when seen through Burp Suite or Wireshark), which suggests that the page does protect the username and password with SSL/TLS,

Steps To Reproduce:
go to http://newsletters.blockstack.org/ and setup wireshark
you can get username , password is in clear text
Mitigation
If any part of a site is required to be protected by SSL, the entire site should be protected by SSL. Ts this would stop the attack outlined above from working, as a certificate error would be displayed to the user.
HTTP Strict Transport security could be used to mitigate this attack, which would tell all browsers not to allow a HTTP connection to this website.

Supporting Material/References:
Please see the atachement of video i have given here only and screenshot down -- 
https://drive.google.com/file/d/1vAVd3t4PtxCAYFWjwLk27i32WkdyG5x9/view?usp=sharing
![Screenshot (699)](https://user-images.githubusercontent.com/74142321/98466887-549b4500-21f8-11eb-98b9-11c1a96012d3.png)

Impact
If a user were to visit this page from a public or shared network (eg, starbucks, airport, library, etc) and submit a comment, a malicious user on the same network would be able to obtain that users username and password by conducting a Man-in-the-Middle attack using sslstrip and wireshark.

This would allow the malicious user complete access to the user's account.

**Comment by jcnelson** [comment]
Hi @Sourabh666, thank you for your report, but this is not the right place for it.  Please instead submit it to https://hackerone.com/blockstack

**Comment by Sourabh666** [comment]
So sir where should I report the bug via mail or github
