### ISSUE TITLE
Cost-tracking: Limit cost-functions to arithmetic operations

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2041]
Clarity-defined cost functions must be limited to arithmetic operations, because evaluating these functions is not charged against the block limit, so we must ensure that these functions are simple and may be evaluated efficiently.

**Comment by jcnelson** [comment]
Does this include preventing access to Clarity globals, like `tx-sender`, `contract-caller`, `total-liquid-ustx`, etc.?

**Comment by kantai** [comment]
Additionally, the cost-function verification should ensure that any contract-call targets that are being intercepted (see #2042) are `define-read-only`.

**Comment by lgalabru** [comment]
@kantai can this issue be marked as closed?

**Comment by kantai** [comment]
Yep!
