### ISSUE TITLE
DB: merge Clarity side-store into its state DB, and remove savepoints

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2045]
Clarity uses a side-store database independent of its MARF'ed database.  These should really be stored to the same database, since it would remove a point of crash-consistency failure.  But in order to do this, we should remove the savepoint logic currently used to execute a block's-worth of Stacks transactions, and instead use the MARF'ed `begin`, `commit`, and `rollback` functions to instantiate, store, and abort bulk operations.

**Comment by kantai** [comment]
This is the same issue as (or rather, this is the planned fix for) https://github.com/blockstack/stacks-blockchain/issues/1939, right?

**Comment by jcnelson** [comment]
Yes; we can close #1939 in favor of this if you want.  If we do, then this issue should also be updated to reflect the need for adding WAL mode.  I think this also fixes my concerns in #1992 about concurrent RPC calls endpoint potentially mucking things up in the Clarity DB.
