### ISSUE TITLE
Using testground for large-scale testing

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2046]
Doing large-scale testing of the `stacks-blockchain` is possible using testground. A basic prototype plan is defined here:

https://github.com/kantai/stacks-blockchain-testground

It doesn't collect many metrics -- there's a couple different avenues for adding more metrics:

1. Parse the stderr logs out of the stacks-blockchain process (shouldn't be too hard, they are in JSON).
2. Have the Go process implement a EventDispatcher client to receive EventDispatcher events.

(1) is probably easier.

**Comment by wileyj** [comment]
https://github.com/blockstack/stacks-blockchain-testground/tree/development
@jcnelson @lgalabru for visibility here. 


Problem: Occasionally, running a test will fail with some of the instances failing to start stacks-node.

```
Dec 21 02:53:01.463211 INFO 463.0579s    MESSAGE << single[003] (bc4b34) >> Get "http://localhost:20443/v2/info": dial tcp 127.0.0.1:20443: connect: connection refused
Dec 21 02:53:01.589109 INFO 463.1838s    MESSAGE << single[001] (d5ea45) >> Get "http://localhost:20443/v2/info": dial tcp 127.0.0.1:20443: connect: connection refused
Dec 21 02:53:02.113005 INFO 463.7076s    MESSAGE << single[002] (9e30c1) >> Stacks block height => 1 :: Burn block height => 308
Dec 21 02:53:02.166044 INFO 463.7607s    MESSAGE << single[002] (9e30c1) >> Inbound/Outbound Neighbors => 1/1
```

It doesn't happen all of the time, and cleaning the old runs, restarting the daemon etc doesn't seem to help. 
What does seem to help (and I have no idea why) is rebooting the VM. There doesn't seem to be any difference in resources used, so it may just be coincidental. 

When this does happen, the instances running stacks-node/bitcoin etc have multiple log files I can see in `/src/net-tools/mnt`

For the failed nodes, I only see a single file `cleanup.sh`:

```
root@dd48e860bd73:/src# ls -al /src/net-test/mnt/
total 16
drwxr-xr-x 2 root root 4096 Dec 14 15:34 .
drwxr-xr-x 1 root root 4096 Dec 19 02:38 ..
-rwxr-xr-x 1 root root  237 Dec 14 15:34 cleanup.sh
```

I do see the attempt to start the stacks-node as well:
```
root        23     1  0 18:02 ?        00:00:00 bash /scripts/simple-start.sh miner 16.0.0.8 16.0.0.7
```

But so far, I haven't found any data as to why the node didn't start. 
Is there anywhere else on the filesytem that *might* contain some useful data that would point me to the reason this stacks-node isn't starting?

**Comment by wileyj** [comment]
@kantai  @jcnelson  log from `simple-start.sh` on a failed node:
```
root@ae3cb959fcea:/src/net-test/mnt# cat simple-start-miner.log 
[13] Setting up Stacks miner node (/src/net-test/etc/conf-miner.toml)...
[13]  Generating Stacks miner config file...ok
[13]  Fetching BTC from the faucet for this miner (monchQ6aejepR4H1bDq4r7Z78aycWVkAhP)...FAILED!  Try again in 2 seconds...
FAILED!  Try again in 3 seconds...
FAILED!  Try again in 3 seconds...
FAILED!  Try again in 5 seconds...
txid 94ee0e359bcbe9dec7a3ca4ff6beae075b2b2900d39ac280260b2ec59c77b739
[13]  Waiting for BTC to get confirmed....wait 2..wait 2..wait 3..wait 3..wait 3..wait 3..wait 5..wait 5..wait 5..wait 7.FAILED
[13] Running!
node failed to boot up
```

**Comment by wileyj** [comment]
[testground-logs.tar.gz](https://github.com/blockstack/stacks-blockchain/files/5731562/testground-logs.tar.gz)

BTC is not being confirmed occasionally, but the process continues to startup

**Comment by wileyj** [comment]
Noted in blockchain meeting: greater than 25 miners may overwhelm bitcoin instance when running test. 
Most i've run currently is 10 instances (with 2 of them never fully started). Code has been updated in https://github.com/blockstack/stacks-blockchain-testground to handle nodes that never fully start. 

Next step is to setup a test with > 25 instances, as well as look at the `checkchainquality` test in `net-test` dir

**Comment by wileyj** [comment]
Testing the inclusion of the check_chain_quality function from blockchain meeting 12/28:
https://github.com/blockstack/stacks-blockchain-testground/blob/development/go/stacks-node-functions.go#L114

will setup test for > 25 nodes shortly

**Comment by wileyj** [comment]
@psq -  you had mentioned something about a potential problem with btc node when there are more than 25 miners in blockchain meeting the other day. 

I ran a test with 30 nodes last night to a height of 150, and I have a lot of data from that test - is there anything I can look for specifically? the size of the data (including miner logs) is far too large to share here, but i can share some specific logs if you'd like

**Comment by wileyj** [comment]
So far the k8s setup for testground is being problematic (as in won't launch) - their docs are several months out of date for the repo they have : https://github.com/testground/infra
Their docs repo: https://github.com/testground/docs/tree/master/runner-library/cluster-k8s

Incidentally, the AMI they define to use in that repo simply doesn't exist and there is not a way to file an issue, only a PR. 
I'm working though it, but until i can get this process ironed out the only viable way to test is on a single, large VM.

**Comment by wileyj** [comment]
it's running in k8s, initial tests are proceeding (2 instances to a height of 10):
```
Jan  6 21:52:19.102961	INFO	pushed image for group	{"runner": "cluster:k8s", "run_id": "bvr31otnf4qajmq6dvu0", "group_id": "single", "tag": "820587342274.dkr.ecr.us-west-2.amazonaws.com/testground-us-west-2-stacks-node:d0fac94efabc"}
Jan  6 21:52:19.103054	INFO	pushing of images finished	{"runner": "cluster:k8s", "run_id": "bvr31otnf4qajmq6dvu0", "took": "4s"}
Jan  6 21:52:19.224437	INFO	deploying testground testplan run on k8s	{"runner": "cluster:k8s", "run_id": "bvr31otnf4qajmq6dvu0", "job-name": "tg-stacks-node"}
Jan  6 21:52:46.280524	INFO	all testplan instances in `Running` state	{"runner": "cluster:k8s", "run_id": "bvr31otnf4qajmq6dvu0", "took": "26s"}
...
```

seeing some additional errors in the logs, but they should be able to be fixed:
```
{"ts":1609970197740780637,"msg":"","group_id":"single","run_id":"bvr31otnf4qajmq6dvu0","event":{"message_event":{"message":"influxdb: failed to upload 128 points; err: All attempts fail:\n#1: {\"error\":\"database not found: \\\"testground\\\"\"}\n\n#2: {\"error\":\"database not found: \\\"testground\\\"\"}\n\n#3: {\"error\":\"database not found: \\\"testground\\\"\"}\n\n#4: {\"error\":\"database not found: \\\"testground\\\"\"}\n\n#5: {\"error\":\"database not found: \\\"testground\\\"\"}\n"}}}
```

The downside is that I had to make some changes to the  https://github.com/testground/infra repo to get this working - mainly to create the AMI that doesn't exist in their account (future commits on their end may fix this, but no way to create an issue about it)

**Comment by wileyj** [comment]
Going to need some adjustments to run this in k8s as well. 
stacks-node died, but it's unclear as to why - it could be not enough resources, incorrect networking, or require some code changes in the plan. I'll also need to update the testground image with recent updates to the repo

```
{"ts":1609970771632824263,"msg":"","group_id":"single","run_id":"bvr31otnf4qajmq6dvu0","event":{"message_event":{"message":"Waiting for node: [Get \"http://localhost:20443/v2/info\": dial tcp 127.0.0.1:20443: connect: connection refused]"}}}
```

```
root@tg-stacks-node-bvr31otnf4qajmq6dvu0-single-1:/src/net-test/mnt# tail simple-start.log 
[11] Starting bitcoind controller...PID 58
[11] Setting up bitcoin faucet...
[11]  Importing faucet private key...ok
[11]  Importing miner address mmNe3BjtYa8ZWtpQxfpsE8aWKgHh77LYTT...ok
[11] Starting bitcoin faucet...PID 76
[11] Setting up Stacks master node...
[11]  Generating Stacks master config file...ok
[11] Starting Stacks master node...PID 321
[11] Running!
node failed to boot up
```

`root         321       1  6 21:53 ?        00:00:52 [stacks-node] <defunct>`

**Comment by wileyj** [comment]
We are now able to test in k8s; i've been slowing ramping up the test instances/block_height parameters and tracking the results. 
One thing to note is the performance is roughly 25% slower than on a standalone VM, so we do have more instances failing to boot up (due to timeouts to BTC faucet. this can be addressed). 

there are several manual steps involved to get the cluster in a state that's required to run a test (all documented). 

so far, i've only been testing using a locally running daemon - there is a way to have the daemon run *in* the cluster, but i haven't tried that method as of yet (it may increase the performance since everything would be running locally). 

will have a push shortly for https://github.com/blockstack/stacks-blockchain-testground
