### ISSUE TITLE
Can't run stacks 1.0 testnet node through test scenarios docker script

### ISSUE THREAD

**Issue by hozzjss** [blockstack/stacks-blockchain#2048]
**Describe the bug**
I'm trying to run a stacks 1.0 testnet node and it runs for a while and then unexpectedly fails, I use this command to run the docker image

```
IMAGE=$(docker run -dt -p 16264:16264 -p 30001:30001 -p 3001:3001 -p 16268:16268 -p 16269:16269 -p 18332:18332 -e BLOCKSTACK_TEST_CLIENT_RPC_PORT=16268 -e BLOCKSTACK_TEST_CLIENT_BIND=0.0.0.0 -e BLOCKSTACK_TEST_BITCOIND_ALLOWIP=172.17.0.0/16 quay.io/blockstack/integrationtests:master blockstack-test-scenario --interactive-web 3001 blockstack_integration_tests.scenarios.testnet_public)
```

**Steps To Reproduce**
It is quite random and I don't really know what makes it fail, but what I would do is I would run the command and try many operations on namespaces, names, and subdomains, through blockstack-cli

**Expected behavior**
It is expected to stay running normally

**Environment:**
 - OS: Ubuntu 20.04
 - Rust version: this is the python stacks node
 - Version of the appropriate binary / software package: quay.io/blockstack/integrationtests:master

**Comment by jcnelson** [comment]
With the launch of Stacks 2.0 mainnet, Stacks 1.0 is now EOL and no longer supported anywhere.  Going to go ahead and close this.
