### ISSUE TITLE
Circular reference error on nested function invocation

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#2053]
**Describe the bug**

In Clarity, nested calls to custom function fails with an unexpected _circular reference_ error.

**Steps To Reproduce**

Evaluate in the [Clarity REPL](https://lgalabru.github.io/clarity-repl/):

```clojure
(define-read-only (identity (n int)) n)
(begin (identity (identity 1)))
```
=>
`Runtime Error: Unchecked(CircularReference(["S1G2081040G2081040G2081040G208105NK8PE5.snippet-0:identity"]))`

**Expected behavior**

Should evaluate to the original value.

**Environment (please complete the following information):**

[Clarity REPL](https://lgalabru.github.io/clarity-repl/):

**Additional context**

Possibly due to inconsistent invocation of custom functions.

**Comment by kantai** [comment]
Closed by #2074
