### ISSUE TITLE
v2/transactions returns string in quotes

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2057]
**Describe the bug**
The v2/transactions endpoint returns the txid in quotes

**Steps To Reproduce**
1. Use the testnet explorer
1. make a transaction
1. look at the response of the transaction

**Expected behavior**
return plain text string e.g. `e161978626f216b2141b156ade10501207ae535fa365a13ef5d7a7c9310a09f2` instead of `"e161978626f216b2141b156ade10501207ae535fa365a13ef5d7a7c9310a09f2"`

**Additional context**
stacks.js uses `JSON.parse(response)` 
https://github.com/blockstack/blockstack.js/blob/ba2243ee7944780b79b1e22c12778ffd0f0bc388/packages/transactions/src/builders.ts#L199

**Comment by kantai** [comment]
I think a string quoted value is the right output here-- this endpoint accepts JSON and returns JSON. A quoted string is valid JSON, while an unquoted one would not be.
