### ISSUE TITLE
POX - stack-stx contact call issue

### ISSUE THREAD

**Issue by talhasch** [blockstack/stacks-blockchain#2062]
**Describe the bug**
[stack-stx](https://docs.blockstack.org/references/stacking-contract#stack-stx) contact call can't get confirmed on the blockchain with the way described in official docs.

I tried with different `start-burn-ht` values such as current burn_block_height, burn_block_height +1, +3, +10, +100, +1000, first burn_block_height of next cycle, last burn_block_height of next cycle... but the chain keeps rejecting calls with error code 24 `ERR_INVALID_START_BURN_HEIGHT`. 

**Steps To Reproduce**
Can be reproduced with trying stack-stx call like documented here: https://docs.blockstack.org/stacks-blockchain/integrate-stacking#step-5-add-stacking-action

**Expected behavior**
It should work as documented.

**Environment (please complete the following information):**
On my local environment (macos) using `@blockstack/`, `@stacks/` javascript libraries. 

**Additional context**
Rejection time can take up to 4-5 hours. Sometimes transaction get inaccessible (get lost somehow) in a couple minutes right after contract call. Can't access with blockchain explorer or stacks api.

**Comment by timstackblock** [comment]
I think this may be a document issue

**Comment by talhasch** [comment]
@timstackblock any hint for correct usage?

**Comment by kyranjamie** [comment]
@talhasch check out @yknl's client https://github.com/blockstack/stacks.js/pull/850, might act as a good example to follow

**Comment by talhasch** [comment]
@kyranjamie i have tried with very similar code with that many times. my transactions ended up with `ERR_INVALID_START_BURN_HEIGHT` error every time like i described above. i think the key point is start-burn-ht value determination. what should it be? current burn block height + ?

**Comment by kyranjamie** [comment]
I don't believe it's plus anything, here's the code being used in the wallet https://github.com/blockstack/stacks-wallet/blob/release/stacking/app/utils/stacking/pox.ts#L144-L157

**Comment by talhasch** [comment]
Created this stack-stx contract call almost 1 hour ago. Still pending. (probably will end up with ERR_INVALID_START_BURN_HEIGHT) https://stacks-node-api.blockstack.org/extended/v1/tx/0xafeaf2ddbeb8ab8c329ff051253e63d49e500dd0f53f153c16758a44d1ad8e9b

<img width="1435" alt="Ekran Resmi 2020-11-25 21 14 55" src="https://user-images.githubusercontent.com/1177676/100266748-605e6980-2f63-11eb-8fa3-d68f55c49f02.png">

Do you see anything wrong with it? (besides amount-ustx. couldn't get enough from faucet.)

**Comment by talhasch** [comment]
After hours, ended up with error 24 `ERR_INVALID_START_BURN_HEIGHT` as i expected.

<img width="1424" alt="Ekran Resmi 2020-11-26 09 05 21" src="https://user-images.githubusercontent.com/1177676/100314022-c92afd80-2fc6-11eb-84a7-ca876cabf72b.png">

**Comment by fintechrecruiters** [comment]
@pradel Can you take a look at Talha’s original issue and determine what might be the problem? Any insight is greatly appreciated. Thanks in advance

**Comment by pradel** [comment]
@talhasch When integrating in my mobile app I am doing height + 1 and never got a rejected transaction. https://github.com/pradel/blockstack-wallet/blob/master/src/screens/StackingConfirm.tsx#L229

**Comment by talhasch** [comment]
@pradel i don't get rejection during contract call too. transactions i sent to blockchain gets rejected after a while. did you track any of your pox contract call transaction? did they get confirmed on blockchain?

**Comment by pradel** [comment]
@talhasch yes they were all confirmed

**Comment by lgalabru** [comment]
Looking at the launch of PoX on Mainnet + ability to build tooling around PoX (wallet, exchanges, etc), I think we can assume that this issue is now behind us. Will close.
