### ISSUE TITLE
Decrease number of side forks to help miner profitability

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#2078]
As it stands, miners still mine too many blocks off of older blocks than the latest block mined by the network, most likely because they haven't received that block yet.

This will yield to a loss of the block reward for this miner for this block, as it won't be on the canonical fork (longest chain), so its coinbase will not be available.  Which would make estimating miner profitability even more complex, and possibly discourage some miners because they lost money.

I'm not sure whether aiming for no side forks is achievable (assuming no bad intent), but at least we should aim for a better outcome that we currently have: less than 1 such block per day (about 144 blocks) might be reasonable, less would be better.

**Comment by diwakergupta** [comment]
@psq was there a specific change or suggestion you had in mind? My expectation is that in the happy path, correct & honest nodes build a chain with minimal forks: if that's not the case, we need to first identify some actionable changes.

**Comment by psq** [comment]
@diwakergupta nothing specific, just that we are not there yet, and there may be more than one fix needed.  This is more a placeholder/reminder as @jcnelson requested Monday during the meeting and that this needs to be improved to reach mainnet.  An other way to measure success would be to have the the stacks chain height advance roughly at the same rate as the btc chain.

**Comment by diwakergupta** [comment]
This is not super-actionable as worded. All known issue are already tracked: mostly #1805, #2272 , #2280 , #2281 . I suggest closing this out unless there's something specific not covered in the other issues.

Does that work @psq ?

**Comment by zone117x** [comment]
I'm in favor of keeping an explicit issue open for this.

**Comment by jcnelson** [comment]
The chain quality has been improving as of late with newer miner enhancements in 2.0.3, but one thing we might want to look at more is having nodes store blocks and microblocks for more than 1 additional burnchain block height (maybe 2 or 3?).

I agree with @zone117x  -- we should pick a threshold at which we can "declare victory" on this issue.

**Comment by jcnelson** [comment]
Going to go ahead and close this issue in favor of a metrics-based issue.  For example, we should have the node track how many blocks are on the same fork, and raise a warning if not.
