### ISSUE TITLE
Testnet-explorer Clarity Sandbox and Clarity tools cannot deploy contracts because of lack of postconditions

### ISSUE THREAD

**Issue by paradigma-cl** [blockstack/stacks-blockchain#2091]
**Describe the bug**
The examples provided in the tools to test and develop Clarity smart-contracts in https://testnet-explorer.blockstack.org/sandbox and Clarity.tools do not have a way to define postconditions and they do not have any define.  But when executed the Stacks blockchain says that the contract could not be deployed because of the defined postconditions

**Steps To Reproduce**
For example in https://testnet-explorer.blockstack.org/sandbox when trying to deploy any of the provided example contracts having the required fees, then the stacks blockchain receives the order to deploy but returns a message after the PoX process it saying that it has not complied with the postconditions, but the contract does not have postconditions.

**Expected behavior**
It should deploy the contract, or it should request the postconditions  or the UI does not allow it
.
Reading the discussions, it looks like that some postconditions have been put as deny the transaction.
The problem is that if we want to facilitate the use and development of Clarity smart contracts, both tools the Sandbox and Clarity tools are very useful for it.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu / Debian] Webbased
 - Rust version
 - Version of the appropriate binary / software package

**Additional context**
Please include any relevant stack traces, error messages and logs.
![poscondition](https://user-images.githubusercontent.com/32182666/100029438-08dbc480-2dd0-11eb-9429-2e7fdcc100d2.PNG)
![postcondition_2](https://user-images.githubusercontent.com/32182666/100029441-0ed1a580-2dd0-11eb-8a8a-07873ff96f6a.PNG)

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

**Comment by diwakergupta** [comment]
clarity.tools is not a project maintained or operated under the blockstack github org

Lack of post-conditions in explorer/sandbox sound more like a feature request than a bug. @paradigma-cl I suggest opening issues in the explorer repo as appropriate, cc/ @agraebe @aulneau 

Closing as there's no bug report for stacks-blockchain in this issue.
