### ISSUE TITLE
Refactoring: ChainsCoordinator + PoxSyncWatchdog

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#2095]
With https://github.com/blockstack/stacks-blockchain/pull/2073, the initializing ChainsState was pulled from the ChainsCoordinator, to avoid a race condition, and resolve https://github.com/blockstack/stacks-blockchain/issues/2066.
It turns out we'd like to restore the previous relationship, so we'll look into another approach once we're done with the consensus critical.

Similarly, per @kantai,

> I think there's a little confusion here with line 216 -- burnchain.wait_for_sortitions(), which will try to wait until the sortition db has caught up with the burnchain tip, and then the activity of the pox sync watchdog, which also does some initial synchronization between the burnchain tip and the sortition db.
I'm not sure what the best way to clean that up is -- the pox sync watchdog should probably be in charge of handling this, but I think if we just blindly removed the burnchain.wait_for_sortitions() call, the neon_node would probably receive way more events during start up than it currently does (the block_height variable is used to ignore sending "mine block" directives before the first tip).

We probably should be revisiting the watchdog.

**Comment by jcnelson** [comment]
Superseded by #2724
