### ISSUE TITLE
[TESTNET BUG] block_txs_payload unwraps Clarity response object

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2097]
## Describe the bug

The following contract defines a fungible token. It was deployed and a transfer call failed because the user didn't own the asset. However, the transaction result is shown as `(err u1)` instead of `(ok (err u1))`
```
(define-constant owner 'ST3X2W2SH9XQZRHHYJ21KWGTT1N6WX3D48K1NSTPE)
(define-fungible-token connect-token)
(begin (ft-mint? connect-token u100000000 owner))
(define-public (transfer (recipient principal) (amount uint))
  (ok (ft-transfer? connect-token amount tx-sender recipient)))
```

## Steps To Reproduce
1. setup mocknet and stacks-node-api
1. deploy contract to mocknet
1. send transfer tx with post condition
1. use tx id to find tx on stacks-node-api
1. see tx_result is equal to `(err u1)`

## Expected behavior

The tx_result should be `(ok (err u1))`

## Example (25 Nov 2020)
contract:
https://stacks-node-api.blockstack.org/extended/v1/tx/0x312cb2ba8c91183a57e02a2928b325ed18753d0043c50da7dd4ad2aa0675f1b6

transfer tx:
https://stacks-node-api.blockstack.org/extended/v1/tx/0x731b5ba5af6b07bea60a0f5d8552555794955dc41350e47c46d745264b22959f

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [x] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by kantai** [comment]
This looks like an issue in the event dispatcher -- it currently "unwraps" the function response, and returns that as the contract-call result to event listeners (in this case, the stacks-node-api):

```rust
...
        let (success, result) = match (receipt.post_condition_aborted, &receipt.result) {
            (false, Value::Response(response_data)) => {
                let status = if response_data.committed {
                    STATUS_RESP_TRUE
                } else {
                    STATUS_RESP_NOT_COMMITTED
                };
                (status, response_data.data.clone())
            }
            (true, Value::Response(response_data)) => {
                (STATUS_RESP_POST_CONDITION, response_data.data.clone())
            }
            _ => unreachable!(), // Transaction results should always be a Value::Response type
        };
...
```

This isn't consensus breaking, but it may potentially be a breaking change for stacks-node-api.
