### ISSUE TITLE
[Stacks v1 → v2 Upgrade] Map placeholder addresses

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#2106]
We are expecting to have proper addresses for all placeholders from the Stacks 1.0 balance & vesting dataset. All but a couple addresses are now accounted for. 

Translating these entries should be done in either the export (Stacks 1.0 codebase) or import (Stacks 2.0 codebase) step. The export step makes the most sense to me. 

@kantai @jcnelson thoughts?

**Comment by kantai** [comment]
I agree -- doing this during the export step makes the most sense to me.

**Comment by jcnelson** [comment]
If we do it during the export step, can you document in the code where the replacement is happening, and with what values?  Maybe also provide a link to where anyone who's auditing the transition can get confirmation that this is the "right" address?

**Comment by zone117x** [comment]
Note there is already a PR for this issue https://github.com/blockstack/stacks-blockchain/pull/2111

**Comment by zone117x** [comment]
Completed with https://github.com/blockstack/stacks-blockchain/pull/2191
