### ISSUE TITLE
ChainsCoordinator/Burnchain integration breaks during Bitcoin forks

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2108]
Bitcoin forks can lead the integration between the `ChainsCoordinator` and the `Burnchain::sync_with_indexer` to break -- in particular:

1. The ChainsCoordinator attempts to process a new burnchain fork by finding the first ancestor in the current sortition fork that is in common (see: https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/coordinator/mod.rs#L481)
2. During the processing of the burn block, the chains coordinator updates the current canonical sortition fork _only if_ the newly processing burn block's height is greater than the current canonical sortition.
3. The `Burnchain::sync_with_indexer` polls the coordinator to process new burn blocks _as they are processed_.

This, together, means that if for example, the following fork occurred:

```
A -> B -> C -> D
         \__> C' -> D' -> E'
```

With block arrivals like `A, B, C, D, C', D', E'`, then the chains coordinator would process A-> D, setting the canonical chain tip to `D`, then `C'` would be correctly processed, but when the coordinator is polled to process `D'`, the canonical chain tip is _still_ `D`, so the coordinator will attempt to process `C'` _again_. This causes the chains coordinator to abort (because it will eventually fail a SQLite uniqueness constraint when trying to insert `C'` a second time).

I believe the best way to address this is by making the ChainsCoordinator check the block height of the "canonical" burnchain tip before processing sortitions, and ensuring that the height is greater than its view of the canonical tip.

**Comment by CharlieC3** [comment]
The Xenon mining (running `v24.0.0.0-xenon`) crashed today around `12 Dec 2020 13:58:42 -0500` with the following error log. We believe it was caused by this issue described above.

Read from bottom going up
```
Dec 12, 2020 @ 13:58:39.902    Error processing new burn block: FailedToProcessSortition(DBError(IndexError(ExistsError)))

Dec 12, 2020 @ 13:58:39.901    Max arrival for child of 0d159480beaa5f1dff9ab2eba28cf82bbf58fc47 (burn 000000000000001c06b4979aa41971ac11e77337b3cc85fa92741a4ce9834ea5) is 1258

Dec 12, 2020 @ 13:58:39.901    TRANSACTION ABORTED when snapshotting block 1897317 (000000000000177e016e0dbc9a7c8e0f4d1de6f45d4a01e70421191ea44831a4): DBError(IndexError(ExistsError))

Dec 12, 2020 @ 13:58:39.901    Block data already exists: ce7c076f12da229b938adc4f17fce16b6c611264c657e844d50e8362756c5fba

Dec 12, 2020 @ 13:58:39.901    New Stacks anchored block arrived since 000000000000001c06b4979aa41971ac11e77337b3cc85fa92741a4ce9834ea5: block 1247 (d7f482f2ab4f1fee37b4a785ea3a5ae3846e22fed9948073660032da6f113498) ari=1258 tip=000000000000001c06b4979aa41971ac11e77337b3cc85fa92741a4ce9834ea5

Dec 12, 2020 @ 13:58:39.901    ChainsCoordinator: unable to evaluate sortition DBError(IndexError(ExistsError))

```
