### ISSUE TITLE
Support STX transfer via Bitcoin operations

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2118]
Similar to our support for invoking `stack-stx` via on-Bitcoin operations, we should support STX transfers. This would allow users to submit STX transfers via broadcasting Bitcoin operations (similar to how Stacks 1.0 transfers work). These operations would be constrained in the same manner as the on-Bitcoin `stack-stx` operation:

* The operation must consume a "known good" UTXO -- we can reuse the PreStackStx op for this, but will rename to something like PreStxOp
* Operations are included in _only_ the Stacks block elected following the burn block that includes the STX transfer. This means that the operations _are not_ "resistant" to forks in the Stacks blockchain: if the block that includes the STX transfer is "forked" away from, the operation isn't re-included in "nephew" blocks.

**Comment by friedger** [comment]
With the property of not being fork resistant what is the use case?

**Comment by kantai** [comment]
The most immediate benefits are:

1. It is more resistant to miner transaction censorship -- miners would need to be able to successfully initiate a fork in order to censor the transaction.
1. Wallets that only support Bitcoin operations would still be able to submit transfers (this maintains a kind of feature parity for transfers with Stacks 1.0).

**Comment by kantai** [comment]
Closed via #2129
