### ISSUE TITLE
Eliminate the Clarity AST Definition Sorter?

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#2123]
The [definition sorter](https://github.com/blockstack/stacks-blockchain/blob/master/src/vm/ast/definition_sorter/mod.rs) of the Clarity AST is an **error-prone module of about 500 LOC** that sorts top-level expressions in dependency order. It can potentially be eliminated by instead making multiple passes when evaluating top level expressions.

A recently discovered error in the definition sorter involved a [failure in dependency cycle detection](https://github.com/blockstack/stacks-blockchain/pull/2115/commits/f00c4f2e161ac94cadc671671f1a1cabbbb2fd99). Past issues with the definition sorter include #1292 and #1625.
 
The definition sorter implements custom processing for Clarity syntactic forms containing one or more symbols that are not supposed to be evaluated. This requirement stems from Clarity's syntax not distinguishing between keywords and symbols that evaluate to a value; Other Lisp dialects typically quotes symbols that aren't supposed to be evaluated, which simplifies such tree-walking of the code. As a consequence, making changes to these syntactic form (or introducing new ones) will typically require updating the definition sorter, which may turn into technical debt by making it harder to introduce desired improvements without breaking the implementation.

A simpler alternative is to make multiple passes when [evaluating top level expressions](https://github.com/blockstack/stacks-blockchain/blob/57953c0ac749c797c5a2cf8bf10c6ed8f6ed212b/src/vm/mod.rs#L234), as in: 

1. Register all top level definitions 
2. Calculate costs 
3. Evaluate other top-level expressions

The [traits resolver] also seems to depend on sorted definitions, which also can be resolved by making multiple passes. Alternatively, the definition sorter could be replaced by an AST step that simply registers top level definitions for random access.

**Comment by jcnelson** [comment]
The consensus from today's blockchain meeting is that while we'd welcome a PR that does this, implementing this is not a high priority for Stacks 2.0.

**Comment by njordhov** [comment]
Good you got a chance to consider this refactoring proposal. A cause for the code smell is that the definition sorter is run early in AST code translation, yet requires semantic knowledge of Clarity's syntactic constructs.

https://github.com/blockstack/stacks-blockchain/blob/ecd16f1200eceae84bd1d71ca4d0688356de8989/src/vm/ast/mod.rs#L60-L67

**Comment by njordhov** [comment]
PS: Does the Definition Sorter really have to process `len` as a special case?

https://github.com/blockstack/stacks-blockchain/blob/ecd16f1200eceae84bd1d71ca4d0688356de8989/src/vm/ast/definition_sorter/mod.rs#L259-L265

**Comment by njordhov** [comment]
Is the handling of `contract-call` in the Definition Sorter up to par with [dynamic dispatch](https://docs.blockstack.org/references/language-overview#dynamic-dispatch) where the callee is passed as an argument? 

https://github.com/blockstack/stacks-blockchain/blob/ecd16f1200eceae84bd1d71ca4d0688356de8989/src/vm/ast/definition_sorter/mod.rs#L235-L243

**Comment by njordhov** [comment]
Should `define-fungible-token` really be ignored in dependency sorting?

https://github.com/blockstack/stacks-blockchain/blob/ecd16f1200eceae84bd1d71ca4d0688356de8989/src/vm/ast/definition_sorter/mod.rs#L202-L203

As a consequence, the supply argument cannot depend on a later defined function, resulting in a _Analysis error: use of unresolved function 'supply'_ error:

```clojure
(define-fungible-token limited-supply-stacks (supply))
(define-read-only (supply) u100)
```

**Comment by diwakergupta** [comment]
@njordhov thanks for the feedback -- we'd very much welcome a PR if you feel strongly enough to take a crack at this! 🙏🏽 

In a similar vein, you're welcome to join the weekly public engineering call for the Stacks Blockchain (Mondays 11am ET) to participate in a more interactive discussion with various stake-holders.

**Comment by njordhov** [comment]
@timstackblock About the labels - this is not a _feature_ as no new functionality is added. It is more of a _chore_, reducing _technical debt_. Maybe there should be a label for _refactor(ing)._

**Comment by jcnelson** [comment]
Now that mainnet has launched, I don't think this issue can be addressed without a hard fork.  Going to go ahead and close it.

**Comment by njordhov** [comment]
> Now that mainnet has launched, I don't think this issue can be addressed without a hard fork. Going to go ahead and close it.

Sure that's a good decision?
