### ISSUE TITLE
VM: Expanded token type methods

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2125]
The fungible and non-fungible token types currently do not have enough expressive power to allow fungible token supplies to be adjusted or queried, nor do they allow non-fungible tokens to be destroyed or re-created.  After talking with the community, it's clear that our token types need these properties in order to implement real-world projects safely.  To address this, the VM will need the following new built-ins for tokens:

* `(ft-get-supply (token-name (string-ascii 256)))) ;; returns (option uint)`:  This method should take the name of the fungible token and return how many units of that token are in circulation.  It should return `none` if the token is not defined.  This function should work for all fungible tokens, even those that don't have a fixed maximum supply.

* `(ft-burn? (token-name (string-ascii 256)) (amount uint) (sender principal)) ;; returns (response bool uint)`: This method works like `ft-transfer?`, but it _destroys_ the `amount` of tokens given.  This causes the total circulating supply of the token to decrease, which will be reflected in a subsequent call to `ft-get-supply`.  Like `ft-transfer?`, it returns `(err u1)` if the `sender` doesn't have `amount` tokens to burn, and returns `(err u3)` if `amount` is non-positive.  Returns `(ok true)` on success.

* `(nft-burn? (asset-class (string-ascii 256)) (asset-identifier T) (sender principal)) ;; returns (response bool uint)`:  This method works like `nft-transfer?`, but it _destroys_ the asset identified by `asset-identifier`.  This allows a subsequent call to `nft-mint?` with the same `asset-class` and `asset-identifier` to succeed in re-creating the asset.  Like `nft-transfer?`, it returns `(err u1)` if `sender` doesn't own the asset, and `(err u3)` if the asset identified with `asset-class` and `asset-identifier` does not exist.  Returns `(ok true)` on success.

Like transfers, we'll want to make it so these methods keep track of tokens moved through a transaction's `AssetMap`, so post-conditions can still enforce safe token burns.

**Comment by friedger** [comment]
To solve expiring or shared ownership of tokens, there needs to be another function, e.g. to address expired BNS names (https://github.com/blockstack/stacks-blockchain/pull/2013#discussion_r532512302)

**Comment by psq** [comment]
even though I haven't revised the `flexr` implementation with these in mind, it seems that having a `burn` and `mint` function as specified above would make it possible to use an `ft-token` by minting or burning tokens to account for past rebases.

Creating the necessary post conditions will probably require and extra function that apps can call prior to do any balance adjustment (transfer in/out).  This is because rebasing does not apply to all owners (not practical), only to the total supply, so the `ft-balance` and the actual balance will differ till it can be adjusted.  The `ft-balance` will match after such an operation, and will start differing again once a rebase happens (to be adjusted again next time the owner makes an operation)

**Comment by jcnelson** [comment]
> To solve expiring or shared ownership of tokens, there needs to be another function, e.g. to address expired BNS names (#2013 (comment))

@friedger I commented in the linked issue with some more details, but it's worth repeating here that `ft-transfer?` and `nft-transfer?` currently do _not_ require that the `sender` argument be equal to `tx-sender`.  This is only required for `stx-transfer?` and `stx-burn?`.

> Creating the necessary post conditions will probably require and extra function that apps can call prior to do any balance adjustment (transfer in/out). This is because rebasing does not apply to all owners (not practical), only to the total supply, so the ft-balance and the actual balance will differ till it can be adjusted. The ft-balance will match after such an operation, and will start differing again once a rebase happens (to be adjusted again next time the owner makes an operation)

Like the other `ft-*` functions, the `ft-balance` function would only be callable within the same contract that declares the token.  This is intentional -- it makes it so that with a hypothetical SRC-20 standard, a token contract would have a dedicated `get-balance` function that can show users whatever their balance _ought_ to be, after upcoming adjustments are taken into account (like rebases).  It's still worthwhile to represent the user's tokens via the native Clarity token type, however, since users can still use the `TransactionPostConditionMode::Deny` flag to prevent a `ContractCall` or `SmartContract` transaction from moving unrelated assets (in addition, a contract that shows a different balance than what `ft-balance` provides can also provide a method to wallets to tell them what post-condition value to supply for limiting the user's token movements).

**Comment by lgalabru** [comment]
Addressed with Clarity: additional token functions #2164
