### ISSUE TITLE
Mint genesis vesting tokens on the fly

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#2139]
In https://github.com/blockstack/stacks-blockchain/pull/2105, we allocate the entire eventual unlocked STX to the vesting contract. This creates difficulties with the PoX minimum lock-up amounts.

Rather than allocating at once, new STX should be minted on the fly as needed during unlock processing.

> I think we should be minting the locked tokens on-the-fly, by intercepting calls to the `lockup` contract and doing the minting there (much like how we have special-case logic for PoX token locks/unlocks).

_Originally posted by @jcnelson in https://github.com/blockstack/stacks-blockchain/pull/2105#discussion_r538022804_

**Comment by kantai** [comment]
This is being handled as part of #2109, right?

**Comment by lgalabru** [comment]
@kantai yep

**Comment by zone117x** [comment]
Closed with https://github.com/blockstack/stacks-blockchain/pull/2109
