### ISSUE TITLE
Transaction fees should be credited to miners as part of their block reward

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#2154]
unless I missed a commit, miners should be getting 40% of their block's transaction fees, and 60% of the previous block transaction fees (per SIP-001) on top of the coinbase reward.

Currently, the fees are subtracted from the transaction senders, but not credited to anyone, which is essentially a burn.

**Comment by lgalabru** [comment]
This issue was addressed with https://github.com/blockstack/stacks-blockchain/pull/2180.
Closing now
