### ISSUE TITLE
PoX: reward cycle must be proof-of-burn only, and should be shorter

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2157]
Per #1805, we need to make it so a PoX prepare phase is always PoB.  This is the consensus-critical portion of the solution to #1805.  In addition, we'll also make it so that the prepare phase is shorter (100 blocks instead of 240).  So, the todo's here are:

- [ ] Make the prepare phase 100 blocks
- [ ] Make the prepare phase PoB-only, and reset the mining smoothing parameter to 0 (#2141) so evaluating prepare-phase sortitions does not require any Stacks chain state
- [ ] Update SIP-007 to describe the above.

**Comment by lgalabru** [comment]
I think this issue was addressed with https://github.com/blockstack/stacks-blockchain/pull/2161, can we close @jcnelson ?

**Comment by jcnelson** [comment]
Yup!
