### ISSUE TITLE
NAME_PREORDER should pay the namespace owner but the STX get burned instead

### ISSUE THREAD

**Issue by MarvinJanssen** [blockstack/stacks-blockchain#2160]
Per the comment here:
https://github.com/blockstack/stacks-blockchain/blob/2c190869dc081b806de505675e22821c49038f4f/src/chainstate/stacks/boot/bns.clar#L500

But the registration fee is never sent to the namespace owner:
https://github.com/blockstack/stacks-blockchain/blob/2c190869dc081b806de505675e22821c49038f4f/src/chainstate/stacks/boot/bns.clar#L519

**Comment by lgalabru** [comment]
Hi @MarvinJanssen, thank you for opening this issue.
To clarify, the comment is off, the initial spec was that funds should be burnt.
That being said, we talked about this issue during a blockchain meeting, and I think we're open to update this behaviour.
cc @jcnelson @kantai.

**Comment by lgalabru** [comment]
Addressed with #2304
