### ISSUE TITLE
[TESTNET BUG]krypton mining node is stopped in local ubuntu, restart node seems issue is gone

### ISSUE THREAD

**Issue by michaeljiflorida08** [blockstack/stacks-blockchain#2162]
## Describe the bug

During krypton mining testing, krypton mining node is stopped in local ubuntu on 2020-12-12, restart node seems issue is gone; 

the running node is on release binary, so, the debugging logging might missing; the local ubuntu is not enabled apport, so, doesn't get dumping either;

## Steps To Reproduce

git clone https://github.com/blockstack/stacks-blockchain.git; cd stacks-blockchain

cargo build --workspace --release --bin stacks-node
target/release/stacks-node xenon

target/release/stacks-node start --config=./krypton.toml

## Expected behavior

krypton mining node should continuously running smoothly without stopping

## Environment

 - OS: NAME="Ubuntu" VERSION="20.04.1 LTS (Focal Fossa)"

 - Rust version: rustc 1.48.0 (7eac88abb 2020-11-16)
 - Output of `stacks-node version`: stacks-node 0.1.0 => 23.0.0.0 (master:1ad60a216, release build, linux [x86_64])

- git rev-parse --short HEAD 68958ae3a

## Additional context

krypton.toml

[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "047435c194e9b01b3d7f7a2802d6684a3af68d05bbf4ec8f17021980d777691f1d51651f7f1d566532c804da506c117bbf79ad62eea81213ba58f8808b4d9504ad@xenon.blockstack.org:20444"
# Enter your private key here!
seed = "XXX"
miner = true

[burnchain]
chain = "bitcoin"
mode = "krypton"
peer_host = "bitcoind.krypton.blockstack.org"
rpc_port = 18443
peer_port = 18444

[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
[[mstx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
[[mstx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000
[[mstx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000

The following error logging is shown on the ubuntu terminal, happened at 2020-12-12:

INFO [1607799417.241435] [testnet/stacks-node/src/neon_node.rs:800] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1607799419.330842] [src/net/p2p.rs:517] [ThreadId(5)] No open socket for 497
INFO [1607799432.768129] [testnet/stacks-node/src/neon_node.rs:800] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1607799448.296563] [testnet/stacks-node/src/neon_node.rs:800] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1607799463.831323] [testnet/stacks-node/src/neon_node.rs:800] [ThreadId(1)] Sleeping 5000 before issuing tenure
WARN [1607799479.172527] [src/burnchains/burnchain.rs:910] [ThreadId(1)] Burnchain reorg detected: highest common ancestor at height 1897316
WARN [1607799479.172561] [src/burnchains/burnchain.rs:1176] [ThreadId(1)] Dropping headers higher than 1897316 due to burnchain reorg
INFO [1607799479.638692] [src/burnchains/burnchain.rs:1237] [ThreadId(1)] Node will fetch burnchain blocks 1897316-1897317...
INFO [1607799479.805371] [src/chainstate/burn/db/sortdb.rs:3117] [ThreadId(3)] ACCEPTED(1897317) leader block commit c4d9db8f229e448f0a2d2d7607274b7d3911742b0e3153523a3e3aab8b4da8ec at 1897317,25
INFO [1607799479.805487] [src/chainstate/burn/db/sortdb.rs:3117] [ThreadId(3)] ACCEPTED(1897317) leader block commit 37649889dea479105301b93349eb12b383a88e90a713f6a83d61068f18d37945 at 1897317,26
INFO [1607799479.805581] [src/chainstate/burn/db/sortdb.rs:3117] [ThreadId(3)] ACCEPTED(1897317) leader block commit 9a9ab995c0ce0147ecb5083b60e0f1267cb692a2d08efbb6ef0ef77ca3a35f60 at 1897317,27
INFO [1607799482.079424] [src/net/chat.rs:1815] [ThreadId(5)] convo:id=394,outbound=true,peer=facade01+80000000://46.101.96.140:20444: failed to recv on P2P conversation: PermanentlyDrained
INFO [1607799484.110805] [src/net/chat.rs:1815] [ThreadId(5)] convo:id=371,outbound=true,peer=facade01+80000000://163.172.80.52:20444: failed to recv on P2P conversation: PermanentlyDrained
INFO [1607799484.954888] [src/net/chat.rs:1815] [ThreadId(5)] convo:id=373,outbound=true,peer=facade01+80000000://139.162.204.44:20444: failed to recv on P2P conversation: PermanentlyDrained
INFO [1607799495.069418] [src/net/chat.rs:1815] [ThreadId(5)] convo:id=378,outbound=true,peer=facade01+80000000://135.181.154.29:20444: failed to recv on P2P conversation: PermanentlyDrained
INFO [1607799495.804653] [src/net/chat.rs:1815] [ThreadId(5)] convo:id=479,outbound=true,peer=facade01+80000000://13.229.109.181:20444: failed to recv on P2P conversation: PermanentlyDrained
INFO [1607799495.966904] [src/net/p2p.rs:517] [ThreadId(5)] No open socket for 479
Process abort due to thread panic
   0: stacks_node::main::{{closure}}
             at testnet/stacks-node/src/main.rs:56
   1: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic::{{closure}}
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:506
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153
   4: std::panicking::begin_panic
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:505
   5: blockstack_lib::net::inv::<impl blockstack_lib::net::p2p::PeerNetwork>::make_getblocksinv
             at src/net/inv.rs:1526
      blockstack_lib::net::inv::<impl blockstack_lib::net::p2p::PeerNetwork>::make_next_getblocksinv
             at src/net/inv.rs:1613
      blockstack_lib::net::inv::<impl blockstack_lib::net::p2p::PeerNetwork>::inv_getblocksinv_begin
             at src/net/inv.rs:1794
      blockstack_lib::net::inv::<impl blockstack_lib::net::p2p::PeerNetwork>::inv_sync_run
             at src/net/inv.rs:1903
      blockstack_lib::net::inv::<impl blockstack_lib::net::p2p::PeerNetwork>::sync_inventories::{{closure}}
             at src/net/inv.rs:1995
   6: blockstack_lib::net::inv::<impl blockstack_lib::net::p2p::PeerNetwork>::with_inv_state
             at src/net/inv.rs:2079
      blockstack_lib::net::inv::<impl blockstack_lib::net::p2p::PeerNetwork>::sync_inventories
             at src/net/inv.rs:1975
   7: blockstack_lib::net::p2p::PeerNetwork::do_network_inv_sync
             at src/net/p2p.rs:2340
      blockstack_lib::net::p2p::PeerNetwork::do_network_work
             at src/net/p2p.rs:2866
      blockstack_lib::net::p2p::PeerNetwork::dispatch_network
             at src/net/p2p.rs:3909
   8: blockstack_lib::net::p2p::PeerNetwork::run
             at src/net/p2p.rs:4044
   9: stacks_node::neon_node::spawn_peer::{{closure}}
             at testnet/stacks-node/src/neon_node.rs:306
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  10: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:464
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308
      std::panicking::try::do_call
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381
      std::panicking::try
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:463
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/michael/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  12: start_thread
  13: clone

Dumping core for pid 2916
Quit (core dumped)
michael@michael-OptiPlex-990:~/blockstack_working_folder/testnet_1/stacks-blockchain$

**Comment by jcnelson** [comment]
Hey @michaeljiflorida08, thank you for your report!

We just merged a bunch of bugfixes to `master`, and I think one of the fixes (the one for #2108) may have addressed this.
