### ISSUE TITLE
Populate bns.clar with data from `stx-genesis` during bootup

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#2165]
(Reducing issue https://github.com/blockstack/stacks-blockchain/issues/2033 into the couple remaining tasks)

* Populate bns.clar with data from `stx-genesis` during bootup.
* Ensure expected contract events are emitted for the genesis block.

**Comment by lgalabru** [comment]
Address with https://github.com/blockstack/stacks-blockchain/pull/2204
