### ISSUE TITLE
Return parent_network_id in neighbors API

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2168]
**Is your feature request related to a problem? Please describe.**
On https://stxnodemap.runkodapps.com/#home there is no way to distinguish between krypton and xenon nodes.

**Describe the solution you'd like**
The `v2/neighbor` endpoint should return more information to identify the used bitcoin network.

**Describe alternatives you've considered**
Make two maps, one for each possible network.

**Comment by friedger** [comment]
//cc @talhasch

**Comment by talhasch** [comment]
got it @friedger
