### ISSUE TITLE
Xenon - Node Fails to Restart from existing chain state

### ISSUE THREAD

**Issue by dantrevino** [blockstack/stacks-blockchain#2179]
**Describe the bug**

Upgrading from 24.0.0.0 to 24.1.0.0 resulted in a crash when restarting my node.  Clearing the "working_dir" resolves the issue.

**Steps To Reproduce**

Stop node. Start node.

**Expected behavior**

Node should read existing chain state and continue.

**Environment (please complete the following information):**

 - OS: Ubuntu 20.04 Server ARM
 - Rust: n/a using binaries from github
 - Version: stacks-node 0.1.0 => 23.0.0.0 (HEAD:1a34c15+, release build, linux [aarch64]) (24.1.0.0 tag)

**Additional context**

Dec 15 20:30:14 ubuntu stacks-node[2022]: DEBG [1608064214.864279] [src/net/p2p.rs:4006] [ThreadId(4)] >>>>>>>>>>>>>>>>>>>>>>> Begin Network Dispatch (poll for 5000) >>>>>>>>>>>>>>>>>>>>>>>>>>>>
Dec 15 20:30:19 ubuntu systemd[1]: Stopping Stacks Xenon Testnet...
Dec 15 20:30:19 ubuntu systemd[1]: stacks-node.service: Succeeded.
Dec 15 20:30:19 ubuntu systemd[1]: Stopped Stacks Xenon Testnet.
Dec 15 20:30:19 ubuntu systemd[1]: Started Stacks Xenon Testnet.
Dec 15 20:30:20 ubuntu stacks-node[11973]: ==> /etc/stacks-blockchain/xenon-miner-conf.toml
Dec 15 20:30:21 ubuntu stacks-node[11973]: WARN [1608064221.309068] [testnet/stacks-node/src/config.rs:96] [ThreadId(1)] 'mstx_balance' inside toml config is deprecated, replace with 'ustx_balance'
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376351] [testnet/stacks-node/src/main.rs:128] [ThreadId(1)] node configuration NodeConfig { name: "helium-node", seed: [191, 134, 134, 133, 14, 100, 158, 56, 221, 173, 224, 150, 55, 239, 159, 3>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376915] [testnet/stacks-node/src/main.rs:129] [ThreadId(1)] burnchain configuration BurnchainConfig { chain: "bitcoin", mode: "xenon", commit_anchor_block_within: 5000, burn_fee_cap: 11000, pee>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376988] [testnet/stacks-node/src/main.rs:130] [ThreadId(1)] connection configuration ConnectionOptions { inbox_maxlen: 100, outbox_maxlen: 100, connect_timeout: 10, handshake_timeout: 30, timeo>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.377156] [testnet/stacks-node/src/main.rs:131] [ThreadId(1)] block_limit ExecutionCost { write_length: 150000000, write_count: 50000, read_length: 1000000000, read_count: 50000, runtime: 1000000>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.863995] [src/burnchains/bitcoin/spv.rs:473] [ThreadId(1)] Initialized block headers at /tmp/stacks/burnchain/spv-headers.dat
Dec 15 20:30:21 ubuntu stacks-node[11973]: INFO [1608064221.864593] [testnet/stacks-node/src/run_loop/neon.rs:128] [ThreadId(1)] Follower node: starting up
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.869167] [src/chainstate/burn/db/sortdb.rs:2012] [ThreadId(1)] Connect/Open  sortdb '/tmp/stacks/burnchain/db/bitcoin/testnet/sortition.db/data.db' as 'readwrite', with index as '/tmp/stacks/bur>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.869680] [src/chainstate/stacks/index/storage.rs:774] [ThreadId(1)] Opened TrieFileStorage /tmp/stacks/burnchain/db/bitcoin/testnet/sortition.db/marf;
Dec 15 20:30:21 ubuntu stacks-node[11973]: Process abort due to thread panic
Dec 15 20:30:22 ubuntu stacks-node[11973]:    0: stacks_node::main::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/testnet/stacks-node/src/main.rs:57
Dec 15 20:30:22 ubuntu stacks-node[11973]:    1: std::panicking::rust_panic_with_hook
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
Dec 15 20:30:22 ubuntu stacks-node[11973]:    2: std::panicking::begin_panic_handler::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
Dec 15 20:30:22 ubuntu stacks-node[11973]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
Dec 15 20:30:22 ubuntu stacks-node[11973]:    4: rust_begin_unwind
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
Dec 15 20:30:22 ubuntu stacks-node[11973]:    5: core::panicking::panic_fmt
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
Dec 15 20:30:22 ubuntu stacks-node[11973]:    6: core::option::expect_none_failed
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
Dec 15 20:30:22 ubuntu stacks-node[11973]:    7: core::result::Result<T,E>::unwrap
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:973
Dec 15 20:30:22 ubuntu stacks-node[11973]:       rusqlite::row::Row::get
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/row.rs:148
Dec 15 20:30:22 ubuntu stacks-node[11973]:    8: blockstack_lib::chainstate::burn::db::sortdb::<impl blockstack_lib::util::db::FromRow<blockstack_lib::chainstate::burn::BlockSnapshot> for blockstack_lib::chainstate::burn::BlockSnapshot>::from_row
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/chainstate/burn/db/sortdb.rs:156
Dec 15 20:30:22 ubuntu stacks-node[11973]:    9: blockstack_lib::util::db::query_row_panic::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/util/db.rs:314
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::next::{{closure}}::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/row.rs:124
Dec 15 20:30:22 ubuntu stacks-node[11973]:       core::result::Result<T,E>::and_then
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:708
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::next::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/row.rs:124
Dec 15 20:30:22 ubuntu stacks-node[11973]:       core::option::Option<T>::map
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:450
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::next
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/row.rs:122
Dec 15 20:30:22 ubuntu stacks-node[11973]:       blockstack_lib::util::db::query_row_panic
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/util/db.rs:316
Dec 15 20:30:22 ubuntu stacks-node[11973]:   10: blockstack_lib::chainstate::burn::db::sortdb::SortitionDB::get_first_block_snapshot
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/chainstate/burn/db/sortdb.rs:2816
Dec 15 20:30:22 ubuntu stacks-node[11973]:       blockstack_lib::chainstate::burn::db::sortdb::SortitionDB::connect
Dec 15 20:30:21 ubuntu stacks-node[11973]: WARN [1608064221.309068] [testnet/stacks-node/src/config.rs:96] [ThreadId(1)] 'mstx_balance' inside toml config is deprecated, replace with 'ustx_balance'
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376351] [testnet/stacks-node/src/main.rs:128] [ThreadId(1)] node configuration NodeConfig { name: "helium-node", seed: [191, 134, 134, 133, 14, 100, 158, 56, 221, 173, 224, 150, 55, 239, 159, 3>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376915] [testnet/stacks-node/src/main.rs:129] [ThreadId(1)] burnchain configuration BurnchainConfig { chain: "bitcoin", mode: "xenon", commit_anchor_block_within: 5000, burn_fee_cap: 11000, pee>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376988] [testnet/stacks-node/src/main.rs:130] [ThreadId(1)] connection configuration ConnectionOptions { inbox_maxlen: 100, outbox_maxlen: 100, connect_timeout: 10, handshake_timeout: 30, timeo>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.377156] [testnet/stacks-node/src/main.rs:131] [ThreadId(1)] block_limit ExecutionCost { write_length: 150000000, write_count: 50000, read_length: 1000000000, read_count: 50000, runtime: 1000000>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.863995] [src/burnchains/bitcoin/spv.rs:473] [ThreadId(1)] Initialized block headers at /tmp/stacks/burnchain/spv-headers.dat
Dec 15 20:30:21 ubuntu stacks-node[11973]: INFO [1608064221.864593] [testnet/stacks-node/src/run_loop/neon.rs:128] [ThreadId(1)] Follower node: starting up
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.869167] [src/chainstate/burn/db/sortdb.rs:2012] [ThreadId(1)] Connect/Open  sortdb '/tmp/stacks/burnchain/db/bitcoin/testnet/sortition.db/data.db' as 'readwrite', with index as '/tmp/stacks/bur>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.869680] [src/chainstate/stacks/index/storage.rs:774] [ThreadId(1)] Opened TrieFileStorage /tmp/stacks/burnchain/db/bitcoin/testnet/sortition.db/marf;
Dec 15 20:30:21 ubuntu stacks-node[11973]: Process abort due to thread panic
Dec 15 20:30:22 ubuntu stacks-node[11973]:    0: stacks_node::main::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/testnet/stacks-node/src/main.rs:57
Dec 15 20:30:22 ubuntu stacks-node[11973]:    1: std::panicking::rust_panic_with_hook
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
Dec 15 20:30:22 ubuntu stacks-node[11973]:    2: std::panicking::begin_panic_handler::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
Dec 15 20:30:22 ubuntu stacks-node[11973]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
Dec 15 20:30:22 ubuntu stacks-node[11973]:    4: rust_begin_unwind
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
Dec 15 20:30:22 ubuntu stacks-node[11973]:    5: core::panicking::panic_fmt
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
Dec 15 20:30:22 ubuntu stacks-node[11973]:    6: core::option::expect_none_failed
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
Dec 15 20:30:22 ubuntu stacks-node[11973]:    7: core::result::Result<T,E>::unwrap
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:973
Dec 15 20:30:22 ubuntu stacks-node[11973]:       rusqlite::row::Row::get
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/row.rs:148
Dec 15 20:30:22 ubuntu stacks-node[11973]:    8: blockstack_lib::chainstate::burn::db::sortdb::<impl blockstack_lib::util::db::FromRow<blockstack_lib::chainstate::burn::BlockSnapshot> for blockstack_lib::chainstate::burn::BlockSnapshot>::from_row
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/chainstate/burn/db/sortdb.rs:156
Dec 15 20:30:22 ubuntu stacks-node[11973]:    9: blockstack_lib::util::db::query_row_panic::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/util/db.rs:314
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::next::{{closure}}::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/row.rs:124
Dec 15 20:30:22 ubuntu stacks-node[11973]:       core::result::Result<T,E>::and_then
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:708
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::next::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/row.rs:124
Dec 15 20:30:22 ubuntu stacks-node[11973]:       core::option::Option<T>::map
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:450
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::next
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/row.rs:122
Dec 15 20:30:22 ubuntu stacks-node[11973]:       blockstack_lib::util::db::query_row_panic
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/util/db.rs:316
Dec 15 20:30:22 ubuntu stacks-node[11973]:   10: blockstack_lib::chainstate::burn::db::sortdb::SortitionDB::get_first_block_snapshot
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/chainstate/burn/db/sortdb.rs:2816
Dec 15 20:30:22 ubuntu stacks-node[11973]:       blockstack_lib::chainstate::burn::db::sortdb::SortitionDB::connect
lines 31385-31431/31901 99%
Dec 15 20:30:21 ubuntu stacks-node[11973]: WARN [1608064221.309068] [testnet/st>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376351] [testnet/st>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376915] [testnet/st>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376988] [testnet/st>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.377156] [testnet/st>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.863995] [src/burnch>
Dec 15 20:30:21 ubuntu stacks-node[11973]: INFO [1608064221.864593] [testnet/st>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.869167] [src/chains>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.869680] [src/chains>
Dec 15 20:30:21 ubuntu stacks-node[11973]: Process abort due to thread panic
Dec 15 20:30:22 ubuntu stacks-node[11973]:    0: stacks_node::main::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/testnet/stacks-n>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    1: std::panicking::rust_panic_wit>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    2: std::panicking::begin_panic_ha>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    3: std::sys_common::backtrace::__>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    4: rust_begin_unwind
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    5: core::panicking::panic_fmt
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    6: core::option::expect_none_fail>
Dec 15 20:30:20 ubuntu stacks-node[11973]: ==> /etc/stacks-blockchain/xenon-miner-conf.toml
Dec 15 20:30:21 ubuntu stacks-node[11973]: WARN [1608064221.309068] [testnet/stacks-node/src/config.rs:96] [ThreadId(1)] 'mst>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376351] [testnet/stacks-node/src/main.rs:128] [ThreadId(1)] node >
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376915] [testnet/stacks-node/src/main.rs:129] [ThreadId(1)] burnc>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.376988] [testnet/stacks-node/src/main.rs:130] [ThreadId(1)] conne>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.377156] [testnet/stacks-node/src/main.rs:131] [ThreadId(1)] block>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.863995] [src/burnchains/bitcoin/spv.rs:473] [ThreadId(1)] Initial>
Dec 15 20:30:21 ubuntu stacks-node[11973]: INFO [1608064221.864593] [testnet/stacks-node/src/run_loop/neon.rs:128] [ThreadId(>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.869167] [src/chainstate/burn/db/sortdb.rs:2012] [ThreadId(1)] Con>
Dec 15 20:30:21 ubuntu stacks-node[11973]: DEBG [1608064221.869680] [src/chainstate/stacks/index/storage.rs:774] [ThreadId(1)>
Dec 15 20:30:21 ubuntu stacks-node[11973]: Process abort due to thread panic
Dec 15 20:30:22 ubuntu stacks-node[11973]:    0: stacks_node::main::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/testnet/stacks-node/src/main.rs:57
Dec 15 20:30:22 ubuntu stacks-node[11973]:    1: std::panicking::rust_panic_with_hook
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/pan>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    2: std::panicking::begin_panic_handler::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/pan>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    4: rust_begin_unwind
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/pan>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    5: core::panicking::panic_fmt
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/pa>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    6: core::option::expect_none_failed
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/op>
Dec 15 20:30:22 ubuntu stacks-node[11973]:    7: core::result::Result<T,E>::unwrap
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/re>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       rusqlite::row::Row::get
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite->
Dec 15 20:30:22 ubuntu stacks-node[11973]:    8: blockstack_lib::chainstate::burn::db::sortdb::<impl blockstack_lib::util::db>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/chainstate/burn/db/sortdb.rs:156
Dec 15 20:30:22 ubuntu stacks-node[11973]:    9: blockstack_lib::util::db::query_row_panic::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/util/db.rs:314
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::n>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite->
Dec 15 20:30:22 ubuntu stacks-node[11973]:       core::result::Result<T,E>::and_then
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/re>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::n>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite->
Dec 15 20:30:22 ubuntu stacks-node[11973]:       core::option::Option<T>::map
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/op>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       <rusqlite::row::AndThenRows<F> as core::iter::traits::iterator::Iterator>::n>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite->
Dec 15 20:30:22 ubuntu stacks-node[11973]:       blockstack_lib::util::db::query_row_panic
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/util/db.rs:316
Dec 15 20:30:22 ubuntu stacks-node[11973]:   10: blockstack_lib::chainstate::burn::db::sortdb::SortitionDB::get_first_block_s>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/chainstate/burn/db/sortdb.rs:2816
Dec 15 20:30:22 ubuntu stacks-node[11973]:       blockstack_lib::chainstate::burn::db::sortdb::SortitionDB::connect
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/chainstate/burn/db/sortdb.rs:2038
Dec 15 20:30:22 ubuntu stacks-node[11973]:   11: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Bur>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/burnchains/burnchain.rs:603
Dec 15 20:30:22 ubuntu stacks-node[11973]:   12: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Bur>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/src/burnchains/burnchain.rs:1200
Dec 15 20:30:22 ubuntu stacks-node[11973]:   13: stacks_node::burnchains::bitcoin_regtest_controller::BitcoinRegtestControlle>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.>
Dec 15 20:30:22 ubuntu stacks-node[11973]:   14: <stacks_node::burnchains::bitcoin_regtest_controller::BitcoinRegtestControll>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       stacks_node::run_loop::neon::RunLoop::start
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/testnet/stacks-node/src/run_loop/neon.rs:135
Dec 15 20:30:22 ubuntu stacks-node[11973]:   15: stacks_node::main
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at src/testnet/stacks-node/src/main.rs:147
Dec 15 20:30:22 ubuntu stacks-node[11973]:   16: core::ops::function::FnOnce::call_once
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/op>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys>
Dec 15 20:30:22 ubuntu stacks-node[11973]:   17: std::rt::lang_start::{{closure}}
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.>
Dec 15 20:30:22 ubuntu stacks-node[11973]:   18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::ca>
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/op>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       std::panicking::try::do_call
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/pan>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       std::panicking::try
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/pan>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       std::panic::catch_unwind
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/pan>
Dec 15 20:30:22 ubuntu stacks-node[11973]:       std::rt::lang_start_internal
Dec 15 20:30:22 ubuntu stacks-node[11973]:              at rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.>
Dec 15 20:30:22 ubuntu stacks-node[11973]:   19: main
Dec 15 20:30:22 ubuntu stacks-node[11973]:   20: __libc_start_main
Dec 15 20:30:22 ubuntu stacks-node[11973]:   21: <unknown>
Dec 15 20:30:22 ubuntu stacks-node[11973]: Dumping core for pid 11973
Dec 15 20:30:40 ubuntu systemd[1]: stacks-node.service: Main process exited, code=dumped, status=3/QUIT
Dec 15 20:30:40 ubuntu systemd[1]: stacks-node.service: Failed with result 'core-dump'.

**Comment by timstackblock** [comment]
@diwakergupta @lgalabru is this issue still a problem that needs to be addressed

**Comment by timstackblock** [comment]
I think this is a known issue thanks for the clarification @diwakergupta

**Comment by diwakergupta** [comment]
Yes, long-standing issue, originally #1576. PR #1607 was a first-attempt to address it, but we have not completed that work. So for now `working_dir` is unsupported -- use at your own risk.
