### ISSUE TITLE
Starting from the same bootstrap node two different chains developped

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2182]
**Is your feature request related to a problem? Please describe.**
During the mining competition on 15 Dec a few miners worked off a fork based on the same bootstrap node:

Looking at the start of the chain, one showed the first mining tx from a different account and with a different amount:  

`STE0DF4KM7..` with 20000 burn fee (v2/info showed unanchored_tip=000000...)
and  
`ST2TJRHDHM..` with 30000 burn fee (v2/info showed unanchored_tip= something not 0000...)

**Describe the solution you'd like**
Provide chain information through an endpoint that makes it easy to identify forks (or whatever happened here)

**Additional context**
This issue is about collecting information about what happened on 15th Dec

Discussion on discord on 15th Dec:
https://discord.com/channels/621759717756370964/728030782693834862/788405581521092658
![Screenshot from 2020-12-16 10-45-44](https://user-images.githubusercontent.com/1449049/102332053-e16db700-3f8b-11eb-9fe1-58c1457548e4.png)

**Comment by tyGavinZJU** [comment]
I haven't seen the source code of storage and p2p yet.
From my experience, the ```stacks-tip-height``` will increase with ```burn-chain-height``` when the ```burn-chain-height``` is bigger than 300(preserve block for blockstack V1). If it won't, high probability the node creates a new folk. I will give the Debug log for folk node when I'm free.

**Comment by tyGavinZJU** [comment]
> **Is your feature request related to a problem? Please describe.**
> During the mining competition on 15 Dec a few miners worked off a fork based on the same bootstrap node:
> 
> Looking at the start of the chain, one showed the first mining tx from a different account and with a different amount:
> 
> `STE0DF4KM7..` with 20000 burn fee (v2/info showed unanchored_tip=000000...)
> and
> `ST2TJRHDHM..` with 30000 burn fee (v2/info showed unanchored_tip= something not 0000...)
> 
> **Describe the solution you'd like**
> Provide chain information through an endpoint that makes it easy to identify forks (or whatever happened here)
> 
> **Additional context**
> This issue is about collecting information about what happened on 15th Dec
> 
> Discussion on discord on 15th Dec:
> https://discord.com/channels/621759717756370964/728030782693834862/788405581521092658
> ![Screenshot from 2020-12-16 10-45-44](https://user-images.githubusercontent.com/1449049/102332053-e16db700-3f8b-11eb-9fe1-58c1457548e4.png)

@friedger 
The folk can be created when ```stacks-tip-height``` is 1, I have had such situation before. It means it creates a totally different folk.

**Comment by psq** [comment]
@tyGavinZJU the first 300 btc blocks are mostly to fill in the faucet, and make sure the blocks have matured enough to be usable

**Comment by psq** [comment]
you'll need to gather DEBUG log files and storage directory for someone to look at it.  Like I said on discord, not sure what more you can do beyond `/v2/info`, especially not something that would help remedy the situation, if it is not just temporary because the node got blocks from someone else in the same situation
And if a node thinks it has all the burn blocks and can't get the stacks blocks, it will start with its own genesis block, perhaps something that could be disabled/enabled with an option, as only 1 node ever will need to create the genesis block

**Comment by friedger** [comment]
> And if a node thinks it has all the burn blocks and can't get the stacks blocks, it will start with its own genesis block, perhaps something that could be disabled/enabled with an option, as only 1 node ever will need to create the genesis block

I see genesis_chainstate_hash in the info of xenon. That would provide the information.

**Comment by dantrevino** [comment]
Is this an issue in xenon, where everyone is running a local bitcoind? Or just an artifact of running regtest mode in krypton?
