### ISSUE TITLE
[Feature Request] Emit microblocks in mocknet

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#2197]
**Is your feature request related to a problem? Please describe.**
I am aiming to develop again microblocks in our UX projects. Here is my current understanding of how to "use" microblocks:

- get `unanchored_chain_tip` from `/v2/info`
- pass that value as `?tip` in RPC endpoints

I am not sure how to 'trigger' a microblock in mocknet. I am using `stacks-node start` with a custom config TOML, in  and `mode = mocknet`, which has `commit_anchor_block_within = 120000` to "simulate" an experience where blocks don't feel fast. However, when I make a transaction, the `unanchored_chain_tip` does not update after I submit a transaction, which is what I would expect to happen.

**Describe the solution you'd like**

This is really a support ticket hidden behind a feature request. I just want to setup a local environment where I can simulate Mainnet/Xenon behavior, where blocks take minutes to confirm. And, I want to use microblocks to provide a better experience to the end user. I could use Xenon, but the stability issues this week and now have hindered that. Maybe that's the proper answer and I just wait until we get Xenon stabilized.

**Comment by hstove** [comment]
I'm gonna close this. My understanding of microblocks was pretty far off. After further reading of the codebase, I now understand that microblocks are broadcasted manually - they don't just happen magically!

**Comment by jcnelson** [comment]
> I'm gonna close this. My understanding of microblocks was pretty far off. After further reading of the codebase, I now understand that microblocks are broadcasted manually - they don't just happen magically!

Yes and no.  Microblocks can be uploaded by an external miner, but once uploaded, they will be propagated through the p2p network like a "big" transaction.  The node currently doesn't generate any events for unconfirmed microblocks, but only because we haven't finished wiring it up yet (once ready, you'd get an event stream for its unconfirmed transactions).
