### ISSUE TITLE
[TESTNET BUG] Stacks tip height not progressing (Krypton / Daemon Challenge)

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/stacks-blockchain#2198]
## Describe the bug

A number of miners are reporting issues properly syncing with the Stacks chain. Before gathering the info below I confirmed the setup is working for me on both Windows 10 + WSL w/ Ubuntu 20.04, as well as on a VM with Ubuntu Server 20.04 installed.

## Steps To Reproduce

Run stacks-node (v24.0.0.0-xenon) and observe v2/info.

## Expected behavior

Expected node to properly assemble stacks chain.

## Environment

I had a few users with the same issue stop their Mining-Bot instance and run the following command to generate debug information per @diwakergupta.

```bash
RUST_BACKTRACE=full BLOCKSTACK_DEBUG=1 ./stacks-node start --config=conf/miner-Krypton.toml 2>&1 | tee -a miner.log | grep -v DEBG
```

Stacks-node version for anyone using mining-bot is:

```
blockstack-core 0.0.1 => 23.0.0.0 (master:c176dda+, release build, linux [x86_64])
```

Default configuration file for the mining-bot:

https://envl.app/whoabuddy/WukWmZ!3GoNlwKHI7lRyrwn

### User 1: Lechu79

 - OS: Windows 10 + WSL w/ Ubuntu
 - [Debug Log File](https://envl.app/whoabuddy/ufJfYm!GwHiF4R3weYFULwu)

V2 info before shutdown:

```
Krypton miner:

{
  "peer_version":385875968,
  "pox_consensus":"13093849fe7744b7dfdb7cb166f9eefe633444dc",
  "burn_block_height":333,
  "stable_pox_consensus":"46d9190d9d73fc97f895dd36634bf1d3c721e693",
  "stable_burn_block_height":332,
  "server_version":"blockstack-core 0.0.1 => 23.0.0.0 (master:c176dda+, release build, linux [x86_64])",
  "network_id":2147483648,
  "parent_network_id":3669344250,
  "stacks_tip_height":16,
  "stacks_tip":"0e99e21e541dbbca59cc9f0cf4bc1418fb67117a2aee69bf1e4b912b1fe9331f",
  "stacks_tip_consensus_hash":"f68bf0817320fa7001bc9cc75ba7811dab28f26b",
  "unanchored_tip":"d087367736c1c522f2e6a7001d7e598b4cd0449829b7087d4058b5ce8fff96bd",
  "exit_at_block_height":null
}

Local miner:

{
  "peer_version":385875968,
  "pox_consensus":"46d9190d9d73fc97f895dd36634bf1d3c721e693",
  "burn_block_height":332,
  "stable_pox_consensus":"f68bf0817320fa7001bc9cc75ba7811dab28f26b",
  "stable_burn_block_height":331,
  "server_version":"blockstack-core 0.0.1 => 23.0.0.0 (master:c176dda+, release build, linux [x86_64])",
  "network_id":2147483648,
  "parent_network_id":3669344250,
  "stacks_tip_height":0,
  "stacks_tip":"0000000000000000000000000000000000000000000000000000000000000000",
  "stacks_tip_consensus_hash":"0000000000000000000000000000000000000000",
  "unanchored_tip":"4ec7ae4a471502547f69ff7165ce5eab0257def1a6607770512fb66e5fcc7e79",
  "exit_at_block_height":null
}
```

### User 2: Бита

 - OS: Windows 10 + WSL w/ Ubuntu
 - [Debug Log File](https://envl.app/whoabuddy/pKWQNr!cz6y5R2vXNMmklwn)

### User 3: Shackler

 - OS: Windows Server 2019 + WSL w/ Ubuntu 18.04
 - [Debug Log File](https://envl.app/whoabuddy/1COmYO!Wo1DkhyGdZgyRMkh)

### User 3: Shackler's Friend

 - OS: Windows Server 2019 + WSL w/ Ubuntu 18.04
 - [Debug Log File](https://envl.app/whoabuddy/EMn8fC!EcdyJut0BdwnXfSs)

## Additional context

Happy to provide more info if needed!

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [x] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by diwakergupta** [comment]
@whoabuddy I'm unable to repro this. Just spun up a fresh Krypton miner:

```json
{
  "peer_version": 385875968,
  "pox_consensus": "5f49d245e61833e82ffc10b59415e7af3338ad00",
  "burn_block_height": 432,
  "stable_pox_consensus": "227eaefb73155b0992a6a37d8959087af465dffb",
  "stable_burn_block_height": 431,
  "server_version": "blockstack-core 0.0.1 => 23.0.0.0 (master:c176dda+, release build, macos [x86_64])",
  "network_id": 2147483648,
  "parent_network_id": 3669344250,
  "stacks_tip_height": 97,
  "stacks_tip": "d08c0b5159d1e06a3f744e471600f83cdf18760f8d1cc4208279d101e7c3a429",
  "stacks_tip_consensus_hash": "5f49d245e61833e82ffc10b59415e7af3338ad00",
  "unanchored_tip": "f1ebac00b65d3a8af4586d98c5c33e1a11e398c928052cca1170069c3f2f5883",
  "exit_at_block_height": null
}
```

Krypton miner reports:
```json
{
  "peer_version": 385875968,
  "pox_consensus": "5f49d245e61833e82ffc10b59415e7af3338ad00",
  "burn_block_height": 432,
  "stable_pox_consensus": "227eaefb73155b0992a6a37d8959087af465dffb",
  "stable_burn_block_height": 431,
  "server_version": "blockstack-core 0.0.1 => 23.0.0.0 (master:c176dda+, release build, linux [x86_64])",
  "network_id": 2147483648,
  "parent_network_id": 3669344250,
  "stacks_tip_height": 97,
  "stacks_tip": "d08c0b5159d1e06a3f744e471600f83cdf18760f8d1cc4208279d101e7c3a429",
  "stacks_tip_consensus_hash": "5f49d245e61833e82ffc10b59415e7af3338ad00",
  "unanchored_tip": "f1ebac00b65d3a8af4586d98c5c33e1a11e398c928052cca1170069c3f2f5883",
  "exit_at_block_height": null
}
```

We'll go through the logs to see if we can learn anything, but in the interim I'd suggest re-trying.

**Comment by whoabuddy** [comment]
Thank you for the quick reply! I'm having the same issue trying to repro but seeing it reported across a small set of users. Happy to grab more logs if needed and have one more to share.

**Comment by diwakergupta** [comment]
I saw a lot of this in Lechu's logs:

```
DEBG [1608479477.496077] [testnet/stacks-node/src/neon_node.rs:580] [ThreadId(7)] Relayer: Run tenure at height 324 (19b6eafa26bf12a1c9c8
5b3581f2b1d9c2cbc51ea37fddc4d89a365f5410f207)
WARN [1608479477.502017] [testnet/stacks-node/src/neon_node.rs:986] [ThreadId(7)] No Stacks chain tip known, attempting to mine a genesis
 block
DEBG [1608479477.502128] [testnet/stacks-node/src/neon_node.rs:1020] [ThreadId(7)] Stacks tip is unchanged since we last tried to mine a block (0000000000000000000000000000000000000000/406f3d7965ec99a31d4319ed5f6f1142b7207a20cb9a5f89171de75cee9b1316 at height 1 with 1 txs, in 19b6eafa26bf12a1c9c85b3581f2b1d9c2cbc51ea37fddc4d89a365f5410f207 at burn height 0)
```

This suggests this miner was not aware of any other valid blocks and thus attempted to mine a genesis block. This usually suggests some networking / timing issue, or perhaps an issue with the nodes' local state.

Is anyone reporting this issue on a non-Windows platform? Trying to see if that's a common thread here, though since it's Ubuntu on WSL that shouldn't really matter.

Where are these nodes located? Perhaps this issue is exacerbated for nodes in a particularly geography or region?

**Comment by luciamucia** [comment]
Hello,
I have similar problem as @whoabuddy 

Windows10 + WSL + Ubunu 20.04
I did planty times restart of mining bot. But unfortunately it doesn't work for me 

here is my http://localhost:20443/v2/info
{
    "peer_version": 385875968,
    "pox_consensus": "fbe838e1053af50fbd9553794542a36668ceb128",
    "burn_block_height": 439,
    "stable_pox_consensus": "de3629b9d94ee94534fd46e0e418d65f5cedb56f",
    "stable_burn_block_height": 438,
    "server_version": "blockstack-core 0.0.1 => 23.0.0.0 (master:c176dda+, release build, linux [x86_64])",
    "network_id": 2147483648,
    "parent_network_id": 3669344250,
    "stacks_tip_height": 1,
    "stacks_tip": "dd760a8eb24c6cb6f05288ffd16a61d1bf3d96d7def53372f480bbe2976366ce",
    "stacks_tip_consensus_hash": "fbe838e1053af50fbd9553794542a36668ceb128",
    "unanchored_tip": "36325ef8ef1418c8fa36fcd277e46738e722cd3d703fa261955958dda71b9d76",
    "exit_at_block_height": null
}

**Comment by LNow** [comment]
> Is anyone reporting this issue on a non-Windows platform? Trying to see if that's a common thread here, though since it's Ubuntu on WSL that shouldn't really matter.

I think it is worth to check also version of WSL. WSL is not exactly the same as WSL2. So users who face this problem on Windows should run:
```
$ wsl -l -v
```
It will show list of available WSL systems and WSL version they operates on.

**Comment by Lechu79** [comment]
> I saw a lot of this in Lechu's logs:
> 
> ```
> DEBG [1608479477.496077] [testnet/stacks-node/src/neon_node.rs:580] [ThreadId(7)] Relayer: Run tenure at height 324 (19b6eafa26bf12a1c9c8
> 5b3581f2b1d9c2cbc51ea37fddc4d89a365f5410f207)
> WARN [1608479477.502017] [testnet/stacks-node/src/neon_node.rs:986] [ThreadId(7)] No Stacks chain tip known, attempting to mine a genesis
>  block
> DEBG [1608479477.502128] [testnet/stacks-node/src/neon_node.rs:1020] [ThreadId(7)] Stacks tip is unchanged since we last tried to mine a block (0000000000000000000000000000000000000000/406f3d7965ec99a31d4319ed5f6f1142b7207a20cb9a5f89171de75cee9b1316 at height 1 with 1 txs, in 19b6eafa26bf12a1c9c85b3581f2b1d9c2cbc51ea37fddc4d89a365f5410f207 at burn height 0)
> ```
> 
> This suggests this miner was not aware of any other valid blocks and thus attempted to mine a genesis block. This usually suggests some networking / timing issue, or perhaps an issue with the nodes' local state.
> 
> Is anyone reporting this issue on a non-Windows platform? Trying to see if that's a common thread here, though since it's Ubuntu on WSL that shouldn't really matter.
> 
> Where are these nodes located? Perhaps this issue is exacerbated for nodes in a particularly geography or region?

Poland

**Comment by whoabuddy** [comment]
> Is anyone reporting this issue on a non-Windows platform? Trying to see if that's a common thread here, though since it's Ubuntu on WSL that shouldn't really matter.

I noticed that while compiling everything, and restarted my windows laptop and tested fresh from there without issue. So it's not 100% consistent, but does seem to be the Windows/WSL crowd.

As for locations, here are some reported back:
- Windows 2019 w/ WSL x 2 = Google Cloud instance in USA (us-central1)
- Windows 10 + WSL = Prague
- Windows 10 + WSL x 2 = Poland

**Comment by luciamucia** [comment]
I'm running as well from Polan
My WSL output
greg@Greg-desk:~$ wsl.exe -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         1
greg@Greg-desk:~$

**Comment by whoabuddy** [comment]
Update: WSL version 1 versus WSL version 2 seems to be a common denominator here. Still working with some to narrow it down, but definitely something worth looking into if you have issues!

https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-2---update-to-wsl-2

**Comment by fluidvoice** [comment]
> Is anyone reporting this issue on a non-Windows platform? Trying to see if that's a common thread here, though since it's Ubuntu on WSL that shouldn't really matter.
> 
> Where are these nodes located? Perhaps this issue is exacerbated for nodes in a particularly geography or region?

I have an Ubuntu 20.04 VM node running in Brazil via mobile connection, though the speed is usually plenty fast.
My bot miner output showed `" [ThreadId(10)] Connection broken; retrying in 13.699939636091283 sec.."`
This could have been when I purposely reset my connection - because my sync is really slow and seems to not be catching up.
But it seems to me that this is a huge/absurd amount of time to wait to retry a connection problem. During this time the rest of the network is running away from you.

**Comment by Lechu79** [comment]
> Update: WSL version 1 versus WSL version 2 seems to be a common denominator here. Still working with some to narrow it down, but definitely something worth looking into if you have issues!
> 
> https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-2---update-to-wsl-2

WORSK PERFECT !!! Update to WSL2 and everything OK !

**Comment by whoabuddy** [comment]
I'm closing this issue as upgrading from WSL v1 to WSL v2 has fixed the problem for all participants.

There are some [pretty significant differences](https://docs.microsoft.com/en-us/windows/wsl/compare-versions) between the two.

Shout out to @LNow for mentioning the problem!
