### ISSUE TITLE
TESTNET BUG: When stacking with the wallet & CLI, BTC address does not receive stacking rewards 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/stacks-blockchain#2205]
**Describe the bug**
When stacking with the wallet and the CLI I do not get a stacking rewards estimate I also do not get stacking rewards sent to the BTC account entered, these 2 transactions were done on the 17th. 

I have stacked several times with the wallet all through out the testing phase and have always used the same BTC address, I have never received stacking rewards. It was understood on the UX team that this functionality does not work yet and might not until we go live. But after talking to @lgalabru he believes that this should work now and I should see some rewards sent for stacking.

**Steps To Reproduce**
Here are 2 successful stacking transactions one done with a test BTC address and one done with a real BTC address.

IMAGE OF THE LOGS SHOWING THE TRANSACTION AS A SUCCESS

<img width="570" alt="Screen Shot 2020-12-22 at 8 50 05 AM" src="https://user-images.githubusercontent.com/49165468/102895457-b9ba9b00-4432-11eb-9f5c-e90902967b93.png">

2 TRANSACTIONS

TESTNET BTC ADDRESS

```
TWs-MacBook-Pro:~ tw$ stx stack 90000000000000 1 mmPKhbTX4mM4R6LAJDfq3yaRR2WHs6XkJS 8b6973b84bc076114a952737f55811d8dacd528998d544d765dc08f50403beeb01 -t
{
  txid: '0x58e7b0733ccf9cd3d519b3a154b099d3f6b95018d16a9371f6d1a14bfdd0b341',
  transaction: 'https://testnet-explorer.now.sh/txid/0x58e7b0733ccf9cd3d519b3a154b099d3f6b95018d16a9371f6d1a14bfdd0b341'
}
```
https://explorer.bitcoin.com/btc/address/mmPKhbTX4mM4R6LAJDfq3yaRR2WHs6XkJS

<img width="901" alt="Screen Shot 2020-12-22 at 8 44 59 AM" src="https://user-images.githubusercontent.com/49165468/102895261-647e8980-4432-11eb-9613-6b8230c8d0a3.png">

MAIN-NET BTC ADDRESS

```
TWs-MacBook-Pro:~ tw$ stx stack 90000000000000 1 1PRgm3vsJjHCt2qQmNoSA8uBvTVfBwnLKL 82d3449c0e185a9027c766fccd073a6b20f276e83fcc241f721cf5e4b6ec68b901 -t
{
  txid: '0x0cafc7762c9b6ce55b9861bd25e6c959d10918ea353c04c714c8d4473391d4cc',
  transaction: 'https://testnet-explorer.now.sh/txid/0x0cafc7762c9b6ce55b9861bd25e6c959d10918ea353c04c714c8d4473391d4cc'
}
```
https://explorer.bitcoin.com/btc/address/1PRgm3vsJjHCt2qQmNoSA8uBvTVfBwnLKL

<img width="912" alt="Screen Shot 2020-12-22 at 8 51 33 AM" src="https://user-images.githubusercontent.com/49165468/102895582-f090b100-4432-11eb-8ae9-d317d6785b27.png">

**Expected behavior**
Ludo believes that even if I stack with the wallet or the CLI I should receive stacking rewards, this is not something we should have to wait until main-net launch to see.

**Comment by yknl** [comment]
I'm also unable to receive stacking rewards currently on Testnet.

**Comment by timstackblock** [comment]
@lgalabru any luck on your side getting this to work in the CLI or V2wallet using a testnet or main-net BTC address. Rewards are not coming in for any address I have.

**Comment by lgalabru** [comment]
Hey @yknl @timstackblock, I'm currently looking into this, will keep you posted.

**Comment by timstackblock** [comment]
cc @markmhx

**Comment by lgalabru** [comment]
@timstackblock @yknl I was able to receive some rewards on a local setup this weekend with the latest master.
Let's go with another round once Xenon is up again.
Before doing your test, please keep a trace of a `GET /v2/pox` and `GET /v2/info` result, and also let us know the parameters beins used when stacking.
Thanks!

**Comment by timstackblock** [comment]
Ok will do! Thanks @lgalabru

**Comment by timstackblock** [comment]
@Ludo The stacking transaction below read successful 

1st transaction with a wallet
https://stacks-node-api.blockstack.org/extended/v1/tx/0xd1fbbf329dffec37132380427c4ae92457b528a98940da6d9b8da2f2b17d6962
2nd transaction with a wallet
https://stacks-node-api.blockstack.org/extended/v1/tx/0x0b82b08b49c249496f51e35bcc5e1300cc9f3496eed128fb13a2c41c05f9fc73

But no Bitcoin was sent to  the testnet address 
https://mempool.space/testnet/address/mmPKhbTX4mM4R6LAJDfq3yaRR2WHs6XkJS

**Comment by timstackblock** [comment]
@diwakergupta @lgalabru The PoX transactions above released the locked stacks but I still have not received my BTC rewards the BTC address in the 2 transactions above can be viewed here.

https://mempool.space/address/1PRgm3vsJjHCt2qQmNoSA8uBvTVfBwnLKL

**Comment by timstackblock** [comment]
https://discord.com/channels/621759717756370964/730814571517968436/797980959327649803

@lgalabru 
I have a total of 7 stackers that will be filling their pockets with tBTC on Xenon:
STP0FZQXFYPZ779DBJCV65RNKD8X1JBV6PMJ23RT did stack 130,000,000 (threshold was 128,150,000), and got rewarded with a total of ‎0.00188000 tBTC, coming from 14 miners, on its address mjXmc52YbLTEByj6Kufu9aTXV6yUAsGQEV 
stacks explorer link: https://testnet-explorer.blockstack.org/txid/0x5c1c62b10f81a11e964760e7831760d6591179e058f926380f9c200ed5b36da1?chain=testnet
bitcoin explorer link: https://mempool.space/testnet/address/mjXmc52YbLTEByj6Kufu9aTXV6yUAsGQEV

Other accounts:
ST3GZ76TY1AZX9VTDMSBJJB0ZBHKFTDDG56WZ2G2B
ST1Z6E1B35N3A8C974PPCMQPVJ10SCEJA68PMPQ95
ST1QPWWGHPKK7MA88ZCC7ZS9PEZ7251P3GF2V72NJ
STXQ76P1N6A470J3B9MGN4SH9KR05GE8RD0AFENK
STC3YY9AFBFFS4K079YF0288HZ1PV7KH2NAX3RXA
STQ3P6QGVPR11H7R98ZREXG6VH0T718H64BX43J
(tests were performed using the @stacks/stacking package from the stacks.js SDK)
