### ISSUE TITLE
SqliteFailure when sync the block in Krypton Release with another bitcoin node

### ISSUE THREAD

**Issue by tyGavinZJU** [blockstack/stacks-blockchain#2216]
**Describe the bug**
I set up a bitcoin node connected with the official Krypton node. After my bitcoin node synced with the Krypton one (check the block height of burnchain), I use following configuration to start the stacks-node 24.0.0.0 release:
```
[burnchain]
chain = "bitcoin"
mode = "krypton"
# peer_host = "bitcoind.krypton.blockstack.org"
peer_host = "MY_OWN_BITCOIN_NODE ip which synced with official krypton node"
username = "blockstack"
password = "blockstacksystem"
rpc_port = 19443
peer_port = 19444
burn_fee_cap = 20000
```

When I execute:
```
./stacks-node start --config= *.toml
```
I got an error which abort the stacks-node:
```
ERRO [1608795164.884802] [src/chainstate/burn/db/processing.rs:291] [ThreadId(6)] TRANSACTION ABORTED when snapshotting block 545 (54cbe448267e5e21b651261403dfa94f6078625d509188abea5779b2497bd635): DBError(IndexError(SQLError(SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file")))))
ERRO [1608795164.884825] [src/chainstate/coordinator/mod.rs:527] [ThreadId(6)] ChainsCoordinator: unable to evaluate sortition DBError(IndexError(SQLError(SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file")))))
............................
ERRO [1608795165.014514] [testnet/stacks-node/src/neon_node.rs:317] [ThreadId(8)] P2P: Failed to process network dispatch: DBError(IndexError(SQLError(SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file")))))
Process abort due to thread panic
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
Dumping core for pid 14878
```

The complete debug file is too big(80MB) to upload here, if you want please tell me. 

I think there is an issue about the the sqlite. I don't know if it was already fixed in latest commit, I just want to let you know.

**Steps To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu / Debian]: MacOS
 - Rust version: rustc 1.47.0 (18bf6b4f0 2020-10-07)
 - Version of the appropriate binary / software package: [24.0.0.0 Xenon](https://github.com/blockstack/stacks-blockchain/releases/tag/v24.0.0.0-xenon)

**Comment by jcnelson** [comment]
Hey @tyGavinZJU, this is likely due to a bad config, or due to the database file not being accessible or writable.  Can you verify your setup?  Thanks!

**Comment by diwakergupta** [comment]
FWIW I believe both @whoabuddy and @psq have successfully used this setup, so it's likely this is a configuration issue, not an actual bug.

@tyGavinZJU can you paste the full contents of your config?
