### ISSUE TITLE
[TESTNET BUG] Mining Bot Alpha 1.0.1

### ISSUE THREAD

**Issue by btcnadzor** [blockstack/stacks-blockchain#2219]
## Describe the bug

knowing the IP address of the node, you can go and reconfigure the server.

## Steps To Reproduce

just go to the node from another browser and it will ask you to assign a password as at the first launch

## Expected behavior

then you can add your wallets and mine to another account

## Environment

 - OS: ubuntu 18 
https://github.com/Daemon-Technologies/Mining-Bot/releases/tag/1.0.1

my info
btcnadzor@gmail.com
3MZxgogTA8REu4VK3PDpPfqZGjrMHvg1UP

**Comment by diwakergupta** [comment]
This repository is only for issues specific to the stacks-blockchain.
