### ISSUE TITLE
Update reward duration details in SIP-007

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain#2228]
Update proposal (for [this section](https://github.com/blockstack/stacks-blockchain/blame/master/sip/sip-007-stacking-consensus.md#L263)):

> These signed messages are valid for at most 25200 Bitcoin blocks (12
reward cycles, or >7 months). If the signed message specifies a lockup
period `x` less than 25200 blocks, then the signed message is only valid for
Stacking participation for `floor(x / 2100)` reward cycles (the minimum 
participation length is one cycle: 2100 blocks).

[bitcoin confirmation avg is at ~13min](https://www.blockchain.com/charts/median-confirmation-time), hence the 7 months.

cc @diwakergupta

**Comment by diwakergupta** [comment]
Fixed with #2230
