### ISSUE TITLE
Appending a buffer or string fails

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#2231]
**Describe the bug**

Appending a buffer or string fails. The [Clarity reference](https://docs.blockstack.org/references/language-functions#append) says 

> The append function takes a list and another value with the same entry type, or a buffer and another buffer of length 1 and outputs a buffer or a list of the same type

**Steps To Reproduce**

Evaluate in the [Clarity REPL](https://lgalabru.github.io/clarity-repl/):

```clojure
(append 0x00 0x01)
=> Analysis error: expecting expression of type list
```

```clojure
(append "abc" "d")
=> Analysis error: expecting expression of type list
```

**Expected behavior**

Appending a buffer or string should work just like it does for a list:

```clojure
(append (list 1 2 3) 4)
=> (1 2 3 4)
```

**Additional context**

Introduced in #1116
Related: #1299

**Comment by kantai** [comment]
Shouldn't these examples all use `concat` rather than `append`? `append` accepts a list and an item of the list, and Clarity doesn't have a notion of an "item" of buffers.

**Comment by lgalabru** [comment]
Yeah I think we had this discussion a while ago, and settled on the fact `append` would only be handling lists.
Documentation fixed in https://github.com/blockstack/stacks-blockchain/pull/2238
