### ISSUE TITLE
`stx-liquid-supply` broken

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2232]
`stx-liquid-supply` evaluation is currently broken: it attempts to read from the HeadersDB at the current block height. This fails, causing the `clarity_db` to return `0` in all cases.

A fix and witnessing test are found in 8cbdabc71 (PR: #2227)

**Comment by jcnelson** [comment]
Great catch @kantai!

I'm leaning towards making it so that `stx-liquid-supply` has to be a MARF variable, if I had to choose an ideal outcome (since it would be weird if transactions could burn tokens but not see a change to `stx-liquid-supply`), but open to push-back.

**Comment by kantai** [comment]
> I'm leaning towards making it so that stx-liquid-supply has to be a MARF variable, if I had to choose an ideal outcome (since it would be weird if transactions could burn tokens but not see a change to stx-liquid-supply), but open to push-back.

Yep, I agree that makes the most sense -- I'll merge the fix in #2227, so that we have at least a functional `stx-liquid-supply` in the next Xenon restart, but leave this issue open for switching to a MARF variable.

**Comment by jcnelson** [comment]
So, this is probably a mainnet-blocker.  We want `stx-liquid-supply` to reflect the latest STX minted through coinbases and burns.  This is probably 1/2 - 1 day of work, and would be consensus-breaking.

**Comment by diwakergupta** [comment]
Fixed by #2260
