### ISSUE TITLE
Merge type inference

### ISSUE THREAD

**Issue by njordhov** [blockstack/stacks-blockchain#2239]
**Describe the bug**

Type checking for `define-data-var` fails for some merged records.   

**Steps To Reproduce**

Evaluate in the [Clarity REPL](https://lgalabru.github.io/clarity-repl/)

```lisp
(define-data-var a {p: uint} (merge {p: 2} {p: u2}))
=> Runtime Error: Unchecked(TypeValueError(TupleType(TupleTypeSignature { type_map: {ClarityName("p"): UIntType} }), Tuple(TupleData { type_signature: TupleTypeSignature { type_map: {ClarityName("p"): IntType} }, data_map: {ClarityName("p"): UInt(2)} })))
```
Another unexpected result:

```lisp
(define-data-var b {p: int, q: int} (merge {p: 2} {q: 3}))
=> Runtime Error: Unchecked(TypeValueError(TupleType(TupleTypeSignature { type_map: {ClarityName("p"): IntType, ClarityName("q"): IntType} }), Tuple(TupleData { type_signature: TupleTypeSignature { type_map: {ClarityName("q"): IntType} }, data_map: {ClarityName("p"): Int(3), ClarityName("q"): Int(2)} })))
```

In contrast, these evaluate without fail:
```lisp
(merge {p: 2} {p: u2})
(merge {p: 2} {q: 3})
(define-data-var c {p: uint} {p: u2})
(define-data-var d {p: uint} (merge {p: u2} {p: u2}))
(define-data-var e {p: int, q: int} {p: 2, q: 3})
(define-data-var f {p: int, q: int} (merge {q: 2, p: 3} {p: 4}))
```

**Expected behavior**

The records are merged without fail to the expected initial value for the defined var.

**Comment by kantai** [comment]
Good catch @njordhov -- it looks like this happens because the VM runtime shallow merges the _data_ of the tuples, but not the type signatures (the Clarity VM tracks the type signature of in-memory tuples).

**Comment by timstackblock** [comment]
@njordhov are you in our community chat on discord I would like to connect you with @jdbender66 so we can discuss your Testnet bug bounty
