### ISSUE TITLE
Vote on a Stacks chain tip in pox.clar (and burn chain)

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2246]
**Describe the bug**
The stack-stx method of pox.clar does not accepts a chain tip

The stacking consensus requires as SIP-07 that stackers do the following:

1.   Indicating to the network how many STX should be locked up, and for how many reward cycles.
1.   Indicate support for a particular chain tip.
1.   Specifying the Bitcoin address for receiving Stacking rewards.

The `stack-stx` method of pox.clar allows to how manx STX for how long should be locked, the bitcoin address.

There is no explicit method described how to specify a chain tip.  (Is there a way to extract how many stackers voted on a particular chain tip?)

There should be a description of the message format to be used on the burn chain.

**Comment by fintechrecruiters** [comment]
@rachit2501 We will need to keep track of this too. @friedger Is it possible for us to write an algorithm to execute these functions or does it need to be hardcoded on the protocol layer?

**Comment by jcnelson** [comment]
> There is no explicit method described how to specify a chain tip. (Is there a way to extract how many stackers voted on a particular chain tip?)

It does, but indirectly.  The Stacker votes for a particular burnchain height to begin Stacking in, via the `start-burn-ht` argument.  This value is a future burn block height.  By providing this value, this means that the Stacker expects that the Stacks chain will advance through this burn block in the future, and will execute PoX.  In doing so, the Stacker is signalling support in their belief that PoX mining will happen in this chain tip.

**Comment by friedger** [comment]
Does this help if there are forks with the same length (or many forks as seen during the competition)? Can stackers prevent a fork by signalling the burn block height? 

Maybe this issue should be moved to docs.

**Comment by jcnelson** [comment]
> Does this help if there are forks with the same length (or many forks as seen during the competition)? Can stackers prevent a fork by signalling the burn block height?

Stackers cannot prevent a Bitcoin fork, because the state of the Stacks chain itself is tied to a specific Bitcoin fork.  If there are two Bitcoin forks, then the Stacks forks on each Bitcoin fork would execute PoX on their respective Bitcoin forks simultaneously.

**Comment by friedger** [comment]
Oh, my understanding was that it is about the stacks chain.
