### ISSUE TITLE
Add current cycle status in /v2/pox 

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#2254]
When starting a new cycle, PoX can be turned off for a few different reasons. We should exhaustively enumerate these reasons, and expose the status in the API (`PoX enabled` / `Pox disabled because ...`).

**Comment by agraebe** [comment]
ideally, this would be based on the "is-pox-active" method in the stacking contract: https://docs.blockstack.org/references/stacking-contract#is-pox-active

**Comment by jcnelson** [comment]
Can we close this in favor of #2385?

**Comment by agraebe** [comment]
I think so, yes!
