### ISSUE TITLE
Clarity runtime errors should not abort block

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2257]
Clarity runtime errors _should not_ result in an invalid block, or cause a miner to not include the transaction. This incorrect behavior is currently relied on by tests in `chainstate::stacks::boot` that use `unwrap-panic!` to abort the transaction, which is then checked to ensure that the transaction is not included in the block.

**Comment by diwakergupta** [comment]
Fixed by #2264
