### ISSUE TITLE
Support TLS/SSL

### ISSUE THREAD

**Issue by JonasPf** [blockstack/stacks-blockchain#2311]
**Is your feature request related to a problem? Please describe.**

I have a bitcoind node running behind a TLS proxy. This is important to me to encrypt the traffic between stacks and bitcoind.

**Describe the solution you'd like**

Ideally stacks should work with a SSL/TLS endpoint without any configuration changes. If this is not possible it would be sufficient to be able to enable/disable SSL/TLS in the config.toml file.

**Describe alternatives you've considered**

1. I've disabled SSL/TLS and it works. This alternative is not ideal because the traffic is now unencrypted.
2. Running stacks and bitcoind in a private network (or VPN) can work but it makes the setup more complicated.

**Additional context**

I get the following error logs when I enable TLS on my proxy:

```
INFO [1610387304.375994] [testnet/stacks-node/src/run_loop/neon.rs:121] [main] Miner node: checking UTXOs at address: mmajH89LN7huT51NhboUJQXJV2a6jDeMUd
ERRO [1610387304.576903] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:467] [main] Bitcoin RPC failure: error listing utxos Network("Bitcoin RPC: status(400) != success, body is \'String(\"(unparseable)\")\'")
```

I'm not a rust developer but this looks like a relevant code location: https://github.com/blockstack/stacks-blockchain/blob/master/src/burnchains/bitcoin/indexer.rs#L116

**Comment by kobrien** [comment]
Hi just wondering if there is any update on this? We would like to run our blockstack node with an external bitcoin node over TLS/SSL, thank you!

**Comment by jcnelson** [comment]
It's probably not going to happen due to the complexity involved.  We recommend you put a TLS terminus in-between your node and the Internet (such as an nginx reverse proxy).
