### ISSUE TITLE
Chainstate: set max block and transaction lengths

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2320]
These should both be 2MB.  It's currently 16MB (maximum p2p message length), but it may be smaller in practice due to VM compute limits.

@reedrosenbluth @kantai are these enforced in Clarity anywhere?

**Comment by kantai** [comment]
No, Clarity won't enforce block or transaction lengths. There's a maximum contract length, but that doesn't have 1-1 correspondence with maximum block length (and the maximum contract length is just the max P2P message length). I don't think Clarity is capable of enforcing maximum block or transaction lengths, as Clarity never sees raw transaction or block data.
