### ISSUE TITLE
Stacks node miner should be able to recover from pending transaction

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2346]
Currently, if a miner submits a block commit bitcoin transaction, but the next bitcoin block arrives without picking up that transaction, the `neon_node` will enter into a deteriorated state: it will try to mine a new transaction for the new block, but it may not be able to "find" a UTXO, because the only UTXO is outstanding.

There's two ways that this could be addressed (possibly both could be implemented)

1. Set the `neon_node` to "wait" until the next burn block if it's unable to mine in the current block (something like #2335)
2. Issue a replace-by-fee transaction to update the pending transaction (this would be very beneficial, because it allows the miner to "correct" the pending transaction into a valid commitment).

**Comment by lgalabru** [comment]
Should be addressed with https://github.com/blockstack/stacks-blockchain/pull/2383

**Comment by lgalabru** [comment]
Addressed with https://github.com/blockstack/stacks-blockchain/releases/tag/2.0.3
