### ISSUE TITLE
Networking: listen for Bitcoin block announcements

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2367]
Instead of polling for Bitcoin blocks, the node should listen for them to arrive.  This should help miners wake up in a timely manner to produce new block-commits.

**Comment by kantai** [comment]
The current default settings for bitcoin poll time and "wait for microblocks" are `10s` and `60s` respectively. I'm not sure that switching from a poll to push configuration for bitcoin will dramatically improve the turnaround time for a miner's first block commit: the `60s` wait time is much more likely to be the driving factor.

We can reduce this wait time, but that will impact the number of blocks mining off the "direct ancestor". I'd be interested to see how reducing the wait time 30s impacts the network.
