### ISSUE TITLE
Mining: "No UTXOs" bug causes missed block commits

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2379]
When mining blocks, I have noticed that the error message `No UTXOs for $PUBLIC_KEY` is correlated strongly with ` Invalid block commit: missed target block` errors.  Moreover, all of the `Invalid block commit: missed target block` errors indicate that the block-commit was _off by one block_ -- if the `intended_modulus` was _n_, then `actual_modulus` is invariably _(n + 1) mod WINDOW_SIZE_.  This suggests to me that there may be a _causal_ relationship between these two problems -- if the node can't find any UTXOs, it uses the block-commit intended for the last burn block.

I've attached the output of `egrep 'No UTXOs|16sAXi1jxhxKCfY84hubDdnFNaAhqd5t49' -i /data/stacks/mainnet/logs/logs.out > /tmp/errors.txt` to this issue to show you what I mean.
[errors.txt](https://github.com/blockstack/stacks-blockchain/files/5863153/errors.txt)

**Comment by lgalabru** [comment]
Should be addressed with https://github.com/blockstack/stacks-blockchain/pulls

**Comment by lgalabru** [comment]
Addressed with https://github.com/blockstack/stacks-blockchain/releases/tag/2.0.3
