### ISSUE TITLE
Make mempool tx chaining limit configurable

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain#2384]
**Is your feature request related to a problem? Please describe.**

For some use-cases (e.g. exchanges), the current `MAXIMUM_MEMPOOL_TX_CHAINING` limit of 25 can be limiting. I believe this limit is not consensus-critical, and miners would exercise a high degree of control on the mempool regardless. 

**Describe the solution you'd like**

Make the maximum mempool tx chaining limit configurable. Alternative would be to bump up the default. Other ideas?

**Comment by kantai** [comment]
Making this configurable could cause a dramatic increase in #2365, particularly so without an anti-entropy protocol. Any nodes that accept long-chained transactions would attempt to broadcast them to their peers, receive a rejection, and not attempt to rebroadcast them at any point. Without a rebroadcasting protocol (which is what the anti-entropy protocol is), making this configurable would likely be problematic.

**Comment by hstove** [comment]
Seems like a good time to implement a bulk-STX-send contract?

**Comment by jcnelson** [comment]
Seconding @kantai.  Increasing the chaining rate on a few nodes is just going to lead to a bunch of orphaned transactions in the mempool.  We'd either need to boost it for all nodes, or implement a transaction anti-entropy protocol.

I like @hstove's idea.  If volume is the issue, then the sender could create a one-off smart contract comprise of just a `(begin ..)` list with a crap-ton of `(stx-transfer? ..)` lists.  A single one of these transactions could send STX to hundreds of users, and if you're trying to sustain sending to hundreds of accounts per block, you'd only need to send one of these transactions per block.

**Comment by diwakergupta** [comment]
Closing as wontfix.
