### ISSUE TITLE
Stacking details in v2/pox

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain#2385]
Over the last few weeks, we've identified a couple of things that could be added to the endpoint in order to make integrations easier:

- Add a field for the # bitcoin blocks before the next prepare phase starts - "next_prepare_phase_in"
- Add a field for the total ustx locked for the upcoming cycle - "next_cycle_ustx_locked"
- Add a field for the pox activation of the upcoming cycle - "next_cycle_pox_active"
- Add a field for the dynamically calculated minimum ustx required for a reward slot - "min_reward_slot_ustx"

cc @kantai @zone117x @kyranjamie

**Comment by jcnelson** [comment]
I think this is a more-refined version of #2254.

**Comment by agraebe** [comment]
as @lgalabru noted in the previous issue, if pox is not active, a reason would be helpful

**Comment by lgalabru** [comment]
Addressed with https://github.com/blockstack/stacks-blockchain/pull/2459
