### ISSUE TITLE
Mempool transactions should be evaluated in nonce-order, not walk-order

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2393]
Currently, mempool transactions are evaluated in the "walk order" of the mempool, which is effectively a "reverse" order: transactions received later are attempted first.

This can impact chained transactions, because higher nonces will be tried first and fail, before the lower nonces are tried. In degenerate cases, this can lead to chained transactions only being included one-per-block, and will slow the rate that chained transactions are mined.

**Comment by pavitthrap** [comment]
Fixed in #2514
