### ISSUE TITLE
Refactoring: remove all runtime panics from the relayer thread

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2404]
We cannot permit the node to runtime-panic due to network I/O.  I've already had to deal with this once now in `develop` when booting up a public follower.  I don't yet know the underlying cause because Rust ate the panic message, but in general, remote peers should not be able to trigger a node crash.

**Comment by zone117x** [comment]
I think I've ran into this twice today while trying to sync a mainnet node. But I'm not getting any panic message or anything else useful. Will report back if I do.

**Comment by jcnelson** [comment]
We'll probably want two modes of operation:  crash-on-error, or warn-on-error. Crash-on-error is appropriate for when there's a downstream event consumer that does not expect any "gap" in the event stream due to a transient failure in the relayer thread.  Warn-on-error is for everything else.
