### ISSUE TITLE
Subsequent STX transfer with insufficient balance stays pending

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#2413]
Opening an issue for something found by @dantrevino.

Check out this address on testnet: https://explorer.stacks.co/address/STQTK2AMC92ZN0ZWTMB6N53E4QF6CNH98QZTF8BN?chain=testnet

The user had 500 STX. They made one STX transfer for 100 STX. Then, while the first was still pending, the user made a 434 STX transfer. This was through the web wallet - and the web wallet should maybe try and detect things like your "pending balance", and maybe catch this. However, it doesn't, so the second TX was broadcasted.

I would have expected that the second TX would simply be rejected (and confirmed). However, the second TX remains pending 8 hours later. The first one was confirmed. The nonce's are correct - the first nonce is `0`, second is `1`.

**Comment by jcnelson** [comment]
Hey, so, this isn't something we can easily do because one transaction might change the balance in a way that cannot be predicted in advance, which makes it impossible to reason about whether or not dependent transactions are valid.  Do you know what other blockchains do to handle this situation?
