### ISSUE TITLE
Remove testnet references when running mainnet code

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/stacks-blockchain#2414]
**Describe the bug**

I am running a follower node to analyze some data on mainnet, and noticed two things that were rather confusing. I wasn't sure the best way to title this so feel free to change!

1. I ran the follower using cargo (same as [I've done in the past](https://github.com/AbsorbingChaos/stx-miner-script/blob/658876998da6459ae1ebf5dc627c49a98f26b1d5/config-miner-krypton.sh#L190)), and while the correct command is executed in the end it was definitely counterintuitive.
```
whoabuddy@stacks-miner-mainnnnet:~/stacks-blockchain$ cargo testnet mainnet
    Finished dev [unoptimized + debuginfo] target(s) in 30.51s
     Running `target/debug/stacks-node mainnet
```
2. The data for the follower was stored in the `/tmp` folder as expected, but the folder name still references testnet.

```
/tmp/stacks-testnet-7f9d67b98617ae12
```

**Steps To Reproduce**

Run a follower node connected to mainnet.

**Expected behavior**

It would be nice to run `cargo mainnet` or maybe even `cargo stacks-node` so it's more in line with the command that's eventually run.

It would be nice if mainnet data were easy to distinguish from testnet data in the /tmp folder, i.e. `stacks-mainnet-abcxyz`

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Rust version: rustc 1.49.0 (e1884a8e3 2020-12-29)
 - Stacks-node version:
 
```
INFO [1612468200.576079] [testnet/stacks-node/src/main.rs:80] [main] stacks-node 0.1.0 (master:6b9110b99, debug build, linux [x86_64])
stacks-node 0.1.0 (master:6b9110b99, debug build, linux [x86_64])
```

**Additional context**

None.

**Comment by lgalabru** [comment]
To be addressed with https://github.com/blockstack/stacks-blockchain/pull/2421

**Comment by lgalabru** [comment]
Addressed with https://github.com/blockstack/stacks-blockchain/pull/2421
