### ISSUE TITLE
Can't update delegate stx amount

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2430]
**Describe the bug**
User A delegated 100 STX to user B calling `delegate-stx`. User B does not yet called `delegate-stack-stx` for user A. Now user A wants to add 10 STX but the `delegate-stx` tx fails with err 20 (ERR_STACKING_ALREADY_DELEGATED).

1st call successful: https://explorer.stacks.co/txid/0x66d587d90a0f2099e1a4091943abd5631ad3a63937197327222ce5763b7920f5?chain=testnet

2nd call failed: https://explorer.stacks.co/txid/0xcbb05975e45c6bd35b2edbd3f8c8787fba3b75967b8c9be87e68553a65f9dae8?chain=testnet

**Steps To Reproduce**
1. call `delegate-stx` twice
2. see error on second tx

**Expected behavior**
The amount of delegated stx should be 110 after the second tx.

**Additional context**
The expected behaviour was explained here: https://github.com/blockstack/stacks-blockchain/issues/2251

It would be nice to get information about the amount of delegated stx.

**Comment by jcnelson** [comment]
Hey @friedger, I think you'll need to first close out user A's delegate relationship before trying to re-establish it with more tokens.  You could deploy a proxy contract that did this, for example.

**Comment by friedger** [comment]
Ok, thank you.
