### ISSUE TITLE
the PoX contract does not support Bech32 addresses

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/stacks-blockchain#2441]
The Phoenix wallet (https://phoenix.acinq.co) generates only Bech32 native segwit addresses, so it can't be used to receive stacking rewards. The Stacks Wallet won't accept this address because the PoX contract does not allow it.

_Originally posted by @fluidvoice in https://github.com/blockstack/stacks-wallet/issues/607#issue-807445821_

**Comment by jcnelson** [comment]
The PoX contract currently only accepts addresses that take the form of `(version-byte, 20-byte-hash)`, so there's not much we can do about this right now.  However, if you're Stacking with a 3rd party like OKCoin, they ought to be able to send your due BTC to the address of your choice.

When Stacks 2.1 is ready -- a scheduled network upgrade at Bitcoin block 700,000 -- we'll have a chance to address this.

**Comment by fluidvoice** [comment]
FYI, the Blue Lightning mobile wallet also uses Bech32 addresses. 
So perhaps this is a growing trend.  https://bluewallet.io

**Comment by jcnelson** [comment]
Closing in favor of #2586
