### ISSUE TITLE
Critical! Leader block commit sent multiple times for one block, which result to potentially infinite overspending

### ISSUE THREAD

**Issue by MaksimalistT** [blockstack/stacks-blockchain#2444]
**Describe the bug**
For some blocks leader block commit sent multiple times, which can result to committing as much as there are available BTC on the wallet if it takes long enough for next block to come.

Here is what happened for block:3710
`
INFO [1613339155.240835] [testnet/stacks-node/src/neon_node.rs:1589] [relayer] Succeeded assembling Stacks block #3710: 57590adf80f5c009d2f53ff5142d5a46af003969a7a10b3811d01887dd9407fc, with 17 txs, attempt 17
INFO [1613339155.291730] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:1037] [relayer] Abort attempt to re-submit identical LeaderBlockCommit
WARN [1613339155.291759] [testnet/stacks-node/src/neon_node.rs:1654] [relayer] Failed to submit Bitcoin transaction
INFO [1613339158.551266] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/7b8ccf2b757f2a8a80277ffc3b31d8bb58633e593fe1f77448918d17e81d233a
INFO [1613339165.308474] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/d57ba9ebcabb807adc5f17c501b006dfb636c605bd02a4c1108f1740ea8d8c51
INFO [1613339212.853869] [src/net/chat.rs:1850] [p2p] convo:id=121,outbound=false,peer=18000000+00000001://47.242.239.96:56764: failed to send on P2P conversation: SendError("Failed to send 4 bytes")
INFO [1613339212.853899] [src/net/p2p.rs:2015] [p2p] Broken connection on event 121: SendError("Failed to send 4 bytes")
INFO [1613339225.942801] [src/net/http.rs:1558] [p2p] Handle GET /v2/neighbors
INFO [1613339277.782220] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/0f0d3a5ba4c78694fddfb3c4e3b65120a46207abe8b41dbedf86be9aee5b720c
INFO [1613339279.783098] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/6ce5929b90346383fa7f1bad556444c2136c0630324f5ea59e44b7d11ebb8836
INFO [1613339281.147181] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/7b87c201b4401046fca6efa0a0ca7f6784a0d3feb3c29cf5b1a6ace041fd7259
INFO [1613339281.147336] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/25099fc6767328feb42b64f446fb0679312f75ffe1e9a34a3d1088256d454ca6
INFO [1613339285.424249] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/4acb5e6e68a35ea3f652dc44ee2719c6ef028ec24164ed6b28cd7f40157ff60a
INFO [1613339286.765199] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/5b76661671e6eee90253c609a379b93bd88d9c277f4cedc8500510cc42f383f8
INFO [1613339286.765346] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/2d5b6e23920ed185fcbb01a58c51a70efd43a82ea3995bf36cd0a877db74cfc5
INFO [1613339286.765429] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/ea211c0e48f7562af2879601c7bf581704ff87a4df0781b4723f6b67458c3994
INFO [1613339287.498162] [src/burnchains/burnchain.rs:1284] [main] Syncing Bitcoin blocks: 100.0% (670627 to 670628 out of 670628)
INFO [1613339287.533403] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/beee497715a4ce692292214dd271e440a64ba9f97093cf0f1419979e9a59fb59
INFO [1613339291.486228] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 7f19cae51ab07d50711ba9d110177aeef12998a756339086c15d730c95e52579 at 670628,31, apparent_sender: 1ASEW7rDjPR131SD96iPvRXRAzTsQ1Nd3V
INFO [1613339291.487482] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit eb7afba7355b2d5e297081a9eaed78b9d0e961d5b047db27646ceac5350e5729 at 670628,131, apparent_sender: 17RfeXjpSQzqWrsEXd71eVWP4d28t1wKis
INFO [1613339291.487600] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit a4b2620725bea1d1128f2b49c0eb7f592dfbf03d3cd7339732bc992e211813a1 at 670628,149, apparent_sender: 15282N4BYEwYh3j1dTgJu64Ey5qWn9Po9F
INFO [1613339291.488119] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 956230941b2b3cf6c2483d170e39387f474a062b2c0057e87ac73e49bd044eef at 670628,264, apparent_sender: 1H3tZ2nmW1bTs7qRYS4xUZwaSa3zm614zg
INFO [1613339291.488613] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 4ce72fc8288863eeb3fee0dbb25658e23beb614e722db69aabf8a0aaf3706cf0 at 670628,467, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.489153] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 2f4b9ab86b3e61010d78e46e7ee94de495d910dcd287dea21c3dd107953d2a1d at 670628,1176, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.489267] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 3cada0a017daa5a3aa37e0cf57b0aebf8ff4904e3a209e064804b898cc470883 at 670628,1177, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.489338] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 1a9bb663dee8ca86f67e313c1f50171f3b3a51f15f28e32121915759313e586f at 670628,1178, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.489929] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 6766ef89169c28d678246ba570bb2dae11742333288e99777a7d7ebb4f304c6f at 670628,1179, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.490566] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 75130270e4bce3bbecb305cf505a468f17b6bd7c513cb1897498a463bfa1abb1 at 670628,1180, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.491580] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit b65c7428a9e1269b51afa3789c31550fb0e7104cb48d9f25a312edbad830fa4c at 670628,1181, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.492096] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 4f5ea54f6dcdf484973b89bfa2cc70a266ca60656122e59d531b0778ff937b85 at 670628,1182, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.492217] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 4e20d480e941bd8e004a1bd281d6db1d1422df4efa18f356121fbb1785b1082d at 670628,1183, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.492712] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 1ef690ca03ee46d8ecaef69a67fde8c474cebf00d5798e540b5b26b1e2ee4452 at 670628,1184, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.493290] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 90725bde49820085219791498c002adb3403f86d8ecd722bd7db3bc01f0c77ae at 670628,1185, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.493393] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit 6af347614c45c5a4ad760ee080f25cccd01038304bd6ed03e424c809f8ff1a91 at 670628,1186, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
INFO [1613339291.493861] [src/chainstate/burn/db/sortdb.rs:3401] [chains-coordinator] ACCEPTED(670628) leader block commit e37a655a48a5bb98f74edc08b548700c627164106b7ce2275a9634145e157213 at 670628,1191, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
`

which resulted to 12 commits in total for 1 block
here is report from stacks-dump

`670628 2 670626 3710> 4,932.80 2,922  7,542,000 br317 s:e09b193dd2 p:8502946e2b c:0fe8e81381 i:5f44ba68f7 b:00000000000000000000b94b3     [7.3]SP137NZXD0 [6.0]SP1KQXKAHW [5.4]SP1PYG1ZEV*[5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [5.4]SP1PYG1ZEV [2.7]SP1RJH1641 [4.0]SP2R0VR6CF [9.4]SPP1DJ1JE2`

Similar happened for block:3718 it was adding commits, then at some point it stoped with 'Failed to submit Bitcoin transaction' (as in as in #2443, same wallet). At the end all commits were rejected from the block and it resulted to 37 commits wasted!

`INFO [1613350121.828605] [testnet/stacks-node/src/neon_node.rs:1589] [relayer] Succeeded assembling Stacks block #3718: 965faa1bf013eaf343ff20b910719823773348b769537b628156ef1a7338195a, with 12 txs, attempt 1
WARN [1613350121.840652] [testnet/stacks-node/src/neon_node.rs:1654] [relayer] Failed to submit Bitcoin transaction
INFO [1613350124.912195] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/7f753f65d153803c41839a05836431530fc221bf5dc251518e3087cab801a5fa
INFO [1613350124.912359] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/64f4b15dfae058db38a34f528b30a18ee3d4f859463227858f5dbdc650785234
INFO [1613350131.054735] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/2a9fdc855930e598825edcfa7063385f51e8224df4bcf1cfce0cfdcb9ba9b1ba
INFO [1613350131.054880] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/5af4ef41facbfeb643b525772a3fad82f15241dacd6ff16d1f86896d0362b1ad
INFO [1613350136.474508] [src/net/http.rs:1558] [p2p] Handle GET /v2/info
INFO [1613350136.479753] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/bfb0fd682d5542244960ed6c616f741c35af6a0952ea96731928ee74c14a7ece
INFO [1613350151.866459] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/d2bc744f8de7fbe2329d27328ba20b4fe4b6a7844caf03577322aac409fe547c
INFO [1613350151.866679] [src/net/http.rs:1558] [p2p] Handle GET /v2/microblocks/confirmed/64f4b15dfae058db38a34f528b30a18ee3d4f859463227858f5dbdc650785234
INFO [1613350160.732441] [src/net/http.rs:1558] [p2p] Handle GET /v2/microblocks/confirmed/2a9fdc855930e598825edcfa7063385f51e8224df4bcf1cfce0cfdcb9ba9b1ba
INFO [1613350160.737432] [src/net/http.rs:1558] [p2p] Handle GET /v2/microblocks/confirmed/7f753f65d153803c41839a05836431530fc221bf5dc251518e3087cab801a5fa
INFO [1613350176.298621] [src/net/http.rs:1558] [p2p] Handle GET /v2/microblocks/confirmed/b042e8386fecc95f8dc20406b69d2dc5247e13bd87ddb97d51c5976494816a3a
INFO [1613350202.665715] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/3856dec439438adde5334c4f46ee342982a068c4cf435e869abd5b1c6aaf8d02
INFO [1613350202.665942] [src/net/http.rs:1558] [p2p] Handle GET /v2/blocks/a8d6d976a7e5e791aa355910872b51f417fb9c8d33222d5a7f72c64dbb861256
INFO [1613350229.127906] [src/burnchains/burnchain.rs:1284] [main] Syncing Bitcoin blocks: 100.0% (670638 to 670639 out of 670639)
WARN [1613350230.162096] [src/chainstate/burn/operations/leader_block_commit.rs:678] [chains-coordinator] Invalid block commit: missed target block, intended_modulus: 3, actual_modulus: 4, block_height: 670639, apparent_sender: 1ASEW7rDjPR131SD96iPvRXRAzTsQ1Nd3V
WARN [1613350230.162397] [src/chainstate/burn/db/processing.rs:66] [chains-coordinator] REJECTED(670639) leader block commit 61c97e59e9855388ef534ffeaee544542accb60945447330b4cd8017c81d24c9 at 670639,13: BlockCommitNoParent
WARN [1613350230.595381] [src/chainstate/burn/operations/leader_block_commit.rs:678] [chains-coordinator] Invalid block commit: missed target block, intended_modulus: 3, actual_modulus: 4, block_height: 670639, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
WARN [1613350230.595694] [src/chainstate/burn/db/processing.rs:66] [chains-coordinator] REJECTED(670639) leader block commit 24bb147dd99cfbee44f5906627d67eaed7f5e9f373ea452e80e257d4516f3e4c at 670639,1795: BlockCommitNoParent
WARN [1613350230.595788] [src/chainstate/burn/operations/leader_block_commit.rs:678] [chains-coordinator] Invalid block commit: missed target block, intended_modulus: 3, actual_modulus: 4, block_height: 670639, apparent_sender: 1B28chuS1TghjhtRyCcP7Z91zKtWqMb3rD
WARN [1613350230.595911] [src/chainstate/burn/db/processing.rs:66] [chains-coordinator] REJECTED(670639) leader block commit 6336b220d91df6f262aa36621157f4fecda5999b41abf3b10cb4ebdac37b326f at 670639,1796: BlockCommitNoParent
...`

log file attached
[leader_block_commit.log.gz](https://github.com/blockstack/stacks-blockchain/files/5980851/leader_block_commit.log.gz)

**in total it resulted to overspending 51 commits**

**Steps To Reproduce**
No idea

**Expected behavior**
Leader block commit included only once for a block

**Environment (please complete the following information):**
OS: Amazon Linux
Rust version: rustc 1.49.0 (e1884a8e3 2020-12-29)
Stacks-node 2.0.4

**Comment by kantai** [comment]
I suspect what is happening here is caused by the logic on this line:

https://github.com/blockstack/stacks-blockchain/blob/master/testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs#L1009

Having debug logs would be helpful for confirming that, though.
