### ISSUE TITLE
Emit dropped mempool txs

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#2446]
Let event observers know when a mempool transaction has been dropped from the node, probably just a new event endpoint where the txid is passed?

(I thought we had an issue for this already, maybe we do and I couldn't find it, if so feel free to close this one)

**Comment by jcnelson** [comment]
We can do this in the garbage-collection path in the relayer.

**Comment by jcnelson** [comment]
This also applies to transactions that get dropped because they're too expensive or get rendered invalid (e.g. RBF'ed).

**Comment by jcnelson** [comment]
This is now addressed in #2479
