### ISSUE TITLE
Event observer http error discarded for /new_burn_block

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#2448]
Related:
* https://github.com/blockstack/stacks-blockchain/pull/2447
* https://github.com/blockstack/stacks-blockchain-api/issues/440

The API was failing to parse the payload from `/new_burn_block` and returning a non-2xx. It looks like the node does not retry/panic when the http request fails. 

The other endpoints (at least `/new_block`) retry/panic (can't remember what the latest behavior is), but we should probably have all event broadcasts have the same behavior. Otherwise it leads to the API and node getting out-of-sync in a way that can be hard to catch.

**Comment by diwakergupta** [comment]
@zone117x is this still an issue?

**Comment by zone117x** [comment]
No, I wasn't able to reproduce.
