### ISSUE TITLE
Severe STX Funds difference from Wallet or Explorer.stacks and node balance

### ISSUE THREAD

**Issue by paradigma-cl** [blockstack/stacks-blockchain#2449]
**Describe the bug**
A similar bug was reported, but still now other similar issues are appearing.  There is a difference between the Wallet or Explorer with the Node balance that you can get with the stx balance <<STX address>>   One case is the Miner Rewards that are not actually accredited to the balance, and there should be funds in the balance, and they are not seen.
**Steps To Reproduce**
The first difference between balances was from the miner awards, the balance that appears on the Wallet and Explorer.
![Screenshot_2021-02-15 STX Address SPY1P…53M64](https://user-images.githubusercontent.com/32182666/107970702-38920700-6f90-11eb-8443-e47727b12ab9.png)
Last friday 12/Feb/2021 I had this balance:
stx balance SPY1PP2KZ67B4SC678YFQKQPKY8Y1AP7TJS53M64
{
  "balance": "11259090907",
  "locked": "0",
  "unlock_height": 0,
  "nonce": 60
}
Note that Nonce is 60
For the same account today 15/Feb/2021 the balance is:
stx balance SPY1PP2KZ67B4SC678YFQKQPKY8Y1AP7TJS53M64
{
  "balance": "9865607380",
  "locked": "0",
  "unlock_height": 0,
  "nonce": 7
}
Note that Nonce is 7
The 2nd Difference detected for the account that we used for Stacking.
The Balance for today 15/0Feb/2021 should have been as the Wallet and Explorers shows here:
![Screenshot_2021-02-15 STX Address SPCJ5…TSS89](https://user-images.githubusercontent.com/32182666/107971306-1482f580-6f91-11eb-91d0-0d917e65c1c8.png)
For the same account today 15/Feb/2021 the balance is:
stx balance SPCJ50KRRNGKRA5HKZXFWMQWH0TEE2356VQTSS89
{
  "balance": "0",
  "locked": "0",
  "unlock_height": 0,
  "nonce": 0
}

**Expected behavior**
The Balance should be the one displayed by the Wallet or the explorer.  The node balance is not synched or it is not calculating correctly the balance,

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu / Debian] Ubuntu /Web
 - Rust version
 - Version of the appropriate binary / software package

**Additional context**
Please include any relevant stack traces, error messages and logs.

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

**Comment by diwakergupta** [comment]
@paradigma-cl we're deploying a new release to the nodes that power the Hiro hosted API. Until those nodes are fully caught up you might see incomplete data (you'll see a notice on the Explorer).
