### ISSUE TITLE
[Feature request] possible improvements to local regtest setup

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#2455]
After spending a bunch of time familiarizing myself with a local regtest setup with puppet chain, a miner, and a follower, I'm wondering if we can potentially update a few things:

- Support a configurable reward cycle length 
  - right now this is hard-coded for 5 blocks with a 1-block prepare phase. I believe I've heard this adds a lot of slowness while nodes sync, but I'm really not sure.
  - A configuration in the `toml` file would be great here
- Allow immediate mining on regtest
  - It seems like puppet-chain automatically mines 300 blocks - is this to give the Stacks miner funds? It takes quite a while for a node just to sync up to 300 blocks. Possibly related to the reward cycle length?
  - The nodes also seem to be doing the PoX `F*w` calculations during these blocks, even though there is no stacks chain tip yet
- Support `use_test_genesis_chainstate = true` in a regtest setup. 
  - It seems like this is ignored?

I'm really only doing this so I can test BNS stuff with Atlas/attachments, which are not supported on mocknet (please correct if I'm mistaken). After quite a few hours (mainly debugging and figuring things out), I haven't actually made progress on a fully successful end-to-end setup with a subdomain registrar, but hopefully my nodes will be all set in the morning.

**Comment by lgalabru** [comment]
> I'm really only doing this so I can test BNS stuff with Atlas/attachments, which are not supported on mocknet (please correct if I'm mistaken).

I just pushed a fix in the PR `fix/atlas-fixes` and tested it, I was able to get attachments resolved + events from it.

**Comment by reedrosenbluth** [comment]
> Support a configurable reward cycle length
From my testing, setting `pox_sync_sample_secs = 0` in your node's config toml drastically speeds up syncing

**Comment by jcnelson** [comment]
I think this is all addressed now @hstove  -- please re-open if not.  Thanks!
