### ISSUE TITLE
Add Dockerfile for building binaries on macos-arm64

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#2458]
[In our CI](https://github.com/blockstack/stacks-blockchain/blob/master/.github/workflows/stacks-blockchain.yml#L82:L82), we have actions that run through the Dockerfiles in `build-scripts` and build binaries for each platform. These are really helpful, especially with the integration into `clarity-js-sdk`.

However, we do not have a `Dockerfile.macos-arm64` build script. When users install `clarity-js-sdk` on Apple Silicon, they need to pass ENV vars to build from source. The DX could be much improved by building binaries automatically.

I did spend some time trying to fiddle with a new `Dockerfile.macos-arm64` build script, but it was a bit out of my depth, especially the `osxcross` stuff. I'm happy to come back to it and try again - it's a good learning process. Building the optimized binaries without Docker are straightforward, fortunately.

If it turns out that `osxcross` is not quite ready for this build target, then another option is to essentially clone the `Dockerfile.macos-x64` file and rename it to `macos-arm64`. This will not be optimized, but the binaries run fine on Apple Silicon, and it would greatly improve the DX for folks who like to download pre-built binaries.

**Comment by zone117x** [comment]
@hstove do you have an M1 or know someone who does who can test this build output? 
https://github.com/blockstack/stacks-blockchain/pull/2456

**Comment by kantai** [comment]
Closing this in favor of #2419
