### ISSUE TITLE
Emit "selected PoX recipient slot" details in `new_burn_block` events

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2463]
Right now, burn block events just report which addresses received rewards, but not which addresses had the "slots" for that block.

For example, if addresses A and B were chosen for block 1, addresses C and D were chosen for block 2, and then a miner commitment from block 1 ended up getting included in block 2, the stacks-node would report rewards for addresses A and B in both blocks.

With the improved RBF logic, this should happen less frequently, but we should also update the burn block events to report who claimed the actual slot -- that way we'd also be able to track when slots were "missed" (e.g., due to too-fast bitcoin blocks).

**Comment by jcnelson** [comment]
Fixed in #2479
