### ISSUE TITLE
Automated API documentation

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain#2468]
**Status quo**
We have multiple API docs for RPC endpoints - all of which are managed manually and by different individuals:
- https://github.com/blockstack/stacks-blockchain/blob/master/docs/rpc-endpoints.md - @kantai 
- https://github.com/blockstack/stacks-blockchain-api/blob/master/docs/openapi.yaml -  @zone117x 
- https://docs.blockstack.org/understand-stacks/stacks-blockchain-api - @agraebe 
- [Postman collection](https://app.getpostman.com/run-collection/614feab5c108d292bffa#?env%5BStacks%20Blockchain%20API%5D=W3sia2V5Ijoic3R4X2FkZHJlc3MiLCJ2YWx1ZSI6IlNUMlRKUkhESE1ZQlE0MTdIRkIwQkRYNDMwVFFBNVBYUlg2NDk1RzFWIiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJibG9ja19pZCIsInZhbHVlIjoiMHgiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6Im9mZnNldCIsInZhbHVlIjoiMCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoibGltaXRfdHgiLCJ2YWx1ZSI6IjIwMCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoibGltaXRfYmxvY2siLCJ2YWx1ZSI6IjMwIiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJ0eF9pZCIsInZhbHVlIjoiMHg1NDA5MGMxNmE3MDJiNzUzYjQzMTE0ZTg4NGJjMTlhODBhNzk2MzhmZDQ0OWE0MGY4MDY4Y2RmMDAzY2RlNmUwIiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJjb250cmFjdF9pZCIsInZhbHVlIjoiU1RKVFhFSlBKUFBWRE5BOUIwNTJOU1JSQkdRQ0ZOS1ZTMTc4VkdIMS5oZWxsb193b3JsZFxuIiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJidGNfYWRkcmVzcyIsInZhbHVlIjoiYWJjIiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJjb250cmFjdF9hZGRyZXNzIiwidmFsdWUiOiJTVEpUWEVKUEpQUFZETkE5QjA1Mk5TUlJCR1FDRk5LVlMxNzhWR0gxIiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJjb250cmFjdF9uYW1lIiwidmFsdWUiOiJoZWxsb193b3JsZCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiY29udHJhY3RfbWFwIiwidmFsdWUiOiJzdG9yZSIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiY29udHJhY3RfbWV0aG9kIiwidmFsdWUiOiJnZXQtdmFsdWUiLCJlbmFibGVkIjp0cnVlfV0=) - @agraebe 

The current state is resulting in inconsistencies - maybe there is a better way?

**Proposal**
We could do the following:
- Use an OpenAPI spec inside this repo to document RPC endpoints
- Use the [`$ref`](https://swagger.io/docs/specification/using-ref/) feature inside the API repo to pull in RPC endpoint docs. The other endpoints will be documented as previously 
- The docs could use the OpenAPI spec in this repo to [generate a markdown](https://github.com/OpenAPITools/openapi-generator) snippet that would replace the list of RPC endpoints in the doc
- The API repo could [automatically generate a new Postman Collection based on the OpenAPI spec](https://github.com/postmanlabs/openapi-to-postman)

With this solution, we have only one source of truth for RPC docs and one source of truth for all API docs. Thoughts?

**Comment by diwakergupta** [comment]
To be clear, this only impacts the proxied `v2/*` endpoints, not _all_ RPC endpoints, right?

**Comment by agraebe** [comment]
yes - the ones we documented already, but manully
