### ISSUE TITLE
API versioning strategy

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain#2469]
We start to see the need for API updates, some of which would introduce breaking changes. It would be great to come up with an API versioning strategy that would allow us to move fast and advance to the best API design reflecting the most recent understanding but also not to break existing clients.

cc @kantai

**Comment by diwakergupta** [comment]
BTW we do have Discussions enabled on this repo -- might be better for these type of open-ended discussions/questions?
https://github.com/blockstack/stacks-blockchain/discussions

**Comment by agraebe** [comment]
ohh, nice! I forgot about this. closing the issue in favor of the discussion.
