### ISSUE TITLE
Testing: allow usage of short-hand smart contract address reference in `contract-call?`

### ISSUE THREAD

**Issue by philipdesmedt** [blockstack/stacks-blockchain#2478]
When using a call to a smart contract using the short-hand syntactic sugar (e.g. `(contract-call? .oracle get-price)`), you cannot execute unit tests without adjusting them with a reference to the (locally or deployed) smart contract.

Running a unit test generates the following error:

![image](https://user-images.githubusercontent.com/577420/109201606-563a4a00-77a2-11eb-9b47-c3306690ce3e.png)

As a result, you have to add the actual smart contract address for the tests to succeed. The expectation would be a successful unit test where the address of the contract gets resolved automatically.

**Comment by jcnelson** [comment]
Hey @philipdesmedt, what are you using to run the unit tests?  Can you give us some more context on how to reproduce this?

**Comment by lgalabru** [comment]
I think this error is raised by the clarity-js-sdk, itself using `clarity-cli` (produced by this repo).

**Comment by philipdesmedt** [comment]
@jcnelson I run the test with `npm test test/unit/stx-reserve.ts` from my repo here: https://github.com/philipdesmedt/arkadiko-dao/blob/master/test/unit/stx-reserve.ts

**Comment by jcnelson** [comment]
Confirmed the problem -- the `clarity-cli check` directive uses a transient contract ID, which is different from the contract ID used to instantiate the other contracts.  This makes it impossible to use the short-hand notation `.oracle`.  

I have a PR here that adds the option to add a contract-id to the `clarity-cli check` invocation here: https://github.com/blockstack/stacks-blockchain/pull/2486.  We'll want to update `clarity-js-sdk` to use it, but at least you can directly check your contracts as follows:

```
$ clarity-cli check ./contracts/stx-reserve.clar /tmp/blockstack-local-1614458833-uk5i11.db/ SP3GWX3NE58KXHESRYE4DYQ1S31PQJTCRXB3PE9SB.stx-reserve
Checks passed.
```

**Comment by philipdesmedt** [comment]
Thanks @jcnelson - I'll try that.

The more "structural" problem you face with this bug is that you can't commit both your unit & integration tests and have them succeeding at the same time. Or you choose to hardcode the contract address, and make the unit tests work.. or you use the short-hand notation and have the integration tests on mocknet work.. but you currently can't have both, which makes it hard to integrate CI into a maturing Stacks project.

**Comment by jcnelson** [comment]
Oh I agree -- it's definitely a bug.  Going to send a PR against `clarity-cli-js` after this that plumbs this change through.

**Comment by jcnelson** [comment]
I've sent a PR to the `clarity-js-sdk` that should fix this.  No code changes are needed on your end, but you will need to use the `clarity-cli` binary produced in #2486 (e.g. manually drop it into `node_modules/@blockstack/clarity-native-bin/.native-bin/v24.3.3.0-xenon/clarity-cli), and use the PR to `clarity-js-sdk` here: https://github.com/blockstack/clarity-js-sdk/pull/148.

I've confirmed that your tests pass with both:

```
$ npm test test/unit/stx-reserve.ts

> arkadiko-dao@0.0.1 test /tmp/arkadiko-dao
> mocha "test/unit/stx-reserve.ts"



  stacks reserve test suite
    ✓ should have a valid syntax (951ms)


  1 passing (1s)

```

**Comment by philipdesmedt** [comment]
@jcnelson awesome, thanks for the quick turnaround. Will try!
