### ISSUE TITLE
all_burns in DEBG output in chronological order, not value-sorted order

### ISSUE THREAD

**Issue by eikeikeik** [blockstack/stacks-blockchain#2485]
Currently the all_burns in debug output of a stacks node is in value-sorted order:

Example: all_burns=[1,1,20000,20000,20000,20000]

This might be useful for determining median value. However, the median value is already indicated in the same output line. The requested functionality has the last 6 burns in chronological order so you can see which blocks you have missed:

e.g. all_burns=[20000,20000,1,1,20000,20000]

**Comment by pavitthrap** [comment]
Finished in #2488
