### ISSUE TITLE
“Send many “

### ISSUE THREAD

**Issue by selcuk73** [blockstack/stacks-blockchain#2487]
What is that 

**Describe the bug**

**Steps To Reproduce**
Please provide detailed instructions (e.g. command line invocation with parameters) to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu / Debian]
 - Rust version
 - Version of the appropriate binary / software package

**Additional context**
Please include any relevant stack traces, error messages and logs.

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

**Comment by jcnelson** [comment]
Empty bug report
