### ISSUE TITLE
Miner produce ~2% more transactions than blocks mined

### ISSUE THREAD

**Issue by MaksimalistT** [blockstack/stacks-blockchain#2489]
**Describe the bug**
Miner produce ~2% more transactions than blocks mined

**Steps To Reproduce**
Collect stats.
What if add additional debug log in order to track the event when transaction is produced without the block being mined.

**Expected behavior**
Miner produce equal amount of transactions to blocks mined

**Environment (please complete the following information):**
 - OS: Amazon Linux
 - Rust version: rustc 1.49.0 (e1884a8e3 2020-12-29)
 - Stacks-node 2.0.6, 2.0.7

**Comment by diwakergupta** [comment]
> **Describe the bug**
> Miner produce ~2% more transactions than blocks mined
>
> **Expected behavior**
> Miner produce equal amount of transactions to blocks mined

Sorry, what's the bug here? There's no expectation that miners produce the same number of transactions as blocks mined -- if anything, we _should_ expect there to be way more transactions than blocks (which is certainly the case right now). Can you clarify @MaksimalistT ?

**Comment by MaksimalistT** [comment]
Got it,
could you please change it to feature request to add more logs in order to be able to track when it happens, understand better the cause and tune miner configuration.
This loses could become critical for mining operations when margin shrinks

**Comment by diwakergupta** [comment]
> Got it,
> could you please change it to feature request to add more logs in order to be able to track when it happens, understand better the cause and tune miner configuration.
> This loses could become critical for mining operations when margin shrinks

For future readers, I believe what this issue is describing is that miners can produce more block-commit transactions (so these are all BTC transactions) than there are Stacks blocks. This can happen for valid reasons. I'm going to close this out, we should open a separate issue(s) with more information on a specific instance that indicates a bug.
