### ISSUE TITLE
`stacks-node` appears to stall during bootup in `develop`

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2491]
This impacted the Xenon miner running an `atlas+develop` branch: the node appeared to stall during bootup due to "nack"s received from the miner's bootstrap node. The miner was able to be nudged out of this state using the chain pusher tool, but there's likely a bug somewhere here that needs to be addressed.

**Comment by jcnelson** [comment]
I think I've figured out why this is -- the relayer isn't waking up the chains coordinator when it receives a _confirmed_ microblock stream, and nothing else.  This happens more often than not, and really should be the cause of a wake-up event.  The current code erroneously uses either the arrival of a Stacks block or an _unconfirmed_ microblock, but ignores the arrival of _confirmed_ microblocks.  Will send a PR once my testnet node finishes sync'ing.

**Comment by jcnelson** [comment]
Yup, that was the problem.  Confirmed that my testnet node continuously streams blocks and microblocks with the fix.

![blocks-and-microblocks](https://user-images.githubusercontent.com/459947/110670019-dd38ea80-81c4-11eb-8a1d-e250ca9d7b66.png)

**Comment by jcnelson** [comment]
PR sent
