### ISSUE TITLE
Improve typing in contexts.rs and vm/mod.rs

### ISSUE THREAD

**Issue by pavitthrap** [blockstack/stacks-blockchain#2506]
Currently, `sender` and `caller` have types `Option<Value>` in multiple places. We can refactor the types to be just `PrincipalData`, since neither of these values should be `None` in any realistic context.

**Comment by jcnelson** [comment]
Looks like this is a dup of #1812.  Want to close one of these two issues?

**Comment by pavitthrap** [comment]
Closing this one!
