### ISSUE TITLE
PoX Updates: Implement 2.1 data port from `pox` -> `pox-v2`

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2536]
As part of the 2.1 PoX updates, a data migration from the `pox` contract to `pox-v2` must be implemented.

**Comment by jcnelson** [comment]
There's no way this could be handled in Clarity via `(at-block)`, could it?  i.e. we'd want `pox-v2` to take effect immediately, and as such we wouldn't know the block hash or the Stacks block height?

**Comment by jcnelson** [comment]
I think this is superseded by #2610, so closing this issue in favor of that issue instead.
