### ISSUE TITLE
Stacks 2.1: Clarity contract-call interposition

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2537]
As part of the upgrade to Stacks 2.1, the Clarity VM needs to implement a way to interpose on contract-calls. This is necessary for:

1. `pox` -> `pox-v2` interposition
2. New native functions implemented via "extension contract"

**Comment by jcnelson** [comment]
Update: we're not actually going to need to do this, since it's safer and easier to explicitly call the new .pox contract
