### ISSUE TITLE
Ability to query PoX consensus data from Clarity 

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#2551]
What's our take on adding a `pox` key to `get-block-info?`, such as `(get-block-info? pox <block-id>)` returns a tuple `(list 2 { recipient: principal, total-transfered: uint })`?

**Comment by jcnelson** [comment]
Let's do it.  Already have a comment on it here: https://github.com/blockstack/stacks-blockchain/issues/2538#issuecomment-806133320

**Comment by jcnelson** [comment]
Closing in favor of #2538
