### ISSUE TITLE
Event leak resulting in "Too many peers"

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain#2552]
Version: `stacks-node 2.0.10 (master:59363a2+)`

As observed on two of the seed nodes and also reported by other node operators. Per one of these operators, this bug doesn't manifest in 2.0.9, but does manifest in 2.0.10. @jcnelson indicated that the bug might already be fixed in `develop`, but AFAIK we don't have a reliable repro nor a regression test that conclusively verifies the fix.

Symptom: after a while, node starts reporting "Too many peers" and at this point the node becomes completely unresponsive. This seems to affect NAT-ed nodes.

`Too many peers, closing TcpStream { addr: 172.25.10.43:20443, peer: 50.19.243.132:57988, fd: 140 } (events: 802, in-flight: 0, capacity: 800)`

**Comment by jcnelson** [comment]
I no longer believe this is happening in `develop`.  I thought it was earlier today, but despite spinning up nodes multiple times to reproduce it, I can't seem to do so.  Will keep trying.

**Comment by jcnelson** [comment]
I've been leaving testnet and mainnet nodes running, both behind NATs and in public, based on #2549.  I haven't been able to reproduce this issue, even though I can reliably reproduce it in `master` under the same conditions.
