### ISSUE TITLE
there is no money left in the wallet. What to do?

### ISSUE THREAD

**Issue by dokvad1976** [blockstack/stacks-blockchain#2566]
Please help me.How do I get the pubkey and secret key on 1wizSAYSbuyXbt9d8JV8ytm5acqq2TorC this address? And why does the money that came to it go **further?

![willet1](https://user-images.githubusercontent.com/71470991/113532745-a4b9e000-95bb-11eb-9a6a-85142da16862.png)
![willet2](https://user-images.githubusercontent.com/71470991/113532764-ad121b00-95bb-11eb-9237-166197f5983c.png)

**Comment by diwakergupta** [comment]
Please use issues to submit bug reports, feature requests etc. For technical support, please use the Forums or Discord. I'm not seeing a bug here, hence closing.
