### ISSUE TITLE
request=true: failed to send on HTTP conversation

### ISSUE THREAD

**Issue by dokvad1976** [blockstack/stacks-blockchain#2577]
INFO [1617777741.628578] [src/net/relay.rs:997] [relayer] Processing newly received Stacks blocks: 1, microblocks: 0
INFO [1617777762.547633] [src/net/rpc.rs:2478] [p2p] http:id=239,request=true: failed to send on HTTP conversation: SendError("Failed to send 155 bytes")
INFO [1617777762.549249] [src/net/rpc.rs:2478] [p2p] http:id=240,request=true: failed to send on HTTP conversation: SendError("Failed to send 154 bytes")
WARN [1617777771.350802] [src/net/p2p.rs:4153] [relayer] Transaction rejected from mempool, {"error":"transaction rejected","reason":"TooMuchChaining","reason_data":{"actual":3001,"expected":26,"is_origin":true,"message":"Nonce would exceed chaining limit in mempool","principal":"SP31596TY1N33159BQCVEC9H16HP0KQ2VTD140157"},"txid":"a29423000aacf28582741346ccfa662ef8143d47d60271b6df43a1d0e0222db0"}
INFO [1617777774.908561] [src/chainstate/burn/db/sortdb.rs:3396] [chains-coordinator] ACCEPTED(671108) leader block commit 5ecb66484270cf3e6151a8e39e9f6f1216c677035b28fbb7adbfe12ddf364d42 at 671108,23, apparent_sender: 1ASEW7rDjPR131SD96iPvRXRAzTsQ1Nd3V

**Comment by dokvad1976** [comment]
Помогите пожалуйста. Возникает постоянно вот такая ошибка. Я менял в config стоимость за байт, но тогда выходит другая ошибка как на скрине. Подскажите в каком файле искать проблему.
![Uploading Error.png…]()

**Comment by diwakergupta** [comment]
spam
