### ISSUE TITLE
Stx transactions still in pending

### ISSUE THREAD

**Issue by NickJack99** [blockstack/stacks-blockchain#2594]
Hi these are my stx pending transactions about 15 hours
2021-04-19 00:39:50 | 99.999 STX | 0x125a7ec4bfcc96ffaa72fe85ceb89e3f523c4f4063f3b461b46b5cea36c136a7 | 0/3 | pending
-- | -- | -- | -- | --
2021-04-19 00:06:02 | 99.999 STX | 0x9ca2f2e887d67af589de1602529a0b28aa673d1dcfd28e4407dace345975bc64 | 1/3 | pending
2021-04-18 22:38:43 | 99.99 STX | 0x512ec7f6e60ac7eaa223acbf420b9f2a79237302348a2adea47756bb75a06391 | 2/3 | pending

**Comment by 314159265359879** [comment]
They show as confirmed when I look at the explorer respectively on 0/3 on anchor block 679711 and 1/3 at 679709 and 2/3 at bitcoin block 679705.
https://explorer.stacks.co/txid/0x125a7ec4bfcc96ffaa72fe85ceb89e3f523c4f4063f3b461b46b5cea36c136a7?chain=mainnet
https://explorer.stacks.co/txid/0x9ca2f2e887d67af589de1602529a0b28aa673d1dcfd28e4407dace345975bc64?chain=mainnet
https://explorer.stacks.co/txid/0x512ec7f6e60ac7eaa223acbf420b9f2a79237302348a2adea47756bb75a06391?chain=mainnet

Latest block confirmed had bitcoin block height: #679762

**Comment by NickJack99** [comment]
And what can i do now

**Comment by 314159265359879** [comment]
What were you using to view the transaction status? (what wallet, what browser name, version etc). It looks a lot like what you were viewing was not properly updating.

**Comment by NickJack99** [comment]
I am using gate .io

**Comment by NickJack99** [comment]
And Google Chrome

**Comment by NickJack99** [comment]
By the official app gate.io i see dame transactions in pending

**Comment by 314159265359879** [comment]
Gate.io is an exchange right? are you transferring into it?
Sometimes exchanges wait for more confirmations, they usually have their own protocols. Best to contact them if your account has not been credited yet. On the network your transactions are confirmed.

**Comment by NickJack99** [comment]
They don t answer me....

**Comment by 314159265359879** [comment]
> 
> 
> They don t answer me....

I am afraid I can not influence that. You could try contacting them again. You could add the three links from the explorer to show that they have been confirmed and ask why they are still pending in your wallet. I am sure you have already tried restarting the app, otherwise you could try that, maybe it is only the user interface that is not updating.

**Comment by diwakergupta** [comment]
Issues in this repo are meant to track bugs or feature requests for the stacks-blockchain. This is neither, hence closing.
