### ISSUE TITLE
Extension contract: tx-sponsor

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2614]
Right now, Stacks 2.1 has a `tx-sponsor` keyword that resolves to the `(optional principal)` that represents the Stacks transaction sponsor.  Trouble is, this can't be a keyword -- contracts today can use this variable name today, and in doing so, make it impossible to represent this functionality as a keyword without breaking these existing contracts.  The `tx-sponsor` keyword will need to be refactored into an extension contract.

The extension contract can use the same functionality in the VM; it just needs to be handled via a `contract-call?` interception instead of a built-in variable.

This is partially blocked on #2607

**Comment by gregorycoppola** [comment]
Is there a syntactic difference between the two of these? Like, does a zero-argument function get called in a way that looks like a variable?

**Comment by jcnelson** [comment]
Yes -- a zero-argument function call is `(function_name)`, whereas a variable is simply `variable_name`.

Example:

```
(let (
   (recipient 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR))
   (stx-transfer? u1 tx-sender recipient)
   (stx-transfer? u1 tx-sender (tx-sponsor)))

**Comment by gregorycoppola** [comment]
I talked to @kantai  offline. This issue should be modified:

1) We should introduce version-based gating for variable names.
2) 'tx-sponsor?' should not become a function, but should stay a variable name.

**Comment by jcnelson** [comment]
Sounds good to me.  At the time this issue was written, we were going to try and implement all the 2.1 Clarity features as extension contracts, which precluded adding new global variables.  But now that that's an option, it makes a lot more sense to simply treat `tx-sponsor` as a variable.

This greatly simplifies this issue, since @pavitthrap already implemented `tx-sponsor` in the `next` branch.  All that really needs to happen here is to gate access to it.
