### ISSUE TITLE
Extension contract: stx-transfer-memo?

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2615]
In Stacks 2.1 right now, `stx-transfer?` can take an optional memo field.  Unfortunately, the presence of this change would mean the parser would need to be aware of the epoch rules in order to know which invocations are allowed.

Instead of doing this, I propose refactoring `stx-transfer?` in 2.1 into an extension contract with the public function `stx-transfer-memo?`.  This would do the same things that `stx-transfer` does, but would use the epoch-switching gates that already would exist for all extension contracts (and wouldn't require modifying the analysis logic).

Open to push-back on this.

**Comment by gregorycoppola** [comment]
@jcnelson Is this feature definitely wanted as it's described here?

Can we consider the idea of the parser knowing which clarity version we have?

The benefit of such a change, I think, is that languages typically keep the same function names when upgrading. I think it's confusing to change.

I also wonder if having the parser be aware of the version would really be that hard?

**Comment by jcnelson** [comment]
Yes, 100%.  Let's not touch the parser if we can help it.  I do not believe this is confusing at all; I think methods with the same name but that take different numbers of arguments are confusing, because they leave room for programmer error (e.g. you could accidentally omit the memo field in a polymorphic `stx-transfer?`, but you *couldn't* if there was an explicit `stx-transfer-memo?`).

**Comment by gregorycoppola** [comment]
@jcnelson It seems like, currently, there is no slot for the 'memo' in the STXTransferEventData.

https://github.com/blockstack/stacks-blockchain/blob/85f07f1aa74638458ac118627477d05936994841/src/chainstate/stacks/events.rs#L185

https://github.com/blockstack/stacks-blockchain/blob/85f07f1aa74638458ac118627477d05936994841/src/vm/contexts.rs#L1178

Is the idea that I should add it? And, then, the unit test would be to check that this event is created with a memo filled?

**Comment by kantai** [comment]
Yep -- I think we should add an `Option` type to the event for carrying the memo

**Comment by gregorycoppola** [comment]
Oh. I just realized that 'stx-transfer' has already been updated with the memo field: https://github.com/blockstack/stacks-blockchain/commit/c55808d9b5321ec09510152185cdfb99b25c249c

So, this PR is just to factor that out (?).

**Comment by kantai** [comment]
> So, this issue is just to factor that out (?).

Yep,

**Comment by kantai** [comment]
> So, this issue is just to factor that out (?).

Yep, pretty much
