### ISSUE TITLE
Extension contract: buff to/from integers

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2616]
There needs to be an extension contract that converts `(buff 16)` to and from `int` or `uint`, big-endian or little-endian.

**Comment by gregorycoppola** [comment]
Any thoughts on what the interface for this function should be?

e.g.


option 1 (buff-to-int big-endian my-buffer)
option 2 (buff-to-number int big-endian my-buffer)
option 3 (buff-to-int-big-endian my-buffer)

**Comment by jcnelson** [comment]
Space is a premium, so I'd recommend making it as terse as can be while remaining comprehensible.  Also, I think the endianness should be part of the function name, not an argument, to keep parsing costs down.  Keep in mind that this issue is calling for four functions: both signed and unsigned integers, as well as big and little endian should be supported.

Example:
```
(let (
  (input (as-max-len? 16 0xaabbccdd)))
 ((as-uint-be input)  ;; buff-16 to uint, big-endian
  (as-int-be input)   ;; buff-16 to int, big-endian
  (as-uint-le input)  ;; buff-16 to uint, little-endian
  (as-int-le input))) ;; buff-16 to int, little-endian
```

**Comment by lgalabru** [comment]
On the signature, I think we should keep in mind the fact that we already have a `(to-uint ...)`, that converts a int to uint.
We could either use that convention, or we could also "fully qualify" the conversion to disambiguate, starting from Clarity 2 (int-to-uint, buff-to-uint, etc). 
Also, should we have `(buff-to-int-be ...)` and `(buff-to-int-le ...)`, or just `(buff-to-int ...)` and introduce a native `(reverse ...)`?
Curious to get some thoughts from @kantai as well!

**Comment by kantai** [comment]
> or we could also "fully qualify" the conversion to disambiguate, starting from Clarity 2 (int-to-uint, buff-to-uint, etc).
Also, should we have (buff-to-int-be ...) and (buff-to-int-le ...), or just (buff-to-int ...) and introduce a native (reverse ...)?

I agree with this -- `to-uint` already means something and so we should disambiguate in the function names.

As for endianness, I'm a little more on the fence, but leaning towards supplying endian-specific functions. While `reverse` would be able to avoid this, it requires that Clarity pick a "default" endianess, _and_ developers remember that.

**Comment by psq** [comment]
agree with taking a hint from `to-uint`, as for using `buff`, I don't think that's necessary as the param type should make that obvious.

so use

```
to-uint-be
to-int-be
to-uint-le
to-int-le
```

Also assuming the `(buff 16)` contains up to 16 bytes, but can contain less, right?

**Comment by gregorycoppola** [comment]
On the question of whether it can be less than 16 bytes:

1) The underlying rust functions requires it to be exactly 16 bytes https://doc.rust-lang.org/std/primitive.u128.html#method.from_le_bytes

2) So, we would have to pad it. Would that mean padding to the left with zeroes for big-endian, and to the right for little-endian? Is that confusing?

**Comment by psq** [comment]
even though passing 15, 14, 13... is probably of little use, being able to decode 8, 4, 2, 1 byte integers without adding one function per size (which would be an ok solution too, but maybe less ideal), and having the function decode the size of the buffer and pad to do what seems logical to the user would make sense to me, so yes, this would mean padding with 0s in the proper place to get the correct integer value.
The fact you'd have to pad is purely an implementation details because of the function used to do the decoding.  From the user's perspective, I'm passing 4 bytes, and expect to get the right value given the endianness (if that's a word...)

**Comment by gregorycoppola** [comment]
Yes. I guess padding is not that confusing.

**Comment by gregorycoppola** [comment]
@jcnelson @kantai @lgalabru Should I change pull/2691 so that the user can supply < 16 bytes in the buffer?
