### ISSUE TITLE
Extension contract: string-ascii/string-utf8 to/from int and uint

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2617]
There needs to be an extension contract that converts a `string-ascii` or a `string-utf8` to/from a `int` or `uint`.

**Comment by gregorycoppola** [comment]
What should the interface be for this one?

It seems to me that we can dynamically detect variations in the input type (i.e., ascii vs utf8, uint vs int). But, the function name should specify the output type.

(string-to-int either_string_type)
(string-to-uint either_string_type)
(int-to-string-ascii either_int_type)
(int-to-string-utf8 either_int_type)

**Comment by gregorycoppola** [comment]
Any thoughts on the interface question above @jcnelson ?
