### ISSUE TITLE
Epoch switch: fix and gate behavior of `principal-of`

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2619]
`principal-of` is broken on mainnet.  This needs to be fixed in 2.1, but the fixed logic must only activate when the epoch switches.

**Comment by jcnelson** [comment]
It always produces a testnet principal from a public key.  It needs to produce a testnet principal only on testnet, and a mainnet principal only on mainnet.

**Comment by gregorycoppola** [comment]
Thanks. And, then, should it always be producing a "single sig" address? So that, the choice is only between?
1) `C32_ADDRESS_VERSION_TESTNET_SINGLESIG`
2) `C32_ADDRESS_VERSION_MAINNET_SINGLESIG`

**Comment by jcnelson** [comment]
Yes, that's correct.  `principal-of` is only meant to act on single public keys using the p2pkh hashing method.
