### ISSUE TITLE
Reliability improvements: tolerate empty sortitions in prepare phase 

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2621]
When evaluating the prepare phase, allow up to 10 empty sortitions without penalizing the network quality.  That is, refine the PoX activation criterion from `F * w >= 80` to `F * w >= 80 - min(E, 10)` where `E` is the number of empty sortitions during the prepare phase.

**Comment by kantai** [comment]
I think this is a duplicate of https://github.com/blockstack/stacks-blockchain/issues/2535 -- closing
