### ISSUE TITLE
Reliability improvements: accurate runtime costs

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2623]
Right now, the runtime costs in the `.costs` contract are too pessimistic.  We need to accurately determine how truly costly these functions are relative to one another, and set compute costs correctly.  We have a chance to fix this all at once in the 2.1 epoch.

To implement this, we'll likely need to gate access to the cost functions at the epoch boundary.  That is, we'll create a `.costs-2.1` contract with the appropriate runtime costs, and update the cost-tracking code to load the appropriate cost functions based on what epoch it's in (but continue to defer to any cost-votes that have finalized, should that occur before the epoch switch).

**Comment by jcnelson** [comment]
Next steps:

* @pavitthrap and @reedrosenbluth to review all benchmarks
* run benchmarks on the target hardware (TBD)
* review Jupyter notebook's graphs to verify that behavior matches the expected asymptotic behavior
* avoid arithmetic overflow in tests
* vary the size of blocks in the fake MARF used for benchmarking in order to get a better estimate on the performance of I/O-bound functions

**Comment by kantai** [comment]
Relevant repository: https://github.com/blockstack/clarity-benchmarking
