### ISSUE TITLE
Epoch switch: gate access to the default cost functions

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2624]
Because the cost functions are likely to change in 2.1 (#2623), we'll need to make sure that the cost-tracking logic loads the appropriate cost functions at the right epoch.

**Comment by jcnelson** [comment]
One possibility: have the epoch-switch logic "vote in" the new cost functions, so we don't have to add gating in Rust.

**Comment by pavitthrap** [comment]
Dupe of next-cost issue #2874. 

Implemented in #2888.
