### ISSUE TITLE
STX transfer from testnet to mainnet address

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2640]
**Describe the bug**
STX can be send from a testnet address to a mainnet address:
https://explorer.stacks.co/txid/0x6a2a56ed130de82d3126ba28b5cd055233b147a5a3b1a7b698a4e056d8878526?chain=testnet

**Steps To Reproduce**
Use send many contract

**Expected behavior**
Reject tx because of invalid address version

**Comment by jcnelson** [comment]
Per the blockchain meeting, this is not a bug, but a feature.  The wallet and tooling should, however, warn the user when the address(es) supplied are "non-standard" -- i.e. have version bytes that the network does not recognize.

**Comment by friedger** [comment]
@jcnelson Can you elaborate why this is a feature?

Using testnet principal on mainnet https://explorer.stacks.co/txid/0x187c01618101c219922cc77f0ac2cac212851e2d99959a431265d80b1c45c9a1?chain=mainnet resulted in rejected transactions for pox contract calls:
```
(node:14804) UnhandledPromiseRejectionWarning: Error: failed to handle transaction 07d49558db8737c1d62471f647739ef717497f470d6d06f578a8fc995c724031: {"error":"transaction rejected","reason":"BadAddressVersionByte","txid":"07d49558db8737c1d62471f647739ef717497f470d6d06f578a8fc995c724031"}
    at Object.handleTransaction 
```

**Comment by jcnelson** [comment]
It's a future-proofing mechanism.  New address versions can indicate principals that have different properties (such as different authentication modes) than the current single-sig and multi-sig modes.  In fact, we're slated to add an alternative multi-sig mode in 2.1 that allows signers to sign in any order (whereas right now, they must sign in a fixed order).

The error you're seeing is from the mempool, which rejects transactions with sender or sponsor address versions it doesn't recognize.  But I don't believe that the chainstate-processing logic cares about the address version (but I'd have to check to confirm).
