### ISSUE TITLE
Extension contract: determine whether or not an address is a "standard" address

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2642]
Make an extension contract that takes a `principal` and determines whether or not its version byte is recognized by the network.

**Comment by gregorycoppola** [comment]
Which "version bytes" are supposed to be recognized by the network?

**Comment by jcnelson** [comment]
No, these ones:

`src/chainstate/stacks/mod.rs`

```
pub const C32_ADDRESS_VERSION_MAINNET_SINGLESIG: u8 = 22; // P
pub const C32_ADDRESS_VERSION_MAINNET_MULTISIG: u8 = 20; // M
pub const C32_ADDRESS_VERSION_TESTNET_SINGLESIG: u8 = 26; // T
pub const C32_ADDRESS_VERSION_TESTNET_MULTISIG: u8 = 21; // N
```

This issue calls for a method that takes a `principal` and returns a `bool` as to whether or not the c32check portion is usable on this network.  For example, `SPxxxx` and `SMxxxx` addresses are only usable on mainnet, whereas `STxxxx` and `SNxxxx` are only usable on testnet and regtest.

**Comment by gregorycoppola** [comment]
What would you call this function?

**Comment by jcnelson** [comment]
How about `is-standard`?

On mainnet:
`(is-standard 'SP2HF9A8BDYAHW8JTDTS4F3TE0RVPPYZ2J9A5K8CV) ;; true`
`(is-standard 'SP2HF9A8BDYAHW8JTDTS4F3TE0RVPPYZ2J9A5K8CV.foo) ;; true`
`(is-standard 'SM2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQVX8X0G) ;; true`
`(is-standard 'SM2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQVX8X0G.foo) ;; true`
`(is-standard 'ST2HF9A8BDYAHW8JTDTS4F3TE0RVPPYZ2JBH0EFSK) ;; false`
`(is-standard 'ST2HF9A8BDYAHW8JTDTS4F3TE0RVPPYZ2JBH0EFSK.foo) ;; false`
`(is-standard 'SN2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKP6D2ZK9) ;; false`
`(is-standard 'SN2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKP6D2ZK9.foo) ;; false`
`(is-standard 'S1G2081040G2081040G2081040G208105NK8PE5) ;; false`

On testnet:
`(is-standard 'SP2HF9A8BDYAHW8JTDTS4F3TE0RVPPYZ2J9A5K8CV) ;; false`
`(is-standard 'SP2HF9A8BDYAHW8JTDTS4F3TE0RVPPYZ2J9A5K8CV.foo) ;; false`
`(is-standard 'SM2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQVX8X0G) ;; false`
`(is-standard 'SM2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQVX8X0G.foo) ;; false`
`(is-standard 'ST2HF9A8BDYAHW8JTDTS4F3TE0RVPPYZ2JBH0EFSK) ;; true`
`(is-standard 'ST2HF9A8BDYAHW8JTDTS4F3TE0RVPPYZ2JBH0EFSK.foo) ;; true`
`(is-standard 'SN2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKP6D2ZK9) ;; true`
`(is-standard 'SN2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKP6D2ZK9.foo) ;; true`
`(is-standard 'S1G2081040G2081040G2081040G208105NK8PE5) ;; false`
