### ISSUE TITLE
Emit miner-relevant prometheus metrics

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2651]
It would be helpful for miners to be able to get more useful miner-relevant prom metrics.

For example:

1. Their computed relative miner score (I think this would be a gauge metric?)
2. Their computed commitment (again a gauge metric)
3. Their current median commitment

There may be some other useful miner-relevant prom metrics, but this would be a start

**Comment by Lucas-Kohorst** [comment]
@kantai thanks for opening this! Having a prometheus metric that exposes the miner score would be extremely helpful, as its a good way to gauge if the miner is preforming as expected without digging through the logs everyday. Ideally using prometheus alerting can be set up when the miner is not performing as expected.
