### ISSUE TITLE
Inability to generate docker build

### ISSUE THREAD

**Issue by dorucioclea** [blockstack/stacks-blockchain#2740]
**Describe the bug**
I am unable to generate a clean docker build using 

`docker build . ` which should generate an alpine build

**Steps To Reproduce**

Run the following 

`docker build .`

**Expected behavior**
Docker command should succeed and create a docker image

**Environment (please complete the following information):**
 - OS: Windows 10

**Additional context**

This seems to be about the  `name_zonefiles` sha hash mismatch 

https://github.com/blockstack/stacks-blockchain/commit/45677475d19a6007e0147ef3431b2eb2489ebbbb#diff-9576931b4e47b927b827aee5a9e6621ee48ebd794321288d936ffb9287db6284

In the above commit the name zonefiles hash seems to have changed but the value doesn't match as shown below

Attaching a screenshot of the docker build error 

![image](https://user-images.githubusercontent.com/39082034/123551230-8d812d80-d779-11eb-9856-7bb7c648df3d.png)

**Comment by wileyj** [comment]
Hey @dorucioclea thanks for the issue - i'll take a look and see what i can find here. 
it may simply be the sha256's aren't correct, but i'll also look into the `docker build .` as whole. 

Is there any documentation you used to try and build this, or just saw the Dockerfile and tried to build it based on it's existence?

**Comment by dorucioclea** [comment]
Hi @wileyj, just tried to build the image on master

**Comment by dorucioclea** [comment]
The command I've referenced above just builds the docker image based off the `Dockerfile` but same happens for the Debian distro. My guess also that the sha256 value isn't correct

**Comment by wileyj** [comment]
Got it, thanks

**Comment by wileyj** [comment]
The sha256 seems fine - can you attach the full build output? I'm running myself but haven't been able to reproduce. 

```
$  sha256sum name_zonefiles.txt
a256860023e6e5a17e07cc647cb01fe75605ecd70a648d9608be3f635874be0e  name_zonefiles.txt

$ cat name_zonefiles.txt.sha256 
a256860023e6e5a17e07cc647cb01fe75605ecd70a648d9608be3f635874be0e
```

**Comment by dorucioclea** [comment]
Alright, I figured this one out. You guys probably build this in linux. Probably because windows has the DOS format, something bad happens when reading plaintext files in a UNIX environment.

**Comment by dorucioclea** [comment]
What I did to make the build work on windows:

```
FROM rust:alpine as build

ARG STACKS_NODE_VERSION="No Version Info"
ARG GIT_BRANCH='No Branch Info'
ARG GIT_COMMIT='No Commit Info'

WORKDIR /src

COPY . .

RUN apk add --no-cache musl-dev dos2unix

RUN find . -type f -print0 | xargs -0 dos2unix

RUN mkdir /out

RUN cd testnet/stacks-node && cargo build --features monitoring_prom,slog_json --release
RUN cd testnet/puppet-chain && cargo build --release

RUN cp target/release/stacks-node /out
RUN cp target/release/puppet-chain /out

FROM alpine

COPY --from=build /out/ /bin/

CMD ["stacks-node", "mainnet"]

```

The change was to add `dos2unix` and have it convert every file copied into the container to the UNIX format

**Comment by wileyj** [comment]
good catch, yes we do indeed build using unix-based systems. 
would you mind PR'ing that change? I can imagine others might also see this issue

**Comment by dorucioclea** [comment]
Yes, I will create a PR 😄

**Comment by wileyj** [comment]
Excellent, thanks again for identifying this for us unix users!
For the PR, just be sure to use the `develop` branch for the target branch.

**Comment by dorucioclea** [comment]
Will do 😄 I think I can also make the build `directly` on windows to work also (it is failing for the same reason). Also, even after you manage to build (I commented out the sha veritication in an attempt to see if it would build before posting this issue) it woudn't start for the same reason because the EOL formatting on smart contracts needs to be the same - Unix. I will try to include all these changes if that's ok
