### ISSUE TITLE
Carriage return not considered as valid ascii/printable string

### ISSUE THREAD

**Issue by dorucioclea** [blockstack/stacks-blockchain#2741]
**Describe the bug**
Carriage return not considered as printable string. 

**Steps To Reproduce**
Try to deploy a contract (counter contract) on windows using the `stacks.js` sdk that has `\r\n`  in it. The broadcastTransaction function will fail with 

`Invalid Stacks string: non-printable or non-ASCII string`

**Expected behavior**
`\r` should be considered valid printable string as well

**Environment (please complete the following information):**
 - OS: Windows 10
 - Docker
 - Both `blockstack/stacks-blockchain:latest` and `blockstack/stacks-blockchain:develop-stretch`
**Additional context**

Sample smart contract here: https://github.com/dorucioclea/stacks-dev-env/blob/aedd1aed32576e0c51a58627f3ad2a7457d6d5bb/contracts/counter.clar#L1

Where this happens: 

https://github.com/blockstack/stacks-blockchain/blob/fe8d3b2a8f3a77123753c10cbb25cb9c4b2e9cfd/src/util/strings.rs#L273

Proposed change: 

```

 pub fn is_printable(s: &String) -> bool {
        if !s.is_ascii() {
            return false;
        }
        // all characters must be ASCII "printable" characters, excluding "delete".
        // This is 0x20 through 0x7e, inclusive, as well as '\t', '\r' and '\n'
        // TODO: DRY up with vm::representations
        for c in s.as_bytes().iter() {
            if (*c < 0x20 && *c != ('\t' as u8) && *c != ('\n' as u8)  && *c != ('\r' as u8)) || (*c > 0x7e) {
                return false;
            }
        }
        true
    }

```

Let me know if this is something you would entertain, I could create a PR

**Comment by jcnelson** [comment]
The omission of carriage return is deliberate, since it is not a printable ASCII character.  If you're using Windows, you may need to convert your text to Unix newline encoding before putting it into a transaction.

**Comment by dorucioclea** [comment]
Cool, thank you 💯
