### ISSUE TITLE
[feature request] Support `sha256` against any data type

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#2752]
I'm working on a system that can validate off-chain-generated signatures from within Clarity. This is already quite do-able with existing features. However, limitations come when trying to validate a signature against a principal. If the principal is a single-signature standard principal, this is do-able with the principal's public key. However, it does not seem possible to validate a signature against a contract or multi-sig principal.

It's possible to support this feature without changing `sha256` if there were other primitives for converting data types into the hash-able data types (int, buff). For example, a function like `(principal-to-buff principal)` could support my desired functionality. Similar for other data types, like `(string-to-buff string-ascii)`.

I wanted to put this issue _somewhere_ just to get my thoughts down, but I know there are many needs for Stacks 2.1, so please feel free to mark this as lower importance.

**Comment by jcnelson** [comment]
Dup: https://github.com/blockstack/stacks-blockchain/issues/2693
