### ISSUE TITLE
Miner doesn't restart properly when mine_microblocks = true

### ISSUE THREAD

**Issue by yknl** [blockstack/stacks-blockchain#2761]
Steps to reproduce:

1. Have miner running with `mine_microblocks = true`
2. Shutdown miner with kill PID
3. Miner restarts and fully syncs
4. Miner does not send out any Bitcoin commits

Restarting again fixes the problem.
This doesn't seem to happen when miner is not mining microblocks.

**Comment by jcnelson** [comment]
The `mine_microblocks = True` setting is actually ignored by the config file parser.

**Comment by yknl** [comment]
> The `mine_microblocks = True` setting is actually ignored by the config file parser.

Then what could be causing the miner to not send out commits? I checked that the miner's utxos were confirmed.

**Comment by jcnelson** [comment]
Do you have `mock_mining` set?  Also, does the debug log indicate that the node has detected your UTXOs when it boots up?

**Comment by yknl** [comment]
I don't have `mock_mining` set and didn't have debug logging enabled. For a period of time on the same node version, this wasn't an issue. However it started happening recently. The only thing I could think of that changed was the `mine_microblocks = true`

**Comment by yknl** [comment]
After further experimentation it seems to be due to not having confirmed UTXOs in the miner address when the miner starts up. Even though by the time the miner is synced and ready to mine, the UTXO's have already been confirmed.

**Comment by diwakergupta** [comment]
So we can close this right @yknl ?
