### ISSUE TITLE
Expose pox delegation state changes to event observer

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#2769]
See issue https://github.com/blockstack/stacks-blockchain-api/issues/465

There's a desire for the node.js API to be able to enumerate and perform other types of queries against PoX delegation state. In order to do this, the stacks-node needs to emit _all_ mutations to the delegation state maps in order for the API to track. 

In this case, I think we need either a new event, or new event data added to an existing event. 

In the future, built-in contracts should attempt to take more advantage of the structured contract-log (i.e. print function) to expose these various kinds of state changes.

**Comment by kantai** [comment]
Thanks for opening this! I'm going to move this content over to #2554 and close this so that it's all captured in one issue.
