### ISSUE TITLE
Fee estimation: New endpoint for obtaining estimates

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2836]
The fee estimation endpoint needs to be updated to provide a true fee rate estimate for transfer operations. Fee rate estimation differs from `ExecutionCost` estimation and the kind of estimation done during block assembly in that fee rate estimation looks at the observed fee rates in the last block produced (and potentially the estimated fee rates in the mempool) and produces an estimated fee rate for inclusion in the next block.

Once a fee rate estimate is obtained, communicating this to clients also requires some changes:

1. The current fee rate endpoint is really only suitable for _transfer_ transactions. This endpoint can be updated to be useful for transfer transactions, and provide a better estimate for other transactions than it currently does. However, this endpoint should probably be marked deprecated.
1. A new endpoint could accept a partial transaction and use that to return the estimated execution cost and estimated fee for the transaction.

Strategy two would require updating dependent libraries: `stacks.js` first, and then any integrators would need to update their scripts, integrations, etc. Wallets like the web wallet and desktop wallet would also need to be updated (though they may just need to update their stacks.js version).

**Comment by markmhx** [comment]
What do we all think about providing three estimate values:

1. **Fast**: Expensive / high value for broadcasting a transaction that will _very_ likely (>95% chance) be picked up by the next anchor block / has large time premium for user
2. **Normal / medium** (for default in wallets, etc): Modest value for broadcasting a transaction that will likely (>60%) be picked up by the next anchor block / has moderate time premium for user
3. **Slow**: Low value for broadcasting a transaction that will likely be picked up within 3-5 anchor blocks / has little to no time premium for user. 

cc @jasperjansz

**Comment by diwakergupta** [comment]
> What do we all think about providing three estimate values:
> 
> 1. **Fast**: Expensive / high value for broadcasting a transaction that will _very_ likely (>95% chance) be picked up by the next anchor block / has large time premium for user
> 2. **Normal** (for default in wallets, etc): Modest value for broadcasting a transaction that will likely (>60%) be picked up by the next anchor block / has moderate time premium for user
> 3. **Slow**: Low value for broadcasting a transaction that will likely be picked up within 3-5 anchor blocks / has little to no time premium for user.

This is an application level concern that IMO doesn't belong in an endpoint exposed by stacks-node -- something like this might be more appropriate for the API.

Regardless, I would strongly discourage using words like "fast" and "slow" -- at best we can talk about probabilities and distributions (so for instance percentiles), but I suggest staying away from words that can be misinterpreted in terms of speed or latency.

**Comment by markmhx** [comment]
Yep that makes sense. Perhaps "high, medium and low" labels would be more appropriate.

I presume clients will be agnostic as to whether these values are provided by the node or API software itself. Though I also presume that the client will need either of them to provide these three distinct values, instead of generating those three based on a _single_ server-provided value. But I'll discuss with the UserX team to get their input here.

cc @andresgalante

**Comment by markmhx** [comment]
Closing this issue out now that https://github.com/blockstack/stacks-blockchain/pull/2872 is released and we have https://github.com/blockstack/stacks-blockchain/issues/2954 for enhancing further.
