### ISSUE TITLE
cargo test testnet fails with "left == right" error

### ISSUE THREAD

**Issue by mrihn** [blockstack/stacks-blockchain#2847]
## Describe the bug

I installed Rust and the support software, cloned the stacks-blockchain repo and ran `cargo build` without any errors (1 warning message), but when I ran `cargo test testnet  -- --test-threads=1` I got the following:

    Finished test [unoptimized + debuginfo] target(s) in 0.12s
     Running unittests (target/debug/deps/blockstack_lib-16d882ece2a84840)

running 2 tests
test clarity::test::test_init_testnet ... ok
test deps::bitcoin::blockdata::constants::test::testnet_genesis_full_block ... FAILED

failures:

---- deps::bitcoin::blockdata::constants::test::testnet_genesis_full_block stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"79a8e69a392983a449d680fe41805aa6ae20829284b1dcbb311264e2be1345d7"`,
 right: `"4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b"`', src/deps/bitcoin/blockdata/constants.rs:199:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:117:5
   4: blockstack_lib::deps::bitcoin::blockdata::constants::test::testnet_genesis_full_block
             at ./src/deps/bitcoin/blockdata/constants.rs:199:9
   5: blockstack_lib::deps::bitcoin::blockdata::constants::test::testnet_genesis_full_block::{{closure}}
             at ./src/deps/bitcoin/blockdata/constants.rs:195:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    deps::bitcoin::blockdata::constants::test::testnet_genesis_full_block

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 1313 filtered out; finished in 1.62s

## Steps To Reproduce

1: Install RUST and make sure it's all setup appropriately
.........................................................
$ curl https://sh.rustup.rs -sSf | sh
$ source $HOME/.cargo/env
$ rustup component add rustfmt
$ rustup update

2: Install these packages
.........................................................
$ sudo apt-get update
$ sudo apt install build-essential git clang libclang-dev pkg-config libssl-dev

3: git clone --depth=1 https://github.com/blockstack/stacks-blockchain

4. Since rust-lld is not pre built, we need to build it
 4.1: git clone https://github.com/WebAssembly/wasi-sdk
 4.2: apt-get install ninja-build
 4.3: cd wasi-sdk
 4.4: git submodule update
 4.5: make package
 4.6: cd build/install/opt/wasi-sdk/bin
 4.7: ln -s lld rust-lld
 4.8: export PATH=<path/of/build/install/opt/wasi-sdk/bin>:$PATH

5: rustup target add wasm32-unknown-unknown
6: cd ../stacks-blockchain
7: cargo build

## Expected behavior

I expected the `cargo test testnet  -- --test-threads=1` command to complete without any failures.

## Environment

Ubuntu "20.04.2 LTS (Focal Fossa)"
rustc 1.55.0 (c8dfcfe04 2021-09-06)
stacks-node 0.1.0 (master:9743464, debug build, linux [s390x])

## Additional context

This build was done on s390x architecture

**Comment by jcnelson** [comment]
Thank you for taking the time to report this.  However, we do not support the s390x architecture.  The test case that's failing isn't even in code we wrote; it's in a vendored test case.
