### ISSUE TITLE
Cost Updates: Implementing block limit change

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#2875]
_Note:_ As discussed in [More Accurate Cost Functions for Clarity Native Function](https://forum.stacks.org/t/more-accurate-cost-functions-for-clarity-native-functions/12386) and recent blockchain meetings, one path forward for updating the costs is a Pre-2.1 fork that _only_ covers cost and block limit updates. Separate from the process of formally proposing, voting on, and confirming such a proposal is the task of actually implementing those changes. This issue is related only to the task of implementing those changes in the `next-costs` branch of this repository.

Currently, a Stacks node has a single notion of the block limit. When the node run loop begins, the chainstate and any other structs that need a view of the block limit are configured with the current block limit (see: [src/run_loop/neon.rs#L236](https://github.com/blockstack/stacks-blockchain/blob/master/testnet/stacks-node/src/run_loop/neon.rs#L236)).

However, in order to change the block limit in a cost-changing fork, nodes will need to switch the block limit used when a given burnchain block has been reached.

**Comment by gregorycoppola** [comment]
> When this is implemented, let's be sure to put the epoch switch height into `Burnchain` or some such so it can be parameterized by tests and on private test networks.

We have this:
https://github.com/blockstack/stacks-blockchain/blob/b18191db524c818798ee93ee553d6b584bdfef84/testnet/stacks-node/src/tests/epoch_205.rs#L490
