### ISSUE TITLE
Cost-updates: pick a Bitcoin block at which they take effect

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2878]
We need to pick a Bitcoin block height at which the new cost-updates in Stacks 2.05 will take effect.

**Comment by jcnelson** [comment]
Well, we're there now.  Let's target a block expected to arrive on November 30, per the SIP-012 PR (https://github.com/stacksgov/sips/pull/41).  Given how Bitcoin difficulty adjusts, let's defer the exact block height decision until when we're closer to the actual date (so we can pick a more accurate number).

**Comment by 0xAsteria** [comment]
@jcnelson I think we should target block ~#711975 for the switch over to 2.05

**Comment by jcnelson** [comment]
Per https://github.com/stacksgov/sips/pull/41, the current proposal is 713,000.

**Comment by jcnelson** [comment]
Officially going with 713,000.  Will close this issue once the code for this gets merged.

**Comment by kantai** [comment]
Closed via #2928
