### ISSUE TITLE
Cost updates: Update function instantiate_epoch_2_05 once costs-2 contract is added

### ISSUE THREAD

**Issue by pavitthrap** [blockstack/stacks-blockchain#2890]
Update the code body for the costs-2 contract in the function `instantiate_epoch_2_05` (in `src/clarity_vm/clarity.rs`) once the contract is added to the repo.

**Comment by jcnelson** [comment]
Still todo:

* ~Update the way the benchmark runs for the AST (ClarityString vs Value)~
* NFT burn must have the same cost as NFT transfer (same for FTs and STX)
    * Functions that should have the same cost must have the same cost
