### ISSUE TITLE
[Clarity] Add `is-contract` function to differentiate contract principal from standard one

### ISSUE THREAD

**Issue by LNow** [blockstack/stacks-blockchain#2919]
**Is your feature request related to a problem? Please describe.**
As a NFT contract developer I'd like to limit minting process to 1 NFT per principal. It doesn't matter what I come up to it is expensive, not user-friendly and easy to bypass with simple proxy contract.

To implement proper solution I need a way to differentiate contract principal from standard principal.

**Describe the solution you'd like**
To implement proper solution I need a way to differentiate contract principal from standard principal.
I'd like to have native `is-contract`function, that returns `true` if provided principal is contract one and `false` if it is standard one.

**Signature:** `(is-contract who)`
**Input:** `principal`
**Output:** `bool`

**Comment by jcnelson** [comment]
Looks like this will be handled by https://github.com/blockstack/stacks-blockchain/pull/2756

**Comment by LNow** [comment]
Yes, looks like with `principal-parse` I should be able to build `is-contract` on my own, by simply comparing `version-byte` with known constant value.
And on top of that it also returns `public key hash` which is something I was waiting for.

**Comment by jcnelson** [comment]
Cool, going to go ahead and close this in favor of #2756.
