### ISSUE TITLE
Miner rewards for bitcoin block 709089?

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2927]
**Describe the bug**
It looks like there is no miner reward distributed for bitcoin block 709089.

**Steps To Reproduce**
[Stacks block 37298](https://stacks-node-api.mainnet.stacks.co/extended/v1/block/by_height/37298) is for btc block 709090 (stacks block hash: 0xc39c814e48bf35e57737b2639c5eacc1661bb4efe66caa1fdce84ad3963f1ea0)

[Stacks block 37297)(https://stacks-node-api.mainnet.stacks.co/extended/v1/block/by_height/37297) is for btc block 709088

That means no stx block for 709089, however, the coin base event for 709090 shows only 1000 STX.

```
select * from miner_rewards mr 
where canonical = true 
and block_hash = '\xc39c814e48bf35e57737b2639c5eacc1661bb4efe66caa1fdce84ad3963f1ea0'
order by mature_block_height desc 
```

|id   |block_hash                                                      |index_block_hash                                                |from_index_block_hash                                           |mature_block_height|canonical|recipient                                |coinbase_amount|tx_fees_anchored|tx_fees_streamed_confirmed|tx_fees_streamed_produced|
|-----|----------------------------------------------------------------|----------------------------------------------------------------|----------------------------------------------------------------|-------------------|---------|-----------------------------------------|---------------|----------------|--------------------------|-------------------------|
|80602|C39C814E48BF35E57737B2639C5EACC1661BB4EFE66CAA1FDCE84AD3963F1EA0|4090F693C6C2DB520F547C3F55C12E415AFF45D7F78095B78A82B9A7107503A5|77E674CA6DA3E23673215B579C633C6F8E6395D87629453DD47187F3678C97C5|              37399|true     |SP11SERAP17NV2F1PGHX6S9RGPE3CSZAE3B6Z9JW7|     1000000000|         4908060|                   3826318|                        0|
80603|C39C814E48BF35E57737B2639C5EACC1661BB4EFE66CAA1FDCE84AD3963F1EA0|4090F693C6C2DB520F547C3F55C12E415AFF45D7F78095B78A82B9A7107503A5|77E674CA6DA3E23673215B579C633C6F8E6395D87629453DD47187F3678C97C5|              37399|true     |SP24BR9PQESYQ2SXXF7FTCJ00WQGTNY7KXQ4C8VEZ|              0|               0|                         0|                        0|

**Expected behavior**
Coinbase_amount should be 2000 STX

**Additional context**
Thank you to Mattematics for reporting: https://discord.com/channels/621759717756370964/728030782693834862/908167161468555284

**Comment by kantai** [comment]
There is a block elected at 709089:

https://stacks-node-api.mainnet.stacks.co/extended/v1/block/by_burn_block_height/709089

It’s just not in the same fork as the one elected at 709090 — miner rewards aren’t redistributed away from forks (that would end up incentivizing the initiation of forks)

**Comment by friedger** [comment]
Thanks for the clarification.
