### ISSUE TITLE
[TESTNET BUG]  stacks-node testnet process running inside the docker container gets stuck

### ISSUE THREAD

**Issue by radicleart** [blockstack/stacks-blockchain#2943]
## Describe the bug

My testnet follower node fell out of sync with testnet chain tip. After restarting (after new docker pull and clearing out persistent data) the stacks-node process running inside the docker container gets stuck.

Syncing a follower node with testnet stops at `Received burnchain block #2034651` - no logging from the node after this line.

I've tried using two independent Debian VMs and it stops in the same place. I've also seen

> INFO [1637261507.342379] [testnet/stacks-node/src/run_loop/neon.rs:118] [ctrl-c] Graceful termination request received, will complete the ongoing runloop cycles and termi..

in the output but can't tell if this is related.

## Steps To Reproduce

I'm using ref: https://docs.stacks.co/understand-stacks/running-testnet-node

but have changed `xenon` to `testnet` in order to get the docker command in the doc to work.

## Expected behavior

docker container output does not stop - stacks tip height catching up with testnet.

## Environment

 - OS: [e.g. Ubuntu / Debian]
 - Rust version
 - stacks-node version
-bash: stacks-node: command not found
docker -v
Docker version 19.03.15, build 99e3ed8919
and 
Docker version 20.10.11, build dea9396
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

## Additional context

I've experienced this type of problem numerous times. I've been unable to find a Config.toml inside the docker container as I thought this might be linked to the parameter something like stop_at_block_height - but was unable to find a toml file. 

The ports are open - eg this happens after the burnchain headers are fetched e.g. after this reaches 100%

INFO [1637332640.434972] [src/burnchains/burnchain.rs:1265] [main] Syncing Bitcoin blocks: 15.1% (2014701 to 2015751 out of 2104595)

I am now trying this using the mainnet instructions but switching the mainnet Config.toml with a testnet Config.toml file found here 
https://github.com/blockstack/stacks-blockchain/blob/63d24b1185bca6a35988aa90667bc5f0a226acb9/testnet/stacks-node/conf/testnet-follower-conf.toml

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by diwakergupta** [comment]
@radicleart see this note on Discord: https://discord.com/channels/621759717756370964/691807526118883418/911312579765366894

The network-upgrade is being tested on the testnet, and the fork activated on Bitcoin testnet block 2,104,380. Please upgrade your testnet nodes to https://github.com/blockstack/stacks-blockchain/releases/tag/next-costs-2 (docker image `blockstack/stacks-blockchain:next-costs-2`)
