### ISSUE TITLE
Didn't receive STX from airdrop

### ISSUE THREAD

**Issue by mattlovelyy** [blockstack/stacks-blockchain#2963]
### Discussed in https://github.com/blockstack/stacks-blockchain/discussions/2958

<div type='discussions-op-text'>

<sup>Originally posted by **mattlovelyy** November 30, 2021</sup>
Hello I am having a problem. I participated in the STX airdrop on blockchain.com, but no coins were credited to my address. I checked everything, changed wallets, but everywhere I see a zero balance.
My STX address (mainnet): SP2NX3W9E62GM1WZ0Z5AQ9K6FNC2T4V3DJ75KXP4G
(testnet): ST2NX3W9E62GM1WZ0Z5AQ9K6FNC2T4V3DJ4QHZFMX
Help me please
![image](https://user-images.githubusercontent.com/58401338/144069442-d7ce1eae-f393-4e23-b875-8e504c4c7d4b.png)
</div>

**Comment by diwakergupta** [comment]
This isn't a bug in the stacks-blockchain. Please follow up with blockchain.com support.
