### ISSUE TITLE
The burnchain-downloader fails to handshake with 34.86.174.130:8333

### ISSUE THREAD

**Issue by ChuYimeng** [blockstack/stacks-blockchain#2964]
**Describe the bug**
Log:
INFO [1638951246.023846] [testnet/stacks-node/src/main.rs:81] [main] stacks-node 2.05.0.0.0 (master:a783b27, release build, linux [x86_64])
INFO [1638951246.023893] [testnet/stacks-node/src/main.rs:114] [main] Loading config at path /src/config.toml
INFO [1638951246.449139] [testnet/stacks-node/src/run_loop/neon.rs:217] [main] Will run as a Follower node
INFO [1638951246.449173] [testnet/stacks-node/src/run_loop/neon.rs:224] [main] Start syncing Bitcoin headers, feel free to grab a cup of coffee, this can take a while
INFO [1638951249.601523] [src/burnchains/burnchain.rs:1271] [main] Syncing Bitcoin blocks: 53.7% (689236 to 691336 out of 713166)
WARN [1638951256.102949] [src/burnchains/bitcoin/indexer.rs:348] [burnchain-downloader] Unhandled error while receiving a message: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
WARN [1638951268.175245] [src/burnchains/bitcoin/network.rs:199] [burnchain-downloader] Failed to handshake with 34.86.174.130:8333: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
WARN [1638951293.743442] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 19.75334424147807 sec...
WARN [1638951313.947511] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 52.42223027486656 sec...
WARN [1638951366.868798] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 60 sec...
WARN [1638951428.561758] [src/burnchains/bitcoin/indexer.rs:348] [burnchain-downloader] Unhandled error while receiving a message: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
WARN [1638951436.726938] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 11.397627486919175 sec...
WARN [1638951460.962150] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 16.4004448784151 sec...
WARN [1638951477.776914] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 37.70629626765331 sec...
WARN [1638951516.141091] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 60 sec...
WARN [1638951576.722534] [src/burnchains/bitcoin/network.rs:199] [burnchain-downloader] Failed to handshake with 34.86.174.130:8333: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
WARN [1638951582.121448] [src/burnchains/bitcoin/network.rs:199] [burnchain-downloader] Failed to handshake with 34.86.174.130:8333: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
WARN [1638951589.873652] [src/burnchains/bitcoin/indexer.rs:348] [burnchain-downloader] Unhandled error while receiving a message: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
WARN [1638951614.465524] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 11.196433799604101 sec...
WARN [1638951636.159095] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 11.908584241354864 sec...
WARN [1638951648.591812] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 25.221449269130307 sec...
WARN [1638951674.321157] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 60 sec...
WARN [1638951760.126827] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 19.518303520991008 sec...
WARN [1638951796.582569] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 13.209490176237706 sec...
WARN [1638951820.013684] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 10.639868635621363 sec...
WARN [1638951831.111740] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 30.74595363506925 sec...
WARN [1638951862.323593] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 60 sec...
WARN [1638951922.740474] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 60 sec...
WARN [1638951983.211331] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 60 sec...
WARN [1638952043.622903] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 60 sec...
WARN [1638952104.085060] [src/burnchains/bitcoin/network.rs:222] [burnchain-downloader] Connection broken; retrying in 60 sec...
WARN [1638952165.418992] [src/burnchains/bitcoin/indexer.rs:348] [burnchain-downloader] Unhandled error while receiving a message: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
WARN [1638952195.452286] [src/burnchains/bitcoin/indexer.rs:348] [burnchain-downloader] Unhandled error while receiving a message: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
...

The mainnet node burnchain-downloader fails to handshake with 34.86.174.130:8333

**Steps To Reproduce**
command:
/bin/stacks-node start --config /src/config.toml
configure:
[node]
working_dir = "/root/stacks-node/data"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "02da7a464ac770ae8337a343670778b93410f2f3fef6bea98dd1c3e9224459d36b@seed-0.mainnet.stacks.co:20444,02afeae522aab5f8c99a00ddf75fbcb4a641e052dd
wait_time_for_microblocks = 10000

[[events_observer]]
endpoint = "stacks-api-svc:3700"
retry_count = 255
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "mainnet"
peer_host = "bitcoin.blockstack.com"
username = "blockstack"
password = "blockstacksystem"
rpc_port = 8332
peer_port = 8333

[connection_options]
read_only_call_limit_write_length = 0
read_only_call_limit_read_length = 100000
read_only_call_limit_write_count = 0
read_only_call_limit_read_count = 30
read_only_call_limit_runtime = 1000000000

**Environment (please complete the following information):**
 container blockstack/stacks-blockchain : stacks-node 2.05.0.0.0 (master:a783b27, release build, linux [x86_64])

**Comment by moko879** [comment]
What was the resolution here?  I'm hitting a similar issue:
INFO [1642474565.323508] [src/burnchains/burnchain.rs:1271] [main] Syncing Bitcoin blocks: 3.9% (666050 to 668150 out of 719240)
WARN [1642474568.317440] [src/burnchains/bitcoin/indexer.rs:334] [burnchain-downloader] Unhandled error SerializationError(Io(Os { code: 41, kind: Other, message: "Protocol wrong type for socket" }))
INFO [1642474568.317502] [src/burnchains/burnchain.rs:1393] [main] Failed to feed burnchain block header 666053: "SendError(..)"
WARN [1642474568.317886] [src/burnchains/burnchain.rs:1426] [main] Try synchronizing the burn chain again: final snapshot 666050 < 668150
ERRO [1642474568.317950] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:449] [main] Unable to sync with burnchain: Try synchronizing again

**Comment by gr-ah** [comment]
Why was this close without a resolution? is there a fix since people are having issue with this error.
