### ISSUE TITLE
Testnet: burnchain error when creating wallet

### ISSUE THREAD

**Issue by Deliver88** [blockstack/stacks-blockchain#2979]
Hello everyone, I am trying to run a testnet miner stacks-node with the following configuration:

`
[node]
working_dir = "../../chain-state/testnet/sqlite"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
seed = "3519899623ffaa438d18e5cfa4a905cc2a6226126450362554beebb2d86e708801"
local_peer_seed = "3519899623ffaa438d18e5cfa4a905cc2a6226126450362554beebb2d86e708801"
miner = true
bootstrap_node = "047435c194e9b01b3d7f7a2802d6684a3af68d05bbf4ec8f17021980d777691f1d51651f7f1d566532c804da506c117bbf79ad62eea81213ba58f8808b4d9504ad@testnet.stacks.co:20444"
wait_time_for_microblocks = 10000

[burnchain]
chain = "bitcoin"
mode = "xenon"
peer_host = "127.0.0.1" 
username = "<USERNAME>"
password = "<PASSWORD>"
rpc_port = 18332
peer_port = 18333

[[ustx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000

[[ustx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000

[[ustx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000

[[ustx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000

`

But I am facing this error:

`
release$: ./stacks-node start --config=../../testnet/stacks-node/conf/testnet-miner-conf.toml 
INFO [1639935212.673005] [testnet/stacks-node/src/main.rs:93] [main] stacks-node 0.1.0 (feat/app-chain-mvp:f3a8e4676, release build, macos [x86_64])
INFO [1639935212.673078] [testnet/stacks-node/src/main.rs:145] [main] Loading config at path ../../testnet/stacks-node/conf/testnet-miner-conf.toml
INFO [1639935212.726252] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:1435] [main] Miner node on Bitcoin: checking UTXOs at address: n28T7oVpL3t8aupVMDCB7E6GpVom2DpsH1
WARN [1639935212.731120] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:1441] [main] Error when creating wallet: Network("Bitcoin RPC: connection failed - Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }")
...
`

Any idea to solve it? What is wrong here?  Thanks .

**Comment by jcnelson** [comment]
This error means your node can't talk to the Bitcoin node -- it's unreachable from the address you provided.  Please check your `[burnchain]` section and make sure you can reach your Bitcoin node with, e.g., `bitcoin-cli`.

**Comment by Deliver88** [comment]
Hello @jcnelson thanks for your feedback. Indeed, I started a local testnet bitcoind node. I had to remove mode = "xenon" due to the error 

```
Bitcoin RPC: status(403) != success, body is 'String(\"(unparseable)\")'"
```

Here is the working config:
```
[node]
working_dir = "../../chain-state/testnet/sqlite"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
seed = "3519899623ffaa438d18e5cfa4a905cc2a6226126450362554beebb2d86e708801"
local_peer_seed = "3519899623ffaa438d18e5cfa4a905cc2a6226126450362554beebb2d86e708801"
miner = true
bootstrap_node = "047435c194e9b01b3d7f7a2802d6684a3af68d05bbf4ec8f17021980d777691f1d51651f7f1d566532c804da506c117bbf79ad62eea81213ba58f8808b4d9504ad@testnet.stacks.co:20444"
wait_time_for_microblocks = 10000

[burnchain]
chain = "bitcoin"
peer_host = "127.0.0.1"
username = "bitcoin"
password = "bitcoin"
rpc_port = 18332
peer_port = 18332

[[ustx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000

[[ustx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000

[[ustx_balance]]
address = "ST1HB1T8WRNBYB0Y3T7WXZS38NKKPTBR3EG9EPJKR"
amount = 10000000000000000

[[ustx_balance]]
address = "STRYYQQ9M8KAF4NS7WNZQYY59X93XEKR31JP64CP"
amount = 10000000000000000

```
