### ISSUE TITLE
Improved Error Responses

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#422]
Currently, error codes and responses can vary greatly in their helpfulness. Improving their output would be very helpful. 

**Verbose errors for clients**

For example instead of:

```
{
	"error": "Failed to transfer balance: Invalid amount"
}
```

We could have something like this:

```
{
	errors: [{
	"code": "invalid_amount",
	"param": "amount",
	"message": "Failed to transfer balance because of invalid amount."
	},
	{
	"code": "invalid_address",
	"param": "address",
	"message": "Provided value is not in a known Bitcoin address format."
	}]
}
```

"code": (required) is a string constant. Clients of the the API can use this code to determine how they want to handle the error. Often this will be used to look up an error message in the user's language to display to the user.

"param": (optional) is the name of the parameter that has a problem. This can be used by clients of the API to display error messages next to the appropriate user input field.

"message": (required) is a human readable error message. This is intended to provide clients of the API with additional information as to why their request failed.

The intention would be that this message: field provides helpful information in explaining the problem for developers. It can be displayed to end users in apps that are MVPs and/or okay with English-only error messages targeted at technical users.

It's preferable to return all of the errors that the API knows about at once so that the app can prompt the user to fix all of their input problems at once.

The CLI client could filter or render these error messages in a more command line friendly format.

**Consistent HTTP status codes**

We should add status codes to the API specification and then add them to the live tests that run on circleCI (or the integration testing framework, when appropriate).

**Examples of Bad Error Cases**

I'm going to keep track of some of the error conditions I've encountered which could have more helpful responses here.

Malformed name requests for price (e.g., name longer than 37 characters) --> 404 URL not found.
Attempting `update` command with insufficient wallet --> 'get_price' failed.

**Comment by kantai** [comment]
Price lookups with invalid names:

```
$ blockstack price test1234
{
    "error": "Failed to get some operation fees: Some fee-query tasks failed: preorder_tx_fee (Failed to get name cost).  Try again with `--debug` for details."
}
```

**Comment by kantai** [comment]
Tracking with checkboxes!

- [ ] `blockstack price test1234` -- names which look like namespaces should error earlier in price lookups.
- [ ] @larrysalibra issue #472 -- not have correct authorization when accessing methods with jwt
- [ ]  errors in registrar -- these should be reported on `blockstack info`

**Comment by muneeb-ali** [comment]
+1 on more detail on error codes. We should track all error codes used in a single file somewhere.

**Comment by jackzampolin** [comment]
+1 this is still an issue! Would love to see better errors. Related: https://github.com/blockstack/blockstack.js/issues/293

**Comment by kantai** [comment]
Closing this out -- a lot of issues related to this have been solved, and this issue itself is too generic to be useful going forward.
