### ISSUE TITLE
virtualchain: Add hooks for user scripts

### ISSUE THREAD

**Issue by vsund** [blockstack/stacks-blockchain#545]
Especially with the future token there's the use case to integrate hooks to run user scripts whenever a Blockstack-related transaction happens (to update an own database or similar things).

@jcnelson said that [`db_commit()`](https://github.com/blockstack/blockstack-core/blob/master/blockstack/lib/nameset/virtualchain_hooks.py#L314) would be the place to implement this.

**Comment by jackzampolin** [comment]
I want to +1 this. If we had those hooks building a notification service for blockstack-core would be possible.
