### ISSUE TITLE
API to iterate over Stacks addresses

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain#877]
Our new explorer has designs for providing some global statistics about the network. Some of those metrics include "total addresses with Stacks" and "total stacks in the network".

If I had an API to iterate over all stacks addresses with balance > 0, I could build aggregators to cache and display this information.

**Comment by jcnelson** [comment]
Can you make a list of exactly what information you need?  I'll start with what I think you're asking:

* A way to iterate through all addresses with a non-zero balance of a particular token type
   * example: `GET /v1/accounts/STACKS?page=0` returns an array of addresses
* The total number of Stacks that exist
   * example: `GET /v1/accounts/STACKS/total` returns the number of Stacks in circulation

Anything else?
