### ISSUE TITLE
Measure ideal maximum stack and context depth

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#913]
We should enforce a maximum Stack depth in the smart contract VM.

Any thoughts on the maximum Stack depth? Because recursion is illegal, stack depths should never really get that big to begin with, so we could set it pretty small.

**Comment by jcnelson** [comment]
Let's think of it in terms of memory footprint -- what's the minimum stack depth possible to fill 1 MB of RAM?  We could go with that value.

Related, I discovered last night that you can use valgrind with the `massif` program to get heap profiles from Rust binaries.  We could start there.

**Comment by kantai** [comment]
Yep -- I can measure that.

**Comment by kantai** [comment]
From measuring with `massif` (with stack measurement turned on!), it looks like a stack depth of `512` yields about 1MB of overhead.

Will run a similar test with contexts, in case someone wants to nest 1MB worth of `(let...)` expressions...

**Comment by kantai** [comment]
Deep let expressions are bit more costly memory-wise than deep function invocations (at a depth of `256`, we reach about 1MB of overhead), though I'm not sure exactly why right now.

For now, I'm going to set the max for both to be 256, but will leave this issue open to revisit as the prototype nears finalization, when the memory usage for both is likely to change.
