### ISSUE TITLE
Price endpoint units are confusing

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/stacks-blockchain#937]
I was trying to look up some pricing information and was confused by the api results. It wasn't clear what units the numbers are in.

Some examples:

https://core.blockstack.org/v2/prices/names/larry.id

```
{
  "name_price": {
    "amount": "40000", 
    "satoshis": 40000, 
    "units": "BTC"
  }
}
```
`amount` 40,000 and and units `BTC` tells me that the price is 40,000 BTC.

It should be something like

```
{
  "name_price": {
    "amount": "40000", 
    "units": "satoshi", 
    "currency": "BTC"
  }
}
```

While people are often familiar with bitcoin and can guess a name probably isn't 40,000 BTC, pricing in stacks is more confusing as people aren't familiar with it.

An example:

https://core.blockstack.org/v2/prices/namespaces/coolnames

```
{
  "amount": "640000000", 
  "units": "STACKS"
}
```

<img width="485" alt="Screen Shot 2019-03-29 at 10 49 55 AM" src="https://user-images.githubusercontent.com/597182/55206144-65a86580-5210-11e9-9138-97c5aaf75756.png">

The result the API gives me is 640,000,000 stacks while the total global number of stacks according to the explorer is 866,827,880 stacks.

If these are Micro Stacks (divide by 1,000,000?), perhaps the api could return something like this:
```
{
  "amount": "640000000", 
  "units": "MICRO_STACKS"
  "currency": "STACKS"
}
```

It might also be nice to have information about what micro stacks are:

```
{
  "amount": "640000000", 
  "units": { 
     name: "micro-stacks",
     multiple: "1000000"
   },
  "currency": "STACKS"
}
```

**Comment by jcnelson** [comment]
The `/v1/accounts` documentation on core.blockstack.org makes it very clear that the units for `STACKS` are in micro-Stacks.  However, the documentation does not indicate this for namespace and name prices.  I'll update the documentation to explicitly state that the units for name/namespace prices, if indicated in `STACKS`, are in micro-Stacks.

We cannot easily change the schema of this endpoint, since multiple clients expect the current behavior.

**Comment by larrysalibra** [comment]
It makes sense that we can't change the behavior in this version. 

It would be a great improvement for a future version.
