### ISSUE TITLE
Add Communication Service to DID document

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#943]
The blockstack profile and therefore the DID document could contain information about how to get in touch with the user.

The communication service needs to be specified (where is the best place to host the spec?)

The communication service shall
* provide an API that allows to invite another user to start a communication. 

An invitation consists of a communication channel, an expiry date, and a invitation message. Invitations should be signed.

Communication channels contain information about the communication protocol and the identity of the inviting person. Examples are
* smtp protocol + email address
* twitter url + twitter handle
* matrix protocol + matrix room id
* stealthy/dmail/.. app id + blockstack id

Possible implementations could be 
* Gaia inboxes
* Radix implementation
* matrix application server

**Comment by jcnelson** [comment]
All of these fit into the `services` field of a DID document.
