### ISSUE TITLE
Consider warning on ignored returns

### ISSUE THREAD

**Issue by lgalabru** [blockstack/stacks-blockchain#972]
What's your take on introducing warnings?
The first I can think of, would be signaling shallowed returns.

```lisp
(begin 
    (func1)   ;; returns (err x)
    (func2))  ;; returns (ok y)
```

`-> Warning: (func1) returns a ResponseType, which is being ignored`

**Comment by lgalabru** [comment]
From https://github.com/blockstack/clarity-js-sdk/pull/4

<img width="641" alt="Screen Shot 2019-05-29 at 5 09 10 PM" src="https://user-images.githubusercontent.com/87777/58591549-8b63e200-8234-11e9-94f5-4d84e4c1372f.png">

**Comment by kantai** [comment]
Right -- I think this is even more important with #975 -- you can't just chain together booleans, since contract-call's will all return error or okay types.

Right now, the branch with algebraic data types has new functions:

```
(expects option on-err)    ;; expects a "Some" from an option type, immediately returning `on-err` from the function if it was a "None"
(default-to default-value option) ;; returns either the value of the "Some" or `default-value` if it was "None"
(is-ok? ...) ;;; just tests 
```

**Comment by kantai** [comment]
Reopening this, since this is still something pretty useful, and relates to #1409.
