### ISSUE TITLE
Improve clarity-cli ux (use Clap arg parser)

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/stacks-blockchain#995]
We need to show users how to use this with a usage same as the others.

**Comment by zone117x** [comment]
The other commands output those usage statements when args are not specified. eval_raw takes no arguments, it reads from stdin and prints the result to stdout. 

```bash
echo "(* 3 5)" | clarity-cli eval_raw
Program executed successfully! Output: 
15
```

Now that the `clarity-cli` bin has its own dependency tree -- we could use more powerful arg parser lib like Clap https://crates.io/crates/clap which gives us more typical and helpful CLI usage like `clarity-cli help eval_raw`. 

A few weeks ago I took a stab at using [getopts](https://crates.io/crates/getopts) (see  https://github.com/blockstack/blockstack-core/compare/0521f916...feature/local-opts) but it doesn't support our sub-commands or positional arguments, which made all the commands much more verbose. 

@jcnelson thoughts?

**Comment by jcnelson** [comment]
I'm fine with using `clap` _as long as_ you only use the following dependencies:

* `bitflags`
* `unicode-width`
* `textwrap`

In particular, do _not_ use features that pull in highly-unsafe termios code.  This includes these packages (which are optional dependencies):

* `term_size`
* `textwrap/term_size`
* `atty`

To achieve this, you need to specify the `no_cargo` or `debug` feature of `clap`.  Do _NOT_ use the default features.

**Comment by moxiegirl** [comment]
@zone117x ok with me if you want to edit this issue forward with an adjusted title.
